UPDATE programa SET nome = 'Os Cavaleiros do Zodíaco - Asgard' WHERE id = 254;
UPDATE programa SET nome = 'Os Cavaleiros do Zodíaco - Cavaleiros de Prata' WHERE id = 255;
UPDATE programa SET nome = 'Os Cavaleiros do Zodíaco - Doze Casas' WHERE id = 256;
UPDATE programa SET nome = 'Os Cavaleiros do Zodíaco - Guerra Galáctica' WHERE id = 257;
UPDATE programa SET nome = 'Os Cavaleiros do Zodíaco - Hades' WHERE id = 258;
UPDATE programa SET nome = 'Os Cavaleiros do Zodíaco - Lost Canvas' WHERE id = 259;
UPDATE programa SET nome = 'Os Cavaleiros do Zodíaco - Poseidon' WHERE id = 260;
UPDATE programa SET nome = 'Coragem - O Cão Covarde - Incompleto' WHERE id = 215;
UPDATE programa SET nome = 'Papa Léguas - Incompleto' WHERE id = 262;
UPDATE programa SET nome = 'Pokémon - Incompleto' WHERE id = 265;
UPDATE programa SET nome = 'Dragon Ball Daima - Legendado' WHERE id = 230;
UPDATE programa SET nome = 'Baki - O Campeão' WHERE id = 209;