DELETE FROM programa; INSERT INTO programa (nome, uuid) VALUES
('Another - Legendado', UUID()),
('As Aventuras de Jackie Chan', UUID()),
('As Meninas Super Poderosas - Incompleto', UUID()),
('Attack on Titans - Legendado', UUID()),
('Avatar - Aang', UUID()),
('Avatar - Korra', UUID()),
('Baki - Hanma', UUID()),
('Baki - O Campeão', UUID()),
('Berserk - Legendado', UUID()),
('Bleach', UUID()),
('Buko no Hero', UUID()),
('Chainsaw Man', UUID()),
('Code Geass - Legendado', UUID()),
('Coragem - O Cão Covarde - Incompleto', UUID()),
('Cowboy Bebop', UUID()),
('Dan da dan', UUID()),
('Death Note', UUID()),
('Demon Slayer - Legendado', UUID()),
('Digimon - Adventure', UUID()),
('Digimon - Frontier', UUID()),
('Digimon - Ghost Game - Legendado', UUID()),
('Digimon - Incompleto', UUID()),
('Digimon - Savers', UUID()),
('Digimon - Tamers', UUID()),
('Digimon - Universe - Appli Monsters - Legendado', UUID()),
('Digimon - Xros Wars - Legendado', UUID()),
('Dr. Stone', UUID()),
('Dragon Ball', UUID()),
('Dragon Ball Daima - Legandado', UUID()),
('Dragon Ball GT', UUID()),
('Dragon Ball Super', UUID()),
('Dragon Ball Z', UUID()),
('Full Metal Alchemist - Brotherhood', UUID()),
('Gantz', UUID()),
('Goblin Slayer', UUID()),
('Hanna-Barbera - Incompleto', UUID()),
('Hellsing', UUID()),
('Hunter x Hunter', UUID()),
('Inuyasha', UUID()),
('Johnny Bravo - Incompleto', UUID()),
('JoJo''s Bizarre Adventure', UUID()),
('Jujutsu Kaisen', UUID()),
('Konosuba', UUID()),
('Looney Tones - Incompleto', UUID()),
('Medabots - Medabots', UUID()),
('Medabots - Spirits', UUID()),
('Mob Psycho 100', UUID()),
('Nanatsu no Taizai', UUID()),
('Naruto', UUID()),
('Neon Genesis Evangelion', UUID()),
('One Piece - Incompleto', UUID()),
('One Punch Man', UUID()),
('Os Cavaleiros do Zodíaco - Asgard', UUID()),
('Os Cavaleiros do Zodíaco - Cavaleiros de Prata', UUID()),
('Os Cavaleiros do Zodíaco - Doze Casas', UUID()),
('Os Cavaleiros do Zodíaco - Guerra Galática', UUID()),
('Os Cavaleiros do Zodíaco - Hades', UUID()),
('Os Cavaleiros do Zodíaco - Lost Canvas', UUID()),
('Os Cavaleiros do Zodíaco - Poseidon', UUID()),
('Overlord', UUID()),
('Papa Léguas - Incompleto', UUID()),
('Parasyte', UUID()),
('Pica Pau - Incompleto', UUID()),
('Pokémon - Incompleto', UUID()),
('Re Zero', UUID()),
('Record of Ragnarok - Incompleto', UUID()),
('Sailor Moon', UUID()),
('Sakura Card Captor', UUID()),
('Samurai Jack', UUID()),
('Samurai Warriors', UUID()),
('Samurai X', UUID()),
('Serial Experiments Lain', UUID()),
('Shurato', UUID()),
('Spy X Family', UUID()),
('Stains;Gate0', UUID()),
('Steins;Gate', UUID()),
('Street Fighter II - Victory', UUID()),
('Super Dragon Ball Heroes - Legendado', UUID()),
('Sword Art Online', UUID()),
('The Promised Neverland - Legendado', UUID()),
('Tiny Toons - Incompleto', UUID()),
('Tokyo Ghoul', UUID()),
('Tokyo Revengers', UUID()),
('Tom e Jerry - Incompleto', UUID()),
('Trigun', UUID()),
('Undead Unluck - Legendado', UUID()),
('Violet Evergarden - Legendado', UUID()),
('Yu Yu Hakusho', UUID()),
('Yu-Gi-Oh! - Incompleto', UUID());
