INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Another - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('As Aventuras de Jackie Chan', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('As Meninas Super Poderosas', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Attack on Titans - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Avatar - Aang', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Avatar - Korra', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Baki - Hanma', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Baki - O Campeão', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Berserk - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Bleach', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Buko no Hero', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Chainsaw Man', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Code Geass - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Coragem - O Cão Covarde', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Cowboy Bebop', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Dan da dan', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Death Note', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Demon Slayer - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Digimon - Adventure', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Digimon - Frontier', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Digimon - Ghost Game - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Digimon - Savers', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Digimon - Tamers', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Digimon - Universe - Appli Monsters - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Digimon - Xros Wars - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Dr. Stone', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Dragon Ball', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Dragon Ball Daima - Legandado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Dragon Ball GT', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Dragon Ball Super', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Dragon Ball Z', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Full Metal Alchemist - Brotherhood', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Gantz', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Goblin Slayer', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Hanna-Barbera', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Hellsing', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Hunter x Hunter', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Inuyasha', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('JoJo''s Bizarre Adventure', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Johnny Bravo', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Jujutsu Kaisen', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Konosuba', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Looney Tones', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Medabots - Medabots', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Medabots - Spirits', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Mob Psycho 100', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Nanatsu no Taizai', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Naruto', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Neon Genesis Evangelion', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('One Piece - Incompleto', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('One Punch Man', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Os Cavaleiros do Zodíaco - Asgard', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Os Cavaleiros do Zodíaco - Cavaleiros de Prata', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Os Cavaleiros do Zodíaco - Doze Casas', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Os Cavaleiros do Zodíaco - Guerra Galática', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Os Cavaleiros do Zodíaco - Hades - Elíseos', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Os Cavaleiros do Zodíaco - Hades - Inferno', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Os Cavaleiros do Zodíaco - Hades - Santuário', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Os Cavaleiros do Zodíaco - Lost Canvas', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Os Cavaleiros do Zodíaco - Poseidon', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Overlord', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Papa Léguas', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Parasyte', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Pica Pau', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Pokémon', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Re Zero', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Record of Ragnarok', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Recovery', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Sailor Moon', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Sakura Card Captor', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Samurai Jack', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Samurai Warriors', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Samurai X', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Serial Experiments Lain', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Shurato', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Spy X Family', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Stains;Gate0', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Steins;Gate', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Street Fighter II - Victory', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Super Dragon Ball Heroes - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Sword Art Online', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('The Promised Neverland - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Tiny Toons', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Tokyo Ghoul', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Tokyo Revengers', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Tom e Jerry', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Trigun', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Undead Unluck - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Violet Evergarden - Legendado', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Yu Yu Hakusho', 'Active', 'Anime', UUID(), 1);
INSERT INTO programa (nome, status_desc, tipo_desc, uuid, temporadas) VALUES ('Yu-Gi-Oh!', 'Active', 'Anime', UUID(), 1);