UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\01_The Other_imagem.jpg' WHERE id = 7216;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\02_Rough sketch_imagem.jpg' WHERE id = 7217;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\03_Bone work_imagem.jpg' WHERE id = 7218;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\04_Put flesh_imagem.jpg' WHERE id = 7219;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\05_Build limbs_imagem.jpg' WHERE id = 7220;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\06_Face to face_imagem.jpg' WHERE id = 7221;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\07_Sphere joint_imagem.jpg' WHERE id = 7222;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\08_Hair stand_imagem.jpg' WHERE id = 7223;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\09_Body paint_imagem.jpg' WHERE id = 7224;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\10_Glass Eye_imagem.jpg' WHERE id = 7225;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\11_Makeup_imagem.jpg' WHERE id = 7226;
UPDATE episodio SET capa_url = 'F:\\\\Another - Legendado\\\\12_Stand by oneself_imagem.jpg' WHERE id = 7227;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\01_A M?o Negra_imagem.jpg' WHERE id = 7228;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\02_For?a Interior_imagem.jpg' WHERE id = 7229;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\03_A M?scara de El Toro_imagem.jpg' WHERE id = 7230;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\04_A V?bora_imagem.jpg' WHERE id = 7231;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\05_O Jogo da Carapa?a_imagem.jpg' WHERE id = 7232;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\06_Viagem Astral_imagem.jpg' WHERE id = 7233;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\07_Fanfarr?es_imagem.jpg' WHERE id = 7234;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\08_Barra Pesada_imagem.jpg' WHERE id = 7235;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\09_A Rocha_imagem.jpg' WHERE id = 7236;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\10_O Macaco de Jade_imagem.jpg' WHERE id = 7237;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\11_Entre C?es e Porcos_imagem.jpg' WHERE id = 7238;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\12_O Tigre e o Gatinho_imagem.jpg' WHERE id = 7239;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\1? Temporada\\\\13_O Dia do Drag?o_imagem.jpg' WHERE id = 7240;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\01_O Inimigo Mais Forte_imagem.jpg' WHERE id = 7241;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\02_Inimigo Mortal_imagem.jpg' WHERE id = 7242;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\03_A Liberta??o da Feiticeira_imagem.jpg' WHERE id = 7243;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\04_Jackie vai pra Cadeia._imagem.jpg' WHERE id = 7244;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\05_Jackie vai para Hollywood_imagem.jpg' WHERE id = 7245;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\06_A Rainha do Shadowkhan_imagem.jpg' WHERE id = 7246;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\07_Lua de Shanghai_imagem.jpg' WHERE id = 7247;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\08_A Armadura dos Deuses_imagem.jpg' WHERE id = 7248;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\09_M? Companhia_imagem.jpg' WHERE id = 7249;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\10_A Nova Atl?ntida_imagem.jpg' WHERE id = 7250;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\11_O Oitavo Portal_imagem.jpg' WHERE id = 7251;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\12_O mundo dos Dem?nios - Parte 1_imagem.jpg' WHERE id = 7252;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\13_O mundo dos Dem?nios - Parte 2_imagem.jpg' WHERE id = 7253;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\14_A M?e De Todas As Batalhas_imagem.jpg' WHERE id = 7254;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\15_Terror no Gelo_imagem.jpg' WHERE id = 7255;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\16_Os Sultras Sagrados_imagem.jpg' WHERE id = 7256;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\17_A Cidade Perdida dos Muntabs_imagem.jpg' WHERE id = 7257;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\18_O Templo de Lotus_imagem.jpg' WHERE id = 7258;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\19_A Maldi??o do Chupa Cabra_imagem.jpg' WHERE id = 7259;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\20_Uma Aventura no Velho Oeste_imagem.jpg' WHERE id = 7260;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\21_Origami_imagem.jpg' WHERE id = 7261;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\22_Agente Secreto_imagem.jpg' WHERE id = 7262;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\23_Cara e coroa_imagem.jpg' WHERE id = 7263;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\24_O Pulo do Gato_imagem.jpg' WHERE id = 7264;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\25_O Cruzeiro_imagem.jpg' WHERE id = 7265;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\26_O Escolhido_imagem.jpg' WHERE id = 7266;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\27_Palavra de Escoteiro_imagem.jpg' WHERE id = 7267;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\28_Meu Amigo Rei._imagem.jpg' WHERE id = 7268;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\29_A Hist?ria da Luva._imagem.jpg' WHERE id = 7269;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\30_Azarado pra Cachorro_imagem.jpg' WHERE id = 7270;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\31_A Garota T_imagem.jpg' WHERE id = 7271;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\32_O Chan que sabia demais_imagem.jpg' WHERE id = 7272;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\33_Querida eu Encolhi o Jackie_imagem.jpg' WHERE id = 7273;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\34_Fazendo Macaquices_imagem.jpg' WHERE id = 7274;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\35_Entrevista com Vampiro_imagem.jpg' WHERE id = 7275;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\36_O Bom, O Mau, O Cego, O Surdo e O Mudo_imagem.jpg' WHERE id = 7276;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\37_A Encarna??o do Guerreiro_imagem.jpg' WHERE id = 7277;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\38_Ca?a a Cobra._imagem.jpg' WHERE id = 7278;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\2? Temporada\\\\39_De Volta ao Passado_imagem.jpg' WHERE id = 7279;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\01_De Volta a Turma do J_imagem.jpg' WHERE id = 7280;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\02_Os Clones_imagem.jpg' WHERE id = 7281;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\03_Poderes Feras_imagem.jpg' WHERE id = 7282;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\04_Macaco Travesso_imagem.jpg' WHERE id = 7283;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\05_Corrida ao Rato Asteca_imagem.jpg' WHERE id = 7284;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\06_Jackie ao Quadrado_imagem.jpg' WHERE id = 7285;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\07_Porcos que Voam_imagem.jpg' WHERE id = 7286;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\08_Mam?e Ficou Invis?vel_imagem.jpg' WHERE id = 7287;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\09_Carneiro Trancendental_imagem.jpg' WHERE id = 7288;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\10_Ningu?m pega esse Coelho_imagem.jpg' WHERE id = 7289;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\11_Valmont Min?sculo e Jade Gigante_imagem.jpg' WHERE id = 7290;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\12_Cabe?as Voadoras_imagem.jpg' WHERE id = 7291;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\13_Deu a Louca nos Bichos_imagem.jpg' WHERE id = 7292;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\14_O Renascimento do Drag?o_imagem.jpg' WHERE id = 7293;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\15_A ?pera_imagem.jpg' WHERE id = 7294;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\16_Quem ? Tohru_imagem.jpg' WHERE id = 7295;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\3? Temporada\\\\17_Socorro Raptaram o Papai Noel_imagem.jpg' WHERE id = 7296;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\01_As M?scaras de Shadowkan_imagem.jpg' WHERE id = 7297;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\02_Ratso, O Samurai_imagem.jpg' WHERE id = 7298;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\03_A Incr?vel Tropa T_imagem.jpg' WHERE id = 7299;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\04_Um Mau Capit?o_imagem.jpg' WHERE id = 7300;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\05_Atr?s de mim N?o_imagem.jpg' WHERE id = 7301;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\06_N?o Tenho Medo de Cara Feia_imagem.jpg' WHERE id = 7302;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\07_Os Comedores de Sombras_imagem.jpg' WHERE id = 7303;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\08_Minha Outra Metade_imagem.jpg' WHERE id = 7304;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\09_? Duro ser Bonzinho_imagem.jpg' WHERE id = 7305;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\10_Mas Que Passado_imagem.jpg' WHERE id = 7306;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\11_1 ? Pouco, 2 ? Demais_imagem.jpg' WHERE id = 7307;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\12_A Equipe J Mirim_imagem.jpg' WHERE id = 7308;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\4? Temporada\\\\13_A ?ltima M?scara_imagem.jpg' WHERE id = 7309;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\01_As Rel?quias dos Imortais_imagem.jpg' WHERE id = 7310;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\02_Faz Parte do Jogo_imagem.jpg' WHERE id = 7311;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\03_Uma Nova Equipe_imagem.jpg' WHERE id = 7312;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\04_Escoteiro da Pesada_imagem.jpg' WHERE id = 7313;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\05_Uma Professora dos Dem?nios_imagem.jpg' WHERE id = 7314;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\06_Espelho, Espelho Meu_imagem.jpg' WHERE id = 7315;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\07_Espet?cular Larry_imagem.jpg' WHERE id = 7316;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\08_Um Frio Danado_imagem.jpg' WHERE id = 7317;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\09_Roubando Trov?es_imagem.jpg' WHERE id = 7318;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\10_O Dem?nio da Montanha_imagem.jpg' WHERE id = 7319;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\11_De Volta ao Futuro_imagem.jpg' WHERE id = 7320;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\12_Briga de Poderes - Parte 1_imagem.jpg' WHERE id = 7321;
UPDATE episodio SET capa_url = 'F:\\\\As Aventuras de Jackie Chan\\\\5? Temporada\\\\13_Briga de Poderes - Parte 2_imagem.jpg' WHERE id = 7322;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\A.Crazy.Mixed.Up.Puffs.avi' WHERE id = 7325;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\A.Made.Up.Story.avi' WHERE id = 7326;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\A.Very.Special.Blossom.avi' WHERE id = 7327;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Abracadaver.avi' WHERE id = 7328;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Bang.For.Your.Buck.avi' WHERE id = 7329;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Beat.Your.Greens.avi' WHERE id = 7330;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Birthday.Bash.avi' WHERE id = 7331;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Boogie.Frights.avi' WHERE id = 7332;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Bought.And.Scold.avi' WHERE id = 7333;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Boy.Toys.avi' WHERE id = 7334;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Bubble.Boy.avi' WHERE id = 7335;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Bubblevision.avi' WHERE id = 7336;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Bubblevivious.avi' WHERE id = 7337;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Buttercrush.avi' WHERE id = 7338;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Candy.Is.Dandy.avi' WHERE id = 7339;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Cat.Man.Do.avi' WHERE id = 7340;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Catastrophe.avi' WHERE id = 7341;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Child.Fearing.avi' WHERE id = 7342;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\City.Of.Clipsville.avi' WHERE id = 7343;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\City.Of.Frownsville.avi' WHERE id = 7344;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\City.Of.Nutsville.avi' WHERE id = 7345;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Collect.Her.avi' WHERE id = 7346;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Cootie.Gras.avi' WHERE id = 7347;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Cop.Out.avi' WHERE id = 7348;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Coupe.D.Etat.avi' WHERE id = 7349;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Cover.Up.avi' WHERE id = 7350;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Criss.Cross.Crisis.avi' WHERE id = 7351;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Curses.avi' WHERE id = 7352;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Custody.Battle.avi' WHERE id = 7353;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Daylight.Savings.avi' WHERE id = 7354;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Divide.And.Conquer.avi' WHERE id = 7355;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Down.N.Dirty.avi' WHERE id = 7356;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Dream.Scheme.avi' WHERE id = 7357;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Fallen.Arches.avi' WHERE id = 7358;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Fuzzy.Logic.avi' WHERE id = 7359;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Geshundfiht.avi' WHERE id = 7360;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Gettin.Twiggy.With.It.avi' WHERE id = 7361;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Hot.Air.Buffoon.avi' WHERE id = 7362;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\I.See.A.Funny.Cartoon.In.Your.Future.avi' WHERE id = 7363;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Ice.Sore.avi' WHERE id = 7364;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Imaginary.Fiend.avi' WHERE id = 7365;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Impeach.Fuzz.avi' WHERE id = 7366;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Insect.Inside.avi' WHERE id = 7367;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Jewel.Of.The.Aisle.avi' WHERE id = 7368;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Just.Another.Manic.Mojo.avi' WHERE id = 7369;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Just.Desserts.avi' WHERE id = 7370;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Keen.Or.Keene.avi' WHERE id = 7371;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Los_.Dos.Mojos.avi' WHERE id = 7372;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Lying.Around.The.House.avi' WHERE id = 7373;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Major.Competition.avi' WHERE id = 7374;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Meninas_Super_Poderosas-O Filme.avi' WHERE id = 7375;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Mime.For.A.Change.avi' WHERE id = 7376;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Mizzen.In.Action.avi' WHERE id = 7377;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Mo.Job.avi' WHERE id = 7378;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Mo.Linguish.avi' WHERE id = 7379;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Mojo.Jonesin.avi' WHERE id = 7380;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Mommy.Fearest.avi' WHERE id = 7381;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Monkey.See.Doggie.Do.avi' WHERE id = 7382;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Monkey.See.Doggie.Two.avi' WHERE id = 7383;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Monstra.City.avi' WHERE id = 7384;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Mr.Mojos.Rising.avi' WHERE id = 7385;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Neighbor.Hood.avi' WHERE id = 7386;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Not.So.Awesome.Blossom.avi' WHERE id = 7387;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Nuthin.Special..avi' WHERE id = 7388;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Octi.Evil.avi' WHERE id = 7389;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Octi.Gone.avi' WHERE id = 7390;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Oops.I.Did.It.Again.avi' WHERE id = 7391;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Paste.Makes.Waste.avi' WHERE id = 7392;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Pee.Pee.Gs.avi' WHERE id = 7393;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Pet.Feud.avi' WHERE id = 7394;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Pilot.-.Crime.101.avi' WHERE id = 7395;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Ploys.R.Us.avi' WHERE id = 7396;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Powerpuff.Bluff.avi' WHERE id = 7397;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Prime.Mates.avi' WHERE id = 7398;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Save.Mojo.avi' WHERE id = 7399;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Schollhouse.Rocked.avi' WHERE id = 7400;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Seed.No.Evil.avi' WHERE id = 7401;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Shotgun.Wedding.avi' WHERE id = 7402;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Shut.The.Pup.Up.avi' WHERE id = 7403;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Slave.The.Day.avi' WHERE id = 7404;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Slumbering.With.The.Enemy.avi' WHERE id = 7405;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Somethings.A.Ms.avi' WHERE id = 7406;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Speed.Demon.avi' WHERE id = 7407;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Stuck.Up.Up.And.Away.avi' WHERE id = 7408;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Substitute.Creature.avi' WHERE id = 7409;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Sun.Scream.avi' WHERE id = 7410;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Super.Zeroes.avi' WHERE id = 7411;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Supper.Villain.avi' WHERE id = 7412;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Telephonies.avi' WHERE id = 7413;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\The.Bare.Facts.avi' WHERE id = 7414;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\The.Headsuckers.avi' WHERE id = 7415;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\The.Mane.Event.avi' WHERE id = 7416;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\The.Ppg.Best.Rainy.Day.Adventure.Ever.avi' WHERE id = 7417;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\The.Rowdyruff.Boys.avi' WHERE id = 7418;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Three.Girls.And.A.Monster.avi' WHERE id = 7419;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Too.Pooped.To.Puff.avi' WHERE id = 7420;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Tough.Love.avi' WHERE id = 7421;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Twisted.Siste.avi' WHERE id = 7422;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\Uh.Oh.Dynamo.avi' WHERE id = 7423;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\West.In.Pieces.avi' WHERE id = 7424;
UPDATE episodio SET capa_url = 'F:\\\\As Meninas Super Poderosas - Incompleto\\\\You.Snooze.You.Lose.avi' WHERE id = 7425;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\01_To You, in 2000 Years - The Fall of Shiganshina, Part 1_imagem.jpg' WHERE id = 7426;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\02_That Day The Fall of Shiganshina, Part 2_imagem.jpg' WHERE id = 7427;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\03_A Dim Light Amid Despair Humanity's - Comeback, Part 1_imagem.jpg' WHERE id = 7428;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\04_The Night of the Closing Ceremony - Humanity's Comeback, Part 2_imagem.jpg' WHERE id = 7429;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\05_First Battle - The Struggle for Trost, Part 1_imagem.jpg' WHERE id = 7430;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\06_The World the Girl Saw - The Struggle for Trost, Part 2_imagem.jpg' WHERE id = 7431;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\07_Small Blade - The Struggle for Trost, Part 3_imagem.jpg' WHERE id = 7432;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\08_I Can Hear His Heartbeat - The Struggle for Trost, Part 4_imagem.jpg' WHERE id = 7433;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\09_Whereabouts of His Left Arm - The Struggle for Trost, Part 5_imagem.jpg' WHERE id = 7434;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\10_Response - The Struggle for Trost, Part 6_imagem.jpg' WHERE id = 7435;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\11_Idol - The Struggle for Trost, Part 7_imagem.jpg' WHERE id = 7436;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\12_Wound - The Struggle for Trost, Part 8_imagem.jpg' WHERE id = 7437;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\13_Primal Desire - The Struggle for Trost, Part 9_imagem.jpg' WHERE id = 7438;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\14_Can't Look into His Eyes Yet - Eve of the Counterattack, Part 1_imagem.jpg' WHERE id = 7439;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\15_Special Operations Squad - Eve of the Counterattack, Part 2_imagem.jpg' WHERE id = 7440;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\16_What Needs to Be Done Now - Eve of the Counterattack, Part 3_imagem.jpg' WHERE id = 7441;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\17_Female Titan - The 57th Exterior Scouting Mission, Part 1_imagem.jpg' WHERE id = 7442;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\18_Forest of Giant Trees - The 57th Exterior Scouting Mission, Part 2_imagem.jpg' WHERE id = 7443;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\19_Bite - The 57th Exterior Scouting Mission, Part 3_imagem.jpg' WHERE id = 7444;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\20_Erwin Smith - The 57th Exterior Scouting Mission, Part 4_imagem.jpg' WHERE id = 7445;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\21_Crushing Blow - The 57th Exterior Scouting Mission, Part 5_imagem.jpg' WHERE id = 7446;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\22_The Defeated - The 57th Exterior Scouting Mission, Part 6_imagem.jpg' WHERE id = 7447;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\23_Smile - Assault on Stohess, Part 1_imagem.jpg' WHERE id = 7448;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\24_Mercy - Assault on Stohess, Part 2_imagem.jpg' WHERE id = 7449;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\1? Temporada\\\\25_Wall - Assault on Stohess, Part 3_imagem.jpg' WHERE id = 7450;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\01_Beast Titan_imagem.jpg' WHERE id = 7451;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\02_I'm Home_imagem.jpg' WHERE id = 7452;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\03_Southwestward_imagem.jpg' WHERE id = 7453;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\04_Soldier_imagem.jpg' WHERE id = 7454;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\05_Historia_imagem.jpg' WHERE id = 7455;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\06_Warrior_imagem.jpg' WHERE id = 7456;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\07_Close Combat_imagem.jpg' WHERE id = 7457;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\08_The Hunters_imagem.jpg' WHERE id = 7458;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\09_Opening_imagem.jpg' WHERE id = 7459;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\10_Children_imagem.jpg' WHERE id = 7460;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\11_Charge_imagem.jpg' WHERE id = 7461;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\2? Temporada\\\\12_Scream_imagem.jpg' WHERE id = 7462;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\01_Smoke Signal_imagem.jpg' WHERE id = 7463;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\02_Pain_imagem.jpg' WHERE id = 7464;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\03_Old Story_imagem.jpg' WHERE id = 7465;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\04_Trust_imagem.jpg' WHERE id = 7466;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\05_Reply_imagem.jpg' WHERE id = 7467;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\06_Sin_imagem.jpg' WHERE id = 7468;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\07_Wish_imagem.jpg' WHERE id = 7469;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\08_Outside the Walls of Orvud District_imagem.jpg' WHERE id = 7470;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\09_Ruler of the Walls_imagem.jpg' WHERE id = 7471;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\10_Friends_imagem.jpg' WHERE id = 7472;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\11_Bystander_imagem.jpg' WHERE id = 7473;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 1\\\\12_Night of the Battle to Retake the Wall_imagem.jpg' WHERE id = 7474;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 2\\\\01_The Town Where Everything Began_imagem.jpg' WHERE id = 7475;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 2\\\\02_Thunder Spears_imagem.jpg' WHERE id = 7476;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 2\\\\03_Descent_imagem.jpg' WHERE id = 7477;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 2\\\\04_Perfect Game_imagem.jpg' WHERE id = 7478;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 2\\\\05_Hero_imagem.jpg' WHERE id = 7479;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 2\\\\06_Midnight Sun_imagem.jpg' WHERE id = 7480;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 2\\\\07_The Basement_imagem.jpg' WHERE id = 7481;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 2\\\\08_That Day_imagem.jpg' WHERE id = 7482;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 2\\\\09_Attack Titan_imagem.jpg' WHERE id = 7483;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\3? Temporada\\\\Parte 2\\\\10_The Other Side of the Wall_imagem.jpg' WHERE id = 7484;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\01_The Other Side of the Sea_imagem.jpg' WHERE id = 7485;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\02_Midnight Train_imagem.jpg' WHERE id = 7486;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\03_The Door of Hope_imagem.jpg' WHERE id = 7487;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\04_From One Hand to Another_imagem.jpg' WHERE id = 7488;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\05_Declaration of War_imagem.jpg' WHERE id = 7489;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\06_The War Hammer Titan_imagem.jpg' WHERE id = 7490;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\07_Assault_imagem.jpg' WHERE id = 7491;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\08_Assassin's Bullet_imagem.jpg' WHERE id = 7492;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\09_Brave Volunteers_imagem.jpg' WHERE id = 7493;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\10_A Sound Argument_imagem.jpg' WHERE id = 7494;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\11_Deceiver_imagem.jpg' WHERE id = 7495;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\12_Guides_imagem.jpg' WHERE id = 7496;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\13_Children of the Forest_imagem.jpg' WHERE id = 7497;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\14_Savagery_imagem.jpg' WHERE id = 7498;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\15_Sole Salvation_imagem.jpg' WHERE id = 7499;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 1\\\\16_Above and Below_imagem.jpg' WHERE id = 7500;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\01_Judgment_imagem.jpg' WHERE id = 7501;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\02_Sneak Attack_imagem.jpg' WHERE id = 7502;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\03_Two Brothers_imagem.jpg' WHERE id = 7503;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\04_Memories of the Future_imagem.jpg' WHERE id = 7504;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\05_From You, 2,000 Years Ago_imagem.jpg' WHERE id = 7505;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\06_Thaw_imagem.jpg' WHERE id = 7506;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\07_Sunset_imagem.jpg' WHERE id = 7507;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\08_Pride_imagem.jpg' WHERE id = 7508;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\09_Night of the End_imagem.jpg' WHERE id = 7509;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\10_Traitor_imagem.jpg' WHERE id = 7510;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\11_Retrospective_imagem.jpg' WHERE id = 7511;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 2\\\\12_The Dawn of Humanity_imagem.jpg' WHERE id = 7512;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 3\\\\01_The Final Chapters_imagem.jpg' WHERE id = 7513;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\4? Temporada\\\\Parte 3\\\\02_The Final Chapters_imagem.jpg' WHERE id = 7514;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\Filmes - Dublado\\\\shingeki-no-kyojin-season-2-movie-kakusei-no-houkou-dublado_imagem.jpg' WHERE id = 7515;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\Lost Girls - Dublado\\\\shingeki-no-kyojin-lost-girls-dublado-ep-1_imagem.jpg' WHERE id = 7516;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\Lost Girls - Dublado\\\\shingeki-no-kyojin-lost-girls-dublado-ep-2_imagem.jpg' WHERE id = 7517;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\Lost Girls - Dublado\\\\shingeki-no-kyojin-lost-girls-dublado-ep-3-final_imagem.jpg' WHERE id = 7518;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\OVAs - Dublado\\\\shingeki-no-kyojin-ova-dublado-ep-1_imagem.jpg' WHERE id = 7519;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\OVAs - Dublado\\\\shingeki-no-kyojin-ova-dublado-ep-2_imagem.jpg' WHERE id = 7520;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\OVAs - Dublado\\\\shingeki-no-kyojin-ova-dublado-ep-3-final_imagem.jpg' WHERE id = 7521;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\Sem Arrependimentos - Dublado\\\\shingeki-no-kyojin-kuinaki-sentaku-dublado-ep-1_imagem.jpg' WHERE id = 7522;
UPDATE episodio SET capa_url = 'F:\\\\Attack on Titans - Legendado\\\\Sem Arrependimentos - Dublado\\\\shingeki-no-kyojin-kuinaki-sentaku-dublado-ep-2-final_imagem.jpg' WHERE id = 7523;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\01_O Espadachim Negro_imagem.jpg' WHERE id = 7715;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\02_Bando do Falc?o_imagem.jpg' WHERE id = 7716;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\03_Primeira Batalha_imagem.jpg' WHERE id = 7717;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\04_A M?o de Deus_imagem.jpg' WHERE id = 7718;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\05_Um Vento de Espadas_imagem.jpg' WHERE id = 7719;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\06_Zodd o Imortal_imagem.jpg' WHERE id = 7720;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\07_O dono da Espada_imagem.jpg' WHERE id = 7721;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\08_Conspira??o_imagem.jpg' WHERE id = 7722;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\09_Assassinato_imagem.jpg' WHERE id = 7723;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\10_Homem Nobre_imagem.jpg' WHERE id = 7724;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\11_A Batalha_imagem.jpg' WHERE id = 7725;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\12_Juntos_imagem.jpg' WHERE id = 7726;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\13_Preparado para a Morte_imagem.jpg' WHERE id = 7727;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\14_Fogueira do Sonhos_imagem.jpg' WHERE id = 7728;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\15_A Batalha Decisiva_imagem.jpg' WHERE id = 7729;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\16_O Conquistador_imagem.jpg' WHERE id = 7730;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\17_Momentos de Gl?ria_imagem.jpg' WHERE id = 7731;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\18_L?pide das chamas_imagem.jpg' WHERE id = 7732;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\19_Separa??o_imagem.jpg' WHERE id = 7733;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\20_Fa?scas_imagem.jpg' WHERE id = 7734;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\21_Confiss?o_imagem.jpg' WHERE id = 7735;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\22_Infiltra??o_imagem.jpg' WHERE id = 7736;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\23_V?spera da Festa_imagem.jpg' WHERE id = 7737;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\24_O Grande Eclipse_imagem.jpg' WHERE id = 7738;
UPDATE episodio SET capa_url = 'F:\\\\Berserk - Legendado\\\\25_Hora da Eternidade_imagem.jpg' WHERE id = 7739;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\01_De Volta ? Saga do Hueco Mundo!_imagem.jpg' WHERE id = 7740;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\02_Banquete Grotesco, O Teatro de Szayel Aporro._imagem.jpg' WHERE id = 7741;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\03_O Segredo de Neliel, A Bela dos Seios Fartos se Junta ? Batalha!_imagem.jpg' WHERE id = 7742;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\04_Encantador, O Macabro Show de Fantoches._imagem.jpg' WHERE id = 7743;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\05_O Passado de Neliel._imagem.jpg' WHERE id = 7744;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\06_Uni?o Extrema! A Seriedade de Pessche._imagem.jpg' WHERE id = 7745;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\07_Se Juntando ? Batalha! O Poderoso Ex?rcito Shinigami Aparece._imagem.jpg' WHERE id = 7746;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\08_A Bankai de Byakuya, a Raiva Silenciosa._imagem.jpg' WHERE id = 7747;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\09_Os Dois Cientistas, a Armadilha de Mayuri._imagem.jpg' WHERE id = 7748;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\10_Santo Nascimento, A Ressurrei??o de Szayel Aporro._imagem.jpg' WHERE id = 7749;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\11_O Corpo Indestrut?vel! Nnoitra ? Alvejado._imagem.jpg' WHERE id = 7750;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\12_A Libera??o de Nnoitra! Os Bra?os Multiplicados._imagem.jpg' WHERE id = 7751;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\13_Conclus?o da Luta Feroz! Quem ? o Mais Forte_imagem.jpg' WHERE id = 7752;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\14_Reuni?o na Cidade de Karakura! S?suke Aizen VS Shinigamis._imagem.jpg' WHERE id = 7753;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\15_A Estrat?gia Suicida de Ichigo._imagem.jpg' WHERE id = 7754;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\10? Temporada\\\\16_Tum! O Torneio de Futebol Hollow._imagem.jpg' WHERE id = 7755;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\11? Temporada\\\\01_Come?a a Saga do Passado! A Verdade de 110 anos Atr?s._imagem.jpg' WHERE id = 7756;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\11? Temporada\\\\02_O Novo Capit?o da 12? Divis?o, Kisuke Urahara._imagem.jpg' WHERE id = 7757;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\11? Temporada\\\\03_S?suke Aizen e o Jovem G?nio._imagem.jpg' WHERE id = 7758;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\11? Temporada\\\\04_A 9? Divis?o de Kensei Come?a a Agir._imagem.jpg' WHERE id = 7759;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\11? Temporada\\\\05_Hiyori Morre O Come?o da Trag?dia._imagem.jpg' WHERE id = 7760;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\11? Temporada\\\\06_Trai??o! O Plano Secreto de S?suke._imagem.jpg' WHERE id = 7761;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\11? Temporada\\\\07_Salvem Shinji Hirako! S?suke VS Kisuke._imagem.jpg' WHERE id = 7762;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\11? Temporada\\\\08_Nasce o Karakuraizer._imagem.jpg' WHERE id = 7763;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\11? Temporada\\\\09_O ?ltimo Dia do Karakuraizer._imagem.jpg' WHERE id = 7764;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\01_Defenda a Cidade de Karakura! A Apari??o Completa dos Shinigamis._imagem.jpg' WHERE id = 7765;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\02_Elite! Os Quatro Shinigamis._imagem.jpg' WHERE id = 7766;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\03_Charlotte, a Linda Guerreira._imagem.jpg' WHERE id = 7767;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\04_Kira, A Batalha Dentro do Desespero._imagem.jpg' WHERE id = 7768;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\05_A Shikai de Hisagi! Seu Nome ?..._imagem.jpg' WHERE id = 7769;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\06_A Queda de Ikkaku! A Crise do Shinigami._imagem.jpg' WHERE id = 7770;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\07_A Batalha Completa! Shinigami VS Espada._imagem.jpg' WHERE id = 7771;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\08_A Dupla mais Terr?vel! Soi Fong & Marechiyo Omaeda._imagem.jpg' WHERE id = 7772;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\09_Um Corpo Milagroso! Ggio Libera sua Ressurecci?n._imagem.jpg' WHERE id = 7773;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\10_A Batalha de 3 contra 1! A Crise de Rangiku._imagem.jpg' WHERE id = 7774;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\11_Os Tenentes s?o Aniquilados! A Terr?vel Fera Demon?aca._imagem.jpg' WHERE id = 7775;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\12_A Conclus?o da Batalha Feroz Em Dire??o ? uma Nova Batalha!_imagem.jpg' WHERE id = 7776;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\13_O Erro Maravilhoso._imagem.jpg' WHERE id = 7777;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\14_Ver?o! Mar! Festival de Biqu?ni!_imagem.jpg' WHERE id = 7778;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\12? Temporada\\\\15_Nasce o Shinigami de Peruca!_imagem.jpg' WHERE id = 7779;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\01_A Materializa??o das Zanpakut?_imagem.jpg' WHERE id = 7780;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\02_Byakuya, Desaparecendo com as P?talas de Cerejeira._imagem.jpg' WHERE id = 7781;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\03_Sode no Shirayuki vs. Rukia!_imagem.jpg' WHERE id = 7782;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\04_Zangetsu se Torna um Inimigo._imagem.jpg' WHERE id = 7783;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\05_Renji Surpreso! As Duas Zabimarus._imagem.jpg' WHERE id = 7784;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\06_Confronto! Sh?hei VS Kazeshini._imagem.jpg' WHERE id = 7785;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\07_Libera??o! O Novo Getsuga Tensh?._imagem.jpg' WHERE id = 7786;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\08_Soi Fon, Cercando as Zanpakut?s._imagem.jpg' WHERE id = 7787;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\09_Amizade ?dio Haineko & Tobiume._imagem.jpg' WHERE id = 7788;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\10_O Despertar do Hyourinmaru! A Violenta Batalha de T?shir?._imagem.jpg' WHERE id = 7789;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\11_A Trai??o de Byakuya._imagem.jpg' WHERE id = 7790;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\12_Uma Quest?o de Orgulho! Byakuya VS Renji._imagem.jpg' WHERE id = 7791;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\13_Shinigami & Zanpakut?, Combate Total._imagem.jpg' WHERE id = 7792;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\14_Luta um-a-um! Ichigo VS Senbonzakura._imagem.jpg' WHERE id = 7793;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\15_O T?o Aguardado... Kenpachi Aparece._imagem.jpg' WHERE id = 7794;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\16_A Busca por Byakuya! As 13 Divis?es Confusas._imagem.jpg' WHERE id = 7795;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\17_Miss?o Especial! Salvem o Comandante Yamamoto!_imagem.jpg' WHERE id = 7796;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\18_Shinigamis Enganados! O Mundo Entra em Crise._imagem.jpg' WHERE id = 7797;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\19_Drag?o de Gelo e Drag?o de Fogo! O Confronto mais Poderoso!_imagem.jpg' WHERE id = 7798;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\20_A Bankai de Senbonzakura! Ataque e Defesa do Mundo Real._imagem.jpg' WHERE id = 7799;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\21_Aquele Homem, Pela Causa de Kuchiki._imagem.jpg' WHERE id = 7800;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\22_Hist?ria Negra! Nasce o Pior Shinigami._imagem.jpg' WHERE id = 7801;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\23_Byakuya, A Verdade por Tr?s da Trai??o._imagem.jpg' WHERE id = 7802;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\24_A Verdadeira Identidade de Muramasa ? Revelada._imagem.jpg' WHERE id = 7803;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\25_Byakuya e Renji, O Retorno da 6? Divis?o._imagem.jpg' WHERE id = 7804;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\26_?ltimo Cap?tulo A Saga da Zanpakut? Desconhecida._imagem.jpg' WHERE id = 7805;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\27_A Raiva de Byakuya! O Colapso da Fam?lia Kuchiki._imagem.jpg' WHERE id = 7806;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\28_Um Novo Inimigo! A Verdadeira Natureza das Espadas Bestiais._imagem.jpg' WHERE id = 7807;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\29_Serpente Dispersa, Macaco Torturado._imagem.jpg' WHERE id = 7808;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\30_Terror! O Monstro que se Esconde Abaixo da Terra._imagem.jpg' WHERE id = 7809;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\31_Conclus?o! Sh?hei VS Kazeshini._imagem.jpg' WHERE id = 7810;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\32_A Pessoa com a Habilidade Desconhecida! Orihime ? o Alvo!_imagem.jpg' WHERE id = 7811;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\33_Haineko Chora! A Tr?gica Espada Bestial._imagem.jpg' WHERE id = 7812;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\34_Aprisionamento! Senbonzakura & Zabimaru._imagem.jpg' WHERE id = 7813;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\35_Batalha das F?meas Nanao VS Katen Ky?kotsu._imagem.jpg' WHERE id = 7814;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\13? Temporada\\\\36_Evolu??o! A Amea?a da Espada Dem?nio Final._imagem.jpg' WHERE id = 7815;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\01_Ichigo VS Ulquiorra, Resumo._imagem.jpg' WHERE id = 7816;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\02_Cora??es Conectados! O Punho Esquerdo Preparado para a Morte._imagem.jpg' WHERE id = 7817;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\03_O ?dio e a Inveja, O Dilema de Orihime._imagem.jpg' WHERE id = 7818;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\04_Ichigo e Ury?, V?nculo de Amizade._imagem.jpg' WHERE id = 7819;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\05_O Come?o do Desespero... Ichigo, a L?mina Inalcan??vel._imagem.jpg' WHERE id = 7820;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\06_Ichigo Morre! Orihime, o Choro de Tristeza!_imagem.jpg' WHERE id = 7821;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\07_Ichigo VS Ulquiorra! A conclus?o_imagem.jpg' WHERE id = 7822;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\08_A F?ria do Tubar?o! A Libera??o de Halibel._imagem.jpg' WHERE id = 7823;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\09_T?shir?, o Funeral de Cem Flores do C?u Congelado!_imagem.jpg' WHERE id = 7824;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\10_A Aproxima??o do Respiro Mortal, O Rei da Morte!_imagem.jpg' WHERE id = 7825;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\11_Morte em um Tiro, Soi Fon, Bankai!_imagem.jpg' WHERE id = 7826;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\12_Cl?max! Shunsui VS Starrk!_imagem.jpg' WHERE id = 7827;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\13_O Pesadelo Retorna... Renascimento do Espada_imagem.jpg' WHERE id = 7828;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\14_Shinji e S?suke... A Reuni?o do Destino!_imagem.jpg' WHERE id = 7829;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\15_Sh?hei e Kaname, O Momento da Separa??o._imagem.jpg' WHERE id = 7830;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\16_Coroa de Mentiras, O Rancor de Barragan._imagem.jpg' WHERE id = 7831;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\17_Poder da Alma! Los Lobos, Ataquem!_imagem.jpg' WHERE id = 7832;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\18_Starrk, A Batalha Solit?ria._imagem.jpg' WHERE id = 7833;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\19_Corrente de Sacrif?cio, O Passado de Halibel._imagem.jpg' WHERE id = 7834;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\20_Cem Anos de Rancor! A Vingan?a de Hiyori._imagem.jpg' WHERE id = 7835;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\21_O Retorno de Ichigo! Proteja a Cidade de Karakura._imagem.jpg' WHERE id = 7836;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\22_Gaiden! Ichigo e a L?mpada M?gica._imagem.jpg' WHERE id = 7837;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\23_A ?ltima Cartada! Ichigo a Caminho do Confronto Decisivo._imagem.jpg' WHERE id = 7838;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\24_Byakuya VS Kenpachi! Come?a a Disputa._imagem.jpg' WHERE id = 7839;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\25_Em Nome da Justi?a! O Homem que Abandonou os Shinigamis._imagem.jpg' WHERE id = 7840;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\26_Luta Desesperada com S?suke! Shinji, Shikai!_imagem.jpg' WHERE id = 7841;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\27_Guerra Total! S?suke Aizen VS Shinigamis._imagem.jpg' WHERE id = 7842;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\28_L?mina de ?dio! A F?ria de T?shir?._imagem.jpg' WHERE id = 7843;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\29_Imposs?vel de Atacar Genry?sai ? Selado!_imagem.jpg' WHERE id = 7844;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\30_Era Tudo uma Armadilha... La?os Planejados!_imagem.jpg' WHERE id = 7845;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\31_A Verdade Chocante... O Misterioso Poder Dentro de Ichigo!_imagem.jpg' WHERE id = 7846;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\32_A Espada Extens?vel! Gin VS Ichigo._imagem.jpg' WHERE id = 7847;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\33_Filme! Festival! O Festival de Filmes Shinigami._imagem.jpg' WHERE id = 7848;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\34_Comemora??o da Estr?ia no Cinema! O Pr?logo da Saga do Inferno._imagem.jpg' WHERE id = 7849;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\35_Kisuke Urahara Aparece! Pare S?suke!_imagem.jpg' WHERE id = 7850;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\36_Ichigo Perde o Esp?rito de Luta! A Expectativa de Gin._imagem.jpg' WHERE id = 7851;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\37_O ?ltimo Getsuga Tensh?! O Treinamento de Ichigo!_imagem.jpg' WHERE id = 7852;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\38_Mundo Humano e Shinigami! Especial de Ano Novo!_imagem.jpg' WHERE id = 7853;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\39_Gaiden Novamente! Agora o Inimigo ? um Monstro!_imagem.jpg' WHERE id = 7854;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\40_Desilus?o! Sh?hei vai at? as Fontes Termais!_imagem.jpg' WHERE id = 7855;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\41_Para Proteger! Ichigo VS Tensa Zangetsu._imagem.jpg' WHERE id = 7856;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\42_Situa??o de Emerg?ncia! S?suke, Nova Evolu??o!_imagem.jpg' WHERE id = 7857;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\43_Adeus... Rangiku._imagem.jpg' WHERE id = 7858;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\44_A Conclus?o da Batalha Feroz! Libere o Getsuga Tensh? Final!_imagem.jpg' WHERE id = 7859;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\45_A Resolu??o de Ichigo! O Pre?o da Batalha Feroz._imagem.jpg' WHERE id = 7860;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\46_Karakuraizer, o Detetive de Almas Ataca Novamente!_imagem.jpg' WHERE id = 7861;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\47_Inaugura??o! O Novo Capit?o da 2? Divis?o!_imagem.jpg' WHERE id = 7862;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\48_O Homem que Arrisca sua Vida na 11? Divis?o!_imagem.jpg' WHERE id = 7863;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\49_Kon ? Visto! O Segredo da Bela Secret?ria._imagem.jpg' WHERE id = 7864;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\50_O Amigo de Yachiru! O Shinigami Justiceiro Aparece!_imagem.jpg' WHERE id = 7865;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\14? Temporada\\\\51_O Dia de Folga de T?shir?!_imagem.jpg' WHERE id = 7866;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\01_Arco do Ex?rcito de Invas?o das 13 Divis?es! Incidentes Incomuns em Seireitei!_imagem.jpg' WHERE id = 7867;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\02_Renji VS Rukia! Batalha de Companheiros!_imagem.jpg' WHERE id = 7868;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\03_A Rede de Captura de Ichigo! Escape da Soul Society!_imagem.jpg' WHERE id = 7869;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\04_As 13 Divis?es, Reuni?o no Mundo Real!_imagem.jpg' WHERE id = 7870;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\05_A Revela??o dos Planos M?tuos, Ikkaku VS Ikkaku!_imagem.jpg' WHERE id = 7871;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\06_Choque! Rukia VS Rukia!_imagem.jpg' WHERE id = 7872;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\07_Proteja Ichigo! A Determina??o de Nozomi._imagem.jpg' WHERE id = 7873;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\08_Recapture Seireitei! Os Capit?es se Movem!_imagem.jpg' WHERE id = 7874;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\09_Pela Causa dos que Creem! Byakuya VS T?shir?!_imagem.jpg' WHERE id = 7875;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\10_As Duas Hinamoris, a Resolu??o de T?shir?._imagem.jpg' WHERE id = 7876;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\11_O Orgulho da Fam?lia Kuchiki! Byakuya VS Byakuya!_imagem.jpg' WHERE id = 7877;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\12_Derrotem Kageroza! Os Shinigamis v?o ? Guerra!_imagem.jpg' WHERE id = 7878;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\13_A Pesquisa Proibida... O Segredo Oculto de Nozomi!_imagem.jpg' WHERE id = 7879;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\14_Eu Quero Viver...! Zanpakut? de Nozomi._imagem.jpg' WHERE id = 7880;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\15_Para Lutar! O Despertar de Nozomi!_imagem.jpg' WHERE id = 7881;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\16_Os Reigais mais Malignos, Apari??o no Mundo Real!_imagem.jpg' WHERE id = 7882;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\17_Destruir Nozomi! A Decis?o de Genry?sai!_imagem.jpg' WHERE id = 7883;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\18_A Reiatsu Diminuindo! Ichigo, Luta Mortal pela Alma!_imagem.jpg' WHERE id = 7884;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\19_Oculta??o no Dangai Outro Ichigo!_imagem.jpg' WHERE id = 7885;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\20_Persiga Kageroza! Departamento de Desenvolvimento Tecnol?gico, Infiltra??o!_imagem.jpg' WHERE id = 7886;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\21_O Criador das Almas Modificadas._imagem.jpg' WHERE id = 7887;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\22_Os Sentimentos de Kon, os Sentimentos de Nozomi._imagem.jpg' WHERE id = 7888;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\23_Proteja Ichigo! Os V?nculos dos Amigos!_imagem.jpg' WHERE id = 7889;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\24_Reigais VS Originais, Apostando o Orgulho na Luta Feroz!_imagem.jpg' WHERE id = 7890;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\25_Arco do Ex?rcito de Invas?o, Conclus?o Final!_imagem.jpg' WHERE id = 7891;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\15? Temporada\\\\26_Obrigado._imagem.jpg' WHERE id = 7892;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\01_Estudante do 3? Ano! Roupa Nova, e um Novo Cap?tulo Come?a._imagem.jpg' WHERE id = 7893;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\02_Uma Disputa na Escola! Ichigo e Ury? Lutam Juntos!_imagem.jpg' WHERE id = 7894;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\03_Ury? ? Atacado! Uma Amea?a se Aproxima dos Amigos._imagem.jpg' WHERE id = 7895;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\04_O Usu?rio do Fullbring - K?go Ginjou._imagem.jpg' WHERE id = 7896;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\05_Um Perigo Rastejante na Fam?lia Kurosaki! A Confus?o de Ichigo!_imagem.jpg' WHERE id = 7897;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\06_O Poder do Distintivo de Substituto, o Orgulho de Ichigo!_imagem.jpg' WHERE id = 7898;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\07_O Pr?ximo Objetivo, as M?os Malignas se Aproximam de Orihime!_imagem.jpg' WHERE id = 7899;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\08_O Homem que Matou um Shinigami Substituto! Tsukishima Faz Seu Movimento._imagem.jpg' WHERE id = 7900;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\09_Fullbring, o Poder Detest?vel!_imagem.jpg' WHERE id = 7901;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\10_Tsukishima Ataca! O Treino foi Frustrado._imagem.jpg' WHERE id = 7902;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\11_Ichigo Domina o Fullbring!_imagem.jpg' WHERE id = 7903;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\12_Ichigo VS Ginjou! Para o Espa?o-Game._imagem.jpg' WHERE id = 7904;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\13_Shinigamis em Guerra! Especial de Ano Novo em Seireitei!_imagem.jpg' WHERE id = 7905;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\14_Amigo ou Inimigo! O Cora??o Invis?vel de Ginjou!_imagem.jpg' WHERE id = 7906;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\15_Amea?a Rastejante... A Habilidade de Tsukishima!_imagem.jpg' WHERE id = 7907;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\16_Choque! Xcution ataca Ginjou._imagem.jpg' WHERE id = 7908;
