UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\25_As Mariposas Resplandecentes_imagem.jpg' WHERE id = 13005;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\26_Mina Se Transforma Numa Estrela_imagem.jpg' WHERE id = 13006;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\27_A Princesa do Planeta do Fogo_imagem.jpg' WHERE id = 13007;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\28_A Lenda da Guerra das Sailors_imagem.jpg' WHERE id = 13008;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\29_O Fim da Princesa do Planeta do Fogo_imagem.jpg' WHERE id = 13009;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\30_Contagem Regressiva para a Destrui??o - A ?ltima Batalha das Sailor Guerreiras_imagem.jpg' WHERE id = 13010;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\31_A Amea?a de Sailor Gal?xia_imagem.jpg' WHERE id = 13011;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\32_A Morte das Estrelas - O ?ltimo Confronto de Urano e Netuno_imagem.jpg' WHERE id = 13012;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\33_A Luz da Esperan?a - A Batalha Final pela Gal?xia_imagem.jpg' WHERE id = 13013;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\34_O Amor de Serena - O Luar Ilumina a Gal?xia_imagem.jpg' WHERE id = 13014;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\01_Sakura e o misterioso livro m?gico.avi' WHERE id = 13015;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\02_A maravilhosa amiga de Sakura.avi' WHERE id = 13016;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\03_O emocionante primeiro encontro da Sakura.avi' WHERE id = 13017;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\04_O atarefado domingo de Sakura.avi' WHERE id = 13018;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\05_Sakura, o panda e a loja.avi' WHERE id = 13019;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\06_Sakura e as mem?rias da m?e.avi' WHERE id = 13020;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\07_A primeira batalha de Sakura contra o misterioso ladr?o.avi' WHERE id = 13021;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\08_O rival de Sakura.avi' WHERE id = 13022;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\09_Sakura e o pregador misterioso.avi' WHERE id = 13023;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\10_Sakura e o dia dos desportos.avi' WHERE id = 13024;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\11_Sakura e Tomoyo e a grande mans?o.avi' WHERE id = 13025;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\12_O dia intermin?vel de Sakura.avi' WHERE id = 13026;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\13_Sakura e o elefante na competi??o de for?a.avi' WHERE id = 13027;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\14_Sakura, Touya e Cinderela.avi' WHERE id = 13028;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\15_A grande briga de Sakura e Kero.avi' WHERE id = 13029;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\16_Sakura e o arco-?ris das recorda??es.avi' WHERE id = 13030;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\17_A aterradora prova de coragem da Sakura.avi' WHERE id = 13031;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\18_Sakura, Yukito e o festival de ver?o.avi' WHERE id = 13032;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\19_Sakura e os deveres de ver?o.avi' WHERE id = 13033;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\20_A nova aluna que enfrenta a Sakura.avi' WHERE id = 13034;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\21_A longa maratona da Sakura.avi' WHERE id = 13035;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\22_Sakura e o seu am?vel pai.avi' WHERE id = 13036;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\23_Sakura, Tomoyo e uma linda can??o.avi' WHERE id = 13037;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\24_A pequena grande aventura da Sakura.avi' WHERE id = 13038;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\25_Sakura e a outra Sakura.avi' WHERE id = 13039;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\26_Sakura e a sua lind?ssima professora.avi' WHERE id = 13040;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\27_Sakura e o templo das recorda??es.avi' WHERE id = 13041;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\28_Sakura e as cartas m?gicas.avi' WHERE id = 13042;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\29_Sakura e a pastelaria.avi' WHERE id = 13043;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\30_Sakura e a carta ferida.avi' WHERE id = 13044;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\31_Sakura e o livro sem nome.avi' WHERE id = 13045;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\32_Sakura, Kero e Syaoran.avi' WHERE id = 13046;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\33_Sakura e a Carta do Gelo.avi' WHERE id = 13047;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\34_Sakura, Yukito e a lua cheia.avi' WHERE id = 13048;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\1? Temporada\\\\35_Que maravilha de Natal.avi' WHERE id = 13049;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\01_Sakura, Yukito e novo ano escolar.avi' WHERE id = 13050;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\02_Sakura e a perda de voz da Tomoyo.avi' WHERE id = 13051;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\03_Sakura e a aventura de colher morangos.avi' WHERE id = 13052;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\04_Dia de febre e enjoos.avi' WHERE id = 13053;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\05_Sakura no sonho.avi' WHERE id = 13054;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\06_Sakura, Syaoran e o mar de areia.avi' WHERE id = 13055;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\07_Sakura e o festival das artes.avi' WHERE id = 13056;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\08_Sakura e a despedida da Meiling.avi' WHERE id = 13057;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\09_Sakura, Kero e a misteriosa professora.avi' WHERE id = 13058;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\10_Sakura e a ?ltima carta de Clow.avi' WHERE id = 13059;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\2? Temporada\\\\11_Sakura e o Ju?zo Final.avi' WHERE id = 13060;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\01_Sakura e o misterioso aluno novo.avi' WHERE id = 13061;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\02_Sakura e o despertar da chave estrela.avi' WHERE id = 13062;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\03_Sakura e o piano perigoso.avi' WHERE id = 13063;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\04_Sakura, Syaoran e o fio invis?vel.avi' WHERE id = 13064;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\05_Sakura e o grande ursinho de peluche.avi' WHERE id = 13065;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\06_Sakura e o aviso das ovelhas.avi' WHERE id = 13066;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\07_Sakura e a bicicleta assustada.avi' WHERE id = 13067;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\08_Sakura e o di?rio das recorda??es.avi' WHERE id = 13068;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\09_Sakura no pa?s das maravilhas.avi' WHERE id = 13069;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\10_Sakura, Kero e a merenda.avi' WHERE id = 13070;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\11_Sakura, Syaoran e o elevador.avi' WHERE id = 13071;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\12_Sakura e o problema duplo.avi' WHERE id = 13072;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\13_Sakura, Tomoyo e a bola armadilhada.avi' WHERE id = 13073;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\14_Sakura e uma querida amiga.avi' WHERE id = 13074;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\15_Sakura, a carta e as prendas.avi' WHERE id = 13075;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\16_Sakura e a estranha profecia.avi' WHERE id = 13076;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\17_Sakura, a piscina e a onda gigante.avi' WHERE id = 13077;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\18_Sakura e a aula de ski na neve.avi' WHERE id = 13078;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\19_Sakura, Yukito e o poder da desmaterializa??o.avi' WHERE id = 13079;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\20_A pessoa de quem a Sakura gosta mais.avi' WHERE id = 13080;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\21_Sakura, Syaoran e o templo Tsukimine.avi' WHERE id = 13081;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\22_Sakura, o passado e o Mestre Clow.avi' WHERE id = 13082;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\23_Sakura encontra-se com o Mestre Clow.avi' WHERE id = 13083;
UPDATE episodio SET capa_url = 'F:\\\\Sakura Card Captor\\\\3? Temporada\\\\24_Sakura e os seus verdadeiros sentimentos.avi' WHERE id = 13084;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\01_O In?cio_imagem.jpg' WHERE id = 13085;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\02_O Samurai Chamado Jack_imagem.jpg' WHERE id = 13086;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\03_A Primeira Luta_imagem.jpg' WHERE id = 13087;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\04_Jack, os L?zudos e os Chritchellites_imagem.jpg' WHERE id = 13088;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\05_Jack no Espa?o_imagem.jpg' WHERE id = 13089;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\06_Jack e a Mulher Guerreira_imagem.jpg' WHERE id = 13090;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\07_Jack e os Tr?s Arqueiros Cegos_imagem.jpg' WHERE id = 13091;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\08_Jack Contra O Jack Furioso_imagem.jpg' WHERE id = 13092;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\09_Jack Debaixo do Mar_imagem.jpg' WHERE id = 13093;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\10_Jack e o Monstro de Lava_imagem.jpg' WHERE id = 13094;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\11_Jack e o Escoc?s_imagem.jpg' WHERE id = 13095;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\12_Jack e os Gangsters_imagem.jpg' WHERE id = 13096;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\1? Temporada\\\\13_Os Contos de Fadas de Aku_imagem.jpg' WHERE id = 13097;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\01_Jack Aprende a Saltar Bem_imagem.jpg' WHERE id = 13098;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\02_As Hist?rias de Jack_imagem.jpg' WHERE id = 13099;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\03_Jack e a Bofetada_imagem.jpg' WHERE id = 13100;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\04_Jack e o Escoc?s - Parte 2_imagem.jpg' WHERE id = 13101;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\05_Jack e os Ultra Rob?s_imagem.jpg' WHERE id = 13102;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\06_Jack Recorda o Passado_imagem.jpg' WHERE id = 13103;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\07_Jack e os Monges_imagem.jpg' WHERE id = 13104;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\08_Jack e o Drag?o Peidorreiro_imagem.jpg' WHERE id = 13105;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\09_Jack e os Ca?adores_imagem.jpg' WHERE id = 13106;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\10_Jack Contra Demongo, o Colecionador de Almas_imagem.jpg' WHERE id = 13107;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\11_Jack Est? Nu_imagem.jpg' WHERE id = 13108;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\12_Jack e os Espartanos_imagem.jpg' WHERE id = 13109;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\2? Temporada\\\\13_As Sand?lias de Jack_imagem.jpg' WHERE id = 13110;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\01_Jack Galinha_imagem.jpg' WHERE id = 13111;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\02_Jack e a Rave_imagem.jpg' WHERE id = 13112;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\03_O Bom, o Mau e o Belo_imagem.jpg' WHERE id = 13113;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\04_Jack e os Zombies_imagem.jpg' WHERE id = 13114;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\05_Jack e o Escaravelho_imagem.jpg' WHERE id = 13115;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\06_Jack e as Criaturas Ambulantes_imagem.jpg' WHERE id = 13116;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\07_Jack e a Criatura Inc?moda_imagem.jpg' WHERE id = 13117;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\08_Jack e o Feiticeiro do P?ntano_imagem.jpg' WHERE id = 13118;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\09_Jack e a Casa Assombrada_imagem.jpg' WHERE id = 13119;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\10_Jack, os Monges e o Filho do Mestre Anci?o_imagem.jpg' WHERE id = 13120;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\11_O Nascimento do Mal - Parte 1_imagem.jpg' WHERE id = 13121;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\12_O Nascimento do Mal - Parte 2_imagem.jpg' WHERE id = 13122;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\3? Temporada\\\\13_Jack e o Labirinto_imagem.jpg' WHERE id = 13123;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\01_Samurai Contra Ninja_imagem.jpg' WHERE id = 13124;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\02_Rob? Samurai Contra Mondo Bot_imagem.jpg' WHERE id = 13125;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\03_Samurai Contra Samurai_imagem.jpg' WHERE id = 13126;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\04_A Contamina??o Aku_imagem.jpg' WHERE id = 13127;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\05_A Princesa e os Ca?adores de Recompensas_imagem.jpg' WHERE id = 13128;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\06_O Escoc?s Salva Jack - Parte 1_imagem.jpg' WHERE id = 13129;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\07_O Escoc?s Salva Jack - Parte 2_imagem.jpg' WHERE id = 13130;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\08_Jack e o Pr?ncipe e Princesa Voadores_imagem.jpg' WHERE id = 13131;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\09_Jack Contra Aku_imagem.jpg' WHERE id = 13132;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\10_As Quatro Esta??es da Morte_imagem.jpg' WHERE id = 13133;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\11_A hist?ria do X49_imagem.jpg' WHERE id = 13134;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\12_O Jovem Jack em ?frica_imagem.jpg' WHERE id = 13135;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\4? Temporada\\\\13_Jack e o Beb?_imagem.jpg' WHERE id = 13136;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\5? Temporada - Legendado\\\\01_XCII_imagem.jpg' WHERE id = 13137;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\5? Temporada - Legendado\\\\02_XCIII_imagem.jpg' WHERE id = 13138;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\5? Temporada - Legendado\\\\03_XCIV_imagem.jpg' WHERE id = 13139;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\5? Temporada - Legendado\\\\04_XCV_imagem.jpg' WHERE id = 13140;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\5? Temporada - Legendado\\\\05_XCVI_imagem.jpg' WHERE id = 13141;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\5? Temporada - Legendado\\\\06_XCVII_imagem.jpg' WHERE id = 13142;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\5? Temporada - Legendado\\\\07_XCVIII_imagem.jpg' WHERE id = 13143;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\5? Temporada - Legendado\\\\08_XCIX_imagem.jpg' WHERE id = 13144;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\5? Temporada - Legendado\\\\09_C_imagem.jpg' WHERE id = 13145;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Jack\\\\5? Temporada - Legendado\\\\10_CI_imagem.jpg' WHERE id = 13146;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\01_A terra da sombra_imagem.jpg' WHERE id = 13147;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\02_A gl?ria de Demon_imagem.jpg' WHERE id = 13148;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\03_O in?cio da busca, parte 1_imagem.jpg' WHERE id = 13149;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\04_O in?cio da busca, parte 2_imagem.jpg' WHERE id = 13150;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\05_A pris?o de C?sar_imagem.jpg' WHERE id = 13151;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\06_O contra ataque_imagem.jpg' WHERE id = 13152;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\07_Rompendo o rochedo_imagem.jpg' WHERE id = 13153;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\08_Amigo ou inimigo_imagem.jpg' WHERE id = 13154;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\09_Hector nas alturas_imagem.jpg' WHERE id = 13155;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\10_Nos mares do c?u_imagem.jpg' WHERE id = 13156;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\11_Ataque ? dinastia_imagem.jpg' WHERE id = 13157;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\12_Na escurid?o_imagem.jpg' WHERE id = 13158;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\13_O destino da armadura samurai_imagem.jpg' WHERE id = 13159;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\14_A armadura da vida_imagem.jpg' WHERE id = 13160;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\15_A batalha do Monge_imagem.jpg' WHERE id = 13161;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\16_A batalha no castelo de Scorpio_imagem.jpg' WHERE id = 13162;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\17_A lenda da armadura_imagem.jpg' WHERE id = 13163;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\18_Scorpio vencedor_imagem.jpg' WHERE id = 13164;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\19_Hector luta contra seu destino_imagem.jpg' WHERE id = 13165;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\20_Samurais contra Sarambo_imagem.jpg' WHERE id = 13166;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\21_A super armadura de Hector_imagem.jpg' WHERE id = 13167;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\22_O desafio mortal do lorde Espadachim Lutador_imagem.jpg' WHERE id = 13168;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\23_O sacrificio de Fogo Branco_imagem.jpg' WHERE id = 13169;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\24_Sol Maligno - O embaixador do mal_imagem.jpg' WHERE id = 13170;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\25_O irm?o g?meo de Jorge da ?gua_imagem.jpg' WHERE id = 13171;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\26_A armadura deve ser destru?da_imagem.jpg' WHERE id = 13172;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\27_Combate na areia_imagem.jpg' WHERE id = 13173;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\28_Lady Kaira e o mundo das trevas_imagem.jpg' WHERE id = 13174;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\29_Demon ressuscita_imagem.jpg' WHERE id = 13175;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\30_Scorpio ataca novamente_imagem.jpg' WHERE id = 13176;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\31_A lenda da armadura branca_imagem.jpg' WHERE id = 13177;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\32_Estrat?gias do mundo das trevas_imagem.jpg' WHERE id = 13178;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\33_Em busca do tesouro secreto_imagem.jpg' WHERE id = 13179;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\34_O desafio de Tommy_imagem.jpg' WHERE id = 13180;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\35_O retorno dos Samurai Warriors_imagem.jpg' WHERE id = 13181;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\36_Truques baratos_imagem.jpg' WHERE id = 13182;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\37_A armadura de Demon ressuscita_imagem.jpg' WHERE id = 13183;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\38_A dama do mal v? a luz_imagem.jpg' WHERE id = 13184;
UPDATE episodio SET capa_url = 'F:\\\\Samurai Warriors\\\\39_A vit?ria dos Samurais_imagem.jpg' WHERE id = 13185;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\01_Kenshin Battousai, o Espadachim Legend?rio_imagem.jpg' WHERE id = 13186;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\02_O Aluno Rebelde_imagem.jpg' WHERE id = 13187;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\03_O Homem Que Deixou o Passado_imagem.jpg' WHERE id = 13188;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\04_O Lutador Sanosuke_imagem.jpg' WHERE id = 13189;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\05_Kenshin contra Zanza_imagem.jpg' WHERE id = 13190;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\06_O Visitante Que Veio Das Trevas_imagem.jpg' WHERE id = 13191;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\07_A Grande Luta_imagem.jpg' WHERE id = 13192;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\08_A Mulher Misteriosa_imagem.jpg' WHERE id = 13193;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\09_Uma Gangue Poderosa_imagem.jpg' WHERE id = 13194;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\10_A Tentativa de um Resgate_imagem.jpg' WHERE id = 13195;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\11_Uma Colis?o Entre a Luz e as Trevas_imagem.jpg' WHERE id = 13196;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\12_O Nascimento de Um Espadachim_imagem.jpg' WHERE id = 13197;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\13_O Lutador de Sum?_imagem.jpg' WHERE id = 13198;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\14_A M?dica Nova na Cidade_imagem.jpg' WHERE id = 13199;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\15_Os Retalhadores Legend?rios_imagem.jpg' WHERE id = 13200;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\16_A Hora da Verdade_imagem.jpg' WHERE id = 13201;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\17_Marimo, o Canh?o Humano_imagem.jpg' WHERE id = 13202;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\18_A Luta de Yahiko_imagem.jpg' WHERE id = 13203;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\19_A Fantasia do Reino Proibido_imagem.jpg' WHERE id = 13204;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\20_A Volta do Estilo Shinko_imagem.jpg' WHERE id = 13205;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\21_A Ambi??o de Raijuuta_imagem.jpg' WHERE id = 13206;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\22_A Viagem de Trem_imagem.jpg' WHERE id = 13207;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\23_Sanosuke Volta ao Passado_imagem.jpg' WHERE id = 13208;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\24_Kenshin Contra Sanosuke_imagem.jpg' WHERE id = 13209;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\25_O Navio Pirata_imagem.jpg' WHERE id = 13210;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\26_A Famosa Pirata Shura_imagem.jpg' WHERE id = 13211;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 1\\\\27_O Fim dos Piratas_imagem.jpg' WHERE id = 13212;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\01_O Retorno do Lobo_imagem.jpg' WHERE id = 13213;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\02_O Inimigo Mais Poderoso_imagem.jpg' WHERE id = 13214;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\03_A Vingan?a do Vil?o_imagem.jpg' WHERE id = 13215;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\04_A Despedida de Kenshin_imagem.jpg' WHERE id = 13216;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\05_A Vida Sem Kenshin_imagem.jpg' WHERE id = 13217;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\06_? Procura de Kenshin_imagem.jpg' WHERE id = 13218;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\07_Uma Garota Valente_imagem.jpg' WHERE id = 13219;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\08_A Cidade Roubada_imagem.jpg' WHERE id = 13220;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\09_O Encontro de Shishio e Kenshin_imagem.jpg' WHERE id = 13221;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\10_Sojiro Versus Kenshin_imagem.jpg' WHERE id = 13222;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\11_O Treinamento de Sanosuke_imagem.jpg' WHERE id = 13223;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\12_A Espada Mais Poderosa_imagem.jpg' WHERE id = 13224;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\13_A Luta Fatal_imagem.jpg' WHERE id = 13225;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\14_O Encontro Com o Mestre_imagem.jpg' WHERE id = 13226;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\15_A Trai??o de Aoshi_imagem.jpg' WHERE id = 13227;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\16_Entre a Vida e a Morte_imagem.jpg' WHERE id = 13228;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\17_A Gangue Mais Poderosa_imagem.jpg' WHERE id = 13229;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\18_A Fuga de Shishio_imagem.jpg' WHERE id = 13230;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\19_O Navio de A?o_imagem.jpg' WHERE id = 13231;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\20_O Encontro da Gangue_imagem.jpg' WHERE id = 13232;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\21_O Passado de Anji_imagem.jpg' WHERE id = 13233;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\22_Os Olhos do Cora??o_imagem.jpg' WHERE id = 13234;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\23_Hora de Honrar a Promessa_imagem.jpg' WHERE id = 13235;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\24_O Duelo Continua_imagem.jpg' WHERE id = 13236;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\25_O Ataque a Aoiya_imagem.jpg' WHERE id = 13237;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\26_O Gigante versus o Super-Homem_imagem.jpg' WHERE id = 13238;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\27_O Para?so Contra a Terra_imagem.jpg' WHERE id = 13239;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\28_O Passado de Sojiro_imagem.jpg' WHERE id = 13240;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\29_A ?ltima Batalha de Sojiro_imagem.jpg' WHERE id = 13241;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\30_A Batalha Final_imagem.jpg' WHERE id = 13242;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\31_A Batalha Continua_imagem.jpg' WHERE id = 13243;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\32_A Luta Continua_imagem.jpg' WHERE id = 13244;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\33_Uma Luta Sem Vencedor_imagem.jpg' WHERE id = 13245;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\34_O Destino do Grupo Juppongatana_imagem.jpg' WHERE id = 13246;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 2\\\\35_A Volta ao Lar_imagem.jpg' WHERE id = 13247;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\01_A Garota do Espadachim_imagem.jpg' WHERE id = 13248;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\02_Pr?ncipe Por um Dia_imagem.jpg' WHERE id = 13249;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\03_O Cachorro Famoso_imagem.jpg' WHERE id = 13250;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\04_O Anel de Noivado_imagem.jpg' WHERE id = 13251;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\05_A Espada Lend?ria_imagem.jpg' WHERE id = 13252;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\06_A Profecia se Cumprir?_imagem.jpg' WHERE id = 13253;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\07_O Momento da Verdade_imagem.jpg' WHERE id = 13254;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\08_Kenshin Nas Trevas_imagem.jpg' WHERE id = 13255;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\09_A Trai??o_imagem.jpg' WHERE id = 13256;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\10_O Passado Triste de Shogo e Sayo_imagem.jpg' WHERE id = 13257;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\11_O Plano Para Matar_imagem.jpg' WHERE id = 13258;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\12_A Tristeza de Sanosuke_imagem.jpg' WHERE id = 13259;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\13_A ?ltima Guerra Santa_imagem.jpg' WHERE id = 13260;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\14_Uma Nova Chance_imagem.jpg' WHERE id = 13261;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\15_Falsa Identidade_imagem.jpg' WHERE id = 13262;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\16_O Artista_imagem.jpg' WHERE id = 13263;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\17_Aprendendo a Lutar_imagem.jpg' WHERE id = 13264;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\18_O Treinamento_imagem.jpg' WHERE id = 13265;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\19_Acontecimento em Shiragaya_imagem.jpg' WHERE id = 13266;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\20_Mais Precioso Que o Dinheiro_imagem.jpg' WHERE id = 13267;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\21_O Elixir Milagroso_imagem.jpg' WHERE id = 13268;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\22_B?lsamo Divino_imagem.jpg' WHERE id = 13269;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\23_A Armadilha Est? Pronta_imagem.jpg' WHERE id = 13270;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\24_Dia Vermelho_imagem.jpg' WHERE id = 13271;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\25_O Fim dos Cavaleiros Negros_imagem.jpg' WHERE id = 13272;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\26_Promessa Eterna_imagem.jpg' WHERE id = 13273;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\27_Entrega Para Meu Anjo_imagem.jpg' WHERE id = 13274;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\28_O Mist?rio do Pentagrama_imagem.jpg' WHERE id = 13275;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\29_Pr?ximo Alvo_imagem.jpg' WHERE id = 13276;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\30_Lei Marcial_imagem.jpg' WHERE id = 13277;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\31_O Inimigo Aguarda_imagem.jpg' WHERE id = 13278;
UPDATE episodio SET capa_url = 'F:\\\\Samurai X\\\\Parte 3\\\\32_O Desenlace Final_imagem.jpg' WHERE id = 13279;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\01_Weird_imagem.jpg' WHERE id = 13280;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\02_Girls_imagem.jpg' WHERE id = 13281;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\03_Psyche_imagem.jpg' WHERE id = 13282;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\04_Religion_imagem.jpg' WHERE id = 13283;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\05_Distortion_imagem.jpg' WHERE id = 13284;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\06_Kids_imagem.jpg' WHERE id = 13285;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\07_Society_imagem.jpg' WHERE id = 13286;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\08_Rumors_imagem.jpg' WHERE id = 13287;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\09_Protocol_imagem.jpg' WHERE id = 13288;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\10_Love_imagem.jpg' WHERE id = 13289;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\11_Infornography_imagem.jpg' WHERE id = 13290;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\12_Landscape_imagem.jpg' WHERE id = 13291;
UPDATE episodio SET capa_url = 'F:\\\\Serial Experiments Lain\\\\13_Ego_imagem.jpg' WHERE id = 13292;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\01_On Shura Sowaka_imagem.jpg' WHERE id = 13293;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\02_Grande Conspira??o_imagem.jpg' WHERE id = 13294;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\03_O Desafio de Ryoma_imagem.jpg' WHERE id = 13295;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\04_O Despertar do Somma,a Explos?o_imagem.jpg' WHERE id = 13296;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\05_Pena! Traz me a Verdade_imagem.jpg' WHERE id = 13297;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\06_A Batalha do Amor e da Dor_imagem.jpg' WHERE id = 13298;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\07_As Armadilhas da Caverna do Luar_imagem.jpg' WHERE id = 13299;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\08_Rumo a ?rvore do Palacio Celestial_imagem.jpg' WHERE id = 13300;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\09_A ?rvore Sagrada da Vida_imagem.jpg' WHERE id = 13301;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\10_Gai Com For?a Total,a Luta da Morte_imagem.jpg' WHERE id = 13302;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\11_Lengue, A Tragedia da Fiel Guerreira_imagem.jpg' WHERE id = 13303;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\12_O Duelo da Amizade_imagem.jpg' WHERE id = 13304;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\13_O Contrataque da Forma??o Mandala_imagem.jpg' WHERE id = 13305;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\14_No Liniar do Amor e do ?dio_imagem.jpg' WHERE id = 13306;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\15_A Temivel Triade do Dem?nio_imagem.jpg' WHERE id = 13307;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\16_O Retorno de Hakeshi_imagem.jpg' WHERE id = 13308;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\17_O Terror da Rosa Vermelha_imagem.jpg' WHERE id = 13309;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\18_Em Busca da Mem?ria Perdida_imagem.jpg' WHERE id = 13310;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\19_Adeus Terra Natal,A Dificil Decis?o_imagem.jpg' WHERE id = 13311;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\20_O Roubo da Tatica Secreta_imagem.jpg' WHERE id = 13312;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\21_O Perigo Dos Shakitis Conectados_imagem.jpg' WHERE id = 13313;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\22_A ?ltima Batalha de Ryoma_imagem.jpg' WHERE id = 13314;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\23_O Palacio Celestial no Meio da Tempestade_imagem.jpg' WHERE id = 13315;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\24_O Adeus de Indra_imagem.jpg' WHERE id = 13316;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\25_A Dor do Destino,Shurato Contra Gai_imagem.jpg' WHERE id = 13317;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\26_Asra o Novo Inimigo_imagem.jpg' WHERE id = 13318;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\27_A Procura do Poderoso Shakiti_imagem.jpg' WHERE id = 13319;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\28_O Destino do Mau, O Retorno de Gai_imagem.jpg' WHERE id = 13320;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\29_O Ataque de Leiga_imagem.jpg' WHERE id = 13321;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\30_O Escolhido_imagem.jpg' WHERE id = 13322;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\31_O Somma da Amizade_imagem.jpg' WHERE id = 13323;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\32_O Surgimento do Shakiti_imagem.jpg' WHERE id = 13324;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\33_O Bem ou o Mau, A Escolha do Deus da Cria??o_imagem.jpg' WHERE id = 13325;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\34_A Batalha Final o Ataque de Odio_imagem.jpg' WHERE id = 13326;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\35_Depois Das Trevas o Futuro_imagem.jpg' WHERE id = 13327;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\36_Convoca??o Urgente - A Batalha Final_imagem.jpg' WHERE id = 13328;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\37_O Ataque Das Aguas Perdidas_imagem.jpg' WHERE id = 13329;
UPDATE episodio SET capa_url = 'F:\\\\Shurato\\\\38_A Eternidade Para o Rei Shura_imagem.jpg' WHERE id = 13330;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\01_Opera??o Strix_imagem.jpg' WHERE id = 13331;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\02_Garantir uma esposa_imagem.jpg' WHERE id = 13332;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\03_Preparativos para a entrevista_imagem.jpg' WHERE id = 13333;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\04_A entrevista do col?gio de elite_imagem.jpg' WHERE id = 13334;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\05_Aprovados ou reprovados_imagem.jpg' WHERE id = 13335;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\06_Esquema de amizade_imagem.jpg' WHERE id = 13336;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\07_Segundo filho do alvo_imagem.jpg' WHERE id = 13337;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\08_Camuflagem contra a pol?cia secreta_imagem.jpg' WHERE id = 13338;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\09_Ostente o seu amor_imagem.jpg' WHERE id = 13339;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\10_O grande plano de queimada_imagem.jpg' WHERE id = 13340;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\11_Estrela_imagem.jpg' WHERE id = 13341;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 1\\\\12_Parque dos pinguins_imagem.jpg' WHERE id = 13342;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\01_Projeto Apple_imagem.jpg' WHERE id = 13343;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\02_Desarmar a bomba-rel?gio_imagem.jpg' WHERE id = 13344;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\03_Um novo integrante da fam?lia_imagem.jpg' WHERE id = 13345;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\04_A cozinha de Yor - O grande plano de romance do informante_imagem.jpg' WHERE id = 13346;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\05_Execute o plano do grifo - Dama Met?lica - Omelete de arroz_imagem.jpg' WHERE id = 13347;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\06_O tio professor particular - Daybreak_imagem.jpg' WHERE id = 13348;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\07_Um plano de vingan?a contra Desmond - A mam?e se tornou o vento_imagem.jpg' WHERE id = 13349;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\08_Investiga??o do hospital geral - C?digo secreto_imagem.jpg' WHERE id = 13350;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\09_Nightfall - Primeiro ataque de ci?mes_imagem.jpg' WHERE id = 13351;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\10_Campbelldon - O torneio clandestino de t?nis_imagem.jpg' WHERE id = 13352;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\11_Um caminho sem volta_imagem.jpg' WHERE id = 13353;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\12_O papel de uma m?e e de uma esposa - Sa?da ?s compras_imagem.jpg' WHERE id = 13354;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\1? Temporada\\\\Parte 2\\\\13_Primeiro contato_imagem.jpg' WHERE id = 13355;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\01_Siga a mam?e e o papai_imagem.jpg' WHERE id = 13356;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\02_Estrat?gia de sobreviv?ncia de Bond -  Pesquisa de campo de Damian_imagem.jpg' WHERE id = 13357;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\03_Dever e fam?lia - O grande Bondman - Cora??o de crian?a - Despertar_imagem.jpg' WHERE id = 13358;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\04_Confeitaria do conhecimento - O grande plano de romance do informante 2_imagem.jpg' WHERE id = 13359;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\05_Plano de cruzar a fronteira_imagem.jpg' WHERE id = 13360;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\06_O temeroso cruzeiro de luxo_imagem.jpg' WHERE id = 13361;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\07_Para quem ? essa miss?o_imagem.jpg' WHERE id = 13362;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\08_Sinfonia em alto mar_imagem.jpg' WHERE id = 13363;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\09_A m?o que se liga ao futuro_imagem.jpg' WHERE id = 13364;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\10_Aproveite o resort ao m?ximo - Se gabando das f?rias_imagem.jpg' WHERE id = 13365;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\11_Meia-noite em Berlint - Dia a dia de Nightfall_imagem.jpg' WHERE id = 13366;
UPDATE episodio SET capa_url = 'F:\\\\Spy X Family\\\\2? Temporada\\\\12_Parte da fam?lia - Legendado_imagem.jpg' WHERE id = 13367;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\01_A Viagem! Um Convite a S?o Francisco_imagem.jpg' WHERE id = 13415;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\02_O ?s da For?a A?rea_imagem.jpg' WHERE id = 13416;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\03_Duelo Em Hong Kong_imagem.jpg' WHERE id = 13417;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\04_No Inferno De Hong Kong_imagem.jpg' WHERE id = 13418;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\05_Um Homem Chamado Drag?o Voador_imagem.jpg' WHERE id = 13419;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\06_O Segredo Das Artes Marciais_imagem.jpg' WHERE id = 13420;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\07_A Vingan?a de Ashura_imagem.jpg' WHERE id = 13421;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\08_A Sombra Do Terror_imagem.jpg' WHERE id = 13422;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\09_Karat? Contra Muai Tai_imagem.jpg' WHERE id = 13423;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\10_O Mensageiro Das Trevas_imagem.jpg' WHERE id = 13424;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\11_Na Trilha Das Feras_imagem.jpg' WHERE id = 13425;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\12_Na Caverna Do Dem?nio_imagem.jpg' WHERE id = 13426;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\13_Em Busca Do Hadouken_imagem.jpg' WHERE id = 13427;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\14_O Pr?ncipe Sanguin?rio_imagem.jpg' WHERE id = 13428;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\15_Encontro de Gigantes_imagem.jpg' WHERE id = 13429;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\16_A M?scara do Poder_imagem.jpg' WHERE id = 13430;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\17_Os Tent?culos da Morte_imagem.jpg' WHERE id = 13431;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\18_A Bela Assassina_imagem.jpg' WHERE id = 13432;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\19_Agentes Secretos_imagem.jpg' WHERE id = 13433;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\20_Hadouken, a Forma Preponderante do Cosmo_imagem.jpg' WHERE id = 13434;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\21_Os Prisioneiros do Castelo_imagem.jpg' WHERE id = 13435;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\22_A Manifesta??o do Hadouken_imagem.jpg' WHERE id = 13436;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\23_O Brilho Misterioso_imagem.jpg' WHERE id = 13437;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\24_O Reencontro Com o Pesadelo_imagem.jpg' WHERE id = 13438;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\25_A Luta Violenta_imagem.jpg' WHERE id = 13439;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\26_A Morte do Amigo_imagem.jpg' WHERE id = 13440;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\27_A Colis?o de Emerg?ncias_imagem.jpg' WHERE id = 13441;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\28_O Dom?nio de Bison_imagem.jpg' WHERE id = 13442;
UPDATE episodio SET capa_url = 'F:\\\\Street Fighter II - Victory\\\\29_A Batalha Final_imagem.jpg' WHERE id = 13443;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\01_O Mundo das Espadas_imagem.jpg' WHERE id = 13444;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\02_Beater_imagem.jpg' WHERE id = 13445;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\03_Rena do Nariz Vermelho_imagem.jpg' WHERE id = 13446;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\04_O Espadachim Negro_imagem.jpg' WHERE id = 13447;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\05_Um Crime Entre Paredes_imagem.jpg' WHERE id = 13448;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\06_O Vingador Fantasma_imagem.jpg' WHERE id = 13449;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\07_A Temperatura do Cora??o_imagem.jpg' WHERE id = 13450;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\08_A Dan?a das Espadas Preta e Branca_imagem.jpg' WHERE id = 13451;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\09_O Monstro de Olhos Azuis_imagem.jpg' WHERE id = 13452;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\10_Inten??o de Matar_imagem.jpg' WHERE id = 13453;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\11_A Garota no Orvalho da Manh?_imagem.jpg' WHERE id = 13454;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\12_O Cora??o de Yui_imagem.jpg' WHERE id = 13455;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\13_? Beira do Abismo do Inferno_imagem.jpg' WHERE id = 13456;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 1\\\\14_O Fim do Mundo_imagem.jpg' WHERE id = 13457;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\01_O Retorno_imagem.jpg' WHERE id = 13458;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\02_A Terra das Fadas_imagem.jpg' WHERE id = 13459;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\03_A Rainha Ref?m_imagem.jpg' WHERE id = 13460;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\04_Em Dire??o ? ?rvore do Mundo_imagem.jpg' WHERE id = 13461;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\05_O Corredor Lugru_imagem.jpg' WHERE id = 13462;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\06_O General da Chama Ardente_imagem.jpg' WHERE id = 13463;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\07_A Verdade Sobre Alfheim_imagem.jpg' WHERE id = 13464;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\08_O Grande Desafio_imagem.jpg' WHERE id = 13465;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\09_La?os_imagem.jpg' WHERE id = 13466;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\10_O Her?i Dourado_imagem.jpg' WHERE id = 13467;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\1? Temporada\\\\Parte 2\\\\11_A Semente do Mundo_imagem.jpg' WHERE id = 13468;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\01_O Mundo das Armas_imagem.jpg' WHERE id = 13469;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\02_A Francoatiradora de Gel_imagem.jpg' WHERE id = 13470;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\03_Memorias de Sangue Fresco_imagem.jpg' WHERE id = 13471;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\04_GGO_imagem.jpg' WHERE id = 13472;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\05_Arma e Espada_imagem.jpg' WHERE id = 13473;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\06_Duelo em Terras Desoladas_imagem.jpg' WHERE id = 13474;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\07_Mem?rias de Escarlate_imagem.jpg' WHERE id = 13475;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\08_A Bala das Balas_imagem.jpg' WHERE id = 13476;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\09_Death Gun_imagem.jpg' WHERE id = 13477;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\10_O Perseguidor da Morte_imagem.jpg' WHERE id = 13478;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\11_O Sentido da For?a_imagem.jpg' WHERE id = 13479;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\12_A Bala Fantasma - Parte 1_imagem.jpg' WHERE id = 13480;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\13_A Bala Fantasma - Parte 2_imagem.jpg' WHERE id = 13481;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 1\\\\14_Um Pequeno Passo_imagem.jpg' WHERE id = 13482;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 2\\\\01_A Rainha do Lago_imagem.jpg' WHERE id = 13483;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 2\\\\02_O Rei dos Gigantes_imagem.jpg' WHERE id = 13484;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 2\\\\03_Excabilur_imagem.jpg' WHERE id = 13485;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 3\\\\01_Casa da Floresta_imagem.jpg' WHERE id = 13486;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 3\\\\02_Zekken_imagem.jpg' WHERE id = 13487;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 3\\\\03_Sleeping Knights_imagem.jpg' WHERE id = 13488;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 3\\\\04_Memorial do Espadachim_imagem.jpg' WHERE id = 13489;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 3\\\\05_Fim da Jornada_imagem.jpg' WHERE id = 13490;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 3\\\\06_Come?o de um Sonho_imagem.jpg' WHERE id = 13491;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\2? Temporada\\\\Parte 3\\\\07_Mother's Rosario_imagem.jpg' WHERE id = 13492;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\01_Submundo_imagem.jpg' WHERE id = 13493;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\02_A ?rvore Demon?aca_imagem.jpg' WHERE id = 13494;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\03_As Montanhas do Fim_imagem.jpg' WHERE id = 13495;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\04_Despedida_imagem.jpg' WHERE id = 13496;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\05_Ocean Turtle_imagem.jpg' WHERE id = 13497;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\06_Projeto Alicization_imagem.jpg' WHERE id = 13498;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\07_Academia da Espada_imagem.jpg' WHERE id = 13499;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\08_Orgulho de Espadachim_imagem.jpg' WHERE id = 13500;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\09_Responsabilidade de um Nobre_imagem.jpg' WHERE id = 13501;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\10_C?digo de Tabus_imagem.jpg' WHERE id = 13502;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\11_Catedral Central_imagem.jpg' WHERE id = 13503;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\12_O S?bio da Biblioteca_imagem.jpg' WHERE id = 13504;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 1\\\\13_Mandante e Mediadora_imagem.jpg' WHERE id = 13505;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 2\\\\01_O Cavaleiro Escarlate_imagem.jpg' WHERE id = 13506;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 2\\\\02_O Cavaleiro Implac?vel_imagem.jpg' WHERE id = 13507;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 2\\\\03_A Cavaleira de Osmanthus_imagem.jpg' WHERE id = 13508;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 2\\\\04_Tr?gua_imagem.jpg' WHERE id = 13509;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 2\\\\05_O Her?i Lend?rio_imagem.jpg' WHERE id = 13510;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 2\\\\06_O Selo no Olho Direito_imagem.jpg' WHERE id = 13511;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 2\\\\07_S?ntese_imagem.jpg' WHERE id = 13512;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 3\\\\01_O 32? Cavaleiro_imagem.jpg' WHERE id = 13513;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 3\\\\02_O Tit? da Espada_imagem.jpg' WHERE id = 13514;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 3\\\\03_Administrador_imagem.jpg' WHERE id = 13515;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 3\\\\04_Meu Her?i_imagem.jpg' WHERE id = 13516;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 4\\\\01_Reflex?o_imagem.jpg' WHERE id = 13517;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 4\\\\02_No Extremo Norte_imagem.jpg' WHERE id = 13518;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 4\\\\03_Incurs?es_imagem.jpg' WHERE id = 13519;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 4\\\\04_O Teste de Carga Final_imagem.jpg' WHERE id = 13520;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 4\\\\05_Territ?rio das Trevas_imagem.jpg' WHERE id = 13521;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 4\\\\06_A Noite Antes da Batalha_imagem.jpg' WHERE id = 13522;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 5\\\\01_Batalha dos Cavaleiros_imagem.jpg' WHERE id = 13523;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 5\\\\02_Estigma do Desqualificado_imagem.jpg' WHERE id = 13524;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 5\\\\03_Vida e Sangue_imagem.jpg' WHERE id = 13525;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 5\\\\04_Espada e Punho_imagem.jpg' WHERE id = 13526;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 5\\\\05_Stacia, a Deusa da Cria??o_imagem.jpg' WHERE id = 13527;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 6\\\\01_Escolha sem Cora??o_imagem.jpg' WHERE id = 13528;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 6\\\\02_Raio de Luz_imagem.jpg' WHERE id = 13529;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 6\\\\03_Guerra do Submundo_imagem.jpg' WHERE id = 13530;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 6\\\\04_Fim da Eternidade_imagem.jpg' WHERE id = 13531;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 6\\\\05_Instiga??o_imagem.jpg' WHERE id = 13532;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 6\\\\06_C?digo 871_imagem.jpg' WHERE id = 13533;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 6\\\\07_O Filho do Diabo_imagem.jpg' WHERE id = 13534;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 7\\\\01_Mem?rias_imagem.jpg' WHERE id = 13535;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 7\\\\02_Despertar_imagem.jpg' WHERE id = 13536;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 7\\\\03_A Espada do C?u Noturno_imagem.jpg' WHERE id = 13537;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 7\\\\04_Al?m do Tempo_imagem.jpg' WHERE id = 13538;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 7\\\\05_Alice_imagem.jpg' WHERE id = 13539;
UPDATE episodio SET capa_url = 'F:\\\\Sword Art Online\\\\3? Temporada\\\\Parte 7\\\\06_New World_imagem.jpg' WHERE id = 13540;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\01_121045_imagem.jpg' WHERE id = 13541;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\02_131045_imagem.jpg' WHERE id = 13542;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\03_181045_imagem.jpg' WHERE id = 13543;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\04_291045_imagem.jpg' WHERE id = 13544;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\05_301045_imagem.jpg' WHERE id = 13545;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\06_311045_imagem.jpg' WHERE id = 13546;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\07_011145_imagem.jpg' WHERE id = 13547;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\08_021145_imagem.jpg' WHERE id = 13548;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\09_031145_imagem.jpg' WHERE id = 13549;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\10_130146_imagem.jpg' WHERE id = 13550;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\11_140146_imagem.jpg' WHERE id = 13551;
