UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\17_A Triste Batalha! Ichigo VS Sado e Orihime!_imagem.jpg' WHERE id = 7909;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\18_Ichigo VS Ury?! Quem ? o Traidor!_imagem.jpg' WHERE id = 7910;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\19_A Nova Apari??o! Conhecendo o Gotei 13!_imagem.jpg' WHERE id = 7911;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\20_Revivido! O Substituto de Shinigami Ichigo Kurosaki!_imagem.jpg' WHERE id = 7912;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\21_Batalha Dura! Shinigami VS Xcution!_imagem.jpg' WHERE id = 7913;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\22_Luta Desesperada! Problemas com a Mem?ria de Byakuya_imagem.jpg' WHERE id = 7914;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\23_Ichigo VS Ginjou! O Segredo do Emblema de Shinigami Substituto_imagem.jpg' WHERE id = 7915;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\16? Temporada\\\\24_Hist?ria Mut?vel, Cora??o Imut?vel!_imagem.jpg' WHERE id = 7916;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\01_O Dia em que me Tornei um Shinigami_imagem.jpg' WHERE id = 7917;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\02_O Trabalho de um Shinigami_imagem.jpg' WHERE id = 7918;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\03_O Desejo do Irm?o Mais Velho, o Desejo da Irm? Mais Nova_imagem.jpg' WHERE id = 7919;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\04_Periquito Amaldi?oado_imagem.jpg' WHERE id = 7920;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\05_Derrote o Inimigo Invis?vel_imagem.jpg' WHERE id = 7921;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\06_Batalha at? a Morte! Ichigo vs Ichigo_imagem.jpg' WHERE id = 7922;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\07_O Acolher de um Le?o de Pel?cia_imagem.jpg' WHERE id = 7923;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\08_17 de Junho, Mem?rias na Chuva_imagem.jpg' WHERE id = 7924;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\09_Inimigo Invenc?vel_imagem.jpg' WHERE id = 7925;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\10_Ataque na Viagem ao Lugar Sagrado!_imagem.jpg' WHERE id = 7926;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\11_O Lend?rio Quincy_imagem.jpg' WHERE id = 7927;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\12_Um Gentil Bra?o Direito_imagem.jpg' WHERE id = 7928;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\13_Flor e Hollow_imagem.jpg' WHERE id = 7929;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\14_Costa a Costa, uma Luta at? a Morte!_imagem.jpg' WHERE id = 7930;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\15_O ?timo Plano de Kon_imagem.jpg' WHERE id = 7931;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\16_Encontro, Renji Abarai!_imagem.jpg' WHERE id = 7932;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\17_Ichigo Morre!_imagem.jpg' WHERE id = 7933;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\18_Recupere! O Poder de Shinigami!_imagem.jpg' WHERE id = 7934;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\19_Ichigo se Transforma em um Hollow!_imagem.jpg' WHERE id = 7935;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\1? Temporada\\\\20_A Sombra de Gin Ichimaru_imagem.jpg' WHERE id = 7936;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\01_Entre! O Mundo dos Shinigamis_imagem.jpg' WHERE id = 7937;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\02_O Homem que Odeia Shinigamis_imagem.jpg' WHERE id = 7938;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\03_14 Dias para a Execu??o de Rukia_imagem.jpg' WHERE id = 7939;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\04_Re?nam-se! As 13 Divis?es_imagem.jpg' WHERE id = 7940;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\05_Penetrar o Centro com uma Gigantesca Bola de Canh?o_imagem.jpg' WHERE id = 7941;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\06_Forma??o! A Pior Companhia_imagem.jpg' WHERE id = 7942;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\07_Libere o Golpe Fatal!_imagem.jpg' WHERE id = 7943;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\08_Orihime est? Sendo Visada_imagem.jpg' WHERE id = 7944;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\09_Avan?ar! A Rede Abrangente dos Shinigamis_imagem.jpg' WHERE id = 7945;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\10_O Confronto de Renji_imagem.jpg' WHERE id = 7946;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\11_A Resolu??o para Matar_imagem.jpg' WHERE id = 7947;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\12_Estrelas e o Devaneio_imagem.jpg' WHERE id = 7948;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\13_Milagre! O Misterioso Novo Her?i_imagem.jpg' WHERE id = 7949;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\14_Trag?dia do Amanhecer_imagem.jpg' WHERE id = 7950;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\15_Aizen Assassinado! As Trevas que se Aproximam_imagem.jpg' WHERE id = 7951;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\16_Zaraki Kenpachi se Aproxima!_imagem.jpg' WHERE id = 7952;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\17_A Raz?o do Punho_imagem.jpg' WHERE id = 7953;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\18_Desespero! A Zangetsu Destru?da_imagem.jpg' WHERE id = 7954;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\19_O Homem Imortal_imagem.jpg' WHERE id = 7955;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\20_A Shinigami que Ganju Conheceu_imagem.jpg' WHERE id = 7956;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\2? Temporada\\\\21_Reuni?o, Ichigo e Rukia_imagem.jpg' WHERE id = 7957;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\01_Yoruichi, Deusa Rel?mpago, Dan?a!_imagem.jpg' WHERE id = 7958;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\02_O Shinigami Desprez?vel_imagem.jpg' WHERE id = 7959;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\03_Ishida, Poder dos Limites!_imagem.jpg' WHERE id = 7960;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\04_Ultrapasse seus Limites!_imagem.jpg' WHERE id = 7961;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\05_Recordes Aut?nticos! A Escola de Shinigamis_imagem.jpg' WHERE id = 7962;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\06_Os Vingadores_imagem.jpg' WHERE id = 7963;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\07_Hitsugaya Ruge!_imagem.jpg' WHERE id = 7964;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\08_O Pesadelo de Rukia_imagem.jpg' WHERE id = 7965;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\09_O Despertar do Le?o_imagem.jpg' WHERE id = 7966;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\10_Manh? da Senten?a_imagem.jpg' WHERE id = 7967;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\11_Renji, Juramento de Alma! Luta Mortal com Byakuya_imagem.jpg' WHERE id = 7968;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\12_A Tenta??o de Gin Ichimaru, Resolu??o de Destrui??o!_imagem.jpg' WHERE id = 7969;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\13_Um Juramento Realizado! Pegue Rukia de Volta!_imagem.jpg' WHERE id = 7970;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\14_O Shinigami mais Poderoso! ?ltimo Confronto entre Mestre e Aprendiz_imagem.jpg' WHERE id = 7971;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\15_Batalha Supers?nica! Defina a Deusa da Bravura_imagem.jpg' WHERE id = 7972;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\16_Senbonzakura, Esmagada! Zangetsu se Impulsiona Atrav?s do C?u!_imagem.jpg' WHERE id = 7973;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\17_Liberada! A Espada Negra, o Poder de um Milagre_imagem.jpg' WHERE id = 7974;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\18_Conclus?o da Batalha de Vida ou Morte! Orgulho Branco e Desejo Negro_imagem.jpg' WHERE id = 7975;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\19_A Realidade Desesperadora, a Adaga do Assassino ? Revelada!_imagem.jpg' WHERE id = 7976;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\20_Aizen Aparece! Ambi??es Horr?veis_imagem.jpg' WHERE id = 7977;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\21_Se Juntem! Grupo dos Shinigamis mais Fortes!_imagem.jpg' WHERE id = 7978;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\3? Temporada\\\\22_Decis?o de Rukia, Sentimentos de Ichigo_imagem.jpg' WHERE id = 7979;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\01_Novo Integrante da Escola, Renji Veio para o Mundo Real!_imagem.jpg' WHERE id = 7980;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\02_Terror Alucinante, a Segunda V?tima_imagem.jpg' WHERE id = 7981;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\03_Avance! A Armadilha Escondida no Labirinto_imagem.jpg' WHERE id = 7982;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\04_O Jogo da Morte! O Desaparecimento do Colega de Classe_imagem.jpg' WHERE id = 7983;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\05_A Verdadeira Identidade do Dem?nio, o Segredo que ? Revelado_imagem.jpg' WHERE id = 7984;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\06_Bounts! Aqueles que Ca?am Almas!_imagem.jpg' WHERE id = 7985;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\07_O Retorno de Rukia! Ressurrei??o do Time Substituto_imagem.jpg' WHERE id = 7986;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\08_O Momento da Colis?o! A M?o Cruel que se Aproxima do Quincy_imagem.jpg' WHERE id = 7987;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\09_Ataque de ?gua! Escapem do Hospital Abandonado_imagem.jpg' WHERE id = 7988;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\10_Reuni?o no Lugar da Sorte! O Homem que Faz seu Movimento_imagem.jpg' WHERE id = 7989;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\11_Mem?rias do Cl? que Vive Eternamente_imagem.jpg' WHERE id = 7990;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\12_Evento Aterrorizante na 11? Divis?o! O Shinigami se Ergue Novamente_imagem.jpg' WHERE id = 7991;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\13_For?a Chocante! Freed VS Zangetsu_imagem.jpg' WHERE id = 7992;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\14_?dio sem Fim! O Shinigami que Kenpachi Retalhou_imagem.jpg' WHERE id = 7993;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\15_Revela??es Chocantes para as 13 Divis?es!! A Verdade Enterrada na Hist?ria_imagem.jpg' WHERE id = 7994;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\16_A Decis?o de Morte de Yoshino_imagem.jpg' WHERE id = 7995;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\17_Ataque de um Inimigo Formid?vel! Uma Fina Linha Final de Defesa!_imagem.jpg' WHERE id = 7996;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\18_Hitsugaya se Move! A Cidade Atacada_imagem.jpg' WHERE id = 7997;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\19_Ichigo VS Dark! A Apari??o da Escurid?o Desvanecida_imagem.jpg' WHERE id = 7998;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\20_Sombra Cinzenta, o Segredo dos Dolls_imagem.jpg' WHERE id = 7999;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\21_Separa??o do Time Substituto A Trai??o de Rukia_imagem.jpg' WHERE id = 8000;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\22_A Batalha Mortal de L?grimas! Rukia VS Orihime_imagem.jpg' WHERE id = 8001;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\23_Rangiku Dan?a! Corte o Inimigo Invis?vel_imagem.jpg' WHERE id = 8002;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\24_Byakuya ? Chamado! As 13 Divis?es Come?am a se Mover_imagem.jpg' WHERE id = 8003;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\25_Aniquila??o dos Tenentes! A Armadilha na Caverna Subterr?nea_imagem.jpg' WHERE id = 8004;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\26_Revanche! Ishida VS Nemu_imagem.jpg' WHERE id = 8005;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\27_Renji Abarai, A Alma da Bankai!_imagem.jpg' WHERE id = 8006;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\4? Temporada\\\\28_Shinigami e Quincy, A Ressurrei??o do Poder_imagem.jpg' WHERE id = 8007;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\01_A Decis?o de T?shir?! A Colis?o se Aproxima._imagem.jpg' WHERE id = 8008;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\02_Ataque dos Bounts! Abalo nas 13 Divis?es._imagem.jpg' WHERE id = 8009;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\03_Invas?o no Mundo dos Shinigamis, Novamente._imagem.jpg' WHERE id = 8010;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\04_Byakuya no Campo de Batalha! A Dan?a das P?talas de Cerejeira Rasga o Vento._imagem.jpg' WHERE id = 8011;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\05_Ichigo - Byakuya - Kariya, a Batalha de Tr?s Extremos!_imagem.jpg' WHERE id = 8012;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\06_O Ataque de T?shir?! Corte o Inimigo na Floresta!_imagem.jpg' WHERE id = 8013;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\07_Confronto! Kenpachi Zaraki VS Maki Ichinose._imagem.jpg' WHERE id = 8014;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\08_Shinigami VS Shinigami! O Poder Incontrol?vel._imagem.jpg' WHERE id = 8015;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\09_A Morte de Soi Fon O Fim do Onmitsu Kidou._imagem.jpg' WHERE id = 8016;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\10_A Bankai de Mayuri! Sawatari - O Confronto dos Dem?nios._imagem.jpg' WHERE id = 8017;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\11_O ?ltimo Quincy! A Explos?o de Poder._imagem.jpg' WHERE id = 8018;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\12_Ishida, o Tiro que Excede os Limites!_imagem.jpg' WHERE id = 8019;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\13_A Batalha Mortal da 10? Divis?o! Libere a Hyourinmaru._imagem.jpg' WHERE id = 8020;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\14_Kariya! A Contagem Regressiva para a Detona??o._imagem.jpg' WHERE id = 8021;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\15_Vida e Vingan?a! A ?ltima Escolha de Ishida._imagem.jpg' WHERE id = 8022;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\16_O Balan?ar da L?mina! O Momento da Ru?na._imagem.jpg' WHERE id = 8023;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\17_A Lamenta??o do Bount! O Confronto Final._imagem.jpg' WHERE id = 8024;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\5? Temporada\\\\18_Ichigo e Rukia, Sentimentos Refletidos no C?u._imagem.jpg' WHERE id = 8025;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\01_Voltando ao Trabalho de Substituto! O Terr?vel Estudante Transferido._imagem.jpg' WHERE id = 8026;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\02_Revela??o! A Verdadeira Face dos Pais._imagem.jpg' WHERE id = 8027;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\03_O In?cio da Guerra, Vaizards e Arrancars._imagem.jpg' WHERE id = 8028;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\04_O Prel?dio do Apocalipse, A Invas?o dos Arrancars!_imagem.jpg' WHERE id = 8029;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\05_Reencontro, Ichigo, Rukia e os Shinigamis._imagem.jpg' WHERE id = 8030;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\06_Miss?o! Os Rec?m-Chegados Shinigamis._imagem.jpg' WHERE id = 8031;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\07_O Olho Diab?lico, Aizen Retorna._imagem.jpg' WHERE id = 8032;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\08_Come?a a Batalha de Rukia! A L?mina Branca de Gelo._imagem.jpg' WHERE id = 8033;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\09_A Bankai de Ikkaku! O Poder Devastador._imagem.jpg' WHERE id = 8034;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\10_O Segredo da Divis?o de Zaraki! Os Homens Sortudos._imagem.jpg' WHERE id = 8035;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\11_A Dispers?o de Hitsugaya! Hyourinmaru Quebrada._imagem.jpg' WHERE id = 8036;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\12_Confronto! O Protetor VS O Portador._imagem.jpg' WHERE id = 8037;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\13_Vaizard! O Poder dos que Despertaram._imagem.jpg' WHERE id = 8038;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\14_Ichigo, Transforma??o Definitiva em Hollow!_imagem.jpg' WHERE id = 8039;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\15_Colis?o! A Bankai Negra e a Bankai Branca._imagem.jpg' WHERE id = 8040;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\16_Aviso Urgente! O Aterrorizante Plano de S?suke._imagem.jpg' WHERE id = 8041;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\17_Ury? VS Ry?ken! A Batalha entre Pai e Filho Quincy._imagem.jpg' WHERE id = 8042;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\18_A Decis?o de Urahara, os Pensamentos de Orihime._imagem.jpg' WHERE id = 8043;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\19_Pesadelo Arrancar! O Time de T?shir? Ataca_imagem.jpg' WHERE id = 8044;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\20_A Chegada do Mensageiro das Trevas! A Propaga??o da Maldade._imagem.jpg' WHERE id = 8045;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\21_O Inimigo Invis?vel! A Cruel Decis?o de T?shir?._imagem.jpg' WHERE id = 8046;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\6? Temporada\\\\22_As L?grimas de Rangiku, a Triste Partida de Irm?o e Irm?._imagem.jpg' WHERE id = 8047;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\01_Hitsugaya, Karin, e a Bola de Futebol._imagem.jpg' WHERE id = 8048;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\02_Ikkaku, o Conto Kendou de Sangue Quente._imagem.jpg' WHERE id = 8049;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\03_O Belo Patissier, Yumichika!_imagem.jpg' WHERE id = 8050;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\04_Kon ? Enganado, Rangiku ? Espreita..._imagem.jpg' WHERE id = 8051;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\05_Guerra Civil no Hueco Mundo! A Morte de Ulquiorra._imagem.jpg' WHERE id = 8052;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\06_A Batalha Maliciosa, a Armadilha de Aizen._imagem.jpg' WHERE id = 8053;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\07_Hueco Mundo Ataca Novamente! T?shir? VS Yammy._imagem.jpg' WHERE id = 8054;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\08_Ichigo VS Grimmjow, a Batalha de 11 Segundos._imagem.jpg' WHERE id = 8055;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\09_A Conspira??o de Ulquiorra, o Momento em que o Sol se P?e._imagem.jpg' WHERE id = 8056;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\10_Adeus... Kurosaki-kun._imagem.jpg' WHERE id = 8057;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\11_Ordem! O Resgate de Orihime Inoue ? Proibido_imagem.jpg' WHERE id = 8058;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\12_Grimmjow Revivido._imagem.jpg' WHERE id = 8059;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\13_Ishida - Chado, A Explos?o dos Novos Poderes._imagem.jpg' WHERE id = 8060;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\14_Re?nam-se, Espada! A Assembl?ia Imperial de Aizen._imagem.jpg' WHERE id = 8061;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\15_Seu Nome ? Nell! Uma Estranha Arrancar Aparece._imagem.jpg' WHERE id = 8062;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\16_A Floresta dos Menos! ? Procura de Rukia._imagem.jpg' WHERE id = 8063;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\17_Ashido, o Shinigami que Veio do Passado._imagem.jpg' WHERE id = 8064;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\18_Atrav?s da Floresta em Ru?nas, 1 Milh?o de Menos._imagem.jpg' WHERE id = 8065;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\19_Juramento! Vivos de Volta a este Lugar._imagem.jpg' WHERE id = 8066;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\7? Temporada\\\\20_A Tempestade Furiosa! Encontro com o Arrancar Dan?arino._imagem.jpg' WHERE id = 8067;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\01_O Contra-Ataque de Ichigo! Esta ? a Minha Bankai.._imagem.jpg' WHERE id = 8068;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\02_Pesquisa Diab?lica! O Plano de Szayel Aporro._imagem.jpg' WHERE id = 8069;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\03_Rukia e Kaien, o Triste Reencontro._imagem.jpg' WHERE id = 8070;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\04_Rukia Contra-Ataca! Libere o Kidou do Desespero._imagem.jpg' WHERE id = 8071;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\05_Ishida e Pessche, Ataque Unido da Amizade._imagem.jpg' WHERE id = 8072;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\06_O Trunfo de Ishida Seele schneider._imagem.jpg' WHERE id = 8073;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\07_Brazo Derecho del Gigante, Brazo Izquierdo del Diablo._imagem.jpg' WHERE id = 8074;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\08_Yasutora Sado Morre! As L?grimas de Orihime._imagem.jpg' WHERE id = 8075;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\09_Testamento, Seu Cora??o est? Aqui..._imagem.jpg' WHERE id = 8076;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\10_O Cruel Arrancar, a Provoca??o de Ulquiorra._imagem.jpg' WHERE id = 8077;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\11_Szayel Aporro Ri, a Armadilha para Renji est? Completa._imagem.jpg' WHERE id = 8078;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\12_Shinigami e Quincy, a Batalha da Loucura._imagem.jpg' WHERE id = 8079;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\13_A Estrat?gia de Ury?, os 20 Segundos de Ataque e Defesa._imagem.jpg' WHERE id = 8080;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\14_O Instinto Assassino Ferve! Grimmjow em ?xtase._imagem.jpg' WHERE id = 8081;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\15_Poder Mortal VS Poder Mortal! Ichigo Hollow._imagem.jpg' WHERE id = 8082;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\8? Temporada\\\\16_O Momento da Decis?o, o Fim de Grimmjow._imagem.jpg' WHERE id = 8083;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\01_Um Novo Capit?o Aparece! Seu Nome ? Sh?suke Amagai._imagem.jpg' WHERE id = 8084;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\02_Um Novo Acontecimento, a Perigosa Estudante Transferida Aparece!_imagem.jpg' WHERE id = 8085;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\03_Batalha sob o Luar, o Misterioso Assassino e a Zanpakut?._imagem.jpg' WHERE id = 8086;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\04_Kenryu, a Exuber?ncia das Flores._imagem.jpg' WHERE id = 8087;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\05_Kibune vai ? Guerra! O Violento Vento Enfurecido._imagem.jpg' WHERE id = 8088;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\06_O Grande Mal Surge! As Trevas que Envolvem a Fam?lia Kasumioji._imagem.jpg' WHERE id = 8089;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\07_Quebre o Limite do Espelho! A Pris?o de Ichigo._imagem.jpg' WHERE id = 8090;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\08_A Vingan?a do Assassino, Ichigo ? o Alvo._imagem.jpg' WHERE id = 8091;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\09_Mist?rio! O Assassino Devorador de Espadas._imagem.jpg' WHERE id = 8092;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\10_A Revers?o de Rukia, a L?mina Enfurecida._imagem.jpg' WHERE id = 8093;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\11_O Pesadelo Emerge, e Ichigo est? Dentro Dele._imagem.jpg' WHERE id = 8094;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\12_Confronto! Amagai VS As 13 Divis?es._imagem.jpg' WHERE id = 8095;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\13_A Decis?o da Princesa, a Triste Noiva._imagem.jpg' WHERE id = 8096;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\14_2? Divis?o ao Ataque! Ichigo ? Cercado._imagem.jpg' WHERE id = 8097;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\15_A Zanpakut? ? Liberada, O Verdadeiro Poder de Amagai!_imagem.jpg' WHERE id = 8098;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\16_As Trevas se Movem! A Verdadeira Face de Makoto._imagem.jpg' WHERE id = 8099;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\17_Izuru e Makoto Ataque e Defesa da 3? Divis?o._imagem.jpg' WHERE id = 8100;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\18_Gelo e Fogo! T?shir? VS Amagai._imagem.jpg' WHERE id = 8101;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\19_Ordem de Ataque! Invas?o ? Mans?o Kasumioji._imagem.jpg' WHERE id = 8102;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\20_Ichigo em F?ria! O Segredo do Assassino._imagem.jpg' WHERE id = 8103;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\21_Duelo! Ichigo VS Amagai._imagem.jpg' WHERE id = 8104;
UPDATE episodio SET capa_url = 'F:\\\\Bleach\\\\9? Temporada\\\\22_Fim do Orgulho Shinigami._imagem.jpg' WHERE id = 8105;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\1? Temporada\\\\10_Encontro com o Desconhecido_imagem.jpg' WHERE id = 8106;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\1? Temporada\\\\11_Game Over_imagem.jpg' WHERE id = 8107;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\1? Temporada\\\\12_All Might_imagem.jpg' WHERE id = 8108;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\1? Temporada\\\\13_Em Cada um dos Nossos Cora??es_imagem.jpg' WHERE id = 8109;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\10_Shoto Todoroki - A Origem_imagem.jpg' WHERE id = 8119;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\11_Iida, For?a_imagem.jpg' WHERE id = 8120;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\12_Todoroki vs. Bakugo_imagem.jpg' WHERE id = 8121;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\13_Hora de Escolher Nomes_imagem.jpg' WHERE id = 8122;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\14_Bizarro! Gran Torino Aparece!_imagem.jpg' WHERE id = 8123;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\15_Midoriya e Shigaraki_imagem.jpg' WHERE id = 8124;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\16_Stain, o Assassino de Super-Her?is vs. Alunos da U.A._imagem.jpg' WHERE id = 8125;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\17_Conclus?o_imagem.jpg' WHERE id = 8126;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\18_A Repercuss?o da Batalha Contra Stain, o Assassino de Super-Her?is_imagem.jpg' WHERE id = 8127;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\19_Os Est?gios de Cada Um_imagem.jpg' WHERE id = 8128;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\20_Aprenda!! Uma Hist?ria do Passado_imagem.jpg' WHERE id = 8130;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\21_Preparem-se para a Prova Final_imagem.jpg' WHERE id = 8131;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\22_A Ascens?o de Yaoyorozu_imagem.jpg' WHERE id = 8132;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\23_Tire a Camada Externa_imagem.jpg' WHERE id = 8133;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\24_Katsuki Bakugo A Origem_imagem.jpg' WHERE id = 8134;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\2? Temporada\\\\25_Encontro_imagem.jpg' WHERE id = 8135;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\10_S?mbolo da Paz_imagem.jpg' WHERE id = 8144;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\11_One For All_imagem.jpg' WHERE id = 8145;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\12_O Fim do Come?o, o Come?o do Fim_imagem.jpg' WHERE id = 8146;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\13_Entrando nos Dormit?rios_imagem.jpg' WHERE id = 8147;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\14_Criem T?cnicas Secretas_imagem.jpg' WHERE id = 8148;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\15_A Prova_imagem.jpg' WHERE id = 8149;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\16_Col?gio Shiketsu ? Espreita_imagem.jpg' WHERE id = 8150;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\17_Turma 1-A_imagem.jpg' WHERE id = 8151;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\18_RUSH!_imagem.jpg' WHERE id = 8152;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\19_Exerc?cios de Resgate_imagem.jpg' WHERE id = 8153;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\20_Epis?dio Especial - Salve o Mundo com Amor_imagem.jpg' WHERE id = 8155;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\21_O que Vamos Fazer_imagem.jpg' WHERE id = 8156;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\22_Uma Conversa sobre 'Individualidade'_imagem.jpg' WHERE id = 8157;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\23_Deku vs. Kazinho - 2? parte_imagem.jpg' WHERE id = 8158;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\24_Esta??o de Encontros_imagem.jpg' WHERE id = 8159;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\3? Temporada\\\\25_Invenc?vel_imagem.jpg' WHERE id = 8160;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\10_Esquadr?o de Tempor?rios_imagem.jpg' WHERE id = 8169;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\11_Lemillion_imagem.jpg' WHERE id = 8170;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\12_Esperan?a Invis?vel_imagem.jpg' WHERE id = 8171;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\13_100% Infinito_imagem.jpg' WHERE id = 8172;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\14_Um Futuro Brilhante_imagem.jpg' WHERE id = 8173;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\15_Chamas Ardentes_imagem.jpg' WHERE id = 8174;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\16_Agarre o Cora??o Dessas Crian?as_imagem.jpg' WHERE id = 8175;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\17_Orgulhem-se, Candidatos ? Licen?a Provis?ria_imagem.jpg' WHERE id = 8176;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\18_Festival Cultural_imagem.jpg' WHERE id = 8177;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\19_O Mais Divertido do Festival Cultural s?o os Preparativos_imagem.jpg' WHERE id = 8178;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\20_Golden Tips Imperial_imagem.jpg' WHERE id = 8180;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\21_Deku vs. Gentle Criminal_imagem.jpg' WHERE id = 8181;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\22_Come?a o Festival Cultural!!_imagem.jpg' WHERE id = 8182;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\23_Deixe Acontecer! Festival Cultural!_imagem.jpg' WHERE id = 8183;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\24_Classifica??o de Super-Her?is Japoneses_imagem.jpg' WHERE id = 8184;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\4? Temporada\\\\25_O Come?o Dele_imagem.jpg' WHERE id = 8185;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\10_Heran?a_imagem.jpg' WHERE id = 8194;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\11_Nossa Batalha Turbulenta_imagem.jpg' WHERE id = 8195;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\12_O Novo Poder e o All for One_imagem.jpg' WHERE id = 8196;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\13_Feliz Natal!_imagem.jpg' WHERE id = 8197;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\14_Para a Ag?ncia do Endeavor!_imagem.jpg' WHERE id = 8198;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\15_Um Passo de Cada Vez_imagem.jpg' WHERE id = 8199;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\16_Quanto Tempo, Selkie!_imagem.jpg' WHERE id = 8200;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\17_A Infernal Casa da Fam?lia Todoroki_imagem.jpg' WHERE id = 8201;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\18_Pessoas que N?o Podem Ser Perdoadas_imagem.jpg' WHERE id = 8202;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\19_Mais Super-Her?i do que Todos_imagem.jpg' WHERE id = 8203;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\20_Minha Academia de Vil?es_imagem.jpg' WHERE id = 8205;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\21_Festa do Segundo Advento_imagem.jpg' WHERE id = 8206;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\22_A Marcha do Homem Triste_imagem.jpg' WHERE id = 8207;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\23_Tenko Shimura - Origem_imagem.jpg' WHERE id = 8208;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\24_Tomura Shigaraki - Origem_imagem.jpg' WHERE id = 8209;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\5? Temporada\\\\25_C?u, Um Azul Profundo Nas Alturas_imagem.jpg' WHERE id = 8210;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\10_Pessoas Dentro de N?s_imagem.jpg' WHERE id = 8219;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\11_A Dan?a do Dabi_imagem.jpg' WHERE id = 8220;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\12_Fios de Esperan?a_imagem.jpg' WHERE id = 8221;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\13_?ltimo Est?gio_imagem.jpg' WHERE id = 8222;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\14_Inferno Infernal_imagem.jpg' WHERE id = 8223;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\15_T?rtaro_imagem.jpg' WHERE id = 8224;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\16_A Infernal Casa da Fam?lia Todoroki 2_imagem.jpg' WHERE id = 8225;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\17_Descontrole do Fogo_imagem.jpg' WHERE id = 8226;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\18_Izuku Midoriya e Tomura Shigaraki_imagem.jpg' WHERE id = 8227;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\19_Poder M?ximo!!_imagem.jpg' WHERE id = 8228;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\20_Assassina_imagem.jpg' WHERE id = 8230;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\21_A Bela Lady Nagant_imagem.jpg' WHERE id = 8231;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\22_Amigo_imagem.jpg' WHERE id = 8232;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\23_Deku vs. Turma A_imagem.jpg' WHERE id = 8233;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\24_Declara??o de Uma Jovem_imagem.jpg' WHERE id = 8234;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\6? Temporada\\\\25_Se Conectando, Se Conectando_imagem.jpg' WHERE id = 8235;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\10_Super-her?i Ferido, Queime e Brilhe Mais Forte!.mkv' WHERE id = 8244;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\11_Light Fades to Rain.mkv' WHERE id = 8245;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\12_Aqueles que defendem e aqueles que violam.mkv' WHERE id = 8246;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\13_Gera??es encadeadas.mkv' WHERE id = 8247;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\14_Efeito borboleta.mkv' WHERE id = 8248;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\15_Butterfly Effect.mkv' WHERE id = 8249;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\16_The Chain Thus Far.mkv' WHERE id = 8250;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\17_Esperan?as.mkv' WHERE id = 8251;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\18_It's a Small World.mkv' WHERE id = 8252;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\19_I AM HERE.mkv' WHERE id = 8253;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\20_O ego de uma garota.mkv' WHERE id = 8255;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\7? Temporada\\\\21_Batalha sem peculiaridade.mkv' WHERE id = 8256;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E01 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8265;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E02 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8266;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E03 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8267;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E04 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8268;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E05 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8269;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E06 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8270;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E07 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8271;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E08 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8272;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E09 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8273;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E10 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8274;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\8? Temporada - Legendado\\\\My Hero Academia AKA Boku no H?r? Akademia S08E11 1080p CR WEBRip DUAL Opus 2.0 AV1-knyf1e.mkv' WHERE id = 8275;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E01v2.mkv' WHERE id = 8276;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E02v2.mkv' WHERE id = 8277;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E03v2.mkv' WHERE id = 8278;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E04v2.mkv' WHERE id = 8279;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E05v2.mkv' WHERE id = 8280;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E06v2.mkv' WHERE id = 8281;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E07v2.mkv' WHERE id = 8282;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E08v2.mkv' WHERE id = 8283;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E09v2.mkv' WHERE id = 8284;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E10v2.mkv' WHERE id = 8285;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E11v2.mkv' WHERE id = 8286;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E12v2.mkv' WHERE id = 8287;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\1? Temporada\\\\[Judas] Vigilantes - S01E13v2.mkv' WHERE id = 8288;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E01v2.mkv' WHERE id = 8289;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E02v2.mkv' WHERE id = 8290;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E03v2.mkv' WHERE id = 8291;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E04v2.mkv' WHERE id = 8292;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E05v2.mkv' WHERE id = 8293;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E06v2.mkv' WHERE id = 8294;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E07v2.mkv' WHERE id = 8295;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E08v2.mkv' WHERE id = 8296;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E09v2.mkv' WHERE id = 8297;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E10v2.mkv' WHERE id = 8298;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E11v2.mkv' WHERE id = 8299;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E12v2.mkv' WHERE id = 8300;
UPDATE episodio SET capa_url = 'F:\\\\Buko no Hero\\\\Illegals - Legendado\\\\2? Temporada\\\\[Judas] Vigilantes - S02E13v2.mkv' WHERE id = 8301;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\01_Cachorro e Motosserra_imagem.jpg' WHERE id = 8302;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\02_Chegada em Tokyo_imagem.jpg' WHERE id = 8303;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\03_O Paradeiro de Miauzin_imagem.jpg' WHERE id = 8304;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\04_Resgate_imagem.jpg' WHERE id = 8305;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\05_O Dem?nio da Arma_imagem.jpg' WHERE id = 8306;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\06_Matem o Denji_imagem.jpg' WHERE id = 8307;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\07_O Sabor do Beijo_imagem.jpg' WHERE id = 8308;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\08_O Som do Disparo_imagem.jpg' WHERE id = 8309;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\09_De Kyoto_imagem.jpg' WHERE id = 8310;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\10_Ainda Mais Podre_imagem.jpg' WHERE id = 8311;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\11_In?cio do Plano_imagem.jpg' WHERE id = 8312;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\1? Temporada\\\\12_Katana vs. Motosserra_imagem.jpg' WHERE id = 8313;
UPDATE episodio SET capa_url = 'F:\\\\Chainsaw Man\\\\Filmes - Legendado\\\\[Erai-raws] Chainsaw Man - Reze-hen - Movie [1080p CR WEBRip HEVC AAC][MultiSub][EB732A7B].mkv' WHERE id = 8314;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\01_O Dia em que o Dem?nio Nasceu_imagem.jpg' WHERE id = 8315;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\02_O Despertar do Cavaleiro Branco_imagem.jpg' WHERE id = 8316;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\03_Colega de Classe Falso_imagem.jpg' WHERE id = 8317;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\04_Seu Nome ? Zero_imagem.jpg' WHERE id = 8318;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\05_A Princesa e a Bruxa_imagem.jpg' WHERE id = 8319;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\06_A M?scara Roubada_imagem.jpg' WHERE id = 8320;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\07_Ataque a Cornelia_imagem.jpg' WHERE id = 8321;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\08_Os Cavaleiros Negros_imagem.jpg' WHERE id = 8322;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\09_Refrain_imagem.jpg' WHERE id = 8323;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\10_Dan?a de Guren_imagem.jpg' WHERE id = 8324;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\11_Batalha por Narita_imagem.jpg' WHERE id = 8325;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\12_O Mensageiro de Kyoto_imagem.jpg' WHERE id = 8326;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\13_Shirley na Mira_imagem.jpg' WHERE id = 8327;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\14_Geass vs. Geass_imagem.jpg' WHERE id = 8328;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\15_Animando Mao_imagem.jpg' WHERE id = 8329;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\16_Nunnally Apreendida_imagem.jpg' WHERE id = 8330;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\17_Cavaleiro_imagem.jpg' WHERE id = 8331;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\18_Kururugi Suzaku, Eu te Ordeno_imagem.jpg' WHERE id = 8332;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\19_Ilha dos Deuses_imagem.jpg' WHERE id = 8333;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\20_A Batalha de Kyushu_imagem.jpg' WHERE id = 8334;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\21_Declara??o no Festival Escolar!_imagem.jpg' WHERE id = 8335;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\22_Euphy Banhada em Sangue_imagem.jpg' WHERE id = 8336;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\23_Ao Menos com Tristeza_imagem.jpg' WHERE id = 8337;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\24_O Palco em Colapso_imagem.jpg' WHERE id = 8338;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\1? Temporada\\\\25_Zero_imagem.jpg' WHERE id = 8339;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\01_O Dia em que o Dem?nio Despertou_imagem.jpg' WHERE id = 8340;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\02_Plano para um Jap?o Independente_imagem.jpg' WHERE id = 8341;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\03_Preso no Campus_imagem.jpg' WHERE id = 8342;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\04_Contra-ataque no Palco da Execu??o_imagem.jpg' WHERE id = 8343;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\05_Knights of the Round_imagem.jpg' WHERE id = 8344;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\06_Ataque-Surpresa sobre o Pac?fico_imagem.jpg' WHERE id = 8345;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\07_A M?scara Abandonada_imagem.jpg' WHERE id = 8346;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\08_Um Milh?o de Milagres_imagem.jpg' WHERE id = 8347;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\09_A Noiva da Cidade Proibida Escarlate_imagem.jpg' WHERE id = 8348;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\10_Quando Shen Hu Recebe a Gl?ria_imagem.jpg' WHERE id = 8349;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\11_Poder do Sentimento_imagem.jpg' WHERE id = 8350;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\12_Love Attack!_imagem.jpg' WHERE id = 8351;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\13_Assassino do Passado_imagem.jpg' WHERE id = 8352;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\14_Ca?a ao Geass_imagem.jpg' WHERE id = 8353;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\15_O Mundo de C_imagem.jpg' WHERE id = 8354;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\16_Primeira Resolu??o da Uni?o Federativa de Na??es_imagem.jpg' WHERE id = 8355;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\17_O Sabor da Humilha??o_imagem.jpg' WHERE id = 8356;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\18_Batalha final de Tokyo II_imagem.jpg' WHERE id = 8357;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\19_Trai??o_imagem.jpg' WHERE id = 8358;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\20_Imperador Indeferido_imagem.jpg' WHERE id = 8359;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\21_A Conex?o Ragnarok_imagem.jpg' WHERE id = 8360;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\22_Imperador Lelouch_imagem.jpg' WHERE id = 8361;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\23_A M?scara de Schneizel_imagem.jpg' WHERE id = 8362;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\24_O C?u de Damocles_imagem.jpg' WHERE id = 8363;
UPDATE episodio SET capa_url = 'F:\\\\Code Geass - Legendado\\\\2? Temporada\\\\25_Re;_imagem.jpg' WHERE id = 8364;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\01 - Uma Noite no Motel Katz - Ensopado de Vov?.mkv' WHERE id = 8365;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\02 - A Sombra do Coragem - Dr.Le Quack Especialista em Amnesia.mkv' WHERE id = 8366;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\03 - Coragem Encontra o Pe Grande - Cabe?a Quente.mkv' WHERE id = 8367;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\04 - O Dem?nio do Colch?o - Fred Esquisit?o.mkv' WHERE id = 8368;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\05 - Noite da Toupeira Lobisomem - Dia das M?es.mkv' WHERE id = 8369;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\06 - Os Irm?os Patos - Shirley, a Medium.mkv' WHERE id = 8370;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\07 - A Maldi??o do Rei Rams?s - O P? Dominador.mkv' WHERE id = 8371;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\08 - O Corcunda de Lugar Nenhum - Os Deuses Est?o Virando Patos.mkv' WHERE id = 8372;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\09 - A Rainha da Po?a Negra - Todo Mundo Quer Dirigir.mkv' WHERE id = 8373;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\10 - O Boneco de Neve - O Patinho Ador?vel, Encantador, Lindo e Carinhoso.mkv' WHERE id = 8374;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\11 - Hamb?rguer com Personalidade - Clube Katz.mkv' WHERE id = 8375;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\12 - A Vingan?a do Frango Espacial - Viagem ao Centro de Lugar Nenhum.mkv' WHERE id = 8376;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\1? Temporada\\\\13 - A Pequena Muriel - O Grande Fusilli.mkv' WHERE id = 8377;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\01 - A ?rvore M?gica de Lugar Nenhum -  O Rob? Randy.mkv' WHERE id = 8378;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\02 - A Maldi??o de Shirley -  Coragem na Cidade Grande.mkv' WHERE id = 8379;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\03 - Neg?cios de Fam?lia -  1000 Anos de Coragem.mkv' WHERE id = 8380;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\04 - Coragem Encontra a M?mia -  Muriel Invis?vel.mkv' WHERE id = 8381;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\05 - Viveiro Humano -  Miss?o Para o Sol.mkv' WHERE id = 8382;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\06 - Uma Mosca Chamada Coragem -  A Loja de Doces.mkv' WHERE id = 8383;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\07 - A TV de Lugar Nenhum -  Mega Muriel, a Magn?fica.mkv' WHERE id = 8384;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\08 - Um Dia Cabeludo -  O Chap?u Proibido de Ouro.mkv' WHERE id = 8385;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\09 - A Serpente do Rio Mal?gno -  O Transplante.mkv' WHERE id = 8386;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\10 - Carro Quebrou, Telefone Sim -  Coragem Cowboy.mkv' WHERE id = 8387;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\11 - O Mordomo Malvado -  O Fantasma de McPherson.mkv' WHERE id = 8388;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\12 - A Casa do Descontentamento -  A Revolta da Baleia de Areia.mkv' WHERE id = 8389;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\2? Temporada\\\\13 - A Torre do Dr. Zalost.mkv' WHERE id = 8390;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\01 - Muriel Arruma Uma S?sia - Coragem Versus Mega-Coragem.mkv' WHERE id = 8391;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\02 - Acampamento do Terror - Um Disco do Outro Mundo.mkv' WHERE id = 8392;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\03 - Tempo Nublado - O Senhor dos Sonhos Dorme.mkv' WHERE id = 8393;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\04 - Disco R?gido do Coragem - A Cavalgada das Valqu?rias.mkv' WHERE id = 8394;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\05 - Scubba Scubba Doo - Conway, o Contaminador.mkv' WHERE id = 8395;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\06 - Katz no Fundo do Mar - A Cortina da Crueldade.mkv' WHERE id = 8396;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\07 - O Banquete dos Sapos - A Minhoca da Tulipa.mkv' WHERE id = 8397;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\08 - Estamos no Maior Louvre - Noite do Espantalho.mkv' WHERE id = 8398;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\09 - Mondo, o M?gico - Olha o Passarinho.mkv' WHERE id = 8399;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\10 - Neg?cio Suspeito - Gente Nervosa e M?.mkv' WHERE id = 8400;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\11 - A Ab?bada da Destrui??o - A Vingan?a do Boneco de Neve.mkv' WHERE id = 8401;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\12 - Clube da Colcha - Vento Enganador.mkv' WHERE id = 8402;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\3? Temporada\\\\13 - O Rei do Flan - Coragem Dentro do Vulc?o.mkv' WHERE id = 8403;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\01 - Hist?ria de um Castor - O Quebra-Nozes.mkv' WHERE id = 8404;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\02 - Bom Velho Kiltskin - Visitas.mkv' WHERE id = 8405;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\03 - Le Quack Bal?o - V?ndalos do Moinho.mkv' WHERE id = 8406;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\04 - A Gripe Incomum - Fazendeiro Ca?ador ? Fazendeiro Ca?ado.mkv' WHERE id = 8407;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\05 - A Noiva do Monstro do P?ntano - Dor Cabra-da-Peste.mkv' WHERE id = 8408;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\06 - Muriel Explode - Perfis de Coragem.mkv' WHERE id = 8409;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\07 - A M?scara.mkv' WHERE id = 8410;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\08 - O Tigre e o C?o - Muriel Muda.mkv' WHERE id = 8411;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\09 - Fazendeiro Aqu?tico - Comida de Drag?o.mkv' WHERE id = 8412;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\10 - O ?ltimo Fazedor de Estrelas - O Filho da Galinha do Espa?o.mkv' WHERE id = 8413;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\11 - Cura Corajosa - A Festa da Vingan?a.mkv' WHERE id = 8414;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\12 - Cabar? Coragem - A F?ria da Bibliotec?ria.mkv' WHERE id = 8415;
UPDATE episodio SET capa_url = 'F:\\\\Coragem - O C?o Covarde - Incompleto\\\\4? Temporada\\\\13 - Lembran?as do Passado do Coragem - Perfeito.mkv' WHERE id = 8416;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\01_Asteroid Blues_imagem.jpg' WHERE id = 8417;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\02_Cachorro de Rua Pomposo_imagem.jpg' WHERE id = 8418;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\03_Honky Tonk Women_imagem.jpg' WHERE id = 8419;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\04_Gateway Shuffle_imagem.jpg' WHERE id = 8420;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\05_Balada dos Anjos Ca?dos_imagem.jpg' WHERE id = 8421;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\06_Simpatia pelo Diabo_imagem.jpg' WHERE id = 8422;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\07_Heavy Metal Queen_imagem.jpg' WHERE id = 8423;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\08_Waltz for Venus_imagem.jpg' WHERE id = 8424;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\09_Jamming with Edward_imagem.jpg' WHERE id = 8425;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\10_Elegia de Ganimedes_imagem.jpg' WHERE id = 8426;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\11_Toys in the Attic_imagem.jpg' WHERE id = 8427;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\12_Jupiter Jazz (Parte 1)_imagem.jpg' WHERE id = 8428;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\13_Jupiter Jazz (Parte 2)_imagem.jpg' WHERE id = 8429;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\14_Bohemian Rhapsody_imagem.jpg' WHERE id = 8430;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\15_My Funny Valentine_imagem.jpg' WHERE id = 8431;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\16_Black Dog Serenade_imagem.jpg' WHERE id = 8432;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\17_Mushroom Samba_imagem.jpg' WHERE id = 8433;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\18_Speak Like a Child_imagem.jpg' WHERE id = 8434;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\19_Wild Horses_imagem.jpg' WHERE id = 8435;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\20_Pierrot le Fou (O Dem?nio das Onze Horas)_imagem.jpg' WHERE id = 8436;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\21_Boogie Woogie Feng Shui_imagem.jpg' WHERE id = 8437;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\22_Cowboy Funk_imagem.jpg' WHERE id = 8438;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\23_Brain Scratch_imagem.jpg' WHERE id = 8439;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\24_Hard Luck Woman_imagem.jpg' WHERE id = 8440;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\25_The Real Folk Blues (Parte 1)_imagem.jpg' WHERE id = 8441;
UPDATE episodio SET capa_url = 'F:\\\\Cowboy Bebop\\\\26_The Real Folk Blues (Parte 2)_imagem.jpg' WHERE id = 8442;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\01_? assim que o amor come?a, t? ligado_imagem.jpg' WHERE id = 8443;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\02_Isso a? ? um alien?gena, n?o ?!_imagem.jpg' WHERE id = 8444;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\03_Tem duas vov?s saindo na m?o!_imagem.jpg' WHERE id = 8445;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\04_Hora de arrebentar com a velha turbo_imagem.jpg' WHERE id = 8446;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\05_Cad? as suas bolas, cara_imagem.jpg' WHERE id = 8447;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\06_Chegou uma mulher que ? treta_imagem.jpg' WHERE id = 8448;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\07_Rumo a um mundo mais gentil_imagem.jpg' WHERE id = 8449;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\08_T? com uma sensa??o meio esquisita_imagem.jpg' WHERE id = 8450;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\09_Fus?o! Serpo Dover Demon Nessie!_imagem.jpg' WHERE id = 8451;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\10_Voc? j? viu uma mutila??o de gado_imagem.jpg' WHERE id = 8452;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\11_O primeiro amor_imagem.jpg' WHERE id = 8453;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\1? Temporada\\\\12_Partiu casa amaldi?oada_imagem.jpg' WHERE id = 8454;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E01.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8455;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E02.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8456;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E03.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8457;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E04.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8458;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E05.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8459;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E06.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8460;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E07.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8461;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E08.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8462;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E09.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8463;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E10.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8464;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E11.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8465;
UPDATE episodio SET capa_url = 'F:\\\\Dan da dan\\\\2? Temporada\\\\DAN.DA.DAN.S02E12.WEB-DL.1080p.x264.DUAL.2.0-SF.mkv' WHERE id = 8466;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\01_Renascimento_imagem.jpg' WHERE id = 8467;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\02_Batalha_imagem.jpg' WHERE id = 8468;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\03_Rela??es_imagem.jpg' WHERE id = 8469;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\04_Persegui??o_imagem.jpg' WHERE id = 8470;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\05_Diplomacia_imagem.jpg' WHERE id = 8471;
