UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\01_Um Novo Pr?logo_imagem.jpg' WHERE id = 14052;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\02_A Armadilha na Mans?o Yojiken_imagem.jpg' WHERE id = 14053;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\03_A Intelig?ncia de Kurama_imagem.jpg' WHERE id = 14054;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\04_Um Novo Enigma_imagem.jpg' WHERE id = 14055;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\05_O Terr?vel Port?o das Trevas_imagem.jpg' WHERE id = 14056;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\06_Os Sete Inimigos_imagem.jpg' WHERE id = 14057;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\07_Doutor, o Misterioso Inimigo_imagem.jpg' WHERE id = 14058;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\08_Acabe com o Territ?rio_imagem.jpg' WHERE id = 14059;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\09_Seaman e a sua Armadilha_imagem.jpg' WHERE id = 14060;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\10_A Ressurrei??o de Kuwabara! A Volta do Poder_imagem.jpg' WHERE id = 14061;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\11_O Passado Negro do Detetive Espiritual_imagem.jpg' WHERE id = 14062;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\12_O Ataque do Dark Angel_imagem.jpg' WHERE id = 14063;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\13_A Persegui??o de Yusuke_imagem.jpg' WHERE id = 14064;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\14_Hagiri e o Alvo da Morte_imagem.jpg' WHERE id = 14065;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\15_Guerra na Caverna_imagem.jpg' WHERE id = 14066;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\16_A Amea?a de Game Master_imagem.jpg' WHERE id = 14067;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\17_A Decis?o Firme de Kurama_imagem.jpg' WHERE id = 14068;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\18_O ?dio de Kurama_imagem.jpg' WHERE id = 14069;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\19_O Combate do Detetive Sobrenatural_imagem.jpg' WHERE id = 14070;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\20_A Dura Batalha de Yusuke_imagem.jpg' WHERE id = 14071;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\21_Koenma e o Golpe Secreto Mafuukan_imagem.jpg' WHERE id = 14072;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\22_Sensui e o Golpe Seikoki_imagem.jpg' WHERE id = 14073;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\23_A Morte de Yusuke_imagem.jpg' WHERE id = 14074;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\24_A Vontade do Amigo Continua_imagem.jpg' WHERE id = 14075;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\25_O Patrulhamento_imagem.jpg' WHERE id = 14076;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\26_A Luta Extrema_imagem.jpg' WHERE id = 14077;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\27_A Batalha Violenta_imagem.jpg' WHERE id = 14078;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 3\\\\28_Ep?logo - O Amanh?_imagem.jpg' WHERE id = 14079;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\01_O Destino de Yusuke_imagem.jpg' WHERE id = 14080;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\02_Os Visitantes das Trevas_imagem.jpg' WHERE id = 14081;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\03_A Despedida_imagem.jpg' WHERE id = 14082;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\04_O Confronto com o Pai_imagem.jpg' WHERE id = 14083;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\05_Lembran?a Inesquec?vel_imagem.jpg' WHERE id = 14084;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\06_O Segredo do Olho Diab?lico_imagem.jpg' WHERE id = 14085;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\07_O Ladr?o das Trevas_imagem.jpg' WHERE id = 14086;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\08_A Mudan?a de Kurama Youko_imagem.jpg' WHERE id = 14087;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\09_As ?ltimas Palavras de Raizen_imagem.jpg' WHERE id = 14088;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\10_A Estranha Proposta_imagem.jpg' WHERE id = 14089;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\11_O In?cio do Novo Torneio_imagem.jpg' WHERE id = 14090;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\12_A Luta Entre Pai e Filho_imagem.jpg' WHERE id = 14091;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\13_A Luta Violenta_imagem.jpg' WHERE id = 14092;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\14_Kurama e o Desligamento com o Passado_imagem.jpg' WHERE id = 14093;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\15_A Luta Entre Hiei e Mukuro_imagem.jpg' WHERE id = 14094;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\16_A For?a Total_imagem.jpg' WHERE id = 14095;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\17_A Decis?o Final_imagem.jpg' WHERE id = 14096;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 4\\\\18_Eternamente Yu Yu Hakusho_imagem.jpg' WHERE id = 14097;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\10_O Espectro se Revela_imagem.jpg' WHERE id = 14098;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\11_O Mico de Duelo_imagem.jpg' WHERE id = 14099;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\12_Os Olhos Vermelhos_imagem.jpg' WHERE id = 14100;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\13_O Esp?rito Maligno do Anel_imagem.jpg' WHERE id = 14101;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\14_A Luz no Fim do T?nel_imagem.jpg' WHERE id = 14102;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\15_Vit?ria por Intimida??o_imagem.jpg' WHERE id = 14103;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\16_As Cicatrizes da Derrota_imagem.jpg' WHERE id = 14104;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\17_A Arena das Almas Perdidas (1)_imagem.jpg' WHERE id = 14105;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\18_A Arena das Almas Perdidas (2)_imagem.jpg' WHERE id = 14106;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\19_Duelo de Confus?o Dupla (1_imagem.jpg' WHERE id = 14107;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\20_Duelo de Confus?o Dupla (2)_imagem.jpg' WHERE id = 14109;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\21_Duelo de Confus?o Dupla (3)_imagem.jpg' WHERE id = 14110;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\22_Confronto (1)_imagem.jpg' WHERE id = 14111;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\23_Confronto (2)_imagem.jpg' WHERE id = 14112;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\24_Confronto (3)_imagem.jpg' WHERE id = 14113;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\25_Amizade Brilhante_imagem.jpg' WHERE id = 14114;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\26_Campe?o VS Criador (1)_imagem.jpg' WHERE id = 14115;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\27_Campe?o VS Criador (2)_imagem.jpg' WHERE id = 14116;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\28_A Noite Anterior_imagem.jpg' WHERE id = 14117;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\29_Identidade de Duelo (1)_imagem.jpg' WHERE id = 14118;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\30_Identidade de Duelo (2)_imagem.jpg' WHERE id = 14120;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\31_Maquina??es de Keith (1)_imagem.jpg' WHERE id = 14121;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\32_Maquina??es de Keith (2)_imagem.jpg' WHERE id = 14122;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\33_Melhor dos Amigos, Melhor dos Duelistas (1)_imagem.jpg' WHERE id = 14123;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\34_Melhor dos Amigos, Melhor dos Duelistas (2)_imagem.jpg' WHERE id = 14124;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\35_Yugi VS Pegasus O Jogo do Mil?nio (1)_imagem.jpg' WHERE id = 14125;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\36_Yugi VS Pegasus O Jogo do Mil?nio (2)_imagem.jpg' WHERE id = 14126;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\37_Yugi VS Pegasus O Jogo do Mil?nio (3)_imagem.jpg' WHERE id = 14127;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\38_Yugi VS Pegasus O Jogo do Mil?nio (4)_imagem.jpg' WHERE id = 14128;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\39_Yugi VS Pegasus O Jogo do Mil?nio (5)_imagem.jpg' WHERE id = 14129;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\40_Consequ?ncias_imagem.jpg' WHERE id = 14131;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\41_A F?ria de Rebecca_imagem.jpg' WHERE id = 14132;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\42_As L?grimas da Amizade_imagem.jpg' WHERE id = 14133;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\43_Her?is Lend?rios (1)_imagem.jpg' WHERE id = 14134;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\44_Her?is Lend?rios (2)_imagem.jpg' WHERE id = 14135;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\45_Her?is Lend?rios (3)_imagem.jpg' WHERE id = 14136;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\46_Monstros dos Dados Masmorra (1)_imagem.jpg' WHERE id = 14137;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\47_Monstros dos Dados Masmorra (2)_imagem.jpg' WHERE id = 14138;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\48_Monstros dos Dados Masmorra (3)_imagem.jpg' WHERE id = 14139;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\1? Temporada\\\\49_Monstros dos Dados Masmorra (4)_imagem.jpg' WHERE id = 14140;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\10_Espa Roba - O Duelista Ps?quico (2)_imagem.jpg' WHERE id = 14147;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\11_Mestre dos Magos (1)_imagem.jpg' WHERE id = 14148;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\12_Mestre dos Magos (2)_imagem.jpg' WHERE id = 14149;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\13_Mestre dos Magos (3)_imagem.jpg' WHERE id = 14150;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\14_Jogando com um Parasita (1)_imagem.jpg' WHERE id = 14151;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\15_Jogando com um Parasita (2)_imagem.jpg' WHERE id = 14152;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\16_Controle de Marionete (1)_imagem.jpg' WHERE id = 14153;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\17_Controle de Marionete (2)_imagem.jpg' WHERE id = 14154;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\18_Controle de Marionete (3)_imagem.jpg' WHERE id = 14155;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\19_Pescador Legend?rio (1)_imagem.jpg' WHERE id = 14156;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\20_Pescador Legend?rio (2)_imagem.jpg' WHERE id = 14158;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\21_Duelo Duplo (1)_imagem.jpg' WHERE id = 14159;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\22_Duelo Duplo (2)_imagem.jpg' WHERE id = 14160;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\23_Duelo Duplo (3)_imagem.jpg' WHERE id = 14161;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\24_Duelo Duplo (4)_imagem.jpg' WHERE id = 14162;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\25_O Resgate_imagem.jpg' WHERE id = 14163;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\26_Amigos at? o Fim (1)_imagem.jpg' WHERE id = 14164;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\27_Amigos at? o Fim (2)_imagem.jpg' WHERE id = 14165;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\28_Amigos at? o Fim (3)_imagem.jpg' WHERE id = 14166;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\29_Amigos at? o Fim (4)_imagem.jpg' WHERE id = 14167;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\30_Sombra do Duelo_imagem.jpg' WHERE id = 14169;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\31_Luzes, C?mera, Duelo!_imagem.jpg' WHERE id = 14170;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\32_Deixe as Finais Come?arem!_imagem.jpg' WHERE id = 14171;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\33_O Esp?rito Obscuro Revelado (1)_imagem.jpg' WHERE id = 14172;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\34_O Esp?rito Obscuro Revelado (2)_imagem.jpg' WHERE id = 14173;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\35_O Esp?rito Obscuro Revelado (3)_imagem.jpg' WHERE id = 14174;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\36_A F?ria dos Deuses Eg?pcios_imagem.jpg' WHERE id = 14175;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\37_Despertar do Mal (1)_imagem.jpg' WHERE id = 14176;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\38_Despertar do Mal (2)_imagem.jpg' WHERE id = 14177;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\39_Despertar do Mal (3)_imagem.jpg' WHERE id = 14178;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\40_Despertar do Mal (4)_imagem.jpg' WHERE id = 14180;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\41_Jogo Mental (1)_imagem.jpg' WHERE id = 14181;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\42_Jogo Mental (2)_imagem.jpg' WHERE id = 14182;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\43_Jogo Mental (3)_imagem.jpg' WHERE id = 14183;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\44_Um Duelo com o Destino (1)_imagem.jpg' WHERE id = 14184;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\45_Um Duelo com o Destino (2)_imagem.jpg' WHERE id = 14185;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\46_O Segredo do Guardador de Tumbas_imagem.jpg' WHERE id = 14186;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\47_Desafio nas Sombras (1)_imagem.jpg' WHERE id = 14187;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\2? Temporada\\\\48_Desafio nas Sombras (2)_imagem.jpg' WHERE id = 14188;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\10_Confus?o Mec?nica (2)_imagem.jpg' WHERE id = 14195;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\11_Decidindo o Placar (1)_imagem.jpg' WHERE id = 14196;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\12_Decidindo o Placar (2)_imagem.jpg' WHERE id = 14197;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\13_O Segredo de Noah_imagem.jpg' WHERE id = 14198;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\14_A Uni?o da Big 5 (1)_imagem.jpg' WHERE id = 14199;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\15_A Uni?o da Big 5 (2)_imagem.jpg' WHERE id = 14200;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\16_A Uni?o da Big 5 (3)_imagem.jpg' WHERE id = 14201;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\17_Irm?os Adotivos (1)_imagem.jpg' WHERE id = 14202;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\18_Irm?os Adotivos (2)_imagem.jpg' WHERE id = 14203;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\19_Irm?os Adotivos (3)_imagem.jpg' WHERE id = 14204;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\20_A Amea?a Final de Noah (1)_imagem.jpg' WHERE id = 14206;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\21_A Amea?a Final de Noah (2)_imagem.jpg' WHERE id = 14207;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\22_T?o Perto e Ainda T?o Longe_imagem.jpg' WHERE id = 14208;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\23_Enterrando o Passado (1)_imagem.jpg' WHERE id = 14209;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 1\\\\24_Enterrando o Passado (2)_imagem.jpg' WHERE id = 14210;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\10_Colis?o no Coliseu (3)_imagem.jpg' WHERE id = 14219;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\11_Colis?o no Coliseu (4)_imagem.jpg' WHERE id = 14220;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\12_Colis?o no Coliseu (5)_imagem.jpg' WHERE id = 14221;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\13_Colis?o no Coliseu (6)_imagem.jpg' WHERE id = 14222;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\14_Batalha pelo Bronze (1)_imagem.jpg' WHERE id = 14223;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\15_Batalha pelo Bronze (2)_imagem.jpg' WHERE id = 14224;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\16_Batalha pelo Bronze (3)_imagem.jpg' WHERE id = 14225;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\17_Confronto Final (1)_imagem.jpg' WHERE id = 14226;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\18_Confronto Final (2)_imagem.jpg' WHERE id = 14227;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\19_Confronto Final (3)_imagem.jpg' WHERE id = 14228;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\20_Confronto Final (4)_imagem.jpg' WHERE id = 14230;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\21_Confronto Final (5)_imagem.jpg' WHERE id = 14231;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\22_Recome?ando a Jornada_imagem.jpg' WHERE id = 14232;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\3? Temporada\\\\Parte 2\\\\23_Olhando Para Tr?s e Indo em Frente_imagem.jpg' WHERE id = 14233;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\10_Mai do Lado do Inimigo (3)_imagem.jpg' WHERE id = 14242;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\11_O Desafio_imagem.jpg' WHERE id = 14243;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\12_O Destino do Fara? (1)_imagem.jpg' WHERE id = 14244;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\13_O Destino do Fara? (2)_imagem.jpg' WHERE id = 14245;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\14_O Destino do Fara? (3)_imagem.jpg' WHERE id = 14246;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\15_O Julgamento da Pedra_imagem.jpg' WHERE id = 14247;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\16_Na Trilha Errada (1)_imagem.jpg' WHERE id = 14248;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\17_Na Trilha Errada (2)_imagem.jpg' WHERE id = 14249;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\18_Na Trilha Errada (3)_imagem.jpg' WHERE id = 14250;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\19_Autodestrui??o_imagem.jpg' WHERE id = 14251;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\20_Revivendo o Passado_imagem.jpg' WHERE id = 14253;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\21_Baralho Blindado_imagem.jpg' WHERE id = 14254;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\22_O Voo do Medo (1)_imagem.jpg' WHERE id = 14255;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\23_O Voo do Medo (2)_imagem.jpg' WHERE id = 14256;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\24_Para?so Encontrado_imagem.jpg' WHERE id = 14257;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\25_Lutando por uma Amiga (1)_imagem.jpg' WHERE id = 14258;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\26_Lutando por uma Amiga (2)_imagem.jpg' WHERE id = 14259;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\27_Lutando por uma Amiga (3)_imagem.jpg' WHERE id = 14260;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\28_Lutando por uma Amiga (4)_imagem.jpg' WHERE id = 14261;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\29_Lutando por uma Amiga (5)_imagem.jpg' WHERE id = 14262;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\30_Lutando com o Guardi?o (1)_imagem.jpg' WHERE id = 14264;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\31_Lutando com o Guardi?o (2)_imagem.jpg' WHERE id = 14265;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\32_Lutando com o Guardi?o (3)_imagem.jpg' WHERE id = 14266;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\33_Duelo com o Dartz (1)_imagem.jpg' WHERE id = 14267;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\34_Duelo com o Dartz (2)_imagem.jpg' WHERE id = 14268;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\35_Duelo com o Dartz (3)_imagem.jpg' WHERE id = 14269;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\36_Duelo com o Dartz (4)_imagem.jpg' WHERE id = 14270;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\37_Duelo com o Dartz (5)_imagem.jpg' WHERE id = 14271;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\38_Duelo com o Dartz (6)_imagem.jpg' WHERE id = 14272;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\39_A Ascens?o da Grande Fera (1)_imagem.jpg' WHERE id = 14273;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\4? Temporada\\\\40_A Ascens?o da Grande Fera (2)_imagem.jpg' WHERE id = 14275;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 1\\\\10_Um Passo ? Frente (1)_imagem.jpg' WHERE id = 14282;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 1\\\\11_Um Passo ? Frente (2)_imagem.jpg' WHERE id = 14283;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 1\\\\12_Segredos Sinistros (1)_imagem.jpg' WHERE id = 14284;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 1\\\\13_Segredos Sinistros (2)_imagem.jpg' WHERE id = 14285;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 1\\\\14_Segredos Sinistros (3)_imagem.jpg' WHERE id = 14286;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\10_Em Busca de um Rei_imagem.jpg' WHERE id = 14296;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\11_Vila da Vingan?a (1)_imagem.jpg' WHERE id = 14297;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\12_Vila da Vingan?a (2)_imagem.jpg' WHERE id = 14298;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\13_Vila da Vingan?a (3)_imagem.jpg' WHERE id = 14299;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\14_Vila da Vingan?a (4)_imagem.jpg' WHERE id = 14300;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\15_Vila da Vingan?a (5)_imagem.jpg' WHERE id = 14301;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\16_O Nome do Jogo_imagem.jpg' WHERE id = 14302;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\17_O Comit? do Mal (1)_imagem.jpg' WHERE id = 14303;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\18_O Comit? do Mal (2)_imagem.jpg' WHERE id = 14304;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\19_O Comit? do Mal (3)_imagem.jpg' WHERE id = 14305;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\20_O Comit? do Mal (4)_imagem.jpg' WHERE id = 14307;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\21_Em Nome do Fara?!_imagem.jpg' WHERE id = 14308;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\22_A ?ltima Viagem_imagem.jpg' WHERE id = 14309;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\23_O Duelo Final (1)_imagem.jpg' WHERE id = 14310;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\24_O Duelo Final (2)_imagem.jpg' WHERE id = 14311;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\25_O Duelo Final (3)_imagem.jpg' WHERE id = 14312;
UPDATE episodio SET capa_url = 'F:\\\\Yu-Gi-Oh! - Incompleto\\\\5? Temporada\\\\Parte 2\\\\26_O Duelo Final (4)_imagem.jpg' WHERE id = 14313;
