UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\1? Temporada\\\\12_150146_imagem.jpg' WHERE id = 13552;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\01_Episode 1_imagem.jpg' WHERE id = 13553;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\02_Episode 2_imagem.jpg' WHERE id = 13554;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\03_Episode 3_imagem.jpg' WHERE id = 13555;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\04_Episode 4_imagem.jpg' WHERE id = 13556;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\05_Episode 5_imagem.jpg' WHERE id = 13557;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\06_Episode 6_imagem.jpg' WHERE id = 13558;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\07_Episode 7_imagem.jpg' WHERE id = 13559;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\08_Episode 8_imagem.jpg' WHERE id = 13560;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\09_Episode 9_imagem.jpg' WHERE id = 13561;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\10_Episode 10_imagem.jpg' WHERE id = 13562;
UPDATE episodio SET capa_url = 'F:\\\\The Promised Neverland - Legendado\\\\2? Temporada\\\\11_Episode 11_imagem.jpg' WHERE id = 13563;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP01_imagem.jpg' WHERE id = 13564;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP02_imagem.jpg' WHERE id = 13565;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP03_imagem.jpg' WHERE id = 13566;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP04_imagem.jpg' WHERE id = 13567;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP05_imagem.jpg' WHERE id = 13568;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP06_imagem.jpg' WHERE id = 13569;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP07_imagem.jpg' WHERE id = 13570;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP08_imagem.jpg' WHERE id = 13571;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP09_imagem.jpg' WHERE id = 13572;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP10_imagem.jpg' WHERE id = 13573;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP11_imagem.jpg' WHERE id = 13574;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP12_imagem.jpg' WHERE id = 13575;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP13_imagem.jpg' WHERE id = 13576;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP14_imagem.jpg' WHERE id = 13577;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP15_imagem.jpg' WHERE id = 13578;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP16_imagem.jpg' WHERE id = 13579;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP17_imagem.jpg' WHERE id = 13580;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP18_imagem.jpg' WHERE id = 13581;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP19_imagem.jpg' WHERE id = 13582;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP20_imagem.jpg' WHERE id = 13583;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP21_imagem.jpg' WHERE id = 13584;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP22_imagem.jpg' WHERE id = 13585;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP23_imagem.jpg' WHERE id = 13586;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP24_imagem.jpg' WHERE id = 13587;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP25_imagem.jpg' WHERE id = 13588;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP26_imagem.jpg' WHERE id = 13589;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP27_imagem.jpg' WHERE id = 13590;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP28_imagem.jpg' WHERE id = 13591;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP29_imagem.jpg' WHERE id = 13592;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP30_imagem.jpg' WHERE id = 13593;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP31_imagem.jpg' WHERE id = 13594;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP32_imagem.jpg' WHERE id = 13595;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP33_imagem.jpg' WHERE id = 13596;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP34_imagem.jpg' WHERE id = 13597;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP35_imagem.jpg' WHERE id = 13598;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP36_imagem.jpg' WHERE id = 13599;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP37_imagem.jpg' WHERE id = 13600;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP38_imagem.jpg' WHERE id = 13601;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP39_imagem.jpg' WHERE id = 13602;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP40_imagem.jpg' WHERE id = 13603;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP41_imagem.jpg' WHERE id = 13604;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP42_imagem.jpg' WHERE id = 13605;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP43_imagem.jpg' WHERE id = 13606;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP44_imagem.jpg' WHERE id = 13607;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP45_imagem.jpg' WHERE id = 13608;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP46_imagem.jpg' WHERE id = 13609;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP47_imagem.jpg' WHERE id = 13610;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP48_imagem.jpg' WHERE id = 13611;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP49_imagem.jpg' WHERE id = 13612;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP50_imagem.jpg' WHERE id = 13613;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP51_imagem.jpg' WHERE id = 13614;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP52_imagem.jpg' WHERE id = 13615;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP53_imagem.jpg' WHERE id = 13616;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP54_imagem.jpg' WHERE id = 13617;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP55_imagem.jpg' WHERE id = 13618;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP56_imagem.jpg' WHERE id = 13619;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP57_imagem.jpg' WHERE id = 13620;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP58_imagem.jpg' WHERE id = 13621;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP59_imagem.jpg' WHERE id = 13622;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP60_imagem.jpg' WHERE id = 13623;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP61_imagem.jpg' WHERE id = 13624;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP62_imagem.jpg' WHERE id = 13625;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP63_imagem.jpg' WHERE id = 13626;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP64_imagem.jpg' WHERE id = 13627;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\1? Temporada\\\\TNYTONST01EP65_imagem.jpg' WHERE id = 13628;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP01_imagem.jpg' WHERE id = 13629;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP02_imagem.jpg' WHERE id = 13630;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP03_imagem.jpg' WHERE id = 13631;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP04_imagem.jpg' WHERE id = 13632;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP05_imagem.jpg' WHERE id = 13633;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP06_imagem.jpg' WHERE id = 13634;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP07_imagem.jpg' WHERE id = 13635;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP08_imagem.jpg' WHERE id = 13636;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP09_imagem.jpg' WHERE id = 13637;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP10_imagem.jpg' WHERE id = 13638;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP11_imagem.jpg' WHERE id = 13639;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP12_imagem.jpg' WHERE id = 13640;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\2? Temporada\\\\TNYTONST02EP13_imagem.jpg' WHERE id = 13641;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP01_imagem.jpg' WHERE id = 13642;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP02_imagem.jpg' WHERE id = 13643;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP03_imagem.jpg' WHERE id = 13644;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP04_imagem.jpg' WHERE id = 13645;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP05_imagem.jpg' WHERE id = 13646;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP06_imagem.jpg' WHERE id = 13647;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP07_imagem.jpg' WHERE id = 13648;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP08_imagem.jpg' WHERE id = 13649;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP09_imagem.jpg' WHERE id = 13650;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP10_imagem.jpg' WHERE id = 13651;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP11_imagem.jpg' WHERE id = 13652;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP12_imagem.jpg' WHERE id = 13653;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP13_imagem.jpg' WHERE id = 13654;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP14_imagem.jpg' WHERE id = 13655;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP15_imagem.jpg' WHERE id = 13656;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP16_imagem.jpg' WHERE id = 13657;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP17_imagem.jpg' WHERE id = 13658;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP18_imagem.jpg' WHERE id = 13659;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP19_imagem.jpg' WHERE id = 13660;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\3? Temporada\\\\TNYTONST03EP20_imagem.jpg' WHERE id = 13661;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\Especiais\\\\TNYTONSESPCLPRMVRA_imagem.jpg' WHERE id = 13662;
UPDATE episodio SET capa_url = 'F:\\\\Tiny Toons - Incompleto\\\\Especiais\\\\TNYTONSESPCLUMNTEMTNTO_imagem.jpg' WHERE id = 13663;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\01_Trag?dia_imagem.jpg' WHERE id = 13664;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\02_Incuba??o_imagem.jpg' WHERE id = 13665;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\03_Pombo_imagem.jpg' WHERE id = 13666;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\04_Jantar_imagem.jpg' WHERE id = 13667;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\05_Cicatrizes_imagem.jpg' WHERE id = 13668;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\06_Tempestade_imagem.jpg' WHERE id = 13669;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\07_Cativeiro_imagem.jpg' WHERE id = 13670;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\08_Circular_imagem.jpg' WHERE id = 13671;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\09_Gaiola_imagem.jpg' WHERE id = 13672;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\10_Aogiri_imagem.jpg' WHERE id = 13673;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\11_Euforia_imagem.jpg' WHERE id = 13674;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\1? Temporada\\\\12_Ghoul_imagem.jpg' WHERE id = 13675;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\01_Nova Onda_imagem.jpg' WHERE id = 13676;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\02_Dan?a das Flores_imagem.jpg' WHERE id = 13677;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\03_Carrasco_imagem.jpg' WHERE id = 13678;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\04_Camada Profunda_imagem.jpg' WHERE id = 13679;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\05_Fenda_imagem.jpg' WHERE id = 13680;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\06_Mil Trajetos_imagem.jpg' WHERE id = 13681;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\07_Permea??o_imagem.jpg' WHERE id = 13682;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\08_Velhos Noves_imagem.jpg' WHERE id = 13683;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\09_Cidade em Espera_imagem.jpg' WHERE id = 13684;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\10_?ltima Chuva_imagem.jpg' WHERE id = 13685;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\11_Dil?vio de Flores_imagem.jpg' WHERE id = 13686;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\2? Temporada\\\\12_Ken_imagem.jpg' WHERE id = 13687;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\01_Start - Aqueles que Ca?am_imagem.jpg' WHERE id = 13688;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\02_Member - Fragmentos_imagem.jpg' WHERE id = 13689;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\03_Fresh - A V?spera do Evento_imagem.jpg' WHERE id = 13690;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\04_Main - Leil?o_imagem.jpg' WHERE id = 13691;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\05_Press - Noite do Massacre_imagem.jpg' WHERE id = 13692;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\06_Turn - No Final_imagem.jpg' WHERE id = 13693;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\07_Mind - Dias de Recorda??es_imagem.jpg' WHERE id = 13694;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\08_Take - Aquele que Atormenta_imagem.jpg' WHERE id = 13695;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\09_Play - Fantasma_imagem.jpg' WHERE id = 13696;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\10_Think - Influ?ncia_imagem.jpg' WHERE id = 13697;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\11_Write - O Ausente_imagem.jpg' WHERE id = 13698;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\3? Temporada\\\\12_Beautiful - Dream Amanhecer_imagem.jpg' WHERE id = 13699;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\01_Place - E Ent?o, Mais Uma Vez_imagem.jpg' WHERE id = 13700;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\02_VOLT - Escurid?o Branca_imagem.jpg' WHERE id = 13701;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\03_Union - Jogo Equilibrado_imagem.jpg' WHERE id = 13702;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\04_Vive - Deixados para Tr?s_imagem.jpg' WHERE id = 13703;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\05_Move - Converg?ncia, Confus?o_imagem.jpg' WHERE id = 13704;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\06_Face - Resplendor_imagem.jpg' WHERE id = 13705;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\07_Proof - La?os_imagem.jpg' WHERE id = 13706;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\08_Incarnation - Crian?a Desperta_imagem.jpg' WHERE id = 13707;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\09_Morse - Lembran?as_imagem.jpg' WHERE id = 13708;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\10_Call - O Outro Lado da Trag?dia_imagem.jpg' WHERE id = 13709;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\11_ACT - Encontros_imagem.jpg' WHERE id = 13710;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Ghoul\\\\4? Temporada\\\\12_Epis?dio 24_imagem.jpg' WHERE id = 13711;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\01_Renascer_imagem.jpg' WHERE id = 13712;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\02_Resisitir_imagem.jpg' WHERE id = 13713;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\03_Resolu??o_imagem.jpg' WHERE id = 13714;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\04_Retorno_imagem.jpg' WHERE id = 13715;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\05_Regresso_imagem.jpg' WHERE id = 13716;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\06_Remorso_imagem.jpg' WHERE id = 13717;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\07_Reviver_imagem.jpg' WHERE id = 13718;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\08_Renovar_imagem.jpg' WHERE id = 13719;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\09_Revolta_imagem.jpg' WHERE id = 13720;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\10_Reerguer_imagem.jpg' WHERE id = 13721;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\11_Respeito_imagem.jpg' WHERE id = 13722;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\12_Retalia??o_imagem.jpg' WHERE id = 13723;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\13_Pontas Soltas_imagem.jpg' WHERE id = 13724;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\14_Rompimento_imagem.jpg' WHERE id = 13725;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\15_Quem n?o chora, n?o mama_imagem.jpg' WHERE id = 13726;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\16_Era uma vez_imagem.jpg' WHERE id = 13727;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\17_N?o pode ser_imagem.jpg' WHERE id = 13728;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\18_Abrir fogo_imagem.jpg' WHERE id = 13729;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\19_Virada_imagem.jpg' WHERE id = 13730;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\20_Vivo ou morto_imagem.jpg' WHERE id = 13731;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\21_Primeiro e ?nico_imagem.jpg' WHERE id = 13732;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\22_Um por todos_imagem.jpg' WHERE id = 13733;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\23_Fim da Guerra_imagem.jpg' WHERE id = 13734;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\1? Temporada\\\\24_Um beb? chor?o_imagem.jpg' WHERE id = 13735;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\01_It is what it is_imagem.jpg' WHERE id = 13736;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\02_Gotta go_imagem.jpg' WHERE id = 13737;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\03_Stand alone_imagem.jpg' WHERE id = 13738;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\04_Family bonds_imagem.jpg' WHERE id = 13739;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\05_Christmas Eve_imagem.jpg' WHERE id = 13740;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\06_Whip up morale_imagem.jpg' WHERE id = 13741;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\07_Sibling rivalry_imagem.jpg' WHERE id = 13742;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\08_Strive together_imagem.jpg' WHERE id = 13743;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\09_Dawning of a new era_imagem.jpg' WHERE id = 13744;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\10_The light of my life_imagem.jpg' WHERE id = 13745;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\11_On my way home_imagem.jpg' WHERE id = 13746;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\12_Last order_imagem.jpg' WHERE id = 13747;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\2? Temporada\\\\13_When it rains, it pours_imagem.jpg' WHERE id = 13748;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\01_The longest day_imagem.jpg' WHERE id = 13749;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\02_Mortal enemy_imagem.jpg' WHERE id = 13750;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\03_Run out of patience_imagem.jpg' WHERE id = 13751;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\04_Come back to life_imagem.jpg' WHERE id = 13752;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\05_A bad hunch_imagem.jpg' WHERE id = 13753;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\06_Rise against_imagem.jpg' WHERE id = 13754;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\07_Turn the tide_imagem.jpg' WHERE id = 13755;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\08_I know in my head_imagem.jpg' WHERE id = 13756;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\09_The blue ogre_imagem.jpg' WHERE id = 13757;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\10_Brave heart_imagem.jpg' WHERE id = 13758;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\11_Nothing is left_imagem.jpg' WHERE id = 13759;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\12_Paradise lost_imagem.jpg' WHERE id = 13760;
UPDATE episodio SET capa_url = 'F:\\\\Tokyo Revengers\\\\3? Temporada - Legendado\\\\13_Meet his fate_imagem.jpg' WHERE id = 13761;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.01.Tom&Jerry.CP.PradO.avi' WHERE id = 13762;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.02.Tom&Jerry.CP.PradO.avi' WHERE id = 13763;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.03.Tom&Jerry.CP.PradO.avi' WHERE id = 13764;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.04.Tom&Jerry.CP.PradO.avi' WHERE id = 13765;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.05.Tom&Jerry.CP.PradO.avi' WHERE id = 13766;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.06.Tom&Jerry.CP.PradO.avi' WHERE id = 13767;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.07.Tom&Jerry.CP.PradO.avi' WHERE id = 13768;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.08.Tom&Jerry.CP.PradO.avi' WHERE id = 13769;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.09.Tom&Jerry.CP.PradO.avi' WHERE id = 13770;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.10.Tom&Jerry.CP.PradO.avi' WHERE id = 13771;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.100.Tom&Jerry.CP.PradO.avi' WHERE id = 13772;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.101.Tom&Jerry.CP.PradO.avi' WHERE id = 13773;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.102.Tom&Jerry.CP.PradO.avi' WHERE id = 13774;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.103.Tom&Jerry.CP.PradO.avi' WHERE id = 13775;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.104.Tom&Jerry.CP.PradO.avi' WHERE id = 13776;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.105.Tom&Jerry.CP.PradO.avi' WHERE id = 13777;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.106.Tom&Jerry.CP.PradO.avi' WHERE id = 13778;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.108.Tom&Jerry.CP.PradO.avi' WHERE id = 13779;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.109.Tom&Jerry.CP.PradO.avi' WHERE id = 13780;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.11.Tom&Jerry.CP.PradO.avi' WHERE id = 13781;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.110.Tom&Jerry.CP.PradO.avi' WHERE id = 13782;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.111.Tom&Jerry.CP.PradO.avi' WHERE id = 13783;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.112.Tom&Jerry.CP.PradO.avi' WHERE id = 13784;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.113.Tom&Jerry.CP.PradO.avi' WHERE id = 13785;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.114.Tom&Jerry.CP.PradO.avi' WHERE id = 13786;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.115.Tom&Jerry.CP.PradO.avi' WHERE id = 13787;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.116.Tom&Jerry.CP.PradO.avi' WHERE id = 13788;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.117.Tom&Jerry.CP.PradO.avi' WHERE id = 13789;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.118.Tom&Jerry.CP.PradO.avi' WHERE id = 13790;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.119.Tom&Jerry.CP.PradO.avi' WHERE id = 13791;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.12.Tom&Jerry.CP.PradO.avi' WHERE id = 13792;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.120.Tom&Jerry.CP.PradO.avi' WHERE id = 13793;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.121.Tom&Jerry.CP.PradO.avi' WHERE id = 13794;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.122.Tom&Jerry.CP.PradO.avi' WHERE id = 13795;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.123.Tom&Jerry.CP.PradO.avi' WHERE id = 13796;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.124.Tom&Jerry.CP.PradO.avi' WHERE id = 13797;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.125.Tom&Jerry.CP.PradO.avi' WHERE id = 13798;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.126.Tom&Jerry.CP.PradO.avi' WHERE id = 13799;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.127.Tom&Jerry.CP.PradO.avi' WHERE id = 13800;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.128.Tom&Jerry.CP.PradO.avi' WHERE id = 13801;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.129.Tom&Jerry.CP.PradO.avi' WHERE id = 13802;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.13.Tom&Jerry.CP.PradO.avi' WHERE id = 13803;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.130.Tom&Jerry.CP.PradO.avi' WHERE id = 13804;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.131.Tom&Jerry.CP.PradO.avi' WHERE id = 13805;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.132.Tom&Jerry.CP.PradO.avi' WHERE id = 13806;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.133.Tom&Jerry.CP.PradO.avi' WHERE id = 13807;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.134.Tom&Jerry.CP.PradO.avi' WHERE id = 13808;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.135.Tom&Jerry.CP.PradO.avi' WHERE id = 13809;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.136.Tom&Jerry.CP.PradO.avi' WHERE id = 13810;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.137.Tom&Jerry.CP.PradO.avi' WHERE id = 13811;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.138.Tom&Jerry.CP.PradO.avi' WHERE id = 13812;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.139.Tom&Jerry.CP.PradO.avi' WHERE id = 13813;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.14.Tom&Jerry.CP.PradO.avi' WHERE id = 13814;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.140.Tom&Jerry.CP.PradO.avi' WHERE id = 13815;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.141.Tom&Jerry.CP.PradO.avi' WHERE id = 13816;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.142.Tom&Jerry.CP.PradO.avi' WHERE id = 13817;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.143.Tom&Jerry.CP.PradO.avi' WHERE id = 13818;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.144.Tom&Jerry.CP.PradO.avi' WHERE id = 13819;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.145.Tom&Jerry.CP.PradO.avi' WHERE id = 13820;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.146.Tom&Jerry.CP.PradO.avi' WHERE id = 13821;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.147.Tom&Jerry.CP.PradO.avi' WHERE id = 13822;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.148.Tom&Jerry.CP.PradO.avi' WHERE id = 13823;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.149.Tom&Jerry.CP.PradO.avi' WHERE id = 13824;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.15.Tom&Jerry.CP.PradO.avi' WHERE id = 13825;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.150.Tom&Jerry.CP.PradO.avi' WHERE id = 13826;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.151.Tom&Jerry.CP.PradO.avi' WHERE id = 13827;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.152.Tom&Jerry.CP.PradO.avi' WHERE id = 13828;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.153.Tom&Jerry.CP.PradO.avi' WHERE id = 13829;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.154.Tom&Jerry.CP.PradO.avi' WHERE id = 13830;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.155.Tom&Jerry.CP.PradO.avi' WHERE id = 13831;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.156.Tom&Jerry.CP.PradO.avi' WHERE id = 13832;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.157.Tom&Jerry.CP.PradO.avi' WHERE id = 13833;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.158.Tom&Jerry.CP.PradO.avi' WHERE id = 13834;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.159.Tom&Jerry.CP.PradO.avi' WHERE id = 13835;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.16.Tom&Jerry.CP.PradO.avi' WHERE id = 13836;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.160.Tom&Jerry.CP.PradO.avi' WHERE id = 13837;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.161.Tom&Jerry.CP.PradO.avi' WHERE id = 13838;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.162.Tom&Jerry.CP.PradO.avi' WHERE id = 13839;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.17.Tom&Jerry.CP.PradO.avi' WHERE id = 13840;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.18.Tom&Jerry.CP.PradO.avi' WHERE id = 13841;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.19.Tom&Jerry.CP.PradO.avi' WHERE id = 13842;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.20.Tom&Jerry.CP.PradO.avi' WHERE id = 13843;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.21.Tom&Jerry.CP.PradO.avi' WHERE id = 13844;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.22.Tom&Jerry.CP.PradO.avi' WHERE id = 13845;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.23.Tom&Jerry.CP.PradO.avi' WHERE id = 13846;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.24.Tom&Jerry.CP.PradO.avi' WHERE id = 13847;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.25.Tom&Jerry.CP.PradO.avi' WHERE id = 13848;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.26.Tom&Jerry.CP.PradO.avi' WHERE id = 13849;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.27.Tom&Jerry.CP.PradO.avi' WHERE id = 13850;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.28.Tom&Jerry.CP.PradO.avi' WHERE id = 13851;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.29.Tom&Jerry.CP.PradO.avi' WHERE id = 13852;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.30.Tom&Jerry.CP.PradO.avi' WHERE id = 13853;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.31.Tom&Jerry.CP.PradO.avi' WHERE id = 13854;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.32.Tom&Jerry.CP.PradO.avi' WHERE id = 13855;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.33.Tom&Jerry.CP.PradO.avi' WHERE id = 13856;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.34.Tom&Jerry.CP.PradO.avi' WHERE id = 13857;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.35.Tom&Jerry.CP.PradO.avi' WHERE id = 13858;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.36.Tom&Jerry.CP.PradO.avi' WHERE id = 13859;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.37.Tom&Jerry.CP.PradO.avi' WHERE id = 13860;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.38.Tom&Jerry.CP.PradO.avi' WHERE id = 13861;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.39.Tom&Jerry.CP.PradO.avi' WHERE id = 13862;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.40.Tom&Jerry.CP.PradO.avi' WHERE id = 13863;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.41.Tom&Jerry.CP.PradO.avi' WHERE id = 13864;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.42.Tom&Jerry.CP.PradO.avi' WHERE id = 13865;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.43.Tom&Jerry.CP.PradO.avi' WHERE id = 13866;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.44.Tom&Jerry.CP.PradO.avi' WHERE id = 13867;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.45.Tom&Jerry.CP.PradO.avi' WHERE id = 13868;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.46.Tom&Jerry.CP.PradO.avi' WHERE id = 13869;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.47.Tom&Jerry.CP.PradO.avi' WHERE id = 13870;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.48.Tom&Jerry.CP.PradO.avi' WHERE id = 13871;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.49.Tom&Jerry.CP.PradO.avi' WHERE id = 13872;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.50.Tom&Jerry.CP.PradO.avi' WHERE id = 13873;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.51.Tom&Jerry.CP.PradO.avi' WHERE id = 13874;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.52.Tom&Jerry.CP.PradO.avi' WHERE id = 13875;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.53.Tom&Jerry.CP.PradO.avi' WHERE id = 13876;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.54.Tom&Jerry.CP.PradO.avi' WHERE id = 13877;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.55.Tom&Jerry.CP.PradO.avi' WHERE id = 13878;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.56.Tom&Jerry.CP.PradO.avi' WHERE id = 13879;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.57.Tom&Jerry.CP.PradO.avi' WHERE id = 13880;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.58.Tom&Jerry.CP.PradO.avi' WHERE id = 13881;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.59.Tom&Jerry.CP.PradO.avi' WHERE id = 13882;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.60.Tom&Jerry.CP.PradO.avi' WHERE id = 13883;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.61.Tom&Jerry.CP.PradO.avi' WHERE id = 13884;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.62.Tom&Jerry.CP.PradO.avi' WHERE id = 13885;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.63.Tom&Jerry.CP.PradO.avi' WHERE id = 13886;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.64.Tom&Jerry.CP.PradO.avi' WHERE id = 13887;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.65.Tom&Jerry.CP.PradO.avi' WHERE id = 13888;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.66.Tom&Jerry.CP.PradO.avi' WHERE id = 13889;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.67.Tom&Jerry.CP.PradO.avi' WHERE id = 13890;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.68.Tom&Jerry.CP.PradO.avi' WHERE id = 13891;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.69.Tom&Jerry.CP.PradO.avi' WHERE id = 13892;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.70.Tom&Jerry.CP.PradO.avi' WHERE id = 13893;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.71.Tom&Jerry.CP.PradO.avi' WHERE id = 13894;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.72.Tom&Jerry.CP.PradO.avi' WHERE id = 13895;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.73.Tom&Jerry.CP.PradO.avi' WHERE id = 13896;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.74.Tom&Jerry.CP.PradO.avi' WHERE id = 13897;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.75.Tom&Jerry.CP.PradO.avi' WHERE id = 13898;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.76.Tom&Jerry.CP.PradO.avi' WHERE id = 13899;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.77.Tom&Jerry.CP.PradO.avi' WHERE id = 13900;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.78.Tom&Jerry.CP.PradO.avi' WHERE id = 13901;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.79.Tom&Jerry.CP.PradO.avi' WHERE id = 13902;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.80.Tom&Jerry.CP.PradO.avi' WHERE id = 13903;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.81.Tom&Jerry.CP.PradO.avi' WHERE id = 13904;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.82.Tom&Jerry.CP.PradO.avi' WHERE id = 13905;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.83.Tom&Jerry.CP.PradO.avi' WHERE id = 13906;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.84.Tom&Jerry.CP.PradO.avi' WHERE id = 13907;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.85.Tom&Jerry.CP.PradO.avi' WHERE id = 13908;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.86.Tom&Jerry.CP.PradO.avi' WHERE id = 13909;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.87.Tom&Jerry.CP.PradO.avi' WHERE id = 13910;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.88.Tom&Jerry.CP.PradO.avi' WHERE id = 13911;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.89.Tom&Jerry.CP.PradO.avi' WHERE id = 13912;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.90.Tom&Jerry.CP.PradO.avi' WHERE id = 13913;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.91.Tom&Jerry.CP.PradO.avi' WHERE id = 13914;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.92.Tom&Jerry.CP.PradO.avi' WHERE id = 13915;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.93.Tom&Jerry.CP.PradO.avi' WHERE id = 13916;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.94.Tom&Jerry.CP.PradO.avi' WHERE id = 13917;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.95.Tom&Jerry.CP.PradO.avi' WHERE id = 13918;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.96.Tom&Jerry.CP.PradO.avi' WHERE id = 13919;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.97.Tom&Jerry.CP.PradO.avi' WHERE id = 13920;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.98.Tom&Jerry.CP.PradO.avi' WHERE id = 13921;
UPDATE episodio SET capa_url = 'F:\\\\Tom e Jerry - Incompleto\\\\Ep.99.Tom&Jerry.CP.PradO.avi' WHERE id = 13922;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\01_O Homem Que Vale 60 Bilh?es_imagem.jpg' WHERE id = 13923;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\02_As Apar?ncias Enganam_imagem.jpg' WHERE id = 13924;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\03_Apaziguador_imagem.jpg' WHERE id = 13925;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\04_Paz e Amor_imagem.jpg' WHERE id = 13926;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\05_Golpe Duro_imagem.jpg' WHERE id = 13927;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\06_July Perdida_imagem.jpg' WHERE id = 13928;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\07_B.D.N_imagem.jpg' WHERE id = 13929;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\08_E Entre o Deserto e o C?us_imagem.jpg' WHERE id = 13930;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\09_Maquina de Matar_imagem.jpg' WHERE id = 13931;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\10_Saque R?pido_imagem.jpg' WHERE id = 13932;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\11_Fugindo da Dor_imagem.jpg' WHERE id = 13933;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\12_Devil_imagem.jpg' WHERE id = 13934;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\13_Vash The Stampede_imagem.jpg' WHERE id = 13935;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\14_Pequena Arc?dia_imagem.jpg' WHERE id = 13936;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\15_Olho do Dem?nio_imagem.jpg' WHERE id = 13937;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\16_Quinta Lua_imagem.jpg' WHERE id = 13938;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\17_REM Salvarem_imagem.jpg' WHERE id = 13939;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\18_Adeus Por Enquanto_imagem.jpg' WHERE id = 13940;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\19_N?o Atire_imagem.jpg' WHERE id = 13941;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\20_Nave Flutuante_imagem.jpg' WHERE id = 13942;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\21_Fora de Tempo_imagem.jpg' WHERE id = 13943;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\22_Alternativa_imagem.jpg' WHERE id = 13944;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\23_Para?so_imagem.jpg' WHERE id = 13945;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\24_Pecado_imagem.jpg' WHERE id = 13946;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\25_Resistindo_imagem.jpg' WHERE id = 13947;
UPDATE episodio SET capa_url = 'F:\\\\Trigun\\\\26_Embaixo do C?u T?o Azul_imagem.jpg' WHERE id = 13948;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 01 [480p DSNP WEB-DL AVC AAC][MultiSub][2969EBD1].mkv' WHERE id = 13949;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 02 [480p DSNP WEB-DL AVC AAC][MultiSub][75604858].mkv' WHERE id = 13950;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 03 [480p DSNP WEB-DL AVC AAC][MultiSub][D6503AC6].mkv' WHERE id = 13951;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 04 [480p DSNP WEB-DL AVC AAC][MultiSub][DB204B15].mkv' WHERE id = 13952;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 05 [480p DSNP WEB-DL AVC AAC][MultiSub][450C2C82].mkv' WHERE id = 13953;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 06 [480p DSNP WEB-DL AVC AAC][MultiSub][E1DB3ABB].mkv' WHERE id = 13954;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 07 [480p DSNP WEB-DL AVC AAC][MultiSub][C79D5241].mkv' WHERE id = 13955;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 08 [480p DSNP WEB-DL AVC AAC][MultiSub][316EDA10].mkv' WHERE id = 13956;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 09 [480p DSNP WEB-DL AVC AAC][MultiSub][5879E334].mkv' WHERE id = 13957;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 10 [480p DSNP WEB-DL AVC AAC][MultiSub][823C0FB5].mkv' WHERE id = 13958;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 11 [480p DSNP WEB-DL AVC AAC][MultiSub][D6F956F3].mkv' WHERE id = 13959;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 12 [480p DSNP WEB-DL AVC AAC][MultiSub][14D99422].mkv' WHERE id = 13960;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 13 [480p DSNP WEB-DL AVC AAC][MultiSub][AF6CA466].mkv' WHERE id = 13961;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 14 [480p DSNP WEB-DL AVC AAC][MultiSub][DE19004C].mkv' WHERE id = 13962;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 15 [480p DSNP WEB-DL AVC AAC][MultiSub][32C0991F].mkv' WHERE id = 13963;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 16 [480p DSNP WEB-DL AVC AAC][MultiSub][7321D533].mkv' WHERE id = 13964;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 17 [480p DSNP WEB-DL AVC AAC][MultiSub][AE10BB33].mkv' WHERE id = 13965;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 18 [480p DSNP WEB-DL AVC AAC][MultiSub][1BB12CB7].mkv' WHERE id = 13966;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 19 [480p DSNP WEB-DL AVC AAC][MultiSub][C56991CE].mkv' WHERE id = 13967;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 20 [480p DSNP WEB-DL AVC AAC][MultiSub][18CBBC43].mkv' WHERE id = 13968;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 21 [480p DSNP WEB-DL AVC AAC][MultiSub][3D812022].mkv' WHERE id = 13969;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 22 [480p DSNP WEB-DL AVC AAC][MultiSub][ADBAC0AB].mkv' WHERE id = 13970;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 23 [480p DSNP WEB-DL AVC AAC][MultiSub][8CF1B789].mkv' WHERE id = 13971;
UPDATE episodio SET capa_url = 'F:\\\\Undead Unluck - Legendado\\\\[Erai-raws] Undead Unluck - 24 [480p DSNP WEB-DL AVC AAC][MultiSub][F19CC46B].mkv' WHERE id = 13972;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\01_Epis?dio 1_imagem.jpg' WHERE id = 13973;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\02_Epis?dio 2_imagem.jpg' WHERE id = 13974;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\03_Epis?dio 3_imagem.jpg' WHERE id = 13975;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\04_Epis?dio 4_imagem.jpg' WHERE id = 13976;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\05_Epis?dio 5_imagem.jpg' WHERE id = 13977;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\06_Epis?dio 6_imagem.jpg' WHERE id = 13978;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\07_Epis?dio 7_imagem.jpg' WHERE id = 13979;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\08_Epis?dio 8_imagem.jpg' WHERE id = 13980;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\09_Epis?dio 9_imagem.jpg' WHERE id = 13981;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\10_Epis?dio 10_imagem.jpg' WHERE id = 13982;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\11_Epis?dio 11_imagem.jpg' WHERE id = 13983;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\12_Epis?dio 12_imagem.jpg' WHERE id = 13984;
UPDATE episodio SET capa_url = 'F:\\\\Violet Evergarden - Legendado\\\\13_Epis?dio 13_imagem.jpg' WHERE id = 13985;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\01_A Morte_imagem.jpg' WHERE id = 13986;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\02_No Mundo Espiritual - Teste da Ressurrei??o_imagem.jpg' WHERE id = 13987;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\03_A Promessa de um Homem_imagem.jpg' WHERE id = 13988;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\04_O Fogo Ardente_imagem.jpg' WHERE id = 13989;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\05_A Ressurrei??o - A Nova Miss?o_imagem.jpg' WHERE id = 13990;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\06_Os Misteriosos Ladr?es Hiei, Kurama e Gouki_imagem.jpg' WHERE id = 13991;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\07_O Segredo de Kurama_imagem.jpg' WHERE id = 13992;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\08_O Rapto de Keiko_imagem.jpg' WHERE id = 13993;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\09_O Sucessor_imagem.jpg' WHERE id = 13994;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\10_A Batalha na Escurid?o_imagem.jpg' WHERE id = 13995;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\11_A Dura Batalha_imagem.jpg' WHERE id = 13996;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\12_A Derrota de Kuwabara_imagem.jpg' WHERE id = 13997;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\13_Lando VS Yusuke_imagem.jpg' WHERE id = 13998;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\14_Desafio do Mundo do Al?m_imagem.jpg' WHERE id = 13999;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\15_A Dan?a da Rosa_imagem.jpg' WHERE id = 14000;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\16_A Luta do Mach?o Kuwabara_imagem.jpg' WHERE id = 14001;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\17_Byakku no Inferno_imagem.jpg' WHERE id = 14002;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\18_A F?ria de Hiei_imagem.jpg' WHERE id = 14003;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\19_O ?ltimo Monstro, Suzaku_imagem.jpg' WHERE id = 14004;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\20_O Incr?vel Suzaku_imagem.jpg' WHERE id = 14005;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\21_Yusuke, a Dura Batalha_imagem.jpg' WHERE id = 14006;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\22_Yukina, a Triste Garota_imagem.jpg' WHERE id = 14007;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\23_Os Mensageiros das Trevas_imagem.jpg' WHERE id = 14008;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\24_Tr?s Monstros - Terr?veis Inimigos_imagem.jpg' WHERE id = 14009;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 1\\\\25_Kuwabara Age por Amor_imagem.jpg' WHERE id = 14010;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\01_Convite ao Torneio dos Monstros_imagem.jpg' WHERE id = 14011;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\02_Partida para a Ilha das Trevas_imagem.jpg' WHERE id = 14012;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\03_O Pequeno e Terr?vel Inimigo Linko_imagem.jpg' WHERE id = 14013;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\04_Kurama e o seu Golpe da Flor_imagem.jpg' WHERE id = 14014;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\05_As Chamas Mortais_imagem.jpg' WHERE id = 14015;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\06_Os Golpes do B?bado Tiyu_imagem.jpg' WHERE id = 14016;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\07_A Luta Decisiva_imagem.jpg' WHERE id = 14017;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\08_Colis?o - Os Oito Melhores Times_imagem.jpg' WHERE id = 14018;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\09_A Complicada Guerra_imagem.jpg' WHERE id = 14019;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\10_A Bela Guerreira Mascarada_imagem.jpg' WHERE id = 14020;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\11_A Purifica??o_imagem.jpg' WHERE id = 14021;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\12_Os Ninjas das Trevas_imagem.jpg' WHERE id = 14022;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\13_A Persist?ncia de Kurama_imagem.jpg' WHERE id = 14023;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\14_A Explos?o de Yusuke_imagem.jpg' WHERE id = 14024;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\15_Jin, o Homem-vento_imagem.jpg' WHERE id = 14025;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\16_A Derrota Inesperada_imagem.jpg' WHERE id = 14026;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\17_A Determina??o de Kuwabara_imagem.jpg' WHERE id = 14027;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\18_A Fisionomia Severa da Mascarada_imagem.jpg' WHERE id = 14028;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\19_A Suprema Doutrina_imagem.jpg' WHERE id = 14029;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\20_Hiei e as Chamas Negras Mortais_imagem.jpg' WHERE id = 14030;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\21_A Transforma??o de Kuromomotaru_imagem.jpg' WHERE id = 14031;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\22_O Ladr?o Lend?rio Kurama Youko_imagem.jpg' WHERE id = 14032;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\23_A Manta da Morte_imagem.jpg' WHERE id = 14033;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\24_As ?ltimas For?as de Genkai_imagem.jpg' WHERE id = 14034;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\25_O Desafio de Suzuki_imagem.jpg' WHERE id = 14035;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\26_A Sombra de Toguro_imagem.jpg' WHERE id = 14036;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\27_A Partida de Genkai_imagem.jpg' WHERE id = 14037;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\28_A Tempestade Vem - Supere a Tristeza_imagem.jpg' WHERE id = 14038;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\29_In?cio da Tumultuada Batalha_imagem.jpg' WHERE id = 14039;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\30_A Ressurrei??o de Kurama Youko_imagem.jpg' WHERE id = 14040;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\31_A ?ltima Cartada de Kurama_imagem.jpg' WHERE id = 14041;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\32_A Amea?a de Bu?_imagem.jpg' WHERE id = 14042;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\33_O Golpe Mortal - As Chamas Negras_imagem.jpg' WHERE id = 14043;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\34_A Estranha Sombra de Toguro_imagem.jpg' WHERE id = 14044;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\35_O ?dio Explode - O Ataque de Kuwabara_imagem.jpg' WHERE id = 14045;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\36_O Confronto de Dois Grandes Lutadores_imagem.jpg' WHERE id = 14046;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\37_O Poder Total de Toguro_imagem.jpg' WHERE id = 14047;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\38_Yusuke e a Doutrina Suprema_imagem.jpg' WHERE id = 14048;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\39_A ?ltima Batalha_imagem.jpg' WHERE id = 14049;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\40_A Explos?o do Est?dio_imagem.jpg' WHERE id = 14050;
UPDATE episodio SET capa_url = 'F:\\\\Yu Yu Hakusho\\\\Parte 2\\\\41_A Recompensa de Toguro_imagem.jpg' WHERE id = 14051;
