UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-582_imagem.jpg' WHERE id = 11816;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-583_imagem.jpg' WHERE id = 11817;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-584_imagem.jpg' WHERE id = 11818;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-585_imagem.jpg' WHERE id = 11819;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-586_imagem.jpg' WHERE id = 11820;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-587_imagem.jpg' WHERE id = 11821;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-588_imagem.jpg' WHERE id = 11822;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-589_imagem.jpg' WHERE id = 11823;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-59_imagem.jpg' WHERE id = 11824;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-590_imagem.jpg' WHERE id = 11825;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-591_imagem.jpg' WHERE id = 11826;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-592_imagem.jpg' WHERE id = 11827;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-593_imagem.jpg' WHERE id = 11828;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-594_imagem.jpg' WHERE id = 11829;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-595_imagem.jpg' WHERE id = 11830;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-596_imagem.jpg' WHERE id = 11831;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-597_imagem.jpg' WHERE id = 11832;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-598_imagem.jpg' WHERE id = 11833;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-599_imagem.jpg' WHERE id = 11834;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-6_imagem.jpg' WHERE id = 11835;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-60_imagem.jpg' WHERE id = 11836;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-600_imagem.jpg' WHERE id = 11837;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-601_imagem.jpg' WHERE id = 11838;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-602_imagem.jpg' WHERE id = 11839;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-604_imagem.jpg' WHERE id = 11840;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-605_imagem.jpg' WHERE id = 11841;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-606_imagem.jpg' WHERE id = 11842;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-607_imagem.jpg' WHERE id = 11843;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-608_imagem.jpg' WHERE id = 11844;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-609_imagem.jpg' WHERE id = 11845;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-61_imagem.jpg' WHERE id = 11846;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-610_imagem.jpg' WHERE id = 11847;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-611_imagem.jpg' WHERE id = 11848;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-612_imagem.jpg' WHERE id = 11849;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-613_imagem.jpg' WHERE id = 11850;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-614_imagem.jpg' WHERE id = 11851;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-615_imagem.jpg' WHERE id = 11852;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-616_imagem.jpg' WHERE id = 11853;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-617_imagem.jpg' WHERE id = 11854;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-618_imagem.jpg' WHERE id = 11855;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-619_imagem.jpg' WHERE id = 11856;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-62_imagem.jpg' WHERE id = 11857;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-620_imagem.jpg' WHERE id = 11858;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-621_imagem.jpg' WHERE id = 11859;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-622_imagem.jpg' WHERE id = 11860;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-623_imagem.jpg' WHERE id = 11861;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-624_imagem.jpg' WHERE id = 11862;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-625_imagem.jpg' WHERE id = 11863;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-626_imagem.jpg' WHERE id = 11864;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-627_imagem.jpg' WHERE id = 11865;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-628_imagem.jpg' WHERE id = 11866;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-63_imagem.jpg' WHERE id = 11867;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-64_imagem.jpg' WHERE id = 11868;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-65_imagem.jpg' WHERE id = 11869;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-66_imagem.jpg' WHERE id = 11870;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-67_imagem.jpg' WHERE id = 11871;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-68_imagem.jpg' WHERE id = 11872;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-69_imagem.jpg' WHERE id = 11873;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-7_imagem.jpg' WHERE id = 11874;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-70_imagem.jpg' WHERE id = 11875;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-71_imagem.jpg' WHERE id = 11876;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-72_imagem.jpg' WHERE id = 11877;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-73_imagem.jpg' WHERE id = 11878;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-74_imagem.jpg' WHERE id = 11879;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-75_imagem.jpg' WHERE id = 11880;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-76_imagem.jpg' WHERE id = 11881;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-77_imagem.jpg' WHERE id = 11882;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-78_imagem.jpg' WHERE id = 11883;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-79_imagem.jpg' WHERE id = 11884;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-8_imagem.jpg' WHERE id = 11885;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-80_imagem.jpg' WHERE id = 11886;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-81_imagem.jpg' WHERE id = 11887;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-82_imagem.jpg' WHERE id = 11888;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-83_imagem.jpg' WHERE id = 11889;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-84_imagem.jpg' WHERE id = 11890;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-85_imagem.jpg' WHERE id = 11891;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-86_imagem.jpg' WHERE id = 11892;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-87_imagem.jpg' WHERE id = 11893;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-88_imagem.jpg' WHERE id = 11894;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-89_imagem.jpg' WHERE id = 11895;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-9_imagem.jpg' WHERE id = 11896;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-90_imagem.jpg' WHERE id = 11897;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-91_imagem.jpg' WHERE id = 11898;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-92_imagem.jpg' WHERE id = 11899;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-93_imagem.jpg' WHERE id = 11900;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-94_imagem.jpg' WHERE id = 11901;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-95_imagem.jpg' WHERE id = 11902;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-96_imagem.jpg' WHERE id = 11903;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-97_imagem.jpg' WHERE id = 11904;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-98_imagem.jpg' WHERE id = 11905;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-99_imagem.jpg' WHERE id = 11906;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\1? Temporada\\\\10_Perigo Sem Igual_imagem.jpg' WHERE id = 11907;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\1? Temporada\\\\11_Dominador do Universo_imagem.jpg' WHERE id = 11908;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\1? Temporada\\\\12_Her?i Mais Forte_imagem.jpg' WHERE id = 11909;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\2? Temporada\\\\10_Rede Cercante da Justi?a_imagem.jpg' WHERE id = 11919;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\2? Temporada\\\\11_Dignidade de Cada Um_imagem.jpg' WHERE id = 11920;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\2? Temporada\\\\12_Arrumando a Bagun?a do Disc?pulo_imagem.jpg' WHERE id = 11921;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E01 - Strategy Meeting (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [E0978733].mkv' WHERE id = 11931;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E02 - Monster Traits (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [65E23E5F].mkv' WHERE id = 11932;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E03 - Organism Limits (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [431E3788].mkv' WHERE id = 11933;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E04 - Counterattack Signal (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [DB0FBE48].mkv' WHERE id = 11934;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E05 - Monster King (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [535955EE].mkv' WHERE id = 11935;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E06 - Motley Heroes (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [D2BFF5CB].mkv' WHERE id = 11936;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E07 - Counterstrike (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [6B8C6B15].mkv' WHERE id = 11937;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E08 - Ninja Tale (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [C7F2467B].mkv' WHERE id = 11938;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E09 - Brave Child (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [5D146843].mkv' WHERE id = 11939;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E10 - Immortal Bloodbath (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [2E90D1D1].mkv' WHERE id = 11940;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E11 - Top Dragons (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [2061BEF7].mkv' WHERE id = 11941;
UPDATE episodio SET capa_url = 'F:\\\\One Punch Man\\\\3? Temporada - Legendado\\\\[Kosaka] One-Punch Man - S03E12 - Ultimate Lifeform (WEBRip 1080p AV1 OPUS) [MultiSubs] [Dual-Audio] [FE370FA4].mkv' WHERE id = 11942;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\01_Fim e Come?o_imagem.jpg' WHERE id = 12114;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\02_Guardi?es dos Andares_imagem.jpg' WHERE id = 12115;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\03_Batalha na Vila Carne_imagem.jpg' WHERE id = 12116;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\04_O Governante da Morte_imagem.jpg' WHERE id = 12117;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\05_Dois Aventureiros_imagem.jpg' WHERE id = 12118;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\06_Jornada_imagem.jpg' WHERE id = 12119;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\07_O Rei S?bio da Floresta_imagem.jpg' WHERE id = 12120;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\08_Espadas G?meas do Corte Mortal_imagem.jpg' WHERE id = 12121;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\09_O Guerreiro das Trevas_imagem.jpg' WHERE id = 12122;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\10_Verdadeiro Vampiro_imagem.jpg' WHERE id = 12123;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\11_Confus?o e Compreens?o_imagem.jpg' WHERE id = 12124;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\12_A Valqu?ria Sanguin?ria_imagem.jpg' WHERE id = 12125;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\1? Temporada\\\\13_Jogador VS NPC_imagem.jpg' WHERE id = 12126;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\01_O Come?o do Desespero_imagem.jpg' WHERE id = 12127;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\02_Partida_imagem.jpg' WHERE id = 12128;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\03_Lizard Men, Unidos!_imagem.jpg' WHERE id = 12129;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\04_Ex?rcito da Morte_imagem.jpg' WHERE id = 12130;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\05_O Deus Congelante_imagem.jpg' WHERE id = 12131;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\06_Aqueles que Auxiliam, Aqueles que s?o Auxiliados_imagem.jpg' WHERE id = 12132;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\07_Rosas Azuis_imagem.jpg' WHERE id = 12133;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\08_Os Sentimentos de Um Garoto_imagem.jpg' WHERE id = 12134;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\09_Fa?scas Ascendentes de Fogo_imagem.jpg' WHERE id = 12135;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\10_O Alvoro?o Come?a na Capital Real_imagem.jpg' WHERE id = 12136;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\11_Jaldabaoth_imagem.jpg' WHERE id = 12137;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\12_A Batalha Final dos Dist?rbios_imagem.jpg' WHERE id = 12138;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\2? Temporada\\\\13_O Triunfo Final_imagem.jpg' WHERE id = 12139;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\01_A Melancolia de Um L?der_imagem.jpg' WHERE id = 12140;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\02_Vila Carne Mais Uma Vez_imagem.jpg' WHERE id = 12141;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\03_Crise de Enri e Dias Agitados_imagem.jpg' WHERE id = 12142;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\04_Gigante do Oriente, Cobra Demon?aca do Oeste_imagem.jpg' WHERE id = 12143;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\05_Dois Lideres_imagem.jpg' WHERE id = 12144;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\06_Convite para a Morte_imagem.jpg' WHERE id = 12145;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\07_Borboleta Enredada em uma Teia de Aranha_imagem.jpg' WHERE id = 12146;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\08_Um Punhado de Esperan?a_imagem.jpg' WHERE id = 12147;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\09_Guerra dos Mundos_imagem.jpg' WHERE id = 12148;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\10_Prepara??o Para a Guerra_imagem.jpg' WHERE id = 12149;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\11_Outra Batalha_imagem.jpg' WHERE id = 12150;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\12_Massacre_imagem.jpg' WHERE id = 12151;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\3? Temporada\\\\13_PVP - Jogador vs Jogador_imagem.jpg' WHERE id = 12152;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\01_Na??o feiticeira de Ainz Ooal Gown_imagem.jpg' WHERE id = 12153;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\02_Reino Re-Estize_imagem.jpg' WHERE id = 12154;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\03_Imp?rio Baharuth_imagem.jpg' WHERE id = 12155;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\04_A R?gua da Conspira??o_imagem.jpg' WHERE id = 12156;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\05_Em busca da Terra dos An?es_imagem.jpg' WHERE id = 12157;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\06_A Crise Iminente_imagem.jpg' WHERE id = 12158;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\07_Senhor dos Drag?es de Gelo_imagem.jpg' WHERE id = 12159;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\08_Um Movimento Inesperado_imagem.jpg' WHERE id = 12160;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\09_Contagem Decrescente para a Extin??o_imagem.jpg' WHERE id = 12161;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\10_O ?ltimo Rei_imagem.jpg' WHERE id = 12162;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\11_Armadilhas bem Preparadas_imagem.jpg' WHERE id = 12163;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\12_Invas?o da Capital Real_imagem.jpg' WHERE id = 12164;
UPDATE episodio SET capa_url = 'F:\\\\Overlord\\\\4? Temporada\\\\13_A Bruxa do Reino Ca?do_imagem.jpg' WHERE id = 12165;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1949.09.16 - Fast and Furry-ous (Jones) LT.avi' WHERE id = 12179;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1952.05.24 - Beep, Beep (Jones) MM.avi' WHERE id = 12180;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1952.08.23 - Going! Going! Gosh! (Jones) MM.avi' WHERE id = 12181;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1953.09.19 - Zipping Along (Jones) MM.avi' WHERE id = 12182;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1954.08.14 - Stop! Look! And Hasten! (Jones) MM.avi' WHERE id = 12183;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1955.05.30 - Ready, Set, Zoom! (Jones) LT.avi' WHERE id = 12184;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1955.12.10 - Guided Muscle (Jones) LT.avi' WHERE id = 12185;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1956.05.05 - Gee Whiz-z-z-z (Jones) LT.avi' WHERE id = 12186;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1956.11.10 - There They Go-Go-Go! (Jones) LT.avi' WHERE id = 12187;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1957.01.26 - Scrambled Aches (Jones) LT.avi' WHERE id = 12188;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1957.09.14 - Zoom and Bored (Jones) MM.avi' WHERE id = 12189;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1958.04.12 - Whoa, Be-Gone! (Jones) MM.avi' WHERE id = 12190;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1958.10.11 - Hook, Line and Stinker (Jones) LT.avi' WHERE id = 12191;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1958.12.06 - Hip Hip-Hurry! (Jones) MM.avi' WHERE id = 12192;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1959.05.09 - Hot-Rod and Reel! (Jones) LT.avi' WHERE id = 12193;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1959.10.10 - Wild About Hurry (Jones) MM.avi' WHERE id = 12194;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1960.01.19 - Fastest With The Mostest (Jones) LT.avi' WHERE id = 12195;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1960.10.08 - Hopalong Casualty (Jones) LT.avi' WHERE id = 12196;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1961.01.21 - Zip 'N' Snort (Jones) MM.avi' WHERE id = 12197;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1961.06.03 - Lickety-Splat (Jones and Levitow) LT.avi' WHERE id = 12198;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1961.11.11 - Beep Prepared (Jones and Noble) MM.avi' WHERE id = 12199;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1962.06.02 - Adventures of the Road Runner (Jones).avi' WHERE id = 12200;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1962.06.30 - Zoom at the Top (Jones and Noble) MM.avi' WHERE id = 12201;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1963.12.31 - To Beep or Not to Beep (Jones and Noble) MM.avi' WHERE id = 12202;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1964.06.06 - War and Pieces (Jones and Noble) LT.avi' WHERE id = 12203;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.01.01 - Zip Zip Hooray (Jones) LT.avi' WHERE id = 12204;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.01.02 - Roadrunner a Go-Go (Jones) MM.avi' WHERE id = 12205;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.02.27 - The Wild Chase (Freleng and Pratt) MM.avi' WHERE id = 12206;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.07.31 - Rushing Roulette (McKimson) MM.avi' WHERE id = 12207;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.08.21 - Run, Run, Sweet Road Runner (Larriva) MM.avi' WHERE id = 12208;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.09.18 - Tired and Feathered (Larriva) LT.avi' WHERE id = 12209;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.10.09 - Boulder Wham! (Larriva) MM.avi' WHERE id = 12210;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.10.30 - Just Plane Beep (Larriva) MM.avi' WHERE id = 12211;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.11.13 - Hairied and Hurried (Larriva) MM.avi' WHERE id = 12212;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.12.11 - Highway Runnery (Larriva) LT.avi' WHERE id = 12213;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1965.12.25 - Chaser on the Rocks (Larriva) MM.avi' WHERE id = 12214;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1966.01.08 - Shot and Bothered (Larriva) LT.avi' WHERE id = 12215;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1966.01.29 - Out and Out Rout (Larriva) MM.avi' WHERE id = 12216;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1966.02.19 - The Solid Tin Coyote (Larriva) LT.avi' WHERE id = 12217;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1966.03.12 - Clippety Clobbered (Larriva) LT.avi' WHERE id = 12218;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1966.11.05 - Sugar and Spies (McKimson) LT.avi' WHERE id = 12219;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1967 - The Road Runner Show - Look Before You Beep (McKimson).avi' WHERE id = 12220;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1979.11.27 - Freeze Frame (Jones) MM.avi' WHERE id = 12221;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1980.05.21 - Soup or Sonic (Jones and Monroe) MM.avi' WHERE id = 12222;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\1994.12.21 - Chariots of Fur (Jones) LT.avi' WHERE id = 12223;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\2000.12.30 - Little Go Beep (Brandt) LT.avi' WHERE id = 12224;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\2003.11.01 - Whizzard of Ow (Haaland) LT.avi' WHERE id = 12225;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Sam Sheepdog & Ralph Wolf\\\\1953.01.03 - Don't Give Up the Sheep (Jones) LT.avi' WHERE id = 12166;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Sam Sheepdog & Ralph Wolf\\\\1954.12.11 - Sheep Ahoy (Jones) MM.avi' WHERE id = 12167;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Sam Sheepdog & Ralph Wolf\\\\1955.07.23 - Double Or Mutton (Jones) LT.avi' WHERE id = 12168;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Sam Sheepdog & Ralph Wolf\\\\1957.06.08 - Steal Wool (Jones) LT.avi' WHERE id = 12169;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Sam Sheepdog & Ralph Wolf\\\\1960.07.30 - Ready, Woolen and Able (Jones) MM.avi' WHERE id = 12170;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Sam Sheepdog & Ralph Wolf\\\\1962.02.10 - A Sheep In The Deep (Jones and Noble) MM.avi' WHERE id = 12171;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Sam Sheepdog & Ralph Wolf\\\\1963.05.11 - Woolen Under Where (Monroe and Thompson) MM.avi' WHERE id = 12172;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Wile E. Coyote Genius & Bugs Bunny\\\\1952.01.19 - Operation Rabbit (Jones) LT.avi' WHERE id = 12173;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Wile E. Coyote Genius & Bugs Bunny\\\\1956.12.15 - To Hare is Human (Jones) MM.avi' WHERE id = 12174;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Wile E. Coyote Genius & Bugs Bunny\\\\1960.06.04 - Rabbit's Feat (Jones) LT.avi' WHERE id = 12175;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Wile E. Coyote Genius & Bugs Bunny\\\\1961.07.29 - Compressed Hare (Jones and Noble) MM.avi' WHERE id = 12176;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Wile E. Coyote Genius & Bugs Bunny\\\\1963.06.08 - Hare-Breadth Hurry (Jones and Noble) LT.avi' WHERE id = 12177;
UPDATE episodio SET capa_url = 'F:\\\\Papa L?guas - Incompleto\\\\Wile E. Coyote Genius & Bugs Bunny\\\\1969.06.07 - Rabbit Stew and Rabbits Too! (McKimson) LT.avi' WHERE id = 12178;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\01_A metamorfose_imagem.jpg' WHERE id = 12226;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\02_O diabo no corpo_imagem.jpg' WHERE id = 12227;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\03_O banquete_imagem.jpg' WHERE id = 12228;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\04_Cabelo embara?ado_imagem.jpg' WHERE id = 12229;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\05_O estrangeiro_imagem.jpg' WHERE id = 12230;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\06_O sol tamb?m se levanta_imagem.jpg' WHERE id = 12231;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\07_Trajet?ria em noite escura_imagem.jpg' WHERE id = 12232;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\08_Ponto de congelamento_imagem.jpg' WHERE id = 12233;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\09_Al?m do bem e do mal_imagem.jpg' WHERE id = 12234;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\10_Loucura do universo_imagem.jpg' WHERE id = 12235;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\11_O p?ssaro azul_imagem.jpg' WHERE id = 12236;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\12_Kokoro_imagem.jpg' WHERE id = 12237;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\13_Bom dia, tristeza_imagem.jpg' WHERE id = 12238;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\14_O gene ego?sta_imagem.jpg' WHERE id = 12239;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\15_Algo sinistro vem por a?_imagem.jpg' WHERE id = 12240;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\16_Uma fam?lia feliz_imagem.jpg' WHERE id = 12241;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\17_O detetive moribundo_imagem.jpg' WHERE id = 12242;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\18_Mais que humanos_imagem.jpg' WHERE id = 12243;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\19_A sangue frio_imagem.jpg' WHERE id = 12244;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\20_Crime e castigo_imagem.jpg' WHERE id = 12245;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\21_Sexo e esp?rito_imagem.jpg' WHERE id = 12246;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\22_Repouso e despertar_imagem.jpg' WHERE id = 12247;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\23_Vida e votos_imagem.jpg' WHERE id = 12248;
UPDATE episodio SET capa_url = 'F:\\\\Parasyte\\\\24_Monstros parasitas_imagem.jpg' WHERE id = 12249;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\000 Pica Pau - Ataca Novamente.avi' WHERE id = 12250;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\001 Pica Pau - Biruta.avi' WHERE id = 12251;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\002 Pica Pau - O Rachador.avi' WHERE id = 12252;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\003 Pica Pau - P?nico na Cozinha.avi' WHERE id = 12253;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\004 Pica Pau - O Matador De Hollywood.avi' WHERE id = 12254;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\005 Pica Pau - Um As Demais.avi' WHERE id = 12255;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\006 Pica Pau - A Loja Do Prego.avi' WHERE id = 12256;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\007 Pica Pau - Baseball Maluco.avi' WHERE id = 12257;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\008 Pica Pau - O Acrobata Maluco.avi' WHERE id = 12258;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\009 Pica Pau - O Afanador De Gasolina.avi' WHERE id = 12259;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\010 Pica Pau - O Barbeiro de Sevilha.avi' WHERE id = 12260;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\011 Pica Pau - O Doido da Praia.avi' WHERE id = 12261;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\012 Pica Pau - Ski Para Dois.avi' WHERE id = 12262;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\013 Pica Pau - Uma Dama Muito Fina.avi' WHERE id = 12263;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\014 Pica Pau - O Pica Pau Come Fora.avi' WHERE id = 12264;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\015 Pica Pau - O Famoso Diplomata.avi' WHERE id = 12265;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\016 Pica Pau - O Biruta A Solta.avi' WHERE id = 12266;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\017 Pica Pau - Quem Cozinha Quem.avi' WHERE id = 12267;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\018 Pica Pau - Hora Do Banho.avi' WHERE id = 12268;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\019 Pica Pau - Carteira de Motorista.avi' WHERE id = 12269;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\020 Pica Pau - Amigos Penosos.avi' WHERE id = 12270;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\021 Pica Pau - Miniaturas Musicais.avi' WHERE id = 12271;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\022 Pica Pau - Presuntos Defumados.avi' WHERE id = 12272;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\023 Pica Pau - O Passarinho do Rel?gio.avi' WHERE id = 12273;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\024 Pica Pau - Roubando Gasolina.avi' WHERE id = 12274;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\025 Pica Pau - O Ovo da Galinha.avi' WHERE id = 12275;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\026 Pica Pau - Mata Gigantes.avi' WHERE id = 12276;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\027 Pica Pau - A Cartola.avi' WHERE id = 12277;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\028 Pica Pau - O Fila B?ia.avi' WHERE id = 12278;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\029 Pica Pau - Hora do Bebe.avi' WHERE id = 12279;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\030 Pica Pau - Ap?lice Cobertor.avi' WHERE id = 12280;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\031 Pica Pau - O Xerife.avi' WHERE id = 12281;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\032 Pica Pau - Del?cia Gelada.avi' WHERE id = 12282;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\033 Pica Pau - O Mensageiro.avi' WHERE id = 12283;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\034 Pica Pau - Durma Bem.avi' WHERE id = 12284;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\035 Pica Pau - Cricket Maluco.avi' WHERE id = 12285;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\036 Pica Pau - Campe?o do Estilingue.avi' WHERE id = 12286;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\037 Pica Pau - Os Trabalhadores Da Floresta.avi' WHERE id = 12287;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\038 Pica Pau - A Polka do Pica Pau.avi' WHERE id = 12288;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\039 Pica Pau - Uma Aventura no Supermercado.avi' WHERE id = 12289;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\040 Pica Pau - Nascido Para Picar.avi' WHERE id = 12290;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\041 Pica Pau - O Grande Logro.avi' WHERE id = 12291;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\042 Pica Pau - Campe?o de Golf.avi' WHERE id = 12292;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\043 Pica Pau - O Cabeleireiro.avi' WHERE id = 12293;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\044 Pica Pau - O Grande Quem Faz Isso.avi' WHERE id = 12294;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\045 Pica Pau - Formigas de Marte.avi' WHERE id = 12295;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\046 Pica Pau - O Varre Varre.avi' WHERE id = 12296;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\047 Pica Pau - O Pirata.avi' WHERE id = 12297;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\048 Pica Pau - Opera??o Cerragem.avi' WHERE id = 12298;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\049 Pica Pau - O Vale Tudo.avi' WHERE id = 12299;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\050 Pica Pau - Os Mensageiros.avi' WHERE id = 12300;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\051 Pica Pau - O Hipnotizador Caipira.avi' WHERE id = 12301;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\052 Pica Pau - Meio Dia Quente.avi' WHERE id = 12302;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\053 Pica Pau - Briga Em Marrocos.avi' WHERE id = 12303;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\054 Pica Pau - A Alameda Para Bali.avi' WHERE id = 12304;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\055 Pica Pau - O Espi?o Espiado.avi' WHERE id = 12305;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\056 Pica Pau - O Vendedor De Carr?es.avi' WHERE id = 12306;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\057 Pica Pau - O Trio Amoroso.avi' WHERE id = 12307;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\058 Pica Pau - Pesadelo Dourado.avi' WHERE id = 12308;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\059 Pica Pau - Concerto Na Marra.avi' WHERE id = 12309;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\060 Pica Pau - Os Desabrigados.avi' WHERE id = 12310;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\061 Pica Pau - A Vassoura da Bruxa.avi' WHERE id = 12311;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\062 Pica Pau - Farejador vs Pica Pau.avi' WHERE id = 12312;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\063 Pica Pau - Pica Pau Ama Seca.avi' WHERE id = 12313;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\064 Pica Pau - Ladr?o Que Rouba Ladr?o.avi' WHERE id = 12314;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\065 Pica Pau - Um Tesouro Dif?cil.avi' WHERE id = 12315;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\066 Pica Pau - M?dico de ?rvore.avi' WHERE id = 12316;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\067 Pica Pau - Depois da Bola.avi' WHERE id = 12317;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\068 Pica Pau - Os Perdidinhos.avi' WHERE id = 12318;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\069 Pica Pau - Chefe Charlie Cavalo.avi' WHERE id = 12319;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\070 Pica Pau - Um Pica Pau de Marte.avi' WHERE id = 12320;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\071 Pica Pau - Festival de Cuckoos.avi' WHERE id = 12321;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\072 Pica Pau - Vamos ?s Cataratas.avi' WHERE id = 12322;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\073 Pica Pau - Artes e Flores.avi' WHERE id = 12323;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\074 Pica Pau - Davy Escovinha enfrenta Pica Pau.avi' WHERE id = 12324;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\075 Pica Pau - Chapeuzinho Diferente.avi' WHERE id = 12325;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\076 Pica Pau - O Bandido do Trem.avi' WHERE id = 12326;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\077 Pica Pau - O Vendedor Insuport?vel.avi' WHERE id = 12327;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\078 Pica Pau - Pica Pau Internacional.avi' WHERE id = 12328;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\079 Pica Pau - Ca?a Ao Pica Pau.avi' WHERE id = 12329;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\080 Pica Pau - Viagem ? Marte.avi' WHERE id = 12330;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\081 Pica Pau - Dopey Dick.avi' WHERE id = 12331;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\082 Pica Pau - Papai Urso.avi' WHERE id = 12332;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\083 Pica Pau - Um Seguro Furado.avi' WHERE id = 12333;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\084 Pica Pau - Ornitolomania.avi' WHERE id = 12334;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\085 Pica Pau - Selins Vazios.avi' WHERE id = 12335;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\086 Pica Pau - Seu Melhor Duende.avi' WHERE id = 12336;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\087 Pica Pau - Investimento N?o T?o Seguro.avi' WHERE id = 12337;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\088 Pica Pau - Era Uma Vez Um Parque.avi' WHERE id = 12338;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\089 Pica Pau - Um Bobo e Tanto.avi' WHERE id = 12339;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\090 Pica Pau - Luta do Gatoso.avi' WHERE id = 12340;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\091 Pica Pau - ? Madeira Pra Burro.avi' WHERE id = 12341;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\092 Pica Pau - Pica Pau Delegado.avi' WHERE id = 12342;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\093 Pica Pau - Pica Pau na Lua.avi' WHERE id = 12343;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\094 Pica Pau - Um Jogador de Sorte.avi' WHERE id = 12344;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\095 Pica Pau - Brincadeira no P?ntano.avi' WHERE id = 12345;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\096 Pica Pau - Alian?a Miri.avi' WHERE id = 12346;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\097 Pica Pau - Surrupiador de Um Bilh?o.avi' WHERE id = 12347;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\098 Pica Pau - Pica Pau Pistoleiro.avi' WHERE id = 12348;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\099 Pica Pau - O Charme Vence.avi' WHERE id = 12349;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\100 Pica Pau - Propaganda Super.avi' WHERE id = 12350;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\101 Pica Pau - Como Rechear Um Pica Pau.avi' WHERE id = 12351;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\102 Pica Pau - Morcegos no Campan?rio.avi' WHERE id = 12352;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\103 Pica Pau - O ?ltimo Martin.avi' WHERE id = 12353;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\104 Pica Pau - Hospitalidade G?rmida.avi' WHERE id = 12354;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\105 Pica Pau - Ca?a ao Fara?.avi' WHERE id = 12355;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\106 Pica Pau - Pirata do Barulho.avi' WHERE id = 12356;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\107 Pica Pau - O P?ssaro Que Veio Pra Jantar.avi' WHERE id = 12357;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\108 Pica Pau - O Jantar de Gaby.avi' WHERE id = 12358;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\109 Pica Pau - O Gato a Jato.avi' WHERE id = 12359;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\110 Pica Pau - N?o Puxe As Minhas Penas.avi' WHERE id = 12360;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\111 Pica Pau - Os Azares do Motorista.avi' WHERE id = 12361;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\112 Pica Pau - O Fantasma da ?pera.avi' WHERE id = 12362;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\113 Pica Pau - O Mestre Cuca.avi' WHERE id = 12363;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\114 Pica Pau - Vamos Nanar Jacar?.avi' WHERE id = 12364;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\115 Pica Pau - O Doce Lar Quase Destru?do.avi' WHERE id = 12365;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\116 Pica Pau - Vivendo Num Buraco.avi' WHERE id = 12366;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\117 Pica Pau - Foguete Fajuto.avi' WHERE id = 12367;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\118 Pica Pau - O Cuidador Descuidado.avi' WHERE id = 12368;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\119 Pica Pau - M?gica Tr?gica.avi' WHERE id = 12369;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\120 Pica Pau - O Rei do Voo-Doo.avi' WHERE id = 12370;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\121 Pica Pau - Os Azares De Um Corvo.avi' WHERE id = 12371;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\122 Pica Pau - Chapeuzinho Vermelho de Araque.avi' WHERE id = 12372;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\123 Pica Pau - O Guloso Z? Jacar?.avi' WHERE id = 12373;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\124 Pica Pau - Pica Pau Robin Hoody.avi' WHERE id = 12374;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\125 Pica Pau - Viagem Ao Hawaii.avi' WHERE id = 12375;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\126 Pica Pau - O Fot?grafo Chato.avi' WHERE id = 12376;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\127 Pica Pau - O Pica Pato.avi' WHERE id = 12377;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\128 Pica Pau - O Inquilino Malandro.avi' WHERE id = 12378;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\129 Pica Pau - O Garimpeiro Garimpado.avi' WHERE id = 12379;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\130 Pica Pau - Chachado Pra Dois.avi' WHERE id = 12380;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\131 Pica Pau - Fric??o Cient?fica.avi' WHERE id = 12381;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\132 Pica Pau - Chamando Dr. Pica Pau.avi' WHERE id = 12382;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\133 Pica Pau - Esperto Contra Sabido.avi' WHERE id = 12383;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\134 Pica Pau - O Calejado da Sala.avi' WHERE id = 12384;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\135 Pica Pau - O Pica Pau na Barbearia.avi' WHERE id = 12385;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\136 Pica Pau - Os Parentes.avi' WHERE id = 12386;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\137 Pica Pau - Que Lindinho O Cachorrinho.avi' WHERE id = 12387;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\138 Pica Pau - Auto Estrada Fracassada.avi' WHERE id = 12388;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\139 Pica Pau - Em Roma Fa?a Como Os Pica Paus.avi' WHERE id = 12389;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\140 Pica Pau - Os Tr?s Pica-Paus.avi' WHERE id = 12390;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\141 Pica Pau - Procura-se Um Pica Pau.avi' WHERE id = 12391;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\142 Pica Pau - A Observadora de P?ssaros.avi' WHERE id = 12392;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\143 Pica Pau - Esse Dia ? Da Ca?a.avi' WHERE id = 12393;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\144 Pica Pau - Jane Calamidade.avi' WHERE id = 12394;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\145 Pica Pau - Um Amigo Leal.avi' WHERE id = 12395;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\146 Pica Pau - O Pica Pau e o Professor.avi' WHERE id = 12396;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\147 Pica Pau - Qual? a Sua, Chap?u.avi' WHERE id = 12397;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\148 Pica Pau - O Solid?rio.avi' WHERE id = 12398;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\149 Pica Pau - Pica Pau e o P? de Feij?o.avi' WHERE id = 12399;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\150 Pica Pau - Hist?ria Boa Pra Cachorro.avi' WHERE id = 12400;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\151 Pica Pau - Encantos e Desencantos.avi' WHERE id = 12401;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\152 Pica Pau - Pica Pau, Um Biruta no Espa?o.avi' WHERE id = 12402;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\153 Pica Pau - Nunca Gema As Claras.avi' WHERE id = 12403;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\154 Pica Pau - Pica Pau Einstein.avi' WHERE id = 12404;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\155 Pica Pau - Xerife Meio Frouxo.avi' WHERE id = 12405;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\156 Pica Pau - O Paladino do Oeste.avi' WHERE id = 12406;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\157 Pica Pau - Biruta N?utico.avi' WHERE id = 12407;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\158 Pica Pau - Esse Cachorro ? Quente.avi' WHERE id = 12408;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\159 - Pica Pau - Problema_Cavalar.avi' WHERE id = 12409;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\160 Pica Pau - Pica Pau, O Agente Secreto.avi' WHERE id = 12410;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\161 Pica Pau - Sorte Grande.avi' WHERE id = 12411;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\162 Pica Pau - Reflorestamento ? For?a.avi' WHERE id = 12412;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\163 Pica Pau - O Rei do Faroeste.avi' WHERE id = 12413;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\164 Pica Pau - Pica Pau Adotivo.avi' WHERE id = 12414;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\165 Pica Pau - Briga Pra Ningu?m Botar Defeito.avi' WHERE id = 12415;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\166 Pica Pau - Alado em Baguid?.avi' WHERE id = 12416;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\167 Pica Pau - Cidade de Um Cavalo S?.avi' WHERE id = 12417;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\168 Pica Pau - Pescaria Agitada.avi' WHERE id = 12418;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\169 Pica Pau - N?o Tem Mosquito.avi' WHERE id = 12419;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\170 Pica Pau - Cumprimentem a Coroa.avi' WHERE id = 12420;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\171 Pica Pau - Trai??o no Deserto.avi' WHERE id = 12421;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\172 Pica Pau - O Marujo Intr?pido.avi' WHERE id = 12422;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\173 Pica Pau - Super Vendedor Pr?-Hist?rico.avi' WHERE id = 12423;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\174 Pica Pau - Upa Upa Pangar?.avi' WHERE id = 12424;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\175 Pica Pau - Foca A Solta.avi' WHERE id = 12425;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\176 Pica Pau - O Pistoleiro Sem Solu??o.avi' WHERE id = 12426;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\177 Pica Pau - Pica Pau Tropical.avi' WHERE id = 12427;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\178 Pica Pau - Constru?a? Demolida.avi' WHERE id = 12428;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\179 Pica Pau - A Grande Aventura de Bonga.avi' WHERE id = 12429;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\180 Pica Pau - Encrencas a Bordo.avi' WHERE id = 12430;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\181 Pica Pau - A Fonte da Juventude.avi' WHERE id = 12431;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\182 Pica Pau - Hora de Dormir.avi' WHERE id = 12432;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\183 Pica Pau - O Recruta Relutante.avi' WHERE id = 12433;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\184 Pica Pau - Como Capturar um Pica Pau.avi' WHERE id = 12434;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\185 Pica Pau - O Toque M?gico Do Pica Pau.avi' WHERE id = 12435;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\186 Pica Pau - O Gato da Cidade.avi' WHERE id = 12436;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\187 Pica Pau - S? Uma Soneca.avi' WHERE id = 12437;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\188 Pica Pau - O Raptado.avi' WHERE id = 12438;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\189 Pica Pau - Hist?ria Pra ?ndio.avi' WHERE id = 12439;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\190 Pica Pau - Nem Tudo que Reluz ? Ouro.avi' WHERE id = 12440;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\191 Pica Pau - Nunca Aposte Num Poste Furado.avi' WHERE id = 12441;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\192 Pica Pau - Chili com Carne.avi' WHERE id = 12442;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\193 Pica Pau - um C?o Falante.avi' WHERE id = 12443;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\194 Pica Pau - Por Um Amor ? Pizza.avi' WHERE id = 12444;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\195 Pica Pau - G?nio Engenhoso.avi' WHERE id = 12445;
UPDATE episodio SET capa_url = 'F:\\\\Pica Pau - Incompleto\\\\196 Pica Pau - Adeus ?s Aulas.avi' WHERE id = 12446;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-1_imagem.jpg' WHERE id = 12447;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-10_imagem.jpg' WHERE id = 12448;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-11_imagem.jpg' WHERE id = 12449;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-12_imagem.jpg' WHERE id = 12450;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-13_imagem.jpg' WHERE id = 12451;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-14_imagem.jpg' WHERE id = 12452;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-15_imagem.jpg' WHERE id = 12453;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-16_imagem.jpg' WHERE id = 12454;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-17_imagem.jpg' WHERE id = 12455;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-18-legendado_imagem.jpg' WHERE id = 12456;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-19_imagem.jpg' WHERE id = 12457;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-2_imagem.jpg' WHERE id = 12458;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-20_imagem.jpg' WHERE id = 12459;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-21_imagem.jpg' WHERE id = 12460;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-22_imagem.jpg' WHERE id = 12461;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-23_imagem.jpg' WHERE id = 12462;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-24_imagem.jpg' WHERE id = 12463;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-25_imagem.jpg' WHERE id = 12464;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-26_imagem.jpg' WHERE id = 12465;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-27_imagem.jpg' WHERE id = 12466;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-28_imagem.jpg' WHERE id = 12467;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-29_imagem.jpg' WHERE id = 12468;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-3_imagem.jpg' WHERE id = 12469;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-30_imagem.jpg' WHERE id = 12470;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-31_imagem.jpg' WHERE id = 12471;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-32_imagem.jpg' WHERE id = 12472;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-33_imagem.jpg' WHERE id = 12473;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-34_imagem.jpg' WHERE id = 12474;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-35-legendado_imagem.jpg' WHERE id = 12475;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-36_imagem.jpg' WHERE id = 12476;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-37_imagem.jpg' WHERE id = 12477;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-38-legendado_imagem.jpg' WHERE id = 12478;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-39_imagem.jpg' WHERE id = 12479;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-4_imagem.jpg' WHERE id = 12480;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-40_imagem.jpg' WHERE id = 12481;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-41_imagem.jpg' WHERE id = 12482;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-42_imagem.jpg' WHERE id = 12483;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-43_imagem.jpg' WHERE id = 12484;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-44_imagem.jpg' WHERE id = 12485;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-45_imagem.jpg' WHERE id = 12486;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-46_imagem.jpg' WHERE id = 12487;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-47_imagem.jpg' WHERE id = 12488;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-48_imagem.jpg' WHERE id = 12489;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-49_imagem.jpg' WHERE id = 12490;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-5_imagem.jpg' WHERE id = 12491;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-50_imagem.jpg' WHERE id = 12492;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-51_imagem.jpg' WHERE id = 12493;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-52_imagem.jpg' WHERE id = 12494;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-53_imagem.jpg' WHERE id = 12495;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-54_imagem.jpg' WHERE id = 12496;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-55_imagem.jpg' WHERE id = 12497;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-56_imagem.jpg' WHERE id = 12498;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-57_imagem.jpg' WHERE id = 12499;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-58_imagem.jpg' WHERE id = 12500;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-59_imagem.jpg' WHERE id = 12501;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-6_imagem.jpg' WHERE id = 12502;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-60_imagem.jpg' WHERE id = 12503;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-61_imagem.jpg' WHERE id = 12504;
