UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\149_A flecha que causa problemas_imagem.jpg' WHERE id = 10144;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\14_O roubo dos ossos sagrados da Kikyou_imagem.jpg' WHERE id = 10145;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\150_A luz que guia ? um santo_imagem.jpg' WHERE id = 10146;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\151_A intui??o de Kagome_imagem.jpg' WHERE id = 10147;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\152_Proteger e roubar_imagem.jpg' WHERE id = 10148;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\153_Uma Reuni?o Cruel_imagem.jpg' WHERE id = 10149;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\154_A youkai que conecta com o outro Mundo_imagem.jpg' WHERE id = 10150;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\155_O youkai que protege o fragmento_imagem.jpg' WHERE id = 10151;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\156_Sesshoumaru enfrenta Inuyasha_imagem.jpg' WHERE id = 10152;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\157_Aniquilando Naraku_imagem.jpg' WHERE id = 10153;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\158_Uma Correria de Ratos youkai_imagem.jpg' WHERE id = 10154;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\159_A Decis?o de Kohaku_imagem.jpg' WHERE id = 10155;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\15_O renascimento da infeliz sacerdotisa Kikyou_imagem.jpg' WHERE id = 10156;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\160_Um Jovem violento que atrai a Felicidade_imagem.jpg' WHERE id = 10157;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\161_O erro no Passado do monge Miroku_imagem.jpg' WHERE id = 10158;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\162_Para sempre junto de Sesshoumaru-sama_imagem.jpg' WHERE id = 10159;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\163_Kohaku, Sango, Kirara e o Jardim Secreto da Flor_imagem.jpg' WHERE id = 10160;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\164_O maior dos inimigo; Pupa parasita de Shippou_imagem.jpg' WHERE id = 10161;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\165_A Grande Pista para Derrotar Naraku_imagem.jpg' WHERE id = 10162;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\166_O compromisso do casal para o uso da J?ia (parte 1)_imagem.jpg' WHERE id = 10163;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\167_O compromisso do casal para o uso da J?ia (parte 2)_imagem.jpg' WHERE id = 10164;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\16_O buraco do vento na m?o direita - Miroku, o monge delinquente_imagem.jpg' WHERE id = 10165;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\17_A tinta corrompida do pintor do Inferno_imagem.jpg' WHERE id = 10166;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\18_A alian?a de Naraku e Sesshoumaru_imagem.jpg' WHERE id = 10167;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\19_Volte para a sua era, Kagome!_imagem.jpg' WHERE id = 10168;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\20_O enigma de Onigumo, o ladr?o diab?lico_imagem.jpg' WHERE id = 10169;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\21_A verdade sobre a origem de Naraku; A alma de Kikyou (Parte 1)_imagem.jpg' WHERE id = 10170;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\22_A verdade sobre a origem de Naraku; A alma de Kikyou (Parte 2)_imagem.jpg' WHERE id = 10171;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\23_A voz de Kagome e o beijo de Kikyou_imagem.jpg' WHERE id = 10172;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\24_Sango, a exterminadora de youkais_imagem.jpg' WHERE id = 10173;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\25_Derrotando o plano de Naraku_imagem.jpg' WHERE id = 10174;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\26_O segredo da J?ia de Quatro Almas ? finalmente revelado_imagem.jpg' WHERE id = 10175;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\27_O Lago da Escurid?o controlado pelo Deus da ?gua_imagem.jpg' WHERE id = 10176;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\28_Miroku cai numa armadilha_imagem.jpg' WHERE id = 10177;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\29_A ang?stia de Sango e a vida de Kohaku_imagem.jpg' WHERE id = 10178;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\30_A Tessaiga roubada e o confronto no castelo de Naraku_imagem.jpg' WHERE id = 10179;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\31_Jinenji, o youkai bondoso e solit?rio_imagem.jpg' WHERE id = 10180;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\32_Kikyou e Inuyasha atra?dos pelo Miasma_imagem.jpg' WHERE id = 10181;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\33_Kikyou ? raptada_imagem.jpg' WHERE id = 10182;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\34_Tesaiga e Tenseiga_imagem.jpg' WHERE id = 10183;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\35_A c?lebre espada escolhe o seu verdadeiro mestre_imagem.jpg' WHERE id = 10184;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\36_O rapto de Kagome; Kouga, o youkai lobo super-veloz_imagem.jpg' WHERE id = 10185;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\37_O youkai que se apaixonou por Kagome_imagem.jpg' WHERE id = 10186;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\38_Separados, os dois se d?o conta dos seus sentimentos_imagem.jpg' WHERE id = 10187;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\39_Um plano ardiloso; A luta de vida ou morte_imagem.jpg' WHERE id = 10188;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\40_A armadilha de Kagura, a mestra dos ventos_imagem.jpg' WHERE id = 10189;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\41_A dan?a de Kagura e o espelho de Kanna_imagem.jpg' WHERE id = 10190;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\42_A Ferida do Vento refletida_imagem.jpg' WHERE id = 10191;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\43_A Tesaiga ? finalmente quebrada_imagem.jpg' WHERE id = 10192;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\44_A espada mal?gna de Kaijinbou_imagem.jpg' WHERE id = 10193;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\45_Sesshoumaru saca Toukijin_imagem.jpg' WHERE id = 10194;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\46_Juuroumaru e Kageroumaru_imagem.jpg' WHERE id = 10195;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\47_O cora??o de Onigumo ainda vive em Naraku_imagem.jpg' WHERE id = 10196;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\48_Quero voltar ao lugar onde nos conhecemos._imagem.jpg' WHERE id = 10197;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\49_A mem?ria perdida de Kohaku_imagem.jpg' WHERE id = 10198;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\50_O rosto que n?o sai do meu cora??o_imagem.jpg' WHERE id = 10199;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\51_O cora??o consumido de Inuyasha_imagem.jpg' WHERE id = 10200;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\52_A verdadeira natureza do youkai n?o pode ser reprimida_imagem.jpg' WHERE id = 10201;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\53_O inimigo mortal do meu pai - Ryoukossei_imagem.jpg' WHERE id = 10202;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\54_Onda Explosiva - o ataque supremo da Tessaiga_imagem.jpg' WHERE id = 10203;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\55_A flor de pedra e o primeiro amor de Shippou_imagem.jpg' WHERE id = 10204;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\56_A armadilha da bela princesa na n?voa_imagem.jpg' WHERE id = 10205;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\57_Tudo o que aconteceu na noite em Tougenkyou (Parte 1)_imagem.jpg' WHERE id = 10206;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\58_Tudo o que aconteceu na noite em Tougenkyou (Parte 2)_imagem.jpg' WHERE id = 10207;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\59_As belas irm?s aprendizes_imagem.jpg' WHERE id = 10208;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\60_A sacerdotisa das sombras; Uma maldi??o de 50 anos_imagem.jpg' WHERE id = 10209;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\61_Kikyou aparece!; O uso do Shikigami_imagem.jpg' WHERE id = 10210;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\62_A maldi??o cruel de Tsubaki_imagem.jpg' WHERE id = 10211;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\63_A sacerdotisa azul e a sacerdotisa vermelha que bloqueiam o caminho_imagem.jpg' WHERE id = 10212;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\64_Tahou, o youkai gigante da torre!_imagem.jpg' WHERE id = 10213;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\65_Adeus aos dias de juventude_imagem.jpg' WHERE id = 10214;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\66_A barreira de Naraku; A decis?o de Kagura_imagem.jpg' WHERE id = 10215;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\67_O devastador vento da trai??o_imagem.jpg' WHERE id = 10216;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\68_O grande desafio de Shippou_imagem.jpg' WHERE id = 10217;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\69_O terr?vel homem sem rosto_imagem.jpg' WHERE id = 10218;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\70_A mem?ria recuperada de Onigumo_imagem.jpg' WHERE id = 10219;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\71_A batalha dos tr?s at? ? morte_imagem.jpg' WHERE id = 10220;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\72_O estranho treino de Toutousai_imagem.jpg' WHERE id = 10221;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\73_A m?e e os sentimentos de Shiori_imagem.jpg' WHERE id = 10222;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\74_A Tessaiga vermelha que quebra a barreira_imagem.jpg' WHERE id = 10223;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\75_A conspira??o dos quatro youkais gatos de fogo_imagem.jpg' WHERE id = 10224;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\76_Os alvos s?o - Sesshoumaru e Inuyasha_imagem.jpg' WHERE id = 10225;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\77_Os gatos de fogo e a espada de dois caninos_imagem.jpg' WHERE id = 10226;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\78_Sango, s? voc?_imagem.jpg' WHERE id = 10227;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\79_O plano de Jaken para roubar a Tessaiga_imagem.jpg' WHERE id = 10228;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\80_Sesshoumaru e o rapto de Rin_imagem.jpg' WHERE id = 10229;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\81_Naraku despeda?ado; E seu paradeiro_imagem.jpg' WHERE id = 10230;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\82_A liga??o entre o Presente e a ?poca das Guerras_imagem.jpg' WHERE id = 10231;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\83_A youkai loba e a grande promessa_imagem.jpg' WHERE id = 10232;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\84_O proposta de casamento super veloz_imagem.jpg' WHERE id = 10233;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\85_O aumento da energia maligna; A cabe?a do youkai_imagem.jpg' WHERE id = 10234;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\86_O segredo da princesa_imagem.jpg' WHERE id = 10235;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\87_A viagem solit?ria de Kikyou_imagem.jpg' WHERE id = 10236;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\88_Os tr?s youkais do Deus Macaco_imagem.jpg' WHERE id = 10237;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\89_O confronto entre Inuyasha e Houjo_imagem.jpg' WHERE id = 10238;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\90_A corajosa declara??o de Souta_imagem.jpg' WHERE id = 10239;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\91_O espiritualista misterioso e a Kirara negra_imagem.jpg' WHERE id = 10240;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\92_A ambi??o dos ressuscitados_imagem.jpg' WHERE id = 10241;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\93_O enigma do monge devasso_imagem.jpg' WHERE id = 10242;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\94_Os criadores da J?ia de Quatro Almas (Parte 1)_imagem.jpg' WHERE id = 10243;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\95_Os criadores da J?ia de Quatro Almas (Parte 2)_imagem.jpg' WHERE id = 10244;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\96_Jaken fica doente_imagem.jpg' WHERE id = 10245;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\97_Kirara n?o volta_imagem.jpg' WHERE id = 10246;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\98_Kikyou e Kagome sozinhas numa caverna_imagem.jpg' WHERE id = 10247;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\99_Kouga e Sesshoumaru! Um perigoso confronto!_imagem.jpg' WHERE id = 10248;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\1? Temporada\\\\S1 E01 O Homem da Selva-A Ilha das Amazonas.avi' WHERE id = 10249;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\1? Temporada\\\\S1 E02 Super Bobalhao-Confusoes na Floresta-Falta de Tempo.avi' WHERE id = 10250;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\1? Temporada\\\\S1 E03 O Homem Sensivel-Bravo Dooby Doo.avi' WHERE id = 10251;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\1? Temporada\\\\S1 E04 Encontro com um Antilope-Voce Viu um Touro por aqui-Crise de Biscoitos.avi' WHERE id = 10252;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\1? Temporada\\\\S1 E05 Eu Costumava ser Engra?ado-Meu Querido Certinho-Era a Noite.avi' WHERE id = 10253;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\1? Temporada\\\\S1 E06 Amigos Bajuladores-Sobre a Corcova-Johnny Bravo Encontra Farrah Fawcett.avi' WHERE id = 10254;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\1? Temporada\\\\S1 E07 Trapa?a com a Manta-Fala Comigo Baby-Fracasso no Hip Hop.avi' WHERE id = 10255;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\1? Temporada\\\\S1 E08C A Pilha de Brinquedos Bagun?ados.avi' WHERE id = 10256;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\1? Temporada\\\\S1 E09C Tratamento Intenssivo.avi' WHERE id = 10257;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\1? Temporada\\\\S1 E8B Controle da Mente_imagem.jpg' WHERE id = 10258;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E14C Um Gel Para Johnny.avi' WHERE id = 10259;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E15 Johnny Pega seu Tutu-O Inferno de Johnny-Tronco da Floresta.avi' WHERE id = 10260;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E16B Estrela esta Machucada.avi' WHERE id = 10261;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E19B Teletom do Johnny.avi' WHERE id = 10262;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E19C O Anjo da Guarda de Johnny.avi' WHERE id = 10263;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E20A Eu Mosca.avi' WHERE id = 10264;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E22A Panico na Cidade da Carne Seca.avi' WHERE id = 10265;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E22B Alien Confidencial.avi' WHERE id = 10266;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E24A Sua Propria Liga.avi' WHERE id = 10267;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E24B Johnny vai Acampar.avi' WHERE id = 10268;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E25A Confusao na Lagoa.avi' WHERE id = 10269;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E26A O Bravo Magnifico.avi' WHERE id = 10270;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E26B Johnny e Julieta.avi' WHERE id = 10271;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E26C Cl? do Urso da Caverna.avi' WHERE id = 10272;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E28A Viva o Idiota.avi' WHERE id = 10273;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E28B Um Tolo para a Irma Sarah.avi' WHERE id = 10274;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E28C Dias de Nervos.avi' WHERE id = 10275;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E33A Yukon Tolo.avi' WHERE id = 10276;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E33B Johnny no Colegio.avi' WHERE id = 10277;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E34A Johnny Lockness_imagem.jpg' WHERE id = 10278;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E34B Johnny Mamaezinha.avi' WHERE id = 10279;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E34B Pouco Idiota_imagem.jpg' WHERE id = 10280;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E35A Enquanto Fico Solu?ando_imagem.jpg' WHERE id = 10281;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E35B Marinho Marrom_imagem.jpg' WHERE id = 10282;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\2? Temporada\\\\S2 E35C Johnny Deus Trov?o_imagem.jpg' WHERE id = 10283;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E32C O Garoto sem Pistas_imagem.jpg' WHERE id = 10284;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E36A Guia do Amor de Luke Perry.avi' WHERE id = 10285;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E36B Na Linha de Johnny_imagem.jpg' WHERE id = 10286;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E36C Johnny Fugitivo_imagem.jpg' WHERE id = 10287;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E37A Johnny Virtual.avi' WHERE id = 10288;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E37B Segurem Aquele Paspalho_imagem.jpg' WHERE id = 10289;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E37C Johnny Ca?ado_imagem.jpg' WHERE id = 10290;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E38A Candidato Johnny_imagem.jpg' WHERE id = 10291;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E38B Johnny Seja Mau_imagem.jpg' WHERE id = 10292;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E38C Air Bravo_imagem.jpg' WHERE id = 10293;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E39A Furo do Bravo.flv' WHERE id = 10294;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E39B O Incrivel Johnny que Encolheu_imagem.jpg' WHERE id = 10295;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E39C Contra Vento.flv' WHERE id = 10296;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E40A O Caso de Johnny Bravo.flv' WHERE id = 10297;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E40B Biosfera Johnny.flv' WHERE id = 10298;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E40C Energia Pura_imagem.jpg' WHERE id = 10299;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E41A Tolo por um Dia.avi' WHERE id = 10300;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E41B So Sonhando.avi' WHERE id = 10301;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E41C Algum Suposto Estupido_imagem.jpg' WHERE id = 10302;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E42A Piada Dental_imagem.jpg' WHERE id = 10303;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E42B Johnny Vermelhinho_imagem.jpg' WHERE id = 10304;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E42C A Noite da Salsicha.avi' WHERE id = 10305;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E43A Idiota Jurassico_imagem.jpg' WHERE id = 10306;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E43B Mascote da Academia.avi' WHERE id = 10307;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E44C 20000 Leguas Acima da Cabe?a_imagem.jpg' WHERE id = 10308;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E45A Um Sonho com Johnny_imagem.jpg' WHERE id = 10309;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E45B Um Bravo Irado_imagem.jpg' WHERE id = 10310;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E45C Feira dos Malucos_imagem.jpg' WHERE id = 10311;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E46 Uma Caminhada no Lago Estupido-Bravo Estrela Solitaria-Enfrentando um Esquilo.avi' WHERE id = 10312;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E47B Johnny Boneco.avi' WHERE id = 10313;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E48A Johnny Tem um Irm?o-Johnny Prisioneiro-Johnny Madereiro_imagem.jpg' WHERE id = 10314;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E49A Senhor de Links.avi' WHERE id = 10315;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E50B Trem Desgovernado.avi' WHERE id = 10316;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E50C Um Dejeto Corre Por Ele.avi' WHERE id = 10317;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\3? Temporada\\\\S3 E52 O Projeto da Bruxa de Joao e Maria- Johnny Q.I.-Pegue o Fedorento.avi' WHERE id = 10318;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\4? Temporada\\\\S4 E53 O Grande Livro do Coelinho-Enfrentando o Esquilo-Frankie Bravo_imagem.jpg' WHERE id = 10319;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\4? Temporada\\\\S4 E54A Problemas de Transito.avi' WHERE id = 10320;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\4? Temporada\\\\S4 E55 Ganhar o Toro Guapo-Johnny Bravo Vira Mulher_imagem.jpg' WHERE id = 10321;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\4? Temporada\\\\S4 E56 Sozinho em Casa_imagem.jpg' WHERE id = 10322;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\4? Temporada\\\\S4 E57 Mini Johnny-Devolta do Futuro_imagem.jpg' WHERE id = 10323;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\4? Temporada\\\\S4 E58 Isso e que e Diversao-Nao e Sim Para o Johnny_imagem.jpg' WHERE id = 10324;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\4? Temporada\\\\S4 E59A Bousa da Pesada_imagem.jpg' WHERE id = 10325;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\4? Temporada\\\\S4 E61A E Uma Vida Magica.avi' WHERE id = 10326;
UPDATE episodio SET capa_url = 'F:\\\\Johnny Bravo - Incompleto\\\\4? Temporada\\\\S4 E62A Antes e Depois_imagem.jpg' WHERE id = 10327;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 1\\\\01_Dio, o invasor_imagem.jpg' WHERE id = 10328;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 1\\\\02_Uma carta do passado_imagem.jpg' WHERE id = 10329;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 1\\\\03_Juventude com Dio_imagem.jpg' WHERE id = 10330;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 1\\\\04_Sobrecarga_imagem.jpg' WHERE id = 10331;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 1\\\\05_Os cavaleiros das trevas_imagem.jpg' WHERE id = 10332;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 1\\\\06_A coragem de amanh?_imagem.jpg' WHERE id = 10333;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 1\\\\07_Infeliz herdeiro_imagem.jpg' WHERE id = 10334;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 1\\\\08_Batalha sangrenta! JoJo e Dio_imagem.jpg' WHERE id = 10335;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 1\\\\09_A ?ltima onda_imagem.jpg' WHERE id = 10336;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\01_JoJo de Nova York_imagem.jpg' WHERE id = 10337;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\02_O mestre do jogo_imagem.jpg' WHERE id = 10338;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\03_O homem do pilar_imagem.jpg' WHERE id = 10339;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\04_JoJo contra o ser supremo_imagem.jpg' WHERE id = 10340;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\05_Guerreiros supremos da antiguidade_imagem.jpg' WHERE id = 10341;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\06_Requisitos de her?i_imagem.jpg' WHERE id = 10342;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\07_Lisa Lisa, treinadora de Hamon_imagem.jpg' WHERE id = 10343;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\08_O plano escondido_imagem.jpg' WHERE id = 10344;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\09_A vingan?a de Von Stroheim_imagem.jpg' WHERE id = 10345;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\10_Corrida ao penhasco_imagem.jpg' WHERE id = 10346;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\11_Jovem Caesar_imagem.jpg' WHERE id = 10347;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\12_Cem contra dois_imagem.jpg' WHERE id = 10348;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\13_Um guerreiro de verdade_imagem.jpg' WHERE id = 10349;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\14_O guerreiro do vento_imagem.jpg' WHERE id = 10350;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\15_Os la?os de JoJo_imagem.jpg' WHERE id = 10351;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\16_O nascimento do ser supremo_imagem.jpg' WHERE id = 10352;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\1? Temporada\\\\Parte 2\\\\17_O ascendente_imagem.jpg' WHERE id = 10353;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\01_O homem possu?do por um esp?rito maligno_imagem.jpg' WHERE id = 10354;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\02_Quem ser? o juiz_imagem.jpg' WHERE id = 10355;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\03_A maldi??o do Dio_imagem.jpg' WHERE id = 10356;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\04_Torre de cinzas_imagem.jpg' WHERE id = 10357;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\05_Silver Chariot_imagem.jpg' WHERE id = 10358;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\06_Lua azul-escura_imagem.jpg' WHERE id = 10359;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\07_For?a_imagem.jpg' WHERE id = 10360;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\08_O diabo_imagem.jpg' WHERE id = 10361;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\09_Yellow Temperance_imagem.jpg' WHERE id = 10362;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\10_O Imperador e o Enforcado ? Parte 1_imagem.jpg' WHERE id = 10363;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\11_O Imperador e o Enforcado ? Parte 2_imagem.jpg' WHERE id = 10364;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\12_A imperatriz_imagem.jpg' WHERE id = 10365;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\13_Roda da fortuna_imagem.jpg' WHERE id = 10366;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\14_Justi?a ? Parte 1_imagem.jpg' WHERE id = 10367;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\15_Justi?a ? Parte 2_imagem.jpg' WHERE id = 10368;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\16_Os amantes ? Parte 1_imagem.jpg' WHERE id = 10369;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\17_Os amantes ? Parte 2_imagem.jpg' WHERE id = 10370;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\18_O Sol_imagem.jpg' WHERE id = 10371;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\19_Morte 13 ? Parte 1_imagem.jpg' WHERE id = 10372;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\20_Morte 13 ? Parte 2_imagem.jpg' WHERE id = 10373;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\21_O julgamento ? Parte 1_imagem.jpg' WHERE id = 10374;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\22_O julgamento ? Parte 2_imagem.jpg' WHERE id = 10375;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\23_A Sacerdotisa - Parte 1_imagem.jpg' WHERE id = 10376;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 1\\\\24_A Sacerdotisa - Parte 2_imagem.jpg' WHERE id = 10377;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\01_Iggy, o louco, e N'Doul, o deus Geb ? Parte 1_imagem.jpg' WHERE id = 10378;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\02_Iggy, o louco, e N'Doul, o deus Geb ? Parte 2_imagem.jpg' WHERE id = 10379;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\03_O Khnum do Ongo e o Thoth do Bongo_imagem.jpg' WHERE id = 10380;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\04_An?bis ? Parte 1_imagem.jpg' WHERE id = 10381;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\05_An?bis ? Parte 2_imagem.jpg' WHERE id = 10382;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\06_Bastet de Mariah ? Parte 1_imagem.jpg' WHERE id = 10383;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\07_Bastet de Mariah ? Parte 2_imagem.jpg' WHERE id = 10384;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\08_Set do Alessi ? Parte 1_imagem.jpg' WHERE id = 10385;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\09_Set do Alessi ? Parte 2_imagem.jpg' WHERE id = 10386;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\10_D'Arby, o apostador ? Parte 1_imagem.jpg' WHERE id = 10387;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\11_D'Arby, o apostador ? Parte 2_imagem.jpg' WHERE id = 10388;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\12_Hol Horse e Bongo ? Parte 1_imagem.jpg' WHERE id = 10389;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\13_Hol Horse e Bongo ? Parte 2_imagem.jpg' WHERE id = 10390;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\14_O guardi?o do inferno Pet Shop ? Parte 1_imagem.jpg' WHERE id = 10391;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\15_O guardi?o do inferno Pet Shop ? Parte 2_imagem.jpg' WHERE id = 10392;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\16_D'Arby, o jogador ? Parte 1_imagem.jpg' WHERE id = 10393;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\17_D'Arby, o jogador ? Parte 2_imagem.jpg' WHERE id = 10394;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\18_O miasma do vazio, Cool Ice ? Parte 1_imagem.jpg' WHERE id = 10395;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\19_O miasma do vazio, Cool Ice ? Parte 2_imagem.jpg' WHERE id = 10396;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\20_O miasma do vazio, Cool Ice ? Parte 3_imagem.jpg' WHERE id = 10397;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\21_O mundo do Dio ? Parte 1_imagem.jpg' WHERE id = 10398;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\22_O mundo do Dio ? Parte 2_imagem.jpg' WHERE id = 10399;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\23_O mundo do Dio ? Parte 3_imagem.jpg' WHERE id = 10400;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\2? Temporada\\\\Parte 2\\\\24_O adeus da longa jornada, amigos_imagem.jpg' WHERE id = 10401;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\01_Jotaro Kujo! Conhece Josuke Higashikata_imagem.jpg' WHERE id = 10402;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\02_Josuke Higashikata! Conhece Angelo_imagem.jpg' WHERE id = 10403;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\03_Os irm?os Nijimura ? Parte 1_imagem.jpg' WHERE id = 10404;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\04_Os irm?os Nijimura ? Parte 2_imagem.jpg' WHERE id = 10405;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\05_Os irm?os Nijimura ? Parte 3_imagem.jpg' WHERE id = 10406;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\06_Koichi Hirose (Reverb)_imagem.jpg' WHERE id = 10407;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\07_Toshikazu Hazamada (Surface)_imagem.jpg' WHERE id = 10408;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\08_Yukako Yamagishi se apaixona ? Parte 1_imagem.jpg' WHERE id = 10409;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\09_Yukako Yamagishi se apaixona ? Parte 2_imagem.jpg' WHERE id = 10410;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\10_Vamos comer comida italiana_imagem.jpg' WHERE id = 10411;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\11_Chili Pepper ? Parte 1_imagem.jpg' WHERE id = 10412;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\12_Chili Pepper ? Parte 2_imagem.jpg' WHERE id = 10413;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\13_Encontramos algo perigoso!_imagem.jpg' WHERE id = 10414;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\14_Vamos para a casa do desenhista ? Parte 1_imagem.jpg' WHERE id = 10415;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\15_Vamos para a casa do desenhista ? Parte 2_imagem.jpg' WHERE id = 10416;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\16_Vamos ca?ar!_imagem.jpg' WHERE id = 10417;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\17_A aventura de Rohan Kishibe_imagem.jpg' WHERE id = 10418;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\18_O Harvest de Shigechi ? Parte 1_imagem.jpg' WHERE id = 10419;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\19_O Harvest de Shigechi ? Parte 2_imagem.jpg' WHERE id = 10420;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\20_Yukako Yamagishi sonha em ser Cinderella_imagem.jpg' WHERE id = 10421;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\21_Yoshikage Kira quer uma vida tranquila ? Parte 1_imagem.jpg' WHERE id = 10422;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\22_Yoshikage Kira quer uma vida tranquila ? Parte 2_imagem.jpg' WHERE id = 10423;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\23_Heart Attack ? Parte 1_imagem.jpg' WHERE id = 10424;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\24_Heart Attack ? Parte 2_imagem.jpg' WHERE id = 10425;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\25_Heart Father_imagem.jpg' WHERE id = 10426;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\26_O pivete do Janken vem a?!_imagem.jpg' WHERE id = 10427;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\27_Eu sou um alien?gena_imagem.jpg' WHERE id = 10428;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\28_Highway Go Go ? Parte 1_imagem.jpg' WHERE id = 10429;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\29_Highway Go Go ? Parte 2_imagem.jpg' WHERE id = 10430;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\30_Gatos amam Yoshikage Kira_imagem.jpg' WHERE id = 10431;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\31_15 de julho (quinta) ? Parte 1_imagem.jpg' WHERE id = 10432;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\32_15 de julho (quinta) ? Parte 2_imagem.jpg' WHERE id = 10433;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\33_15 de julho (quinta) ? Parte 3_imagem.jpg' WHERE id = 10434;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\34_15 de julho (quinta) ? Parte 4_imagem.jpg' WHERE id = 10435;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\35_Bites the Dust ? Parte 1_imagem.jpg' WHERE id = 10436;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\36_Bites the Dust ? Parte 2_imagem.jpg' WHERE id = 10437;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\37_Shining D (Diamond) ? inquebr?vel ? Parte 1_imagem.jpg' WHERE id = 10438;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\38_Shining D (Diamond) ? inquebr?vel ? Parte 2_imagem.jpg' WHERE id = 10439;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\3? Temporada\\\\39_Adeus, Morioh ? O cora??o de ouro_imagem.jpg' WHERE id = 10440;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\01_Golden Wind_imagem.jpg' WHERE id = 10441;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\02_Bucciarati vem a?_imagem.jpg' WHERE id = 10442;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\03_Conhe?a o g?ngster atr?s do muro_imagem.jpg' WHERE id = 10443;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\04_Inicia??o na gangue_imagem.jpg' WHERE id = 10444;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\05_Em busca da fortuna de Polpo!_imagem.jpg' WHERE id = 10445;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\06_O contra-ataque do Moody Jazz_imagem.jpg' WHERE id = 10446;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\07_As seis balas aparecem ? Parte 1_imagem.jpg' WHERE id = 10447;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\08_As seis balas aparecem ? Parte 2_imagem.jpg' WHERE id = 10448;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\09_A primeira miss?o do chefe_imagem.jpg' WHERE id = 10449;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\10_Time de assassinos_imagem.jpg' WHERE id = 10450;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\11_O Li'l Bomber de Narancia_imagem.jpg' WHERE id = 10451;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\12_A segunda miss?o do chefe_imagem.jpg' WHERE id = 10452;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\13_Homem-Espelho e Purple Smoke_imagem.jpg' WHERE id = 10453;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\14_Trem expresso para Floren?a_imagem.jpg' WHERE id = 10454;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\15_Thankful Death ? Parte 1_imagem.jpg' WHERE id = 10455;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\16_Thankful Death ? Parte 2_imagem.jpg' WHERE id = 10456;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\17_Babyhead_imagem.jpg' WHERE id = 10457;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\18_Para Veneza!_imagem.jpg' WHERE id = 10458;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\19_White Ice_imagem.jpg' WHERE id = 10459;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\20_A ?ltima miss?o do chefe_imagem.jpg' WHERE id = 10460;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\21_O mist?rio do Emperor Crimson_imagem.jpg' WHERE id = 10461;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\22_A coragem_imagem.jpg' WHERE id = 10462;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\23_Crush e Talking Mouth_imagem.jpg' WHERE id = 10463;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\24_Notorious Chase_imagem.jpg' WHERE id = 10464;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\25_Spicy Lady_imagem.jpg' WHERE id = 10465;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\26_Uma historinha do passado ? Meu Nome ? Doppio_imagem.jpg' WHERE id = 10466;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\27_Emperor Crimson contra Metallic_imagem.jpg' WHERE id = 10467;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\28_Sob um c?u que pode desabar a qualquer momento_imagem.jpg' WHERE id = 10468;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\29_Para o Coliseu de Roma!_imagem.jpg' WHERE id = 10469;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\30_Green Tea e Sanctuary ? Parte 1_imagem.jpg' WHERE id = 10470;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\31_Green Tea e Sanctuary ? Parte 2_imagem.jpg' WHERE id = 10471;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\32_Green Tea e Sanctuary ? Parte 3_imagem.jpg' WHERE id = 10472;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\33_O nome dele ? Diavolo_imagem.jpg' WHERE id = 10473;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\34_O r?quiem silencioso ? Parte 1_imagem.jpg' WHERE id = 10474;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\35_O r?quiem silencioso ? Parte 2_imagem.jpg' WHERE id = 10475;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\36_As faces de Diavolo_imagem.jpg' WHERE id = 10476;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\37_O rei supremo_imagem.jpg' WHERE id = 10477;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\38_Golden Wind Requiem_imagem.jpg' WHERE id = 10478;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\4? Temporada\\\\39_O escravo adormecido_imagem.jpg' WHERE id = 10479;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\01_Oceano de pedra_imagem.jpg' WHERE id = 10480;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\02_Prisioneira FE40536 - Jolyne Cujoh_imagem.jpg' WHERE id = 10481;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\03_Visitante (1)_imagem.jpg' WHERE id = 10482;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\04_Visitante (2)_imagem.jpg' WHERE id = 10483;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\05_Prisioneira do amor_imagem.jpg' WHERE id = 10484;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\06_Adesivos da Ermes_imagem.jpg' WHERE id = 10485;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\07_Somos seis!_imagem.jpg' WHERE id = 10486;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\08_F.F._imagem.jpg' WHERE id = 10487;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\09_Cobrador de d?vidas Mary Lynn Manson_imagem.jpg' WHERE id = 10488;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\10_Opera??o Savage Guardian ? siga para o p?tio! (1)_imagem.jpg' WHERE id = 10489;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\11_Opera??o Savage Guardian ? siga para o p?tio! (2)_imagem.jpg' WHERE id = 10490;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 1\\\\12_Aviso de chuva torrencial_imagem.jpg' WHERE id = 10491;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\01_Beijo de amor e vingan?a ? Parte 1_imagem.jpg' WHERE id = 10492;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\02_Beijo de amor e vingan?a ? Parte 2_imagem.jpg' WHERE id = 10493;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\03_Ala ultrassegura_imagem.jpg' WHERE id = 10494;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\04_O segredo do guarda Westwood_imagem.jpg' WHERE id = 10495;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\05_Apresentando Drake's Dream_imagem.jpg' WHERE id = 10496;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\06_Apresentando os F.F._imagem.jpg' WHERE id = 10497;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\07_Nascimento do Verde_imagem.jpg' WHERE id = 10498;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\08_F.F. ? A testemunha_imagem.jpg' WHERE id = 10499;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\09_Despertar_imagem.jpg' WHERE id = 10500;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\10_Hora do c?u! Lua nova! Padre novo!_imagem.jpg' WHERE id = 10501;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\11_Jailhouse Lock!_imagem.jpg' WHERE id = 10502;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 2\\\\12_Fuga..._imagem.jpg' WHERE id = 10503;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\01_Bohemian Ecstatic (1)_imagem.jpg' WHERE id = 10504;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\02_Bohemian Ecstatic (2)_imagem.jpg' WHERE id = 10505;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\03_Sky Guy_imagem.jpg' WHERE id = 10506;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\04_O c?u est? pr?ximo - tr?s dias at? a lua nova_imagem.jpg' WHERE id = 10507;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\05_Netherworld_imagem.jpg' WHERE id = 10508;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\06_Heavy Forecast(1)_imagem.jpg' WHERE id = 10509;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\07_Heavy Forecast(2)_imagem.jpg' WHERE id = 10510;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\08_Heavy Forecast(3)_imagem.jpg' WHERE id = 10511;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\09_Gravidade da lua nova_imagem.jpg' WHERE id = 10512;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\10_See Moon(1)_imagem.jpg' WHERE id = 10513;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\11_See Moon(2)_imagem.jpg' WHERE id = 10514;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\12_Maiden Heaven(1)_imagem.jpg' WHERE id = 10515;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\13_Maiden Heaven(2)_imagem.jpg' WHERE id = 10516;
UPDATE episodio SET capa_url = 'F:\\\\JoJo's Bizarre Adventure\\\\5? Temporada\\\\Parte 3\\\\14_Que mundo maravilhoso!_imagem.jpg' WHERE id = 10517;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\01_Ryomen Sukuna_imagem.jpg' WHERE id = 10518;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\02_Por Mim Mesmo_imagem.jpg' WHERE id = 10519;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\03_Garota de A?o_imagem.jpg' WHERE id = 10520;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\04_Morte ao Feto Amaldi?oado_imagem.jpg' WHERE id = 10521;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\05_Morte ao Feto Amaldi?oado - 2_imagem.jpg' WHERE id = 10522;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\06_Depois da Chuva_imagem.jpg' WHERE id = 10523;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\07_Ataque_imagem.jpg' WHERE id = 10524;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\08_T?dio_imagem.jpg' WHERE id = 10525;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\09_Peixes Pequenos e Puni??es Reversas_imagem.jpg' WHERE id = 10526;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\10_Transfigura??o Inerte_imagem.jpg' WHERE id = 10527;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\11_Mente Fechada_imagem.jpg' WHERE id = 10528;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\12_Para Voc?, em Algum Dia_imagem.jpg' WHERE id = 10529;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\13_Amanh?_imagem.jpg' WHERE id = 10530;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\14_Interc?mbio com a Escola Irm? de Kyoto - Batalha de Grupos 0_imagem.jpg' WHERE id = 10531;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\15_Interc?mbio com a Escola Irm? de Kyoto - Batalha de Grupos 1_imagem.jpg' WHERE id = 10532;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\16_Interc?mbio com a Escola Irm? de Kyoto - Batalha de Grupos 2_imagem.jpg' WHERE id = 10533;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\17_Interc?mbio com a Escola Irm? de Kyoto - Batalha de Grupos 3_imagem.jpg' WHERE id = 10534;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\18_S?bio_imagem.jpg' WHERE id = 10535;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\19_Fulgor Negro_imagem.jpg' WHERE id = 10536;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\20_Fora do Padr?o_imagem.jpg' WHERE id = 10537;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\21_Jujutsu Koshien_imagem.jpg' WHERE id = 10538;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\22_A Origem da Obedi?ncia Cega_imagem.jpg' WHERE id = 10539;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\23_A Origem da Obedi?ncia Cega - 2_imagem.jpg' WHERE id = 10540;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\1? Temporada\\\\24_C?mplices_imagem.jpg' WHERE id = 10541;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\01_Invent?rio Oculto_imagem.jpg' WHERE id = 10542;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\02_Invent?rio Oculto 2_imagem.jpg' WHERE id = 10543;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\03_Invent?rio Oculto 3_imagem.jpg' WHERE id = 10544;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\04_Invent?rio Oculto 4_imagem.jpg' WHERE id = 10545;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\05_Morte Prematura_imagem.jpg' WHERE id = 10546;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\06_E ? Assim_imagem.jpg' WHERE id = 10547;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\07_Festival ao Fim de Tarde_imagem.jpg' WHERE id = 10548;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\08_Incidente em Shibuya_imagem.jpg' WHERE id = 10549;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\09_Incidente em Shibuya - Port?o Aberto_imagem.jpg' WHERE id = 10550;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\10_Pandem?nio_imagem.jpg' WHERE id = 10551;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\11_Sess?o Espiritual_imagem.jpg' WHERE id = 10552;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\12_Faca Cega_imagem.jpg' WHERE id = 10553;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\13_Escama Vermelha_imagem.jpg' WHERE id = 10554;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\14_Flutua??es_imagem.jpg' WHERE id = 10555;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\15_Flutua??es, Parte 2_imagem.jpg' WHERE id = 10556;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\16_Trov?o_imagem.jpg' WHERE id = 10557;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\17_Trov?o, Parte 2_imagem.jpg' WHERE id = 10558;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\18_Certo e Errado_imagem.jpg' WHERE id = 10559;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\19_Certo e Errado, Parte 2_imagem.jpg' WHERE id = 10560;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\20_Certo e Errado, Parte 3_imagem.jpg' WHERE id = 10561;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\21_Metamorfose_imagem.jpg' WHERE id = 10562;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\22_Metamorfose, Parte 2_imagem.jpg' WHERE id = 10563;
UPDATE episodio SET capa_url = 'F:\\\\Jujutsu Kaisen\\\\2? Temporada\\\\23_Incidente em Shibuya - Port?es Fechados_imagem.jpg' WHERE id = 10564;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\1? Temporada\\\\01_Esta deusa autoproclamada e uma reencarna??o em outro mundo!_imagem.jpg' WHERE id = 10565;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\1? Temporada\\\\02_Uma explos?o para este ch?niby?!_imagem.jpg' WHERE id = 10566;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\1? Temporada\\\\03_Um tesouro de lingerie para esta m?o direita!_imagem.jpg' WHERE id = 10567;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\1? Temporada\\\\04_Magia explosiva para este inimigo formid?vel!_imagem.jpg' WHERE id = 10568;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\1? Temporada\\\\05_Um pr?mio por esta espada amaldi?oada!_imagem.jpg' WHERE id = 10569;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\1? Temporada\\\\06_Uma conclus?o para essa luta in?til!_imagem.jpg' WHERE id = 10570;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\1? Temporada\\\\07_Uma segunda morte nesta esta??o congelante!_imagem.jpg' WHERE id = 10571;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\1? Temporada\\\\08_Uma m?o carinhosa para nossa equipe quando n?o conseguirmos superar o inverno!_imagem.jpg' WHERE id = 10572;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\1? Temporada\\\\09_Uma b?n??o para esta loja maravilhosa!_imagem.jpg' WHERE id = 10573;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\1? Temporada\\\\10_Uma ?ltima chama para esta fortaleza aberrante!_imagem.jpg' WHERE id = 10574;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\2? Temporada\\\\01_Al?vio para este julgamento injusto!_imagem.jpg' WHERE id = 10575;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\2? Temporada\\\\02_Um amigo para essa garota dem?nio escarlate!_imagem.jpg' WHERE id = 10576;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\2? Temporada\\\\03_Paz para o mestre deste labirinto!_imagem.jpg' WHERE id = 10577;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\2? Temporada\\\\04_Um noivo para a filha desta nobre!_imagem.jpg' WHERE id = 10578;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\2? Temporada\\\\05_Um escravo de um cavaleiro mascarado!_imagem.jpg' WHERE id = 10579;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\2? Temporada\\\\06_Um adeus a este mundo chato!_imagem.jpg' WHERE id = 10580;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\2? Temporada\\\\07_Um convite para esse idiota acabado!_imagem.jpg' WHERE id = 10581;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\2? Temporada\\\\08_Turismo para esta cidade miser?vel!_imagem.jpg' WHERE id = 10582;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\2? Temporada\\\\09_Uma deusa para esta cidade de fontes termais corruptas!_imagem.jpg' WHERE id = 10583;
UPDATE episodio SET capa_url = 'F:\\\\Konosuba\\\\2? Temporada\\\\10_Uma b?n??o para este grupo maravilhoso!_imagem.jpg' WHERE id = 10584;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP001-Adoro_receber_ordens_de_voce.avi' WHERE id = 10585;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP002-Agua_por_todos_os_lados.avi' WHERE id = 10586;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP003-Alimentando_a_cria.avi' WHERE id = 10587;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP004-Alucinacao_coletiva.avi' WHERE id = 10588;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP005-Amigos_amigos_ratos_a_parte.avi' WHERE id = 10589;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP006-Amor_e_pragas.avi' WHERE id = 10590;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP007-As_aparencias_enganam.avi' WHERE id = 10591;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP008-As_peripecias_de_patolino.avi' WHERE id = 10592;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP009-As_suas_ordens_madame.avi' WHERE id = 10593;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP010-Ataque_aereo.avi' WHERE id = 10594;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP011-Ataque_ao_forte_do_patolino.avi' WHERE id = 10595;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP012-Atras_do_papa_leguas.avi' WHERE id = 10596;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP013-Auto_magnetismo.avi' WHERE id = 10597;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP014-Azar_de_coiote.avi' WHERE id = 10598;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP015-A_eterna_cacada.avi' WHERE id = 10599;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP016-A_infancia_do_pernalonga.avi' WHERE id = 10600;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP017-A_ingenuidade_de_frangolino.avi' WHERE id = 10601;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP018-A_message_to_gracias.avi' WHERE id = 10602;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP019-A_parada_dos_pinguins.avi' WHERE id = 10603;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP020-A_raposa_e_o_pato.avi' WHERE id = 10604;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP021-A_vida_atras_das_grades.avi' WHERE id = 10605;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP022-Baba_por_um_dia.avi' WHERE id = 10606;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP023-Bancando_a_isca.avi' WHERE id = 10607;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP024-Banho_de_coelho.avi' WHERE id = 10608;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP025-Bruxa_shakesperiana.avi' WHERE id = 10609;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP026-Cacando_o_rato.avi' WHERE id = 10610;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP027-Camundongos_travessos.avi' WHERE id = 10611;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP028-Cancando_de_apanhar.avi' WHERE id = 10612;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP029-Cangooro_e_frajola_em_papai_sabe_tudo.avi' WHERE id = 10613;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP030-Canguroo_em_um_rato_no_farol.avi' WHERE id = 10614;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP031-Carrinho_valente.avi' WHERE id = 10615;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP032-Cavaleiro_pernalonga.avi' WHERE id = 10616;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP033-Centro_de_rosquinhas_que_buraco.avi' WHERE id = 10617;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP034-Chuva_de_verao.avi' WHERE id = 10618;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP035-Coelho_18_quilates.avi' WHERE id = 10619;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP036-Coelho_cacado.avi' WHERE id = 10620;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP037-Coelho_feat.avi' WHERE id = 10621;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP038-Coelho_heroico.avi' WHERE id = 10622;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP039-Coelho_para_cima.avi' WHERE id = 10623;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP040-Coelho_selvagem.avi' WHERE id = 10624;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP041-Coelho_selvagem_do_velho_oeste.avi' WHERE id = 10625;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP042-Coelho_sem_lar.avi' WHERE id = 10626;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP043-Coiote_em_usando_novos_invento.avi' WHERE id = 10627;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP044-Colegio_catnip.avi' WHERE id = 10628;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP045-Como_reconhecer_uma_galinha.avi' WHERE id = 10629;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP046-Como_se_casar_com_um_galo.avi' WHERE id = 10630;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP047-Complexo_de_Napoleao.avi' WHERE id = 10631;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP048-Compre_veja_e_preste_atencao.avi' WHERE id = 10632;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP049-Concerto_sem_do.avi' WHERE id = 10633;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP050-Corn_on_the_cop.avi' WHERE id = 10634;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP051-De_cara_na_parede.avi' WHERE id = 10635;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP052-De_pai_para_filhos.avi' WHERE id = 10636;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP053-Dia_de_cao.avi' WHERE id = 10637;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP054-Diversao_na_neve.avi' WHERE id = 10638;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP055-Doce_sioux.avi' WHERE id = 10639;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP056-Dois_corvos_e_um_gafanhoto.avi' WHERE id = 10640;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP057-Elmert_o_ingrato.avi' WHERE id = 10641;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP058-Em_busca_de_um_lar.avi' WHERE id = 10642;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP059-Encrencas_do_pernalonga.avi' WHERE id = 10643;
