UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP060-Enganados_por_um_rato.avi' WHERE id = 10644;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP061-Era_filho_de_um_acrobata.avi' WHERE id = 10645;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP062-Escalando_o_pico.avi' WHERE id = 10646;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP063-Esporte_dos_campeoes.avi' WHERE id = 10647;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP064-Fabrica_de_bebes.avi' WHERE id = 10648;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP065-Falando_do_tempo.avi' WHERE id = 10649;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP066-Ferias_aereas.avi' WHERE id = 10650;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP067-Filho_de_rato_ratinho_e.avi' WHERE id = 10651;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP068-Folga_do_sapateiro.avi' WHERE id = 10652;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP069-Frajola_o_heroi.avi' WHERE id = 10653;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP070-Frangolino_bom_de_briga.avi' WHERE id = 10654;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP071-Frangolino_chocando_ovo.avi' WHERE id = 10655;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP072-Frangolino_em_aprendendo_a_ser_frango.avi' WHERE id = 10656;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP073-Frangolino_em_raposa_medrosa.avi' WHERE id = 10657;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP074-Frangolino_em_sirva-se_fuinha.avi' WHERE id = 10658;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP075-Frangolino_em_uma_fuinha_infernal.avi' WHERE id = 10659;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP076-Frangolino_tudo_por_um_calor_galinaceo.avi' WHERE id = 10660;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP077-Frango_a_moda_sulista.avi' WHERE id = 10661;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP078-Fugindo_do_inferno.avi' WHERE id = 10662;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP079-Gaguinho_em_castelo_dos_doendes.avi' WHERE id = 10663;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP080-Gaguinho_e_Patolino_em_cobertura_total.avi' WHERE id = 10664;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP081-Gaguinho_e_patolino_em_descanso_merecido.avi' WHERE id = 10665;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP082-Gatos_e_explosivos_nao_se_mistiram.avi' WHERE id = 10666;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP083-Guerra_e_guerra.avi' WHERE id = 10667;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP084-Historias_da_mamae_ganso.avi' WHERE id = 10668;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP085-Historia_natural.avi' WHERE id = 10669;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP086-Ideia_de_genio.avi' WHERE id = 10670;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP087-Kitty_kornered.avi' WHERE id = 10671;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP088-Lagarta_de_sorte.avi' WHERE id = 10672;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP089-Lagrima_de_crocodilos.avi' WHERE id = 10673;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP090-Ligeirinho_em_prato_mexicano.avi' WHERE id = 10674;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP091-Ligeirinho_salva_a_cidade.avi' WHERE id = 10675;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP092-Little_red_walking_hood.avi' WHERE id = 10676;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP093-Lobo_na_pele_de_ovelha.avi' WHERE id = 10677;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP094-Louvre_de_volta_a_mim.avi' WHERE id = 10678;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP095-Mamae_galo.avi' WHERE id = 10679;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP096-Manda_bala.avi' WHERE id = 10680;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP097-Marcianos_invadem_a_terra.avi' WHERE id = 10681;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP098-Meu_pato_favorito.avi' WHERE id = 10682;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP099-Moby_duck_ligeirinho_e_patolino.avi' WHERE id = 10683;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP100-Mostra_de_caes.avi' WHERE id = 10684;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP101-Mudanca_de_vida.avi' WHERE id = 10685;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP102-Mudanca_rapida.avi' WHERE id = 10686;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP103-Muito_trabalho_para_nada.avi' WHERE id = 10687;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP104-Mundo_do_futebol.avi' WHERE id = 10688;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP105-Musica_perambulante.avi' WHERE id = 10689;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP106-Nao_abandone_as_ovelhas.avi' WHERE id = 10690;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP107-Nao_ha_dinheiro_que_nao_pague.avi' WHERE id = 10691;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP108-Nasce_uma_estrela.avi' WHERE id = 10692;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP109-Na_compania_do_patolino.avi' WHERE id = 10693;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP110-No_caminho_do_progresso.avi' WHERE id = 10694;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP111-Oeste_selvagem.avi' WHERE id = 10695;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP112-Operacao_coelho.avi' WHERE id = 10696;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP113-Os_tres_porquinhos.avi' WHERE id = 10697;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP114-Ouro_de_coelho.avi' WHERE id = 10698;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP115-O_abominavel_coelho_das_neves.avi' WHERE id = 10699;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP116-O_alegre_passeio_mexicano.avi' WHERE id = 10700;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP117-O_aprendiz_de_papa_galinhas.avi' WHERE id = 10701;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP118-O_aristogato.avi' WHERE id = 10702;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP119-O_artista_patolino.avi' WHERE id = 10703;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP120-O_cacador_de_coelhos.avi' WHERE id = 10704;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP121-O_coelho_boxer.avi' WHERE id = 10705;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP122-O_coelho_de_wackiki.avi' WHERE id = 10706;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP123-O_coelho_do_dia.avi' WHERE id = 10707;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP124-O_coelho_que_veio_para_jantar.avi' WHERE id = 10708;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP125-O_dia_da_marmota.avi' WHERE id = 10709;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP126-O_esperto_e_excentrico_pato.avi' WHERE id = 10710;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP127-O_estupido_cupido.avi' WHERE id = 10711;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP128-O_fim_secreto.avi' WHERE id = 10712;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP129-O_flautista_de_guadalupe.avi' WHERE id = 10713;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP130-O_galo_atrapalhado.avi' WHERE id = 10714;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP131-O_gato_sai_e_os_ratos_fazem_a_festa.avi' WHERE id = 10715;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP132-O_gaviao_exigente.avi' WHERE id = 10716;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP133-O_hipinotizador_de_gatos.avi' WHERE id = 10717;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP134-O_indio_joe.avi' WHERE id = 10718;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP135-O_lobo_chocado.avi' WHERE id = 10719;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP136-O_melhor_amigo_do_cao.avi' WHERE id = 10720;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP137-O_mundo_e_dos_mais_vivos.avi' WHERE id = 10721;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP138-O_oscar_vai_para_pernalonga.avi' WHERE id = 10722;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP139-O_osso.avi' WHERE id = 10723;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP140-O_pequeno_cao_orfao.avi' WHERE id = 10724;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP141-O_pica_pau_ouconsciencia.avi' WHERE id = 10725;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP142-O_rato_destruidor.avi' WHERE id = 10726;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP143-O_refugio.avi' WHERE id = 10727;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP144-O_resfriado.avi' WHERE id = 10728;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP145-O_sonho_de_jack.avi' WHERE id = 10729;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP146-O_terror_do_deserto.avi' WHERE id = 10730;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP147-O_treinador_de_frajola.avi' WHERE id = 10731;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP148-O_ultimo_gato_faminto.avi' WHERE id = 10732;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP149-O_ultimo_moicano.avi' WHERE id = 10733;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP150-O_vigia_noturno.avi' WHERE id = 10734;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP151-O_vilao.avi' WHERE id = 10735;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP152-Paixoes_de_rato.avi' WHERE id = 10736;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP153-Panchicho_vanila.avi' WHERE id = 10737;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP154-Parabens_voce_e_pai.avi' WHERE id = 10738;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP155-Passeio_pelo_hawaii.avi' WHERE id = 10739;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP156-Patolino_detetive.avi' WHERE id = 10740;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP157-Patolino_em_hollywood.avi' WHERE id = 10741;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP158-Patolino_em_nao_me_coma.avi' WHERE id = 10742;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP159-Patolino_em_o_bebe_da_cegonha.avi' WHERE id = 10743;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP160-Patolino_e_seus_truques.avi' WHERE id = 10744;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP161-Patolino_no_velho_oeste.avi' WHERE id = 10745;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP162-Pato_pasmo.avi' WHERE id = 10746;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP163-Pato_superior.avi' WHERE id = 10747;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP164-Pepe_le_pew_em_amor_selvagem.avi' WHERE id = 10748;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP165-Pepe_le_pew_em_aventura_inesquecivel.avi' WHERE id = 10749;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP166-Pepe_le_pew_em_romance_nos_alpes.avi' WHERE id = 10750;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP167-Pepe_le_pew_na_legiao_estrangeira.avi' WHERE id = 10751;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP168-Perdidos_na_ilha.avi' WHERE id = 10752;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP169-Perdido_e_orfao.avi' WHERE id = 10753;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP170-Pernalonga_a_descoberta_da_america.avi' WHERE id = 10754;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP171-Pernalonga_em_coelho_do_deserto.avi' WHERE id = 10755;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP172-Pernalonga_em_contatos_imediatos.avi' WHERE id = 10756;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP173-Pernalonga_em_frente_e_marche.avi' WHERE id = 10757;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP174-Pernalonga_em_gorila_dos_meus_sonhos.avi' WHERE id = 10758;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP175-Pernalonga_em_marte.avi' WHERE id = 10759;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP176-Pernalonga_em_o_coelho_espacial.avi' WHERE id = 10760;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP177-Pernalonga_em_o_ouro_da_cobica.avi' WHERE id = 10761;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP178-Pernalonga_em_rasgando_o_contrato.avi' WHERE id = 10762;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP179-Pernalonga_em_triangulo_amoroso.mp4.avi' WHERE id = 10763;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP180-Pernalonga_e_o_lobo_mau.avi' WHERE id = 10764;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP181-Pernalonga_e_o_marciano.avi' WHERE id = 10765;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP182-Pernalonga_e_o_pe_de_feijao.avi' WHERE id = 10766;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP183-Pesadelo_de_coelho.avi' WHERE id = 10767;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP184-Piu_piu_em_frajola_na_gaiola.avi' WHERE id = 10768;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP185-Piu_piu_em_novos_vizinhos.avi' WHERE id = 10769;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP186-Piu_piu_em_passaro_indigesto.avi' WHERE id = 10770;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP187-Piu_piu_e_frajola_a_historia_de_piu_piu.avi' WHERE id = 10771;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP188-Piu_piu_e_frajola_em_visitando_o_zoologico.avi' WHERE id = 10772;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP189-Piu_piu_e_frajola_presos_na_nevasca.avi' WHERE id = 10773;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP190-Pocos_do_texa.avi' WHERE id = 10774;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP191-Porcos_e_porcos.avi' WHERE id = 10775;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP192-Praga_de_rato.avi' WHERE id = 10776;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP193-Quem_ri_por_ultimo_ri_melhor.avi' WHERE id = 10777;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP194-Que_opera_velhinho.avi' WHERE id = 10778;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP195-Que_pedrada.avi' WHERE id = 10779;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP196-Rapoza_de_prata.avi' WHERE id = 10780;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP197-Ratinhos_brincalhoes.avi' WHERE id = 10781;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP198-Rato_quinta_coluna.avi' WHERE id = 10782;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP199-Rato_tamanho_familia.avi' WHERE id = 10783;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP200-Razoes_sentimentais.avi' WHERE id = 10784;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP201-Rhapsody_in_rivets.avi' WHERE id = 10785;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP202-Roedorzinho_vermelho.avi' WHERE id = 10786;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP203-Romance_no_gelo.avi' WHERE id = 10787;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP204-Romeu_sentimental.avi' WHERE id = 10788;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP205-Sniffles_bells_the_cat.avi' WHERE id = 10789;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP206-Sniffles_takes_a_trip.avi' WHERE id = 10790;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP207-Sobrevivencia_na_floresta_com_frangolino.avi' WHERE id = 10791;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP208-Sono_espacial.avi' WHERE id = 10792;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP209-Sr_e_sra_e_o_nome.avi' WHERE id = 10793;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP210-Super_coelho.avi' WHERE id = 10794;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP211-Swooner_crooner.avi' WHERE id = 10795;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP212-Tentando_hibernar.avi' WHERE id = 10796;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP213-Tentando_tudo.avi' WHERE id = 10797;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP214-Toquinho_vai_acampanhar.avi' WHERE id = 10798;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP215-Uma_cacada_no_cartoon.avi' WHERE id = 10799;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP216-Uma_festa_em_malibu.avi' WHERE id = 10800;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP217-Uma_noite_com_os_astros.avi' WHERE id = 10801;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP218-Um_chapeuzinho_vermelho_diferente.avi' WHERE id = 10802;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP219-Um_gato_bem_informado.avi' WHERE id = 10803;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP220-Um_moco_em_bagda.avi' WHERE id = 10804;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP221-Uniao_em_perigo.avi' WHERE id = 10805;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP222-Valeu_bicho.avi' WHERE id = 10806;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP223-Vamos_tocar.avi' WHERE id = 10807;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP224-Vida_de_cachorro.avi' WHERE id = 10808;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP225-Vida_de_gato_e_fogo.avi' WHERE id = 10809;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP226-Vida_selvagem.avi' WHERE id = 10810;
UPDATE episodio SET capa_url = 'F:\\\\Looney Tones - Incompleto\\\\EP227-Visita_indesejada.avi' WHERE id = 10811;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\01_Autointitulado paranormal - Arataka Reigen ? E Mob_imagem.jpg' WHERE id = 10903;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\02_D?vidas da juventude ? Surge o Clube da Telepatia_imagem.jpg' WHERE id = 10904;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\03_Um convite a uma reuni?o ? Sem rodeios, s? quero ser popular_imagem.jpg' WHERE id = 10905;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\04_Um evento s? para idiotas ? Kin_imagem.jpg' WHERE id = 10906;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\05_Ochimusha ? Eu e poderes paranormais_imagem.jpg' WHERE id = 10907;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\06_Disson?ncia ? Como acabar numa_imagem.jpg' WHERE id = 10908;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\07_Efervesc?ncia ? Obtive perdas_imagem.jpg' WHERE id = 10909;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\08_O irm?o se inclina ? Inten??o de destrui??o_imagem.jpg' WHERE id = 10910;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\09_Garra ? 7? divis?o_imagem.jpg' WHERE id = 10911;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\10_A colossal aura maligna ? O cabe?a_imagem.jpg' WHERE id = 10912;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\11_Mestre ? L?der_imagem.jpg' WHERE id = 10913;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\1? Temporada\\\\12_Mob e Reigen ? Surge um gigantesco tsuchinoko_imagem.jpg' WHERE id = 10914;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\01_Em peda?os ? Algu?m est? olhando_imagem.jpg' WHERE id = 10915;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\02_Lendas urbanas ? Encontrando rumores_imagem.jpg' WHERE id = 10916;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\03_Um perigo ap?s o outro ? Degenera??o_imagem.jpg' WHERE id = 10917;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\04_Dentro ? Esp?rito maligno_imagem.jpg' WHERE id = 10918;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\05_Desarmonia ? Escolhas_imagem.jpg' WHERE id = 10919;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\06_Solit?rio Whitey_imagem.jpg' WHERE id = 10920;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\07_Encurralado ? Verdadeira identidade_imagem.jpg' WHERE id = 10921;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\08_Mesmo assim ? Em frente_imagem.jpg' WHERE id = 10922;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\09_Me mostre ? Reuni?o_imagem.jpg' WHERE id = 10923;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\10_Colis?o ? Tipo de poder_imagem.jpg' WHERE id = 10924;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\11_Orienta??o ? Paranormal de detec??o_imagem.jpg' WHERE id = 10925;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\12_A batalha pela reabilita??o social ? Amizade_imagem.jpg' WHERE id = 10926;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\2? Temporada\\\\13_Luta com o chefe ? A ?ltima luz_imagem.jpg' WHERE id = 10927;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\01_Futuro ? Carreira que desejo seguir_imagem.jpg' WHERE id = 10928;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\02_O ca?ador de Yokais! A chegada de Haruaki Amakusa! ? A amea?a dos cem dem?nios!_imagem.jpg' WHERE id = 10929;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\03_Se empolgando ? 100%_imagem.jpg' WHERE id = 10930;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\04_?rvore divina 1 ? O fundador aparece_imagem.jpg' WHERE id = 10931;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\05_?rvore divina 2 ? Paz_imagem.jpg' WHERE id = 10932;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\06_?rvore divina 3 ? Covinhas ?_imagem.jpg' WHERE id = 10933;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\07_Comunica??o 1 ? F?rias de inverno_imagem.jpg' WHERE id = 10934;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\08_Comunica??o 2 ? Encontrando o desconhecido_imagem.jpg' WHERE id = 10935;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\09_Mob 1 ? Mudan?a_imagem.jpg' WHERE id = 10936;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\10_Mob 2 ? Rival_imagem.jpg' WHERE id = 10937;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\11_Mob 3 ? Trauma_imagem.jpg' WHERE id = 10938;
UPDATE episodio SET capa_url = 'F:\\\\Mob Psycho 100\\\\3? Temporada\\\\12_Confiss?o ? O futuro_imagem.jpg' WHERE id = 10939;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\01_Os Sete Pecados Capitais_imagem.jpg' WHERE id = 10940;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\02_A Espada do Paladino_imagem.jpg' WHERE id = 10941;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\03_O Pecado da Floresta Adormecida_imagem.jpg' WHERE id = 10942;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\04_O Sonho de uma Jovem Garota_imagem.jpg' WHERE id = 10943;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\05_Acha Mesmo que Voc? iria Morrer_imagem.jpg' WHERE id = 10944;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\06_In?cio de um Poema_imagem.jpg' WHERE id = 10945;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\07_Reuni?o Comovente_imagem.jpg' WHERE id = 10946;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\08_O Terr?vel Perseguidor_imagem.jpg' WHERE id = 10947;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\09_O Pulso Negro_imagem.jpg' WHERE id = 10948;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\10_A Luta de Byzel no Festival_imagem.jpg' WHERE id = 10949;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\11_Um Sentimento de Longa Data_imagem.jpg' WHERE id = 10950;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\12_O Canh?o Aterrorizante_imagem.jpg' WHERE id = 10951;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\13_Ap?stolo da Destrui??o_imagem.jpg' WHERE id = 10952;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\14_O Leitor_imagem.jpg' WHERE id = 10953;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\15_O Cavaleiro Profano_imagem.jpg' WHERE id = 10954;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\16_As Lendas Encurraladas_imagem.jpg' WHERE id = 10955;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\17_Primeira V?tima_imagem.jpg' WHERE id = 10956;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\18_Mesmo que eu Tenha que Desistir da Minha Vida por Isso_imagem.jpg' WHERE id = 10957;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\19_O Rei Fada que Esperou em V?o_imagem.jpg' WHERE id = 10958;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\20_A Maldi??o da Coragem_imagem.jpg' WHERE id = 10959;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\21_Uma Amea?a Iminente Se Aproxima_imagem.jpg' WHERE id = 10960;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\22_O que Eu Posso Fazer por Voc?_imagem.jpg' WHERE id = 10961;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\23_Desespero Descende_imagem.jpg' WHERE id = 10962;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\1? Temporada\\\\24_Her?is_imagem.jpg' WHERE id = 10963;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\01_Renascimento do Cl? dos Dem?nios_imagem.jpg' WHERE id = 10964;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\02_Exist?ncia e Prova_imagem.jpg' WHERE id = 10965;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\03_Tesouro sagrado Lostvayne_imagem.jpg' WHERE id = 10966;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\04_Os Dez Mandamentos se Movem_imagem.jpg' WHERE id = 10967;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\05_Viol?ncia Implac?vel_imagem.jpg' WHERE id = 10968;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\06_O Capit?o Reconciliado dos Cavaleiros Sagrados_imagem.jpg' WHERE id = 10969;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\07_Onde as Mem?rias Levam_imagem.jpg' WHERE id = 10970;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\08_A Terra Sagrada dos Druidas_imagem.jpg' WHERE id = 10971;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\09_A Promessa Com a Pessoa Amada_imagem.jpg' WHERE id = 10972;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\10_Aquilo Que Nos Faltava_imagem.jpg' WHERE id = 10973;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\11_Pai e Filho_imagem.jpg' WHERE id = 10974;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\12_O Sentido do Amor_imagem.jpg' WHERE id = 10975;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\13_Adeus! Amado Bandido! Eu Vencerei Os Dez Mandamentos_imagem.jpg' WHERE id = 10976;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\14_O Senhor do Sol!_imagem.jpg' WHERE id = 10977;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\15_Uma Confiss?o Horripilante_imagem.jpg' WHERE id = 10978;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\16_Labirinto da Armadilha da Morte_imagem.jpg' WHERE id = 10979;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\17_Figuras Lend?rias_imagem.jpg' WHERE id = 10980;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\18_Para quem essa Luz Brilha_imagem.jpg' WHERE id = 10981;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\19_Meliodas Contra os Dez Mandamentos_imagem.jpg' WHERE id = 10982;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\20_Busca da Esperan?a_imagem.jpg' WHERE id = 10983;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\21_Certo Calor_imagem.jpg' WHERE id = 10984;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\22_Retorno dos Pecados_imagem.jpg' WHERE id = 10985;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\23_O Her?i se Levanta_imagem.jpg' WHERE id = 10986;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\2? Temporada\\\\24_Enquanto Voc? Estiver Aqui_imagem.jpg' WHERE id = 10987;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\01_A Luz Que Afasta A Escurid?o_imagem.jpg' WHERE id = 10988;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\02_Mem?rias Da Guerra Sagrada_imagem.jpg' WHERE id = 10989;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\03_Faca-se Luz_imagem.jpg' WHERE id = 10990;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\04_Dez Mandamentos VS Quatro Arcanjos_imagem.jpg' WHERE id = 10991;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\05_Um Turbilh?o de Emoc?es_imagem.jpg' WHERE id = 10992;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\06_Chamamos a isso Amor_imagem.jpg' WHERE id = 10993;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\07_Pecados Mortais, Unidos!_imagem.jpg' WHERE id = 10994;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\08_O Boneco em Busca de Amor_imagem.jpg' WHERE id = 10995;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\09_Os Amantes Amaldi?oados_imagem.jpg' WHERE id = 10996;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\10_A Vida que Levamos_imagem.jpg' WHERE id = 10997;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\11_Os Odiosos N?o Descansam_imagem.jpg' WHERE id = 10998;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\12_O Poder de Uma Donzela ? o Amor_imagem.jpg' WHERE id = 10999;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\13_O Mais Forte VS O Mais Mal?fico_imagem.jpg' WHERE id = 11000;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\14_Uma Nova Amea?a_imagem.jpg' WHERE id = 11001;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\15_Ao Capit?o_imagem.jpg' WHERE id = 11002;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\16_O Fim Dos Sete Pecados Mortais_imagem.jpg' WHERE id = 11003;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\17_A Nossa Escolha_imagem.jpg' WHERE id = 11004;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\18_Quando Os Santos Marcham_imagem.jpg' WHERE id = 11005;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\19_O Tratado da Guerra Sagrada_imagem.jpg' WHERE id = 11006;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\20_A Crian?a De Esperan?a_imagem.jpg' WHERE id = 11007;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\21_O ?nicio da Guerra Sagrada_imagem.jpg' WHERE id = 11008;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\22_Brittania Devastada Pela Guerra_imagem.jpg' WHERE id = 11009;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\23_Aquele Que as Trevas Distorceram_imagem.jpg' WHERE id = 11010;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\3? Temporada\\\\24_Amor Descontrolado_imagem.jpg' WHERE id = 11011;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\01_Purgat?rio_imagem.jpg' WHERE id = 11012;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\02_Encontro com o desconhecido_imagem.jpg' WHERE id = 11013;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\03_Um amor obstinado_imagem.jpg' WHERE id = 11014;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\04_As v?timas da Guerra Santa_imagem.jpg' WHERE id = 11015;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\05_Golpe tr?gico_imagem.jpg' WHERE id = 11016;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\06_Enfrentando o desespero_imagem.jpg' WHERE id = 11017;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\07_Esperan?a, conflito e desespero_imagem.jpg' WHERE id = 11018;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\08_Porta da esperan?a_imagem.jpg' WHERE id = 11019;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\09_Reunidos_imagem.jpg' WHERE id = 11020;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\10_A salva??o do sol_imagem.jpg' WHERE id = 11021;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\11_Quem se op?e a um deus_imagem.jpg' WHERE id = 11022;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\12_A uni?o faz a for?a_imagem.jpg' WHERE id = 11023;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\13_O fim de uma longa jornada_imagem.jpg' WHERE id = 11024;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\14_Adeus, Sete Pecados Capitais_imagem.jpg' WHERE id = 11025;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\15_Irm?os predestinados_imagem.jpg' WHERE id = 11026;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\16_A batalha final_imagem.jpg' WHERE id = 11027;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\17_A voz que chama seu nome_imagem.jpg' WHERE id = 11028;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\18_O rei canta sozinho_imagem.jpg' WHERE id = 11029;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\19_A luta_imagem.jpg' WHERE id = 11030;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\20_Inimigos mortais_imagem.jpg' WHERE id = 11031;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\21_O que a bruxa sempre quis_imagem.jpg' WHERE id = 11032;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\22_Gostinho de caos_imagem.jpg' WHERE id = 11033;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\23_Um reino eterno_imagem.jpg' WHERE id = 11034;
UPDATE episodio SET capa_url = 'F:\\\\Nanatsu no Taizai\\\\4? Temporada\\\\24_Herdeiros_imagem.jpg' WHERE id = 11035;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\10_A Floresta de Chakra_imagem.jpg' WHERE id = 11036;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\11_O Pa?s que Teve um Her?i_imagem.jpg' WHERE id = 11037;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\12_Luta na Ponte! Zabuza de Novo!!_imagem.jpg' WHERE id = 11038;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\13_Jutsu Secreto do Haku Makyo Hyosho_imagem.jpg' WHERE id = 11039;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\14_N?mero 1 em Imprevistos - Naruto Participa da Luta!_imagem.jpg' WHERE id = 11040;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\15_Luta com Visibilidade Zero - O Sharingan ? Inibido_imagem.jpg' WHERE id = 11041;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\16_O Selo Liberado_imagem.jpg' WHERE id = 11042;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\17_O Passado Branco - Os Sentimentos Internos_imagem.jpg' WHERE id = 11043;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\18_Uma Ferramenta Chamada Shinobi_imagem.jpg' WHERE id = 11044;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\19_Zabuza se Dispersa na Neve..._imagem.jpg' WHERE id = 11045;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\20_Um Novo Cap?tulo Come?a! ? o Exame Chunin, To Certo_imagem.jpg' WHERE id = 11047;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\21_Apresentem-se! Os Oponentes Chegaram!!_imagem.jpg' WHERE id = 11048;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\22_Anima??o a 120% - Um Novo Desafio Dif?cil!_imagem.jpg' WHERE id = 11049;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\23_Acabe com os Rivais! Os 9 Novatos Est?o Reunido_imagem.jpg' WHERE id = 11050;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\24_Eu J? Falhei A Dif?cil Primeira Parte_imagem.jpg' WHERE id = 11051;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\1? Temporada\\\\25_Um Novo Desafio! A Quest?o 10 que Devo Decidir_imagem.jpg' WHERE id = 11052;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\10_Proibido Tentar Espiar! O Segredo do Pergaminho_imagem.jpg' WHERE id = 11061;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\11_O Confronto dos Clones! Eu Sou o Protagonista, To Certo!_imagem.jpg' WHERE id = 11062;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\12_Segundo Teste Completo! Todos os Nove Novatos Est?o Aqui!_imagem.jpg' WHERE id = 11063;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\13_Candidatos Calassificados Reduzidos ? Metade! Uma Disputa Inesperada, To Certo!!_imagem.jpg' WHERE id = 11064;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\14_A Inveja do Sobrancelhudo! Nasce o Shishi Rendan!_imagem.jpg' WHERE id = 11065;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\15_Uma Situa??o Cr?tica!! Kakashi VS Orochimaru_imagem.jpg' WHERE id = 11066;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\16_O Confronto das Rivais! Os Cora??es das Garotas no Modo S?rio_imagem.jpg' WHERE id = 11067;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\17_A Melhor Batalha ? Demais!!_imagem.jpg' WHERE id = 11068;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\18_Shikamaru Abalado! A Fervorosa Batalha das Kunoichi_imagem.jpg' WHERE id = 11069;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\19_Akamaru Entra na Briga!! Quem Ser? o Perdedor_imagem.jpg' WHERE id = 11070;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\20_Hinata Envergonhada! Os Espectadores Ficam Boquiabertos, o Trunfo de Naruto!_imagem.jpg' WHERE id = 11072;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\21_Byakugan Liberado!! A Ousada Determina??o da T?mida Hinata!_imagem.jpg' WHERE id = 11073;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\22_Em Frente a Uma Pessoa Que Eu Admiro!!_imagem.jpg' WHERE id = 11074;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\23_Gaara Esmagado!! Juventude! Poder! Explos?o!_imagem.jpg' WHERE id = 11075;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\24_Fracassado de Sangue Quente! Finalmente Explode, o Golpe Secreto Proibido!_imagem.jpg' WHERE id = 11076;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\25_Ah, Rock Lee! ? Assim que um Homem Deve Ser!!_imagem.jpg' WHERE id = 11077;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\26_A Sombra Sinuosa na Escurid?o - O Perigo se Aproxima do Sasuke!_imagem.jpg' WHERE id = 11078;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\27_Ebisu de Novo! N?o Permitirei Safadesa!_imagem.jpg' WHERE id = 11079;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\2? Temporada\\\\28_Espere um Pouco! Aparece o Ero-Sennin!_imagem.jpg' WHERE id = 11080;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\10_Eliminado! Perigo! Queda! As Finais com Muitas Reviravoltas!_imagem.jpg' WHERE id = 11089;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\11_As Nuvens S?o Legais... O Homem sem Vontade_imagem.jpg' WHERE id = 11090;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\12_Batalha! O Momento em que a Folha Dan?a e a Areia se Move_imagem.jpg' WHERE id = 11091;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\13_O Homem que Chama a Tempestade! O Taijutsu Estilo Sobrancelhudo do Sasuke!_imagem.jpg' WHERE id = 11092;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\14_Eu N?o Estava Atrasado ? Toa! Momento Supremo - Chidori Revelado!!_imagem.jpg' WHERE id = 11093;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\15_Come?a a Destrui??o da Folha!_imagem.jpg' WHERE id = 11094;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\16_Estava Esperando por Isso! ? uma Miss?o de Rank A, To Certo!!_imagem.jpg' WHERE id = 11095;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\17_O Fuj?o N?mero 1 - ? Chato Mas tenho que Fazer!!_imagem.jpg' WHERE id = 11096;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\18_Imcompar?vel na Hist?ria! Luta de um N?vel Chamado Hokage_imagem.jpg' WHERE id = 11097;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\19_O Erro do Hokage - A Verdadeira Face Debaixo da M?scara_imagem.jpg' WHERE id = 11098;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\20_O Jutsu Secreto Proibido! Shiki F?jin_imagem.jpg' WHERE id = 11100;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\21_Aterrorizante! O Verdadeiro Gaara_imagem.jpg' WHERE id = 11101;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\22_Passando dos Limites... A Decis?o do Sasuke!!_imagem.jpg' WHERE id = 11102;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\23_Assassino da Noite de Lua_imagem.jpg' WHERE id = 11103;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\3? Temporada\\\\24_Luz e Escurid?o - Nome Chamado Gaara_imagem.jpg' WHERE id = 11104;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\10_For?a de Vontade!!! Estoure o Bal?o d'?gua!_imagem.jpg' WHERE id = 11113;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\11_A Marca da Folha e a Bandana_imagem.jpg' WHERE id = 11114;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\12_Ondula??o_imagem.jpg' WHERE id = 11115;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\13_Explos?o de Raiva! N?o Perdoarei, To Certo_imagem.jpg' WHERE id = 11116;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\14_A Heran?a do Shodai Hokage - O Colar que Chama a Morte_imagem.jpg' WHERE id = 11117;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\15_Sim ou N?o! A Resposta de Tsunade_imagem.jpg' WHERE id = 11118;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\16_Quebra de Acordo!!_imagem.jpg' WHERE id = 11119;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\17_Engula! O Rasengan da Raiva_imagem.jpg' WHERE id = 11120;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\18_Quinta Hokage - A Batalha em que se Aposta a Vida!_imagem.jpg' WHERE id = 11121;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\19_A Batalha do Trio Sem Sa?da_imagem.jpg' WHERE id = 11122;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\20_A Experi?ncia de Naruto nas Fontes Termais_imagem.jpg' WHERE id = 11124;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\21_Desista de Ser Ninja! O Aviso de Tsunade_imagem.jpg' WHERE id = 11125;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\22_Aquele que Suscede a Vontade do Fogo_imagem.jpg' WHERE id = 11126;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\23_O La?o Mestre-Disc?pulo dos Sangue Quente ~Quando um Homem Atravessa o Seu Estilo Ninja~_imagem.jpg' WHERE id = 11127;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\24_Quero Ver! Saber! Conferir! O Rosto do Kakashi-sensei_imagem.jpg' WHERE id = 11128;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\25_Nova Miss?o Emergencial - Resgate do Dever, Pessoas e o Pa?s do Ch?!_imagem.jpg' WHERE id = 11129;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\4? Temporada\\\\26_Naruto Afunda! O Grande Oceano com um Redemoinho de Conspira??o_imagem.jpg' WHERE id = 11130;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\10_Poder Total! Queime, Choji_imagem.jpg' WHERE id = 11139;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\11_Adeus Meu Amigo...! Mesmo Assim, Ainda Acredito em Voc?_imagem.jpg' WHERE id = 11140;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\12_O Seu Advers?rio sou Eu!_imagem.jpg' WHERE id = 11141;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\13_Vis?o de 360? - O Ponto Fraco do Byakugan_imagem.jpg' WHERE id = 11142;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\14_Perder N?o ? Uma Op??o_imagem.jpg' WHERE id = 11143;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\15_Ao Resgate ~ O Recipiente que N?o Chegou a Tempo_imagem.jpg' WHERE id = 11144;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\16_Fracasso! Um Novo Inimigo_imagem.jpg' WHERE id = 11145;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\17_Rosne! Uive! Revezamento Extremo_imagem.jpg' WHERE id = 11146;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\18_A Luta de Cada Um_imagem.jpg' WHERE id = 11147;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\19_Falso! Shikamaru, o Homem que Aposta na Virada do Jogo_imagem.jpg' WHERE id = 11148;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\20_A Besta Verde da Folha Aparece!_imagem.jpg' WHERE id = 11150;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\21_A Explos?o da Besta! Dispare, Voe, Penetre!_imagem.jpg' WHERE id = 11151;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\22_Aliados da Folha - Shinobis da Areia_imagem.jpg' WHERE id = 11152;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\23_A Batalha Final! Gaara VS Kimimaro!_imagem.jpg' WHERE id = 11153;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\24_Golpe da Vingan?a! Sawarabi no Mai_imagem.jpg' WHERE id = 11154;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\5? Temporada\\\\25_Grito Fora de Alcance_imagem.jpg' WHERE id = 11155;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\10_Trai??o Purificada - Desejos Moment?neos_imagem.jpg' WHERE id = 11164;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\11_Aterrorizante! O Castelo de Orochimaru_imagem.jpg' WHERE id = 11165;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\12_Duas Batidas - A Armadilha de Kabuto_imagem.jpg' WHERE id = 11166;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\13_A Determina??o de Sakura_imagem.jpg' WHERE id = 11167;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\14_O Terr?vel Trio que Protege a Fortaleza!_imagem.jpg' WHERE id = 11168;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\15_Corra Ton-Ton! Dependemos do Seu Nariz, To Certo_imagem.jpg' WHERE id = 11169;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\16_Nova C?lula Tripla - Duas Pessoas e Um Animal!_imagem.jpg' WHERE id = 11170;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\17_Explos?o! A Nova Forma??o Ino-Shika-Cho_imagem.jpg' WHERE id = 11171;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\18_Ambi??es Remanescentes - A Sombra de Orochimaru_imagem.jpg' WHERE id = 11172;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\19_Confronto do Destino! Voc? Nunca me Derrotar?_imagem.jpg' WHERE id = 11173;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\20_Rastreamento que Deixa Akamaru com Inveja! A Busca do Raro Besouro Bikochu_imagem.jpg' WHERE id = 11175;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\21_Qual a Diferen?a Os Insetos N?o S?o Todos Iguais_imagem.jpg' WHERE id = 11176;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\22_Engane, Confunda e Seja Confundido! A Grande Batalha de Insetos_imagem.jpg' WHERE id = 11177;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\23_Queime Byakugan! Esse ? o Meu Jeito Ninja_imagem.jpg' WHERE id = 11178;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\24_Marcha F?nebre Para os que Vivem_imagem.jpg' WHERE id = 11179;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\6? Temporada\\\\25_Encontre seu Cora??o! Punho do Amor_imagem.jpg' WHERE id = 11180;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\10_Estrategista - Os Esquemas de Komei_imagem.jpg' WHERE id = 11189;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\11_O Ajudante Atrasado_imagem.jpg' WHERE id = 11190;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\12_Naruto Morre_imagem.jpg' WHERE id = 11191;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\13_O Tempo que Parou_imagem.jpg' WHERE id = 11192;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\14_Quando a Gar?a Bate Suas Asas_imagem.jpg' WHERE id = 11193;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\15_A Panela Ferve! Misturem, Amassem e Cozinhem!!_imagem.jpg' WHERE id = 11194;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\16_M?morias - A P?gina Perdida_imagem.jpg' WHERE id = 11195;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\17_Colis?o - A Porta Fechada_imagem.jpg' WHERE id = 11196;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\18_Infiltra??o - A Armadilha Planejada_imagem.jpg' WHERE id = 11197;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\19_Desespero - O Cora??o Partido_imagem.jpg' WHERE id = 11198;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\20_Batalha Aqu?tica - O Poder Liberado_imagem.jpg' WHERE id = 11200;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\21_N?o Acredito, To Certo! A T?cnica das Celebridades Kinton no Jutsu_imagem.jpg' WHERE id = 11201;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\22_Cavem Aqui AU AU! A Busca do Tesouro Enterrado_imagem.jpg' WHERE id = 11202;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\23_Correndo, Cambaleando e Esquivando! Seguir, Ser Seguido e Ser Enganado_imagem.jpg' WHERE id = 11203;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\24_Oh! Por Favor ? Senhor Carteiro_imagem.jpg' WHERE id = 11204;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\7? Temporada\\\\25_Encontro - O Garoto com Nome de Estrela_imagem.jpg' WHERE id = 11205;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\10_Misteriosos - Os Mercadores Perseguidos_imagem.jpg' WHERE id = 11214;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\11_Debaixo d'?gua! Uma Infinidade de Armas Ninja_imagem.jpg' WHERE id = 11215;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\12_O Byakugan Viu! O Ponto Fraco dos Usu?rios do Im?_imagem.jpg' WHERE id = 11216;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\13_Senten?a de Morte - Nublado e ?s Vezes Ensolarado_imagem.jpg' WHERE id = 11217;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\14_O Grito de Ino! O Para?so ? Roli?o_imagem.jpg' WHERE id = 11218;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\15_Desafio Dojo Biba! A Juventude ? Explosiva_imagem.jpg' WHERE id = 11219;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\16_Grotesco - O Castelo Mau-Assombrado_imagem.jpg' WHERE id = 11220;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\17_A Longevidade de Dai-san - Sua Maior Rival_imagem.jpg' WHERE id = 11221;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\18_Confronto de L?grimas! A Batalha Entre Mestre e Disc?pulo de Sangue Quente_imagem.jpg' WHERE id = 11222;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\19_Confus?o! Os 11 da Folha se Agrupam_imagem.jpg' WHERE id = 11223;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\20_ANBU Desiste - A Mem?ria de Naruto_imagem.jpg' WHERE id = 11225;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\21_Fora de Foco - O Alvo ? Vista_imagem.jpg' WHERE id = 11226;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\22_Trabalho Ativo! O Maior Ajudante_imagem.jpg' WHERE id = 11227;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\23_Muitas Armadilhas - Contagem Regressiva para a Destrui??o_imagem.jpg' WHERE id = 11228;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\8? Temporada\\\\24_As 5 Melhores Batalhas Ninjas entre Suor e L?grimas!_imagem.jpg' WHERE id = 11229;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\9? Temporada\\\\10_O Caminho de Cada Um_imagem.jpg' WHERE id = 11238;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\9? Temporada\\\\11_Lembran?as Perdidas_imagem.jpg' WHERE id = 11239;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\9? Temporada\\\\12_Realidade Recuperada_imagem.jpg' WHERE id = 11240;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\9? Temporada\\\\13_Passado que Quero Apagar_imagem.jpg' WHERE id = 11241;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\9? Temporada\\\\14_O Artes?o Desaparecido - Shukaku ? o Alvo_imagem.jpg' WHERE id = 11242;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\9? Temporada\\\\15_Aliados da Areia - Shinobis da Folha_imagem.jpg' WHERE id = 11243;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\9? Temporada\\\\16_Areia Selada - O Contra-ataque de Suiko_imagem.jpg' WHERE id = 11244;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\9? Temporada\\\\17_Arma Suprema Ressuscitada_imagem.jpg' WHERE id = 11245;
UPDATE episodio SET capa_url = 'F:\\\\Naruto\\\\9? Temporada\\\\18_Partida_imagem.jpg' WHERE id = 11246;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\01_Ataque do anjo_imagem.jpg' WHERE id = 11256;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\02_Ambiente desconhecido_imagem.jpg' WHERE id = 11257;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\03_Telefone silencioso_imagem.jpg' WHERE id = 11258;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\04_Chuva depois da fuga_imagem.jpg' WHERE id = 11259;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\05_Rei, al?m de seu cora??o_imagem.jpg' WHERE id = 11260;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\06_Confronto em Neo T?quio Tr?s_imagem.jpg' WHERE id = 11261;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\07_A cria??o humana_imagem.jpg' WHERE id = 11262;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\08_Asuka ataca!_imagem.jpg' WHERE id = 11263;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\09_Momento de uni?o de mentes_imagem.jpg' WHERE id = 11264;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\10_Inferno de magma!_imagem.jpg' WHERE id = 11265;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\11_Na escurid?o silenciosa_imagem.jpg' WHERE id = 11266;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\12_O valor de um milagre_imagem.jpg' WHERE id = 11267;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\13_A invas?o dos anjos_imagem.jpg' WHERE id = 11268;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\14_SEELE, um lugar para a alma!_imagem.jpg' WHERE id = 11269;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\15_Mentiras e sil?ncio_imagem.jpg' WHERE id = 11270;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\16_Doen?a at? a morte_imagem.jpg' WHERE id = 11271;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\17_A quarta crian?a_imagem.jpg' WHERE id = 11272;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\18_O julgamento da vida_imagem.jpg' WHERE id = 11273;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\19_A luta de um homem_imagem.jpg' WHERE id = 11274;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\20_Forma da mente, forma de homem_imagem.jpg' WHERE id = 11275;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\21_O nascimento da Nerv_imagem.jpg' WHERE id = 11276;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\22_Pelo menos, seja humano_imagem.jpg' WHERE id = 11277;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\23_L?grimas_imagem.jpg' WHERE id = 11278;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\24_O mensageiro final_imagem.jpg' WHERE id = 11279;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\25_O fim do mundo_imagem.jpg' WHERE id = 11280;
UPDATE episodio SET capa_url = 'F:\\\\Neon Genesis Evangelion\\\\26_A fera que gritou eu no cora??o do mundo_imagem.jpg' WHERE id = 11281;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-1_imagem.jpg' WHERE id = 11282;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-10_imagem.jpg' WHERE id = 11283;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-100_imagem.jpg' WHERE id = 11284;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-101_imagem.jpg' WHERE id = 11285;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-102_imagem.jpg' WHERE id = 11286;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-103_imagem.jpg' WHERE id = 11287;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-104_imagem.jpg' WHERE id = 11288;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-105_imagem.jpg' WHERE id = 11289;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-106_imagem.jpg' WHERE id = 11290;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-107_imagem.jpg' WHERE id = 11291;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-108_imagem.jpg' WHERE id = 11292;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-109_imagem.jpg' WHERE id = 11293;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-11_imagem.jpg' WHERE id = 11294;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-110_imagem.jpg' WHERE id = 11295;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-111_imagem.jpg' WHERE id = 11296;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-112_imagem.jpg' WHERE id = 11297;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-113_imagem.jpg' WHERE id = 11298;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-114_imagem.jpg' WHERE id = 11299;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-115_imagem.jpg' WHERE id = 11300;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-116_imagem.jpg' WHERE id = 11301;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-117_imagem.jpg' WHERE id = 11302;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-118_imagem.jpg' WHERE id = 11303;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-119_imagem.jpg' WHERE id = 11304;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-12_imagem.jpg' WHERE id = 11305;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-120_imagem.jpg' WHERE id = 11306;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-121_imagem.jpg' WHERE id = 11307;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-122_imagem.jpg' WHERE id = 11308;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-123_imagem.jpg' WHERE id = 11309;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-124_imagem.jpg' WHERE id = 11310;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-125_imagem.jpg' WHERE id = 11311;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-126_imagem.jpg' WHERE id = 11312;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-127_imagem.jpg' WHERE id = 11313;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-128_imagem.jpg' WHERE id = 11314;
UPDATE episodio SET capa_url = 'F:\\\\One Piece - Incompleto\\\\one-piece-dublado-ep-129_imagem.jpg' WHERE id = 11315;
