UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-62_imagem.jpg' WHERE id = 12505;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-63_imagem.jpg' WHERE id = 12506;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-64_imagem.jpg' WHERE id = 12507;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-65_imagem.jpg' WHERE id = 12508;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-66_imagem.jpg' WHERE id = 12509;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-67_imagem.jpg' WHERE id = 12510;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-68_imagem.jpg' WHERE id = 12511;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-69_imagem.jpg' WHERE id = 12512;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-7_imagem.jpg' WHERE id = 12513;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-70_imagem.jpg' WHERE id = 12514;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-71_imagem.jpg' WHERE id = 12515;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-72_imagem.jpg' WHERE id = 12516;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-73_imagem.jpg' WHERE id = 12517;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-74_imagem.jpg' WHERE id = 12518;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-75_imagem.jpg' WHERE id = 12519;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-76_imagem.jpg' WHERE id = 12520;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-77_imagem.jpg' WHERE id = 12521;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-78_imagem.jpg' WHERE id = 12522;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-79_imagem.jpg' WHERE id = 12523;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-8_imagem.jpg' WHERE id = 12524;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-80_imagem.jpg' WHERE id = 12525;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-81_imagem.jpg' WHERE id = 12526;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-82_imagem.jpg' WHERE id = 12527;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\1? Temporada\\\\pokemon-dublado-ep-9_imagem.jpg' WHERE id = 12528;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-100_imagem.jpg' WHERE id = 12529;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-101_imagem.jpg' WHERE id = 12530;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-102_imagem.jpg' WHERE id = 12531;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-103_imagem.jpg' WHERE id = 12532;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-104_imagem.jpg' WHERE id = 12533;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-105_imagem.jpg' WHERE id = 12534;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-106_imagem.jpg' WHERE id = 12535;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-107_imagem.jpg' WHERE id = 12536;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-108_imagem.jpg' WHERE id = 12537;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-109_imagem.jpg' WHERE id = 12538;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-110_imagem.jpg' WHERE id = 12539;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-111_imagem.jpg' WHERE id = 12540;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-112_imagem.jpg' WHERE id = 12541;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-113_imagem.jpg' WHERE id = 12542;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-114_imagem.jpg' WHERE id = 12543;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-115_imagem.jpg' WHERE id = 12544;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-116_imagem.jpg' WHERE id = 12545;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-117_imagem.jpg' WHERE id = 12546;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-118_imagem.jpg' WHERE id = 12547;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-83_imagem.jpg' WHERE id = 12548;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-84_imagem.jpg' WHERE id = 12549;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-85_imagem.jpg' WHERE id = 12550;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-86_imagem.jpg' WHERE id = 12551;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-87_imagem.jpg' WHERE id = 12552;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-88_imagem.jpg' WHERE id = 12553;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-89_imagem.jpg' WHERE id = 12554;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-90_imagem.jpg' WHERE id = 12555;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-91_imagem.jpg' WHERE id = 12556;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-92_imagem.jpg' WHERE id = 12557;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-93_imagem.jpg' WHERE id = 12558;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-94_imagem.jpg' WHERE id = 12559;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-95_imagem.jpg' WHERE id = 12560;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-96_imagem.jpg' WHERE id = 12561;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-97_imagem.jpg' WHERE id = 12562;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-98_imagem.jpg' WHERE id = 12563;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\2? Temporada\\\\pokemon-dublado-ep-99_imagem.jpg' WHERE id = 12564;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-119_imagem.jpg' WHERE id = 12565;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-120_imagem.jpg' WHERE id = 12566;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-121_imagem.jpg' WHERE id = 12567;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-122_imagem.jpg' WHERE id = 12568;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-123_imagem.jpg' WHERE id = 12569;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-124_imagem.jpg' WHERE id = 12570;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-125_imagem.jpg' WHERE id = 12571;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-126_imagem.jpg' WHERE id = 12572;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-127_imagem.jpg' WHERE id = 12573;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-128_imagem.jpg' WHERE id = 12574;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-129_imagem.jpg' WHERE id = 12575;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-130_imagem.jpg' WHERE id = 12576;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-131_imagem.jpg' WHERE id = 12577;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-132_imagem.jpg' WHERE id = 12578;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-133_imagem.jpg' WHERE id = 12579;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-134_imagem.jpg' WHERE id = 12580;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-135_imagem.jpg' WHERE id = 12581;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-136_imagem.jpg' WHERE id = 12582;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-137_imagem.jpg' WHERE id = 12583;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-138_imagem.jpg' WHERE id = 12584;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-139_imagem.jpg' WHERE id = 12585;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-140_imagem.jpg' WHERE id = 12586;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-141_imagem.jpg' WHERE id = 12587;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-142_imagem.jpg' WHERE id = 12588;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-143_imagem.jpg' WHERE id = 12589;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-144_imagem.jpg' WHERE id = 12590;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-145_imagem.jpg' WHERE id = 12591;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-146_imagem.jpg' WHERE id = 12592;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-147_imagem.jpg' WHERE id = 12593;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-148_imagem.jpg' WHERE id = 12594;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-149_imagem.jpg' WHERE id = 12595;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-150_imagem.jpg' WHERE id = 12596;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-151_imagem.jpg' WHERE id = 12597;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-152_imagem.jpg' WHERE id = 12598;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-153_imagem.jpg' WHERE id = 12599;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-154_imagem.jpg' WHERE id = 12600;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-155_imagem.jpg' WHERE id = 12601;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-156_imagem.jpg' WHERE id = 12602;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-157_imagem.jpg' WHERE id = 12603;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-158_imagem.jpg' WHERE id = 12604;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\3? Temporada\\\\pokemon-dublado-ep-159_imagem.jpg' WHERE id = 12605;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-160_imagem.jpg' WHERE id = 12606;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-161_imagem.jpg' WHERE id = 12607;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-162_imagem.jpg' WHERE id = 12608;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-163_imagem.jpg' WHERE id = 12609;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-164_imagem.jpg' WHERE id = 12610;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-165_imagem.jpg' WHERE id = 12611;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-166_imagem.jpg' WHERE id = 12612;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-167_imagem.jpg' WHERE id = 12613;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-168_imagem.jpg' WHERE id = 12614;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-169_imagem.jpg' WHERE id = 12615;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-170_imagem.jpg' WHERE id = 12616;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-171_imagem.jpg' WHERE id = 12617;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-172_imagem.jpg' WHERE id = 12618;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-173_imagem.jpg' WHERE id = 12619;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-174_imagem.jpg' WHERE id = 12620;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-175_imagem.jpg' WHERE id = 12621;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-176_imagem.jpg' WHERE id = 12622;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-177_imagem.jpg' WHERE id = 12623;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-178_imagem.jpg' WHERE id = 12624;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-179_imagem.jpg' WHERE id = 12625;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-180_imagem.jpg' WHERE id = 12626;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-181_imagem.jpg' WHERE id = 12627;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-182_imagem.jpg' WHERE id = 12628;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-183_imagem.jpg' WHERE id = 12629;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-184_imagem.jpg' WHERE id = 12630;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-185_imagem.jpg' WHERE id = 12631;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-186_imagem.jpg' WHERE id = 12632;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-187_imagem.jpg' WHERE id = 12633;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-188_imagem.jpg' WHERE id = 12634;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-189_imagem.jpg' WHERE id = 12635;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-190_imagem.jpg' WHERE id = 12636;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-191_imagem.jpg' WHERE id = 12637;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-192_imagem.jpg' WHERE id = 12638;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-193_imagem.jpg' WHERE id = 12639;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-194_imagem.jpg' WHERE id = 12640;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-195_imagem.jpg' WHERE id = 12641;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-196_imagem.jpg' WHERE id = 12642;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-197_imagem.jpg' WHERE id = 12643;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-198_imagem.jpg' WHERE id = 12644;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-199_imagem.jpg' WHERE id = 12645;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-200_imagem.jpg' WHERE id = 12646;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-201_imagem.jpg' WHERE id = 12647;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-202_imagem.jpg' WHERE id = 12648;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-203_imagem.jpg' WHERE id = 12649;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-204_imagem.jpg' WHERE id = 12650;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-205_imagem.jpg' WHERE id = 12651;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-206_imagem.jpg' WHERE id = 12652;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-207_imagem.jpg' WHERE id = 12653;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-208_imagem.jpg' WHERE id = 12654;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-209_imagem.jpg' WHERE id = 12655;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-210_imagem.jpg' WHERE id = 12656;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\4? Temporada\\\\pokemon-dublado-ep-211_imagem.jpg' WHERE id = 12657;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-212_imagem.jpg' WHERE id = 12658;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-213_imagem.jpg' WHERE id = 12659;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-214_imagem.jpg' WHERE id = 12660;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-215_imagem.jpg' WHERE id = 12661;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-216_imagem.jpg' WHERE id = 12662;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-217_imagem.jpg' WHERE id = 12663;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-218_imagem.jpg' WHERE id = 12664;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-219_imagem.jpg' WHERE id = 12665;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-220_imagem.jpg' WHERE id = 12666;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-221_imagem.jpg' WHERE id = 12667;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-222_imagem.jpg' WHERE id = 12668;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-223_imagem.jpg' WHERE id = 12669;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-224_imagem.jpg' WHERE id = 12670;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-225_imagem.jpg' WHERE id = 12671;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-226_imagem.jpg' WHERE id = 12672;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-227_imagem.jpg' WHERE id = 12673;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-228_imagem.jpg' WHERE id = 12674;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-229_imagem.jpg' WHERE id = 12675;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-230_imagem.jpg' WHERE id = 12676;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-231_imagem.jpg' WHERE id = 12677;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-232_imagem.jpg' WHERE id = 12678;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-233_imagem.jpg' WHERE id = 12679;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-234_imagem.jpg' WHERE id = 12680;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-235_imagem.jpg' WHERE id = 12681;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-236_imagem.jpg' WHERE id = 12682;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-237_imagem.jpg' WHERE id = 12683;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-238_imagem.jpg' WHERE id = 12684;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-239_imagem.jpg' WHERE id = 12685;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-240_imagem.jpg' WHERE id = 12686;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-241_imagem.jpg' WHERE id = 12687;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-242_imagem.jpg' WHERE id = 12688;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-243_imagem.jpg' WHERE id = 12689;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-244_imagem.jpg' WHERE id = 12690;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-245_imagem.jpg' WHERE id = 12691;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-246_imagem.jpg' WHERE id = 12692;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-247_imagem.jpg' WHERE id = 12693;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-248_imagem.jpg' WHERE id = 12694;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-249_imagem.jpg' WHERE id = 12695;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-250_imagem.jpg' WHERE id = 12696;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-251_imagem.jpg' WHERE id = 12697;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-252-legendado_imagem.jpg' WHERE id = 12698;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-253_imagem.jpg' WHERE id = 12699;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-254_imagem.jpg' WHERE id = 12700;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-255_imagem.jpg' WHERE id = 12701;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-256_imagem.jpg' WHERE id = 12702;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-257_imagem.jpg' WHERE id = 12703;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-258_imagem.jpg' WHERE id = 12704;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-259_imagem.jpg' WHERE id = 12705;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-260_imagem.jpg' WHERE id = 12706;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-261_imagem.jpg' WHERE id = 12707;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-262_imagem.jpg' WHERE id = 12708;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-263_imagem.jpg' WHERE id = 12709;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-264_imagem.jpg' WHERE id = 12710;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-265_imagem.jpg' WHERE id = 12711;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-266_imagem.jpg' WHERE id = 12712;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-267_imagem.jpg' WHERE id = 12713;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-268_imagem.jpg' WHERE id = 12714;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-269_imagem.jpg' WHERE id = 12715;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-270_imagem.jpg' WHERE id = 12716;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-271_imagem.jpg' WHERE id = 12717;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-272_imagem.jpg' WHERE id = 12718;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-273_imagem.jpg' WHERE id = 12719;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-274_imagem.jpg' WHERE id = 12720;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-275_imagem.jpg' WHERE id = 12721;
UPDATE episodio SET capa_url = 'F:\\\\Pok?mon - Incompleto\\\\5? Temporada\\\\pokemon-dublado-ep-276-final_imagem.jpg' WHERE id = 12722;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\01_O Fim do Come?o e o Come?o do Fim_imagem.jpg' WHERE id = 12723;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\02_Reuni?o com a Bruxa_imagem.jpg' WHERE id = 12724;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\03_Come?ando a Vida do Zero em Outro Mundo_imagem.jpg' WHERE id = 12725;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\04_A Fam?lia Feliz da Mans?o Roswaal_imagem.jpg' WHERE id = 12726;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\05_A Manh? da Nossa Promessa Ainda Est? Longe_imagem.jpg' WHERE id = 12727;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\06_O Som das Correntes_imagem.jpg' WHERE id = 12728;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\07_O Recome?o de Natsuki Subaru_imagem.jpg' WHERE id = 12729;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\08_Chorei, Chorei At? Ficar sem Ar, Ent?o Parei de Chorar_imagem.jpg' WHERE id = 12730;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\09_O Significado da Coragem_imagem.jpg' WHERE id = 12731;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\10_M?todos Fan?ticos Como o de Um Dem?nio_imagem.jpg' WHERE id = 12732;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\11_Rem_imagem.jpg' WHERE id = 12733;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\12_Retorno ? Capital_imagem.jpg' WHERE id = 12734;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\13_Cavaleiro Autointitulado Natsuki Subaru_imagem.jpg' WHERE id = 12735;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\14_A Doen?a Chamada Desespero_imagem.jpg' WHERE id = 12736;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\15_A Face da Loucura_imagem.jpg' WHERE id = 12737;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\16_A Gan?ncia de Um Porco_imagem.jpg' WHERE id = 12738;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\17_Desgra?a ao Extremo_imagem.jpg' WHERE id = 12739;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\18_Do Zero_imagem.jpg' WHERE id = 12740;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\19_Batalha Contra a Baleia Branca_imagem.jpg' WHERE id = 12741;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\20_Wilhelm van Astrea_imagem.jpg' WHERE id = 12742;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\21_Uma Aposta Que Desafia o Desespero_imagem.jpg' WHERE id = 12743;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\22_Um Instante de Pregui?a_imagem.jpg' WHERE id = 12744;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\23_Abomin?vel Pregui?a_imagem.jpg' WHERE id = 12745;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\24_O Cavaleiro Autoproclamado e o Cavaleiro da Piedade_imagem.jpg' WHERE id = 12746;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\1? Temporada\\\\25_E ? Sobre Isso Que Essa Hist?ria se Trata_imagem.jpg' WHERE id = 12747;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\01_A promessa de cada um_imagem.jpg' WHERE id = 12748;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\02_O pr?ximo local_imagem.jpg' WHERE id = 12749;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\03_A t?o esperada reuni?o_imagem.jpg' WHERE id = 12750;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\04_Pai e filho_imagem.jpg' WHERE id = 12751;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\05_Um passo ? frente_imagem.jpg' WHERE id = 12752;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\06_O Envangelho da Garota_imagem.jpg' WHERE id = 12753;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\07_Amigo_imagem.jpg' WHERE id = 12754;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\08_O Valor da Vida_imagem.jpg' WHERE id = 12755;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\09_Amo Amo Amo Amo Amo Amo Voc?_imagem.jpg' WHERE id = 12756;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\10_Eu conhe?o o inferno_imagem.jpg' WHERE id = 12757;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\11_O Sabor da Morte_imagem.jpg' WHERE id = 12758;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\12_A Festa do Ch? das Bruxas_imagem.jpg' WHERE id = 12759;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 1\\\\13_O som que me d? vontade de chorar_imagem.jpg' WHERE id = 12760;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\01_Aposta Direta_imagem.jpg' WHERE id = 12761;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\02_Otto Suwen-Raz?o para Acreditar_imagem.jpg' WHERE id = 12762;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\03_N?o D? Pra Levantar uma Pedra Quayne Sozinho_imagem.jpg' WHERE id = 12763;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\04_Jornada Pelas Mem?rias_imagem.jpg' WHERE id = 12764;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\05_O Dia Que Beteugeuse Riu_imagem.jpg' WHERE id = 12765;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\06_O Gelo Perene da Floresta Elior_imagem.jpg' WHERE id = 12766;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\07_O Come?o do Santu?rio e o Come?o do Colapso_imagem.jpg' WHERE id = 12767;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\08_A Reuni?o dos Rugidos_imagem.jpg' WHERE id = 12768;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\09_A Felicidade Refletida na Superf?cie da ?gua_imagem.jpg' WHERE id = 12769;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\10_Ame At? Meu Sangue e Entranhas_imagem.jpg' WHERE id = 12770;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\11_Me Escolha_imagem.jpg' WHERE id = 12771;
UPDATE episodio SET capa_url = 'F:\\\\Re Zero\\\\2? Temporada\\\\Parte 2\\\\12_Um Passo Imprudente Sob a Lua_imagem.jpg' WHERE id = 12772;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\01_Ragnarok_imagem.jpg' WHERE id = 12773;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\02_Advers?rio digno_imagem.jpg' WHERE id = 12774;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\03_Golpe mortal_imagem.jpg' WHERE id = 12775;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\04_Alegria_imagem.jpg' WHERE id = 12776;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\05_ARQUIVO N? 00000000001_imagem.jpg' WHERE id = 12777;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\06_C?pia_imagem.jpg' WHERE id = 12778;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\07_Expulso do para?so_imagem.jpg' WHERE id = 12779;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\08_Gra?a abundante_imagem.jpg' WHERE id = 12780;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\09_Tirano do oceano_imagem.jpg' WHERE id = 12781;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\10_Maior perdedor_imagem.jpg' WHERE id = 12782;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\11_A andorinha contempla o abismo_imagem.jpg' WHERE id = 12783;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\1? Temporada\\\\12_E Ragnarok continua - Final_imagem.jpg' WHERE id = 12784;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 1\\\\01_O bem contra o mal_imagem.jpg' WHERE id = 12785;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 1\\\\02_O indom?vel Deus da Guerra_imagem.jpg' WHERE id = 12786;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 1\\\\03_O nascimento de um monstro_imagem.jpg' WHERE id = 12787;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 1\\\\04_O trabalho final_imagem.jpg' WHERE id = 12788;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 1\\\\05_R?quiem_imagem.jpg' WHERE id = 12789;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 1\\\\06_Motiva??es incompat?veis_imagem.jpg' WHERE id = 12790;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 1\\\\07_Os Cem Selos_imagem.jpg' WHERE id = 12791;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 1\\\\08_O topo dos 1.116 deuses_imagem.jpg' WHERE id = 12792;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 1\\\\09_Reverbera??o_imagem.jpg' WHERE id = 12793;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 1\\\\10_No limite_imagem.jpg' WHERE id = 12794;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 2\\\\shuumatsu-no-valkyrie-ii-part-2-dublado-ep-1_imagem.jpg' WHERE id = 12795;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 2\\\\shuumatsu-no-valkyrie-ii-part-2-dublado-ep-2_imagem.jpg' WHERE id = 12796;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 2\\\\shuumatsu-no-valkyrie-ii-part-2-dublado-ep-3_imagem.jpg' WHERE id = 12797;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 2\\\\shuumatsu-no-valkyrie-ii-part-2-dublado-ep-4_imagem.jpg' WHERE id = 12798;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\2? Temporada\\\\Parte 2\\\\shuumatsu-no-valkyrie-ii-part-2-dublado-ep-5-final_imagem.jpg' WHERE id = 12799;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 01 [1080p NF WEBRip HEVC AAC][MultiSub][F03B9042].mkv' WHERE id = 12800;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 02 [1080p NF WEBRip HEVC AAC][MultiSub][304338DA].mkv' WHERE id = 12801;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 03 [1080p NF WEBRip HEVC AAC][MultiSub][DC874BD0].mkv' WHERE id = 12802;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 04 [1080p NF WEBRip HEVC AAC][MultiSub][8540D853].mkv' WHERE id = 12803;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 05 [1080p NF WEBRip HEVC AAC][MultiSub][F96F6888].mkv' WHERE id = 12804;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 06 [1080p NF WEBRip HEVC AAC][MultiSub][EC88A5A6].mkv' WHERE id = 12805;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 07 [1080p NF WEBRip HEVC AAC][MultiSub][3EABB6D5].mkv' WHERE id = 12806;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 08 [1080p NF WEBRip HEVC AAC][MultiSub][39FDB848].mkv' WHERE id = 12807;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 09 [1080p NF WEBRip HEVC AAC][MultiSub][F7D4AC98].mkv' WHERE id = 12808;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 10 [1080p NF WEBRip HEVC AAC][MultiSub][0C72EC5F].mkv' WHERE id = 12809;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 11 [1080p NF WEBRip HEVC AAC][MultiSub][A468387B].mkv' WHERE id = 12810;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 12 [1080p NF WEBRip HEVC AAC][MultiSub][FA07676F].mkv' WHERE id = 12811;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 13 [1080p NF WEBRip HEVC AAC][MultiSub][2E8D3053].mkv' WHERE id = 12812;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 14 [1080p NF WEBRip HEVC AAC][MultiSub][69090D8F].mkv' WHERE id = 12813;
UPDATE episodio SET capa_url = 'F:\\\\Record of Ragnarok - Incompleto\\\\3? Temporada - Legendado\\\\[Erai-raws] Shuumatsu no Walkure III - 15 [1080p NF WEBRip HEVC AAC][MultiSub][4B6F1328].mkv' WHERE id = 12814;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\01_Como uma Garota Medrosa se Transforma em Guerreira_imagem.jpg' WHERE id = 12815;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\02_A Casa da Adivinha ? um Ninho de Monstros_imagem.jpg' WHERE id = 12816;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\03_Salvem as Garotas Apaixonadas_imagem.jpg' WHERE id = 12817;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\04_Quer Ficar Magra_imagem.jpg' WHERE id = 12818;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\05_O Misterioso Perfume dos Coelhos_imagem.jpg' WHERE id = 12819;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\06_Serena ? um Bom Cupido_imagem.jpg' WHERE id = 12820;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\07_O Longo e Sinuoso Caminho para o Estrelato_imagem.jpg' WHERE id = 12821;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\08_Terror no Semin?rio Lava-Cuca_imagem.jpg' WHERE id = 12822;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\09_O Desastre de Serena? Cuidado com o Rel?gio!_imagem.jpg' WHERE id = 12823;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\10_O ?nibus Fantasma Sailor Mars, a Guerreira de Fogo_imagem.jpg' WHERE id = 12824;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\11_O Parque de Divers?es_imagem.jpg' WHERE id = 12825;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\12_Quero ter Namorado - A Cilada do Cruzeiro de Luxo_imagem.jpg' WHERE id = 12826;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\13_Garotas, Vamos nos Unir Contra Jedite_imagem.jpg' WHERE id = 12827;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\14_Chegou um Poderoso Inimigo Nephryte_imagem.jpg' WHERE id = 12828;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\15_Serena Preocupa-se Com o Primeiro Encontro de Rei_imagem.jpg' WHERE id = 12829;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\16_O Sonho das Garotas Serena Torna-se Noiva_imagem.jpg' WHERE id = 12830;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\17_Serena Modelo As Malignas Tornam-se Fot?grafas_imagem.jpg' WHERE id = 12831;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\18_O Amor de Sammy A Boneca Misteriosa_imagem.jpg' WHERE id = 12832;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\19_Surpresa! Uma Carta de Tuxedo Mask Para Serena_imagem.jpg' WHERE id = 12833;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\20_O Ver?o, o Mar, Garotas e Tamb?m Fantasmas_imagem.jpg' WHERE id = 12834;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\21_Proteja os Sonhos das Crian?as Amizade Atrav?s do Anime_imagem.jpg' WHERE id = 12835;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\22_Um Romance Sob a Lua - Primeiro Beijo de Serena_imagem.jpg' WHERE id = 12836;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\23_Estrela Cadente - Proteja o Primeiro Amor de Molly_imagem.jpg' WHERE id = 12837;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\24_As L?grimas de Molly Nepryte Morre Por Amor_imagem.jpg' WHERE id = 12838;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\25_A Poderosa Sailor J?piter Est? Apaixonada_imagem.jpg' WHERE id = 12839;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\26_A Amizade de Serena Devolve a Felicidade ? Molly_imagem.jpg' WHERE id = 12840;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\27_Richard se apaixona por Amy_imagem.jpg' WHERE id = 12841;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\28_Serena e Darien em um Retrato de Amor_imagem.jpg' WHERE id = 12842;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\29_Um Estranho Tri?ngulo Amoroso. Ou Ser? um Quadrado_imagem.jpg' WHERE id = 12843;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\30_O Av? de Rei Ficou Louco_imagem.jpg' WHERE id = 12844;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\31_Amada e Perseguida O Pior Dia de Lua_imagem.jpg' WHERE id = 12845;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\32_Kelvin Se Torna Her?i e Salva Molly_imagem.jpg' WHERE id = 12846;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\33_A ?ltima Guerreira - Sailor V?nus Apareceu_imagem.jpg' WHERE id = 12847;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\34_Resplandecente Cristal de Prata - A Princesa Moon vem a?_imagem.jpg' WHERE id = 12848;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\35_As Lembran?as de Serena e Darien_imagem.jpg' WHERE id = 12849;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\36_A Confus?o de Serena - Tuxedo Mask ? Ruim_imagem.jpg' WHERE id = 12850;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\37_Serena Prepara-se Para Ser Princesa_imagem.jpg' WHERE id = 12851;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\38_A Neve, as Montanhas, Amizade e Monstros_imagem.jpg' WHERE id = 12852;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\39_Lita ? a Rainha de Patina??o no Gelo_imagem.jpg' WHERE id = 12853;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\40_O Esp?rito Maligno do Lago Une a Fam?lia_imagem.jpg' WHERE id = 12854;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\41_Amy Se Apaixona e Luta Contra Darien_imagem.jpg' WHERE id = 12855;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\42_O Passado de Sailor V?nus? O Tr?gico Amor de Mina_imagem.jpg' WHERE id = 12856;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\43_Serena Fica Sozinha? Sailor Moon Contra as Outras Guerreiras_imagem.jpg' WHERE id = 12857;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\44_O Despertar de Serena - Uma Mensagem do Grandioso Passado_imagem.jpg' WHERE id = 12858;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\45_As Guerreiras Morrem - O Tr?gico Combate Final_imagem.jpg' WHERE id = 12859;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\1? Temporada\\\\46_O Sonho Eterno de Serena - Uma Nova Vida_imagem.jpg' WHERE id = 12860;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\01_O Retorno de Sailor Moon - Surgem os Alien?genas Misteriosos_imagem.jpg' WHERE id = 12861;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\02_Pelo Amor e Justi?a! As Sailor Guerreiras Voltam a Se Reunir_imagem.jpg' WHERE id = 12862;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\03_O Cavaleiro da Lua_imagem.jpg' WHERE id = 12863;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\04_Serena Fica Desconsolada - A Tiara Lunar Parou de Funcionar_imagem.jpg' WHERE id = 12864;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\05_A Transforma??o de Serena_imagem.jpg' WHERE id = 12865;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\06_Crise no Jardim de Inf?ncia_imagem.jpg' WHERE id = 12866;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\07_Os Problemas de Ser uma Bab?_imagem.jpg' WHERE id = 12867;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\08_A Can??o de Rei_imagem.jpg' WHERE id = 12868;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\09_Amar ?..._imagem.jpg' WHERE id = 12869;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\10_A Opera??o Branca de Neve de Anne_imagem.jpg' WHERE id = 12870;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\11_Perigo Depois das Aulas - Usagi ? o Alvo_imagem.jpg' WHERE id = 12871;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\12_O Amor Perdido - A F?ria da ?rvore_imagem.jpg' WHERE id = 12872;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\13_O Segredo da ?rvore_imagem.jpg' WHERE id = 12873;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\14_Anjo ou Dem?nio A Menina Misteriosa Que Caiu do C?u_imagem.jpg' WHERE id = 12874;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\15_Serena Devastada - Darien Declara Separa??o_imagem.jpg' WHERE id = 12875;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\16_A Amizade da Guerreira - Adeus, Ami_imagem.jpg' WHERE id = 12876;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\17_Jovens, Fortes e Belas - A Nova T?cnica Especial de Rei_imagem.jpg' WHERE id = 12877;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\18_Em Busca do Cristal de Prata - O Segredo de Chibi-Usa_imagem.jpg' WHERE id = 12878;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\19_Briga em Defesa do Amor - O Conflito de Minako e Makoto_imagem.jpg' WHERE id = 12879;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\20_O Sentimento Maternal de Serena - O Tri?ngulo Amoroso do Curry_imagem.jpg' WHERE id = 12880;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\21_F?rias na Praia - Um Descanso Para as Sailors_imagem.jpg' WHERE id = 12881;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\22_Temos Que Proteger Rini - A Grande Batalha das Dez Guerreiras_imagem.jpg' WHERE id = 12882;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\23_Pesadelo - O Despertar de Sailor Moon_imagem.jpg' WHERE id = 12883;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\24_Uma Luta Pelo Amor - Sailor Marte VS Cooan_imagem.jpg' WHERE id = 12884;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\25_Pela Amizade! Ami VS Beruche_imagem.jpg' WHERE id = 12885;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\26_Rubeus Sem Cora??o! A Tristeza das Quatro Irm?s_imagem.jpg' WHERE id = 12886;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\27_U.F.O.? O Rapto das Sailors_imagem.jpg' WHERE id = 12887;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\28_Derrote Rubeus - A Batalha Decisiva no Espa?o_imagem.jpg' WHERE id = 12888;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\29_Uma Nova Sailor - Chegou Sailor Plut?o_imagem.jpg' WHERE id = 12889;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\30_A Magica da Escurid?o - A Invas?o de Esmeralda_imagem.jpg' WHERE id = 12890;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\31_Sentimentos Compartilhados - Usagi e Mamoru se Apaixonam Novamente_imagem.jpg' WHERE id = 12891;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\32_Os Cuidados Terr?veis de Mina_imagem.jpg' WHERE id = 12892;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\33_A Aventura de Artemis - O Reino Animal do Monstro_imagem.jpg' WHERE id = 12893;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\34_A Solid?o de Ami_imagem.jpg' WHERE id = 12894;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\35_O Port?o Negro Est? Pronto_imagem.jpg' WHERE id = 12895;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\36_Viagem Para o Futuro - A Batalha no Corredor do Tempo-Espa?o_imagem.jpg' WHERE id = 12896;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\37_A Hist?ria de Black Moon - A Ambi??o Sombria do Pr?ncipe Diamonde_imagem.jpg' WHERE id = 12897;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\38_O Segredo da Pequena Dama_imagem.jpg' WHERE id = 12898;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\39_A Rainha das Trevas - O Nascimento de Black Lady_imagem.jpg' WHERE id = 12899;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\40_Saphiro Morre - A Armadilha do Grande S?bio_imagem.jpg' WHERE id = 12900;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\41_Acreditando no Amor e no Futuro - A Decis?o de Usagi_imagem.jpg' WHERE id = 12901;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\42_A Batalha Final entre a Luz e a Escurid?o - O Juramento de Amor para o Futuro_imagem.jpg' WHERE id = 12902;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\2? Temporada\\\\43_A Resolu??o de Serena e as Garotas - Pr?logo Para uma Nova Batalha_imagem.jpg' WHERE id = 12903;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\01_Come?a uma Nova Batalha_imagem.jpg' WHERE id = 12904;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\02_A Nova Transforma??o de Serena_imagem.jpg' WHERE id = 12905;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\03_Ele ou Ela_imagem.jpg' WHERE id = 12906;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\04_A Eleg?ncia de Michiru_imagem.jpg' WHERE id = 12907;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\05_O Primeiro Beijo_imagem.jpg' WHERE id = 12908;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\06_Quando Se Sofre Por Amor, Fale Com Sailor Moon_imagem.jpg' WHERE id = 12909;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\07_O Inimigo de Lita_imagem.jpg' WHERE id = 12910;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\08_Labirinto aqu?tico, Ami ? atacada!_imagem.jpg' WHERE id = 12911;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\09_A Uni?o Entre Sailor Moon e Sailor Urano_imagem.jpg' WHERE id = 12912;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\10_O Amor Frustrado Entre Nicolas e Rei_imagem.jpg' WHERE id = 12913;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\11_Mina Renuncia_imagem.jpg' WHERE id = 12914;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\12_O Sapatinho de Cristal (parte 1)_imagem.jpg' WHERE id = 12915;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\13_O Sapatinho de Cristal (parte 2)_imagem.jpg' WHERE id = 12916;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\14_Chegou a Pequena Sailor Chibi Moon_imagem.jpg' WHERE id = 12917;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\15_As Atividades de Sailor Chibi Moon_imagem.jpg' WHERE id = 12918;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\16_O Caminho Errado de Lita_imagem.jpg' WHERE id = 12919;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\17_Unidos Pelo Destino_imagem.jpg' WHERE id = 12920;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\18_O Primeiro Amor de Rini_imagem.jpg' WHERE id = 12921;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\19_Serena Dan?a_imagem.jpg' WHERE id = 12922;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\20_A Revela??o_imagem.jpg' WHERE id = 12923;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\21_Aparecem os Talism?s_imagem.jpg' WHERE id = 12924;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\22_A Ta?a Lunar_imagem.jpg' WHERE id = 12925;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\23_O Caos Entre o Bem e o Mal_imagem.jpg' WHERE id = 12926;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\24_O Segredo de Hotaru_imagem.jpg' WHERE id = 12927;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\25_A Ang?stia de Mimete_imagem.jpg' WHERE id = 12928;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\26_A Sombra do Sil?ncio_imagem.jpg' WHERE id = 12929;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\27_A Amizade de Hotaru_imagem.jpg' WHERE id = 12930;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\28_A Ajuda de Serena_imagem.jpg' WHERE id = 12931;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\29_Uma Luta em Outra Dimens?o_imagem.jpg' WHERE id = 12932;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\30_O Despertar do Enviado do Sil?ncio_imagem.jpg' WHERE id = 12933;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\31_O mist?rio do col?gio Mugen_imagem.jpg' WHERE id = 12934;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\32_Tellu, a Terceira Bruxa_imagem.jpg' WHERE id = 12935;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\33_Ami, a Menina Mais Am?vel das Sailors_imagem.jpg' WHERE id = 12936;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\34_O Despertar do Enviado do Mal_imagem.jpg' WHERE id = 12937;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\35_As Oito Sailors Lutam Desesperadamente_imagem.jpg' WHERE id = 12938;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\36_Sailor Saturno e o Enviado do Bem_imagem.jpg' WHERE id = 12939;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\37_O Come?o de uma Nova Vida_imagem.jpg' WHERE id = 12940;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\3? Temporada\\\\38_A For?a Est? Dentro do Cora??o Puro_imagem.jpg' WHERE id = 12941;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\01_Uma Visita Inesperada_imagem.jpg' WHERE id = 12942;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\02_O Poder de P?gasus_imagem.jpg' WHERE id = 12943;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\03_Temos Que Proteger Mam?e Ikuko_imagem.jpg' WHERE id = 12944;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\04_O Plano do Trio Amazonas Ikuko_imagem.jpg' WHERE id = 12945;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\05_O Amor de Serena e Darien_imagem.jpg' WHERE id = 12946;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\06_Artemis Engana a Lua_imagem.jpg' WHERE id = 12947;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\07_A Amizade de Lita_imagem.jpg' WHERE id = 12948;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\08_Rini e o P?gasus_imagem.jpg' WHERE id = 12949;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\09_Os Ci?mes de Serena_imagem.jpg' WHERE id = 12950;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\10_O Convite de uma Linda Fada_imagem.jpg' WHERE id = 12951;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\11_O Autom?vel dos Meus Sonhos_imagem.jpg' WHERE id = 12952;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\12_A Ang?stia de Miharu_imagem.jpg' WHERE id = 12953;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\13_A Ang?stia de Miharu_imagem.jpg' WHERE id = 12954;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\14_Os Dois Amores de Mina_imagem.jpg' WHERE id = 12955;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\15_Um Menu de Amor Para Voc?_imagem.jpg' WHERE id = 12956;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\16_As Transforma??es das Sailors_imagem.jpg' WHERE id = 12957;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\17_Um Ver?o Inesquec?vel[_imagem.jpg' WHERE id = 12958;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\18_O Baile de Serena_imagem.jpg' WHERE id = 12959;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\19_A Princesa Rubina Visita um Festival de Ver?o_imagem.jpg' WHERE id = 12960;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\20_A Inoc?ncia de Lita_imagem.jpg' WHERE id = 12961;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\21_Uma Sombra Maligna Amea?a o Trio Amazonas_imagem.jpg' WHERE id = 12962;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\22_A ?ltima Atua??o do Trio Amazonas_imagem.jpg' WHERE id = 12963;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\23_O Quarteto das Amazonas_imagem.jpg' WHERE id = 12964;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\24_O Novo Poder de Ami_imagem.jpg' WHERE id = 12965;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\25_O Poder Especial de Sailor Marte_imagem.jpg' WHERE id = 12966;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\26_A Armadilha de Para-Para_imagem.jpg' WHERE id = 12967;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\27_A Briga de Mina e Lita_imagem.jpg' WHERE id = 12968;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\28_Um Salto Sem Temor_imagem.jpg' WHERE id = 12969;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\29_Um Salto Sem Temor_imagem.jpg' WHERE id = 12970;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\30_P?gasus Desapareceu_imagem.jpg' WHERE id = 12971;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\31_O Segredo de P?gasus_imagem.jpg' WHERE id = 12972;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\32_A Raps?dia de Amor de Rini_imagem.jpg' WHERE id = 12973;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\33_A Confus?o do Quarteto Amazonas_imagem.jpg' WHERE id = 12974;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\34_A Rainha das Trevas_imagem.jpg' WHERE id = 12975;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\35_O Circo Lua da Morte_imagem.jpg' WHERE id = 12976;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\36_Sailor Chibi Moon, Capturada_imagem.jpg' WHERE id = 12977;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\37_A Magia de Neherenia_imagem.jpg' WHERE id = 12978;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\38_O Poder de um Lindo Sonho_imagem.jpg' WHERE id = 12979;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\4? Temporada\\\\39_Sempre Existir?o Sonhos Lindos_imagem.jpg' WHERE id = 12980;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\01_A Rainha das Trevas Revive_imagem.jpg' WHERE id = 12981;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\02_O Despertar de Saturno! A Uni?o das Dez Sailor Guerreiras_imagem.jpg' WHERE id = 12982;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\03_A Maldi??o do Espelho Darien ? Preso no Pesadelo_imagem.jpg' WHERE id = 12983;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\04_A Noite do Destino! A Prova??o de uma Guerreira_imagem.jpg' WHERE id = 12984;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\05_Por Amor - Uma Luta Intermin?vel no Mundo Sombrio_imagem.jpg' WHERE id = 12985;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\06_O Poder Lunar do Amor - O Fim do Pesadelo_imagem.jpg' WHERE id = 12986;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\07_Encontros e Despedidas - O Destino das Estrelas_imagem.jpg' WHERE id = 12987;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\08_Os Three Lights V?o Estudar na Nossa Escola_imagem.jpg' WHERE id = 12988;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\09_A Ambi??o de Mina_imagem.jpg' WHERE id = 12989;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\10_A Verdadeira Identidade de Sailor Fighter_imagem.jpg' WHERE id = 12990;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\11_A Transforma??o de Taiki_imagem.jpg' WHERE id = 12991;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\12_A Verdadeira Personalidade de Yaten_imagem.jpg' WHERE id = 12992;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\13_Sailor Versus Sailor_imagem.jpg' WHERE id = 12993;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\14_Haruka e Michiru_imagem.jpg' WHERE id = 12994;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\15_Serena e Seiya T?m um Encontro Emocionante_imagem.jpg' WHERE id = 12995;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\16_Uma Estranha Visita_imagem.jpg' WHERE id = 12996;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\17_O Acampamento do Terror_imagem.jpg' WHERE id = 12997;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\18_Serena em Apuros_imagem.jpg' WHERE id = 12998;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\19_N?o Perca a Esperan?as_imagem.jpg' WHERE id = 12999;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\20_O Segredo de Chibi-Chibi_imagem.jpg' WHERE id = 13000;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\21_A Transforma??o de Chibi-Chibi_imagem.jpg' WHERE id = 13001;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\22_Um Convite ao Terror_imagem.jpg' WHERE id = 13002;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\23_Um Conflito Entre as Sailors_imagem.jpg' WHERE id = 13003;
UPDATE episodio SET capa_url = 'F:\\\\Sailor Moon\\\\5? Temporada\\\\24_O Passado de Seiya, Taiki e Yaten_imagem.jpg' WHERE id = 13004;
