UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\06_Desligamento_imagem.jpg' WHERE id = 8472;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\07_Tenta??o_imagem.jpg' WHERE id = 8473;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\08_Linha de Vista_imagem.jpg' WHERE id = 8474;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\09_Contato_imagem.jpg' WHERE id = 8475;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\10_D?vida_imagem.jpg' WHERE id = 8476;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\11_Colis?o_imagem.jpg' WHERE id = 8477;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\12_Amor_imagem.jpg' WHERE id = 8478;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\13_Confiss?o_imagem.jpg' WHERE id = 8479;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\14_Amigos_imagem.jpg' WHERE id = 8480;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\15_Aposta_imagem.jpg' WHERE id = 8481;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\16_Decis?o_imagem.jpg' WHERE id = 8482;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\17_Execu??o_imagem.jpg' WHERE id = 8483;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\18_Companheiro_imagem.jpg' WHERE id = 8484;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\19_Matsuda_imagem.jpg' WHERE id = 8485;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\20_Sucessor_imagem.jpg' WHERE id = 8486;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\21_Atividade_imagem.jpg' WHERE id = 8487;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\22_Dire??o_imagem.jpg' WHERE id = 8488;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\23_Loucura_imagem.jpg' WHERE id = 8489;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\24_Ressurrei??o_imagem.jpg' WHERE id = 8490;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\25_Sil?ncio_imagem.jpg' WHERE id = 8491;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\26_Renova??o_imagem.jpg' WHERE id = 8492;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\27_Abdu??o_imagem.jpg' WHERE id = 8493;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\28_Impaci?ncia_imagem.jpg' WHERE id = 8494;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\29_Pai_imagem.jpg' WHERE id = 8495;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\30_Justi?a_imagem.jpg' WHERE id = 8496;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\31_Transfer?ncia_imagem.jpg' WHERE id = 8497;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\32_Sele??o_imagem.jpg' WHERE id = 8498;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\33_Desd?m_imagem.jpg' WHERE id = 8499;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\34_Espreita_imagem.jpg' WHERE id = 8500;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\35_Sanguinol?ncia_imagem.jpg' WHERE id = 8501;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\36_28-01_imagem.jpg' WHERE id = 8502;
UPDATE episodio SET capa_url = 'F:\\\\Death Note\\\\37_Novo Mundo_imagem.jpg' WHERE id = 8503;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\01_Crueldade_imagem.jpg' WHERE id = 8504;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\02_Sakonji Urokodaki, o treinador_imagem.jpg' WHERE id = 8505;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\03_Sabito e Makomo_imagem.jpg' WHERE id = 8506;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\04_A sele??o final_imagem.jpg' WHERE id = 8507;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\05_Meu pr?prio a?o_imagem.jpg' WHERE id = 8508;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\06_O espadachim que acompanhada um oni_imagem.jpg' WHERE id = 8509;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\07_Muzan Kibutsuji_imagem.jpg' WHERE id = 8510;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\08_O cheiro sedutor de sangue_imagem.jpg' WHERE id = 8511;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\09_O Oni da Temari e o Oni da Flecha_imagem.jpg' WHERE id = 8512;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\10_Juntos para sempre_imagem.jpg' WHERE id = 8513;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\11_A mans?o Tsuzumi_imagem.jpg' WHERE id = 8514;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\12_O javali mostra as presas, enquanto Zenitsu dorme_imagem.jpg' WHERE id = 8515;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\13_Algo mais importante que a vida_imagem.jpg' WHERE id = 8516;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\14_A casa do bras?o da glic?nia_imagem.jpg' WHERE id = 8517;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\15_Monte Natagumo_imagem.jpg' WHERE id = 8518;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\16_Deixar outra pessoa ir na sua frente_imagem.jpg' WHERE id = 8519;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\17_Seja mestre de uma ?nica coisa_imagem.jpg' WHERE id = 8520;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\18_Um la?o falso_imagem.jpg' WHERE id = 8521;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\19_Hinokami_imagem.jpg' WHERE id = 8522;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\20_Fam?lia de faz de conta_imagem.jpg' WHERE id = 8523;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\21_Contra as Regras do Esquadr?o_imagem.jpg' WHERE id = 8524;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\22_O senhor da mans?o_imagem.jpg' WHERE id = 8525;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\23_Reuni?o dos Hashiras_imagem.jpg' WHERE id = 8526;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\24_Treino de Reabilita??o_imagem.jpg' WHERE id = 8527;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\25_Kanao Tsuyuri, a Tsuguko_imagem.jpg' WHERE id = 8528;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\1? Temporada\\\\26_Uma nova miss?o_imagem.jpg' WHERE id = 8529;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 1\\\\01_O Pilar das Chamas, Kyojuro Rengoku_imagem.jpg' WHERE id = 8530;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 1\\\\02_Sono Profundo_imagem.jpg' WHERE id = 8531;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 1\\\\03_Se fosse verdade_imagem.jpg' WHERE id = 8532;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 1\\\\04_Insulto_imagem.jpg' WHERE id = 8533;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 1\\\\05_Siga em frente!_imagem.jpg' WHERE id = 8534;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 1\\\\06_Akaza_imagem.jpg' WHERE id = 8535;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 1\\\\07_Deixe seu cora??o em chamas_imagem.jpg' WHERE id = 8536;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\01_Tengen Uzui, o Pilar do Som_imagem.jpg' WHERE id = 8537;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\02_Invas?o do Distrito do Entretenimento_imagem.jpg' WHERE id = 8538;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\03_Quem_imagem.jpg' WHERE id = 8539;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\04_Esta noite_imagem.jpg' WHERE id = 8540;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\05_Vamos bem extravagantes!_imagem.jpg' WHERE id = 8541;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\06_Mem?rias Sobrepostas_imagem.jpg' WHERE id = 8542;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\07_Transforma??o_imagem.jpg' WHERE id = 8543;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\08_Reuni?o_imagem.jpg' WHERE id = 8544;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\09_Quando eu Derrotar os Onis Superiores_imagem.jpg' WHERE id = 8545;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\10_Jamais vou desistir_imagem.jpg' WHERE id = 8546;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\2? Temporada\\\\Parte 2\\\\11_N?o importa quantas vidas_imagem.jpg' WHERE id = 8547;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\01_Sonho de Algu?m_imagem.jpg' WHERE id = 8548;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\02_Yoriichi Tipo Zero_imagem.jpg' WHERE id = 8549;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\03_Uma Espada de mais de 300 Anos_imagem.jpg' WHERE id = 8550;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\04_Obrigado, Tokito_imagem.jpg' WHERE id = 8551;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\05_Espada Vermelha Brilhante_imagem.jpg' WHERE id = 8552;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\06_N?o vai se tornar um Hashira_imagem.jpg' WHERE id = 8553;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\07_Vil?o Terr?vel_imagem.jpg' WHERE id = 8554;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\08_O Mu de Muichiro_imagem.jpg' WHERE id = 8555;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\09_O Pilar da N?voa, Muichiro Tokito_imagem.jpg' WHERE id = 8556;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\10_A Pilar do Amor, Mitsuri Kanroji_imagem.jpg' WHERE id = 8557;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\3? Temporada\\\\11_La?os Conectados - Amanhecer e a Primeira Luz_imagem.jpg' WHERE id = 8558;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\4? Temporada\\\\01_Para derrotar Muzan Kibutsuji.mkv' WHERE id = 8559;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\4? Temporada\\\\02_A dor do Pilar da ?gua, Giyu Tomioka.mkv' WHERE id = 8560;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\4? Temporada\\\\03_Tanjiro Completamente Recuperado!! Ele se junta ao Treinamento Hashira.mkv' WHERE id = 8561;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\4? Temporada\\\\04_Para colocar um sorriso no seu rosto.mkv' WHERE id = 8562;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\4? Temporada\\\\05_Eu at? comi dem?nios....mkv' WHERE id = 8563;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\4? Temporada\\\\06_O mais forte do Esquadr?o de Exterminadores.mkv' WHERE id = 8564;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\4? Temporada\\\\07_Gyomei Himejima, o Pilar das Rochas.mkv' WHERE id = 8565;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\4? Temporada\\\\08_Os Hashira se Unem.mkv' WHERE id = 8566;
UPDATE episodio SET capa_url = 'F:\\\\Demon Slayer - Legendado\\\\Filmes\\\\Demon.Slayer.Kimetsu.No.Yaiba.The.Movie.Infinity.Castle.2025.V2.1080p.TELESYNC.MULTi.x264-SyncUP.mkv' WHERE id = 8567;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\01_Stone World_imagem.jpg' WHERE id = 9025;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\02_King of the Stone World_imagem.jpg' WHERE id = 9026;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\03_Armas da Ci?ncia_imagem.jpg' WHERE id = 9027;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\04_Dispare o Sinal de Fuma?a_imagem.jpg' WHERE id = 9028;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\05_Stone World The Beginning_imagem.jpg' WHERE id = 9029;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\06_Duas Na??es do Mundo de Pedra_imagem.jpg' WHERE id = 9030;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\07_Onde se passaram 2 milh?es de anos_imagem.jpg' WHERE id = 9031;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\08_Stone Road_imagem.jpg' WHERE id = 9032;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\09_Fa?a-se a luz da ci?ncia_imagem.jpg' WHERE id = 9033;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\10_T?nue Alian?a_imagem.jpg' WHERE id = 9034;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\11_Clear World_imagem.jpg' WHERE id = 9035;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\12_Amigos de Costas contra Costas_imagem.jpg' WHERE id = 9036;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\13_Guerreiro Mascarado_imagem.jpg' WHERE id = 9037;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\14_Master of Flame_imagem.jpg' WHERE id = 9038;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\15_Cristaliza??o de 2 Milh?es de Anos_imagem.jpg' WHERE id = 9039;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\16_Um Conto de Milhares de Anos_imagem.jpg' WHERE id = 9040;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\17_Cem noites e mil c?us_imagem.jpg' WHERE id = 9041;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\18_Stone Wars_imagem.jpg' WHERE id = 9042;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\19_E em dire??o ? modernidade_imagem.jpg' WHERE id = 9043;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\20_A Era da Pot?ncia_imagem.jpg' WHERE id = 9044;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\21_Clube de Artesanato Espartano_imagem.jpg' WHERE id = 9045;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\22_O Tesouro_imagem.jpg' WHERE id = 9046;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\23_Onda da Ci?ncia_imagem.jpg' WHERE id = 9047;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\1? Temporada\\\\24_Vozes a uma Dist?ncia Infinita_imagem.jpg' WHERE id = 9048;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\01_As Stone Wars come?am_imagem.jpg' WHERE id = 9049;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\02_Hot Line_imagem.jpg' WHERE id = 9050;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\03_Telefone dos Mortos_imagem.jpg' WHERE id = 9051;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\04_Ataque com For?a Total_imagem.jpg' WHERE id = 9052;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\05_Steam Gorilla_imagem.jpg' WHERE id = 9053;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\06_Prison Break_imagem.jpg' WHERE id = 9054;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\07_Miss?o Confidencial_imagem.jpg' WHERE id = 9055;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\08_Final Battle_imagem.jpg' WHERE id = 9056;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\09_Para destruir e salvar_imagem.jpg' WHERE id = 9057;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\10_A Dupla Mais Poderosa da Humanidade_imagem.jpg' WHERE id = 9058;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\2? Temporada\\\\11_Prologue of Dr. Stone_imagem.jpg' WHERE id = 9059;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 1\\\\01_Mapa do novo mundo_imagem.jpg' WHERE id = 9060;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 1\\\\02_Querer = Justi?a_imagem.jpg' WHERE id = 9061;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 1\\\\03_Primeiro Contato_imagem.jpg' WHERE id = 9062;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 1\\\\04_Olhos da Ci?ncia_imagem.jpg' WHERE id = 9063;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 1\\\\05_O Navio Cient?fico Perseu_imagem.jpg' WHERE id = 9064;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 1\\\\06_Ba? do Tesouro_imagem.jpg' WHERE id = 9065;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 1\\\\07_Luz do Desespero e da Esperan?a_imagem.jpg' WHERE id = 9066;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 1\\\\08_Carta na Manga dentro do Navio da Ci?ncia_imagem.jpg' WHERE id = 9067;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 1\\\\10_Guerras Cient?ficas_imagem.jpg' WHERE id = 9068;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 1\\\\11_Com este punho, um milagre_imagem.jpg' WHERE id = 9069;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\01_O Reino da Ci?ncia Contra-Ataca_imagem.jpg' WHERE id = 9070;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\02_O Verdadeiro Rosto da Medusa_imagem.jpg' WHERE id = 9071;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\03_Deal Game, Batalha de C?rebros_imagem.jpg' WHERE id = 9072;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\04_Batalha em Tr?s Dimens?es_imagem.jpg' WHERE id = 9073;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\05_Guerra Total_imagem.jpg' WHERE id = 9074;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\06_Coringa_imagem.jpg' WHERE id = 9075;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\07_Brilho da Destrui??o_imagem.jpg' WHERE id = 9076;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\08_O ?ltimo Homem_imagem.jpg' WHERE id = 9077;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\09_Primeiro Sonho_imagem.jpg' WHERE id = 9078;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\10_Ilha do Tesouro_imagem.jpg' WHERE id = 9079;
UPDATE episodio SET capa_url = 'F:\\\\Dr. Stone\\\\3? Temporada\\\\Parte 2\\\\11_Al?m do Novo Mundo_imagem.jpg' WHERE id = 9080;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\01_Fullmetal Alchemist_imagem.jpg' WHERE id = 9796;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\02_O primeiro dia_imagem.jpg' WHERE id = 9797;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\03_Cidade da heresia_imagem.jpg' WHERE id = 9798;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\04_A ang?stia de um alquimista_imagem.jpg' WHERE id = 9799;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\05_Chuva de dores_imagem.jpg' WHERE id = 9800;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\06_Estrada da esperan?a_imagem.jpg' WHERE id = 9801;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\07_Verdades ocultas_imagem.jpg' WHERE id = 9802;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\08_O Quinto Laborat?rio_imagem.jpg' WHERE id = 9803;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\09_Sentimentos criados_imagem.jpg' WHERE id = 9804;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\10_Destinos Separados_imagem.jpg' WHERE id = 9805;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\11_Milagre em Rush Valley_imagem.jpg' WHERE id = 9806;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\12_Um ? tudo, tudo ? um_imagem.jpg' WHERE id = 9807;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\13_Bestas de Dublith_imagem.jpg' WHERE id = 9808;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\14_Aqueles que se escondem no subsolo_imagem.jpg' WHERE id = 9809;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\15_Enviado do leste _imagem.jpg' WHERE id = 9810;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\16_Passos de um camarada de armas _imagem.jpg' WHERE id = 9811;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\17_Chama Fria_imagem.jpg' WHERE id = 9812;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\18_A palma arrogante de um pequeno ser humano_imagem.jpg' WHERE id = 9813;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\19_Morte dos Imortais_imagem.jpg' WHERE id = 9814;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\20_Pai Antes do T?mulo_imagem.jpg' WHERE id = 9815;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\21_Avan?o do Louco_imagem.jpg' WHERE id = 9816;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\22_Costas na dist?ncia_imagem.jpg' WHERE id = 9817;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\23_Garota no campo de batalha_imagem.jpg' WHERE id = 9818;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\24_Dentro da barriga_imagem.jpg' WHERE id = 9819;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\25_Porta da Escurid?o_imagem.jpg' WHERE id = 9820;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\26_Reuni?o_imagem.jpg' WHERE id = 9821;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\27_Festa de Interl?dio_imagem.jpg' WHERE id = 9822;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\28_Pai_imagem.jpg' WHERE id = 9823;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\29_Luta do tolo_imagem.jpg' WHERE id = 9824;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\30_A Guerra de Exterm?nio de Ishvalan_imagem.jpg' WHERE id = 9825;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\31_A promessa dos 520 Cens_imagem.jpg' WHERE id = 9826;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\32_O filho do F?hrer_imagem.jpg' WHERE id = 9827;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\33_A Muralha do Norte de Briggs_imagem.jpg' WHERE id = 9828;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\34_Rainha de gelo_imagem.jpg' WHERE id = 9829;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\35_A forma deste pa?s_imagem.jpg' WHERE id = 9830;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\36_Retrato de fam?lia_imagem.jpg' WHERE id = 9831;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\37_O Primeiro Hom?nculo_imagem.jpg' WHERE id = 9832;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\38_Conflito na Baschool_imagem.jpg' WHERE id = 9833;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\39_Daydream_imagem.jpg' WHERE id = 9834;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\40_Hom?nculo (O An?o no Frasco)_imagem.jpg' WHERE id = 9835;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\41_The Abyss_imagem.jpg' WHERE id = 9836;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\42_Sinais de uma contra-ofensiva_imagem.jpg' WHERE id = 9837;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\43_Mordida da formiga_imagem.jpg' WHERE id = 9838;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\44_Acelerando a todo vapor_imagem.jpg' WHERE id = 9839;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\45_O Dia Prometido_imagem.jpg' WHERE id = 9840;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\46_Sombras iminentes_imagem.jpg' WHERE id = 9841;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\47_Emiss?rio das Trevas_imagem.jpg' WHERE id = 9842;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\48_O juramento no t?nel_imagem.jpg' WHERE id = 9843;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\49_Afeto Filial_imagem.jpg' WHERE id = 9844;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\50_Revolta no Centro_imagem.jpg' WHERE id = 9845;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\51_A Legi?o Imortal_imagem.jpg' WHERE id = 9846;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\52_For?a Combinada_imagem.jpg' WHERE id = 9847;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\53_Chama da Vingan?a_imagem.jpg' WHERE id = 9848;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\54_Al?m do Inferno_imagem.jpg' WHERE id = 9849;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\55_Modo de vida dos adultos_imagem.jpg' WHERE id = 9850;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\56_O Retorno do F?hrer_imagem.jpg' WHERE id = 9851;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\57_Licen?a eterna_imagem.jpg' WHERE id = 9852;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\58_Sacrif?cios_imagem.jpg' WHERE id = 9853;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\59_Lost Light_imagem.jpg' WHERE id = 9854;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\60_Olho do C?u, Portal da Terra_imagem.jpg' WHERE id = 9855;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\61_Aquele que Engoliria Deus_imagem.jpg' WHERE id = 9856;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\62_Um contra-ataque feroz_imagem.jpg' WHERE id = 9857;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\63_O outro lado do portal_imagem.jpg' WHERE id = 9858;
UPDATE episodio SET capa_url = 'F:\\\\Full Metal Alchemist - Brotherhood\\\\64_Fim da jornada_imagem.jpg' WHERE id = 9859;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.01.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9860;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.02.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9861;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.03.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9862;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.04.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9863;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.05.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9864;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.06.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9865;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.07.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9866;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.08.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9867;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.09.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9868;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.10.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9869;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.11.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9870;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.12.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9871;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\1? Temporada\\\\Gantz.13.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9872;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.14.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9873;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.15.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9874;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.16.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9875;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.17.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9876;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.18.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9877;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.19.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9878;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.20.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9879;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.21.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9880;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.22.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9881;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.23.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9882;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.24.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9883;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.25.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9884;
UPDATE episodio SET capa_url = 'F:\\\\Gantz\\\\2? Temporada\\\\Gantz.26.BD1080p.MemoriadaTV.Menor.mkv' WHERE id = 9885;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\01_O destino de certos aventureiros_imagem.jpg' WHERE id = 9886;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\02_Matador de Goblins_imagem.jpg' WHERE id = 9887;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\03_Visitantes inesperados_imagem.jpg' WHERE id = 9888;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\04_Os fortes_imagem.jpg' WHERE id = 9889;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\05_Aventuras e o dia-a-dia_imagem.jpg' WHERE id = 9890;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\06_Matador de Goblins na Cidade da ?gua_imagem.jpg' WHERE id = 9891;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\07_L? e de volta outra vez_imagem.jpg' WHERE id = 9892;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\08_Cochilando_imagem.jpg' WHERE id = 9893;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\09_Reuni?o de aventureiros_imagem.jpg' WHERE id = 9894;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\11_Reuni?o de aventureiros_imagem.jpg' WHERE id = 9895;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\1? Temporada\\\\12_O destino de um aventureiro_imagem.jpg' WHERE id = 9896;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\01_Um Dia Qualquer de Primavera_imagem.jpg' WHERE id = 9897;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\02_O Jovem Mago Ruivo_imagem.jpg' WHERE id = 9898;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\03_Local de Treinamento nas Cercanias da Cidade_imagem.jpg' WHERE id = 9899;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\04_Indo para uma Aventura_imagem.jpg' WHERE id = 9900;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\05_Cortador de barbas, indo ao Rio do Sul_imagem.jpg' WHERE id = 9901;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\06_A Floresta do Elfo Rei_imagem.jpg' WHERE id = 9902;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\07_Cruzeiro na Floresta_imagem.jpg' WHERE id = 9903;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\08_Fundo das Trevas_imagem.jpg' WHERE id = 9904;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\09_A Juventude que um Dia se Fez Presente, Agora S?o Cinzas_imagem.jpg' WHERE id = 9905;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\10_Aventura na Cidade_imagem.jpg' WHERE id = 9906;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\11_O Supl?cio da Princesa_imagem.jpg' WHERE id = 9907;
UPDATE episodio SET capa_url = 'F:\\\\Goblin Slayer\\\\2? Temporada\\\\12_?, Ora??es, Est?o Chegando aos C?us_imagem.jpg' WHERE id = 9908;
UPDATE episodio SET capa_url = 'F:\\\\Hanna-Barbera - Incompleto\\\\O Melhor da Warner Bros- CD 2.2013_imagem.jpg' WHERE id = 9909;
UPDATE episodio SET capa_url = 'F:\\\\Hanna-Barbera - Incompleto\\\\O Melhor da Warner Bros.CD 1_imagem.jpg' WHERE id = 9910;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\01_The Undead_imagem.jpg' WHERE id = 9911;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\02_Club M_imagem.jpg' WHERE id = 9912;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\03_Sword Dancer_imagem.jpg' WHERE id = 9913;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\04_Innocent as a Human_imagem.jpg' WHERE id = 9914;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\05_Brotherhood_imagem.jpg' WHERE id = 9915;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\06_Dead Zone_imagem.jpg' WHERE id = 9916;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\07_Duel_imagem.jpg' WHERE id = 9917;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\08_Kill House_imagem.jpg' WHERE id = 9918;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\09_Red Rose Vertigo_imagem.jpg' WHERE id = 9919;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\10_Master of Monster_imagem.jpg' WHERE id = 9920;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\11_Transcend Force_imagem.jpg' WHERE id = 9921;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\12_Total Destruction_imagem.jpg' WHERE id = 9922;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\1? Temporada\\\\13_Hellfire_imagem.jpg' WHERE id = 9923;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\2? Temporada\\\\01_Hellsing I_imagem.jpg' WHERE id = 9924;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\2? Temporada\\\\02_Hellsing II_imagem.jpg' WHERE id = 9925;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\2? Temporada\\\\03_Hellsing III_imagem.jpg' WHERE id = 9926;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\2? Temporada\\\\04_Hellsing IV_imagem.jpg' WHERE id = 9927;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\2? Temporada\\\\05_Hellsing V_imagem.jpg' WHERE id = 9928;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\2? Temporada\\\\06_Hellsing VI_imagem.jpg' WHERE id = 9929;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\2? Temporada\\\\07_Hellsing VII_imagem.jpg' WHERE id = 9930;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\2? Temporada\\\\08_Hellsing VIII_imagem.jpg' WHERE id = 9931;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\2? Temporada\\\\09_Hellsing IX_imagem.jpg' WHERE id = 9932;
UPDATE episodio SET capa_url = 'F:\\\\Hellsing\\\\2? Temporada\\\\10_Hellsing X_imagem.jpg' WHERE id = 9933;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\01_Partida ? e ? Amigos_imagem.jpg' WHERE id = 9934;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\02_Teste ? dos ? Testes_imagem.jpg' WHERE id = 9935;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\03_Rivais ? Pela ? Sobreviv?ncia_imagem.jpg' WHERE id = 9936;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\04_Esperan?a ? e ? Ambi??o_imagem.jpg' WHERE id = 9937;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\05_Hisoka ? ? ? Sorrateiro_imagem.jpg' WHERE id = 9938;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\06_Um ? Desafio ? Surpreendente_imagem.jpg' WHERE id = 9939;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\07_Batalha ? no ? Dirig?vel_imagem.jpg' WHERE id = 9940;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\08_Voto ? da ? Maioria_imagem.jpg' WHERE id = 9941;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\09_Cuidado ? com ? os Prisioneiros_imagem.jpg' WHERE id = 9942;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\100_Rastreamento x e x Persegui??o_imagem.jpg' WHERE id = 9943;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\101_Ikalgo x e x Rel?mpago_imagem.jpg' WHERE id = 9944;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\102_Poder x e x Jogos_imagem.jpg' WHERE id = 9945;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\103_Xeque x Mate_imagem.jpg' WHERE id = 9946;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\104_D?vida x e x Excita??o_imagem.jpg' WHERE id = 9947;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\105_Determina??o x e x Despertar_imagem.jpg' WHERE id = 9948;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\106_Knov x e x Morel_imagem.jpg' WHERE id = 9949;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\107_Retorno x e x Retirada_imagem.jpg' WHERE id = 9950;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\108_Gungi x de x Komugi_imagem.jpg' WHERE id = 9951;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\109_Balan?o x e x A??o_imagem.jpg' WHERE id = 9952;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\10_Truque ? para ? um Truque_imagem.jpg' WHERE id = 9953;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\110_Confus?o x e x Expectativa_imagem.jpg' WHERE id = 9954;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\111_Atacar x e x Invadir_imagem.jpg' WHERE id = 9955;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\112_Forasteiro x e x Monstro_imagem.jpg' WHERE id = 9956;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\113_Um x Inseto x Endividado_imagem.jpg' WHERE id = 9957;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\114_Divis?o x e x Conquista_imagem.jpg' WHERE id = 9958;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\115_Dever x e x Perguntas_imagem.jpg' WHERE id = 9959;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\116_Vingan?a x e x Recupera??o_imagem.jpg' WHERE id = 9960;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\117_Insulto x e x Troco_imagem.jpg' WHERE id = 9961;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\118_Uma x F?ria x Falsa_imagem.jpg' WHERE id = 9962;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\119_Forte x ou x Fraco_imagem.jpg' WHERE id = 9963;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\11_Problemas ? com ? a Aposta_imagem.jpg' WHERE id = 9964;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\120_Falso x e x Verdadeiro_imagem.jpg' WHERE id = 9965;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\121_Derrota x e x Dignidade_imagem.jpg' WHERE id = 9966;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\122_Postura x e x Nome_imagem.jpg' WHERE id = 9967;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\123_Centop?ia x e x Mem?ria_imagem.jpg' WHERE id = 9968;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\124_Colapso x e x Despertar_imagem.jpg' WHERE id = 9969;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\125_Grande Poder x e x Poder Supremo_imagem.jpg' WHERE id = 9970;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\126_Zero x e x Rosa_imagem.jpg' WHERE id = 9971;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\127_Hostilidade x e x Determina??o_imagem.jpg' WHERE id = 9972;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\128_Felicidade Incompar?vel x e x Amor Incondicional_imagem.jpg' WHERE id = 9973;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\129_Inimigo Formid?vel x e x Objetivo Claro_imagem.jpg' WHERE id = 9974;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\12_?ltimo Teste ? de ? Determina??o_imagem.jpg' WHERE id = 9975;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\130_Magiar x do x Desespero_imagem.jpg' WHERE id = 9976;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\131_Raiva x e x Luz_imagem.jpg' WHERE id = 9977;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\132_Lampejo x e x In?cio_imagem.jpg' WHERE id = 9978;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\133_Prazo x Para x Viver_imagem.jpg' WHERE id = 9979;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\134_Uma Palavra x e x Nada Mais_imagem.jpg' WHERE id = 9980;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\135_Essa Pessoa x e x Esse Momento_imagem.jpg' WHERE id = 9981;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\136_Voltando Para Casa x e x Nome Verdadeiro_imagem.jpg' WHERE id = 9982;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\137_Debate x dos x Zod?acos_imagem.jpg' WHERE id = 9983;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\138_Um Inc?modo x e x Um Desejo_imagem.jpg' WHERE id = 9984;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\139_Alluka x e x Coisa_imagem.jpg' WHERE id = 9985;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\13_Carta ? de ? Gon_imagem.jpg' WHERE id = 9986;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\140_Juntar-se ? Batalha x e x Batalha Declarada_imagem.jpg' WHERE id = 9987;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\141_Mago x e x Mordomo_imagem.jpg' WHERE id = 9988;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\142_Agulhas x e x D?vida_imagem.jpg' WHERE id = 9989;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\143_Pecado x e x Garra_imagem.jpg' WHERE id = 9990;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\144_Aprova??o x e x Coaliz?o_imagem.jpg' WHERE id = 9991;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\145_Derrota x e x Reuni?o!_imagem.jpg' WHERE id = 9992;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\146_Presidente x e x Liberta??o_imagem.jpg' WHERE id = 9993;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\147_Salva??o x e x Futuro_imagem.jpg' WHERE id = 9994;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\148_O que veio x e x O que esta por vir_imagem.jpg' WHERE id = 9995;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\14_Acerte ? o ? Alvo_imagem.jpg' WHERE id = 9996;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\15_Explos?o ? de ? Decep??o_imagem.jpg' WHERE id = 9997;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\16_Derrota ? e ? Desgra?a_imagem.jpg' WHERE id = 9998;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\17_Armadilha ? no ? Buraco_imagem.jpg' WHERE id = 9999;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\18_Entrevista ? Muito ? Importante_imagem.jpg' WHERE id = 10000;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\19_Sem Vencer ? e ? Sem Perder_imagem.jpg' WHERE id = 10001;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\20_Mudan?a ? de Eventos ? Inesperada_imagem.jpg' WHERE id = 10002;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\21_Problemas ? Entre ? Irm?os_imagem.jpg' WHERE id = 10003;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\22_C?o ? de Guarda ? Perigoso_imagem.jpg' WHERE id = 10004;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\23_O Dever ? de ? um Guarda_imagem.jpg' WHERE id = 10005;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\24_A ? Fam?lia ? Zoldyck_imagem.jpg' WHERE id = 10006;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\25_N?o Sei ? Se Voc? ? ? Cego_imagem.jpg' WHERE id = 10007;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\26_Antes ? e ? Depois_imagem.jpg' WHERE id = 10008;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\27_Chegada ? ? ? Torre_imagem.jpg' WHERE id = 10009;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\28_Nen ? e ? Nen_imagem.jpg' WHERE id = 10010;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\29_Despertar ? e ? Potencial_imagem.jpg' WHERE id = 10011;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\30_Feroz ? e ? Ardente_imagem.jpg' WHERE id = 10012;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\31_Destino ? e ? Tenacidade_imagem.jpg' WHERE id = 10013;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\32_Uma ? Surpreendente ? Vit?ria_imagem.jpg' WHERE id = 10014;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\33_Uma ? Amea?a ? Vazia_imagem.jpg' WHERE id = 10015;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\34_Poder ? para ? Vingar_imagem.jpg' WHERE id = 10016;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\35_O ? Verdadeiro ? Exame_imagem.jpg' WHERE id = 10017;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\36_Um Grande D?bito ? e ? Um Pequeno Chute_imagem.jpg' WHERE id = 10018;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\37_Ging ? e ? Gon_imagem.jpg' WHERE id = 10019;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\38_Resposta ? do ? Pai_imagem.jpg' WHERE id = 10020;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\39_Desejo ? e ? Promessa_imagem.jpg' WHERE id = 10021;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\40_Usu?rios ? de Nen ? Reunem-se_imagem.jpg' WHERE id = 10022;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\41_Reuni?o ? de ? Her?is_imagem.jpg' WHERE id = 10023;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\42_Defender ? e ? Atacar_imagem.jpg' WHERE id = 10024;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\43_Uma ? Trag?dia ? Chocante_imagem.jpg' WHERE id = 10025;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\44_Uma Grande ? Batalha ? se Aproxima_imagem.jpg' WHERE id = 10026;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\45_Restri??o ? e ? Juramento_imagem.jpg' WHERE id = 10027;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\46_Perseguindo ? e ? Esperando_imagem.jpg' WHERE id = 10028;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\47_Condi??o ? e ? Condi??o_imagem.jpg' WHERE id = 10029;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\48_Olhos ? Muito ? Afiados_imagem.jpg' WHERE id = 10030;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\49_Persegui??o ? e ? An?lise_imagem.jpg' WHERE id = 10031;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\50_Aliado ? e ? Espada_imagem.jpg' WHERE id = 10032;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\51_Campo ? de Batalha ? Brutal_imagem.jpg' WHERE id = 10033;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\52_Ataque ? e ? Impacto_imagem.jpg' WHERE id = 10034;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\53_Farsa ? e ? Psique_imagem.jpg' WHERE id = 10035;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\54_Previs?o x Falsa_imagem.jpg' WHERE id = 10036;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\55_Camaradas x e x Engana??es!_imagem.jpg' WHERE id = 10037;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\56_Amado x e x Desastre!_imagem.jpg' WHERE id = 10038;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\57_Iniciativa x e x Instru??es!_imagem.jpg' WHERE id = 10039;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\58_Adeus x e x Arma_imagem.jpg' WHERE id = 10040;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\59_Lance x e x Pressa_imagem.jpg' WHERE id = 10041;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\60_Fim x e x Come?o_imagem.jpg' WHERE id = 10042;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\61_Convite x e x Amigo_imagem.jpg' WHERE id = 10043;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\62_Realidade x e x Cura_imagem.jpg' WHERE id = 10044;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\63_Uma x Mestra x Severa_imagem.jpg' WHERE id = 10045;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\64_For?a x e x Amea?a_imagem.jpg' WHERE id = 10046;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\65_Punhos do Mal x e x Pedra,Papel ou Tesoura_imagem.jpg' WHERE id = 10047;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\66_Estrat?gia x e x Esquema_imagem.jpg' WHERE id = 10048;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\67_15 x e x 15_imagem.jpg' WHERE id = 10049;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\68_Piratas x e x Convidados_imagem.jpg' WHERE id = 10050;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\69_Um x Confronto x Esquentado_imagem.jpg' WHERE id = 10051;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\70_Coragem x e x Ra?a_imagem.jpg' WHERE id = 10052;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\71_Barganha x e x Acordo_imagem.jpg' WHERE id = 10053;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\72_Persegui??o x e x Acaso_imagem.jpg' WHERE id = 10054;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\73_Insanidade x e x Sanidade_imagem.jpg' WHERE id = 10055;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\74_Vencedor x e x Perdedor_imagem.jpg' WHERE id = 10056;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\75_Amigos do Ging x e x Verdadeiros Amigos_imagem.jpg' WHERE id = 10057;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\76_Reuni?o x e x Compreens?o_imagem.jpg' WHERE id = 10058;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\77_Desconfort?vel x e x Avistamento_imagem.jpg' WHERE id = 10059;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\78_Reprodu??o x Muito x R?pida_imagem.jpg' WHERE id = 10060;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\79_N?o x Adianta x NGL_imagem.jpg' WHERE id = 10061;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\80_Malaigno x e x Assustador_imagem.jpg' WHERE id = 10062;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\81_A x Luta x Come?a_imagem.jpg' WHERE id = 10063;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\82_Kite x e x Slots_imagem.jpg' WHERE id = 10064;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\83_Inspira??o x Para x Evoluir_imagem.jpg' WHERE id = 10065;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\84_Um x Despertar x Predestinado_imagem.jpg' WHERE id = 10066;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\85_Luz x e x Trevas_imagem.jpg' WHERE id = 10067;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\86_Promessa x e x Reuni?o_imagem.jpg' WHERE id = 10068;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\87_Duelo x e x Fuga_imagem.jpg' WHERE id = 10069;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\88_Pedra,Papel, Tesoura x e x Ponto Fraco_imagem.jpg' WHERE id = 10070;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\89_Piedade x e x For?a_imagem.jpg' WHERE id = 10071;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\90_Juros x e x Maldi??o_imagem.jpg' WHERE id = 10072;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\91_O Forte x e x O Fraco_imagem.jpg' WHERE id = 10073;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\92_Um Desejo x e x Duas Promessas_imagem.jpg' WHERE id = 10074;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\93_Encontro x Com x Palm_imagem.jpg' WHERE id = 10075;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\94_Amigo x e x Jornada_imagem.jpg' WHERE id = 10076;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\95_Rancar x e x Pavor_imagem.jpg' WHERE id = 10077;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\96_Uma Casa x Sem x Sem Lei_imagem.jpg' WHERE id = 10078;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\97_Massacre x e x Devasta??o_imagem.jpg' WHERE id = 10079;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\98_Infiltra??o x e x Sele??o_imagem.jpg' WHERE id = 10080;
UPDATE episodio SET capa_url = 'F:\\\\Hunter x Hunter\\\\99_Combina??o x e x Evolu??o_imagem.jpg' WHERE id = 10081;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\01_A Garota que Volta no Tempo e o Garoto Lacrado_imagem.jpg' WHERE id = 10082;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\02_As pessoas atr?s da J?ia de Quatro Almas_imagem.jpg' WHERE id = 10083;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\03_A volta pelo po?o Come-Ossos_imagem.jpg' WHERE id = 10084;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\04_Yura dos Cabelos Invertidos_imagem.jpg' WHERE id = 10085;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\05_O Tem?vel Pr?ncipe Sesshoumaru_imagem.jpg' WHERE id = 10086;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\06_Tessaiga o canino de a?o destruidor_imagem.jpg' WHERE id = 10087;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\07_O confronto Sesshoumaru vs. Tessaiga_imagem.jpg' WHERE id = 10088;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\08_O Senhor Feudal youkai - Sapo de tsukumo_imagem.jpg' WHERE id = 10089;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\09_Entra em cena Shippou!; Os irm?os youkai rel?mpago Hitten e Manten_imagem.jpg' WHERE id = 10090;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\100_Pesadelo Real! A batalha na Floresta do Desespero_imagem.jpg' WHERE id = 10091;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\101_Sete anos depois As neves eternas_imagem.jpg' WHERE id = 10092;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\102_O l?der dos youkais lobos ? atacado por um zombi_imagem.jpg' WHERE id = 10093;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\103_O ex?rcito dos sete ressuscitados_imagem.jpg' WHERE id = 10094;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\104_Mukotsu, o envenenador_imagem.jpg' WHERE id = 10095;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\105_O terr?vel guerreiro de a?o, Guinkoutsu_imagem.jpg' WHERE id = 10096;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\106_Sepultados sob as chamas_imagem.jpg' WHERE id = 10097;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\107_As primeiras l?grimas de Inuyasha_imagem.jpg' WHERE id = 10098;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\108_O segredo do explendor puro_imagem.jpg' WHERE id = 10099;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\109_O monte sagrado Hakurei_imagem.jpg' WHERE id = 10100;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\10_Confronto da espada rel?mpago contra Tesaiga_imagem.jpg' WHERE id = 10101;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\110_Surge o l?der dos Shichinintai Bankotsu_imagem.jpg' WHERE id = 10102;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\111_Acerto de contas - Banryuu contra Ferida do Vento_imagem.jpg' WHERE id = 10103;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\112_A barreira na Ilha Hijiri_imagem.jpg' WHERE id = 10104;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\113_O Dokko sagrado e o segredo da m?mia_imagem.jpg' WHERE id = 10105;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\114_A batalha solit?ria de Kouga_imagem.jpg' WHERE id = 10106;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\115_Engolido pela luz negra_imagem.jpg' WHERE id = 10107;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\116_A nova apar?ncia de Naraku_imagem.jpg' WHERE id = 10108;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\117_O rio de fogo_imagem.jpg' WHERE id = 10109;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\118_No cora??o do Monte Hakurei_imagem.jpg' WHERE id = 10110;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\119_Um Santo divino e malicioso_imagem.jpg' WHERE id = 10111;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\11_A m?scara da maldi??o que ressuscita na ?poca actual_imagem.jpg' WHERE id = 10112;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\120_Adeus!; Uma marcha f?nebre para Jakotsu_imagem.jpg' WHERE id = 10113;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\121_A batalha final!; O ?ltimo e mais forte dos Shichinintai_imagem.jpg' WHERE id = 10114;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\122_Poderosa Banryuu!; O combate mortal dentro do Monte Hakurei_imagem.jpg' WHERE id = 10115;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\123_Naraku regenerado al?m da escurid?o_imagem.jpg' WHERE id = 10116;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\124_Adeus, minha querida Kikyou_imagem.jpg' WHERE id = 10117;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\125_A escurid?o no cora??o de Kagome_imagem.jpg' WHERE id = 10118;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\126_Transformando a dor em coragem_imagem.jpg' WHERE id = 10119;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\127_Os terr?veis youkais secos_imagem.jpg' WHERE id = 10120;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\128_Os youkais invadem o festival cultural_imagem.jpg' WHERE id = 10121;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\129_Cho Kyukai e as noivas roubadas_imagem.jpg' WHERE id = 10122;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\12_Tatarimoke e o pequeno esp?rito mau_imagem.jpg' WHERE id = 10123;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\130_O rugido e a ferida no cora??o de Shippou_imagem.jpg' WHERE id = 10124;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\131_Os pergaminhos de Kannon_imagem.jpg' WHERE id = 10125;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\132_A mais perigosa confiss?o de Miroku_imagem.jpg' WHERE id = 10126;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\133_A mulher que amou Sesshoumaru (Parte 1)_imagem.jpg' WHERE id = 10127;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\134_A mulher que amou Sesshoumaru (Parte 2)_imagem.jpg' WHERE id = 10128;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\135_O ?ltimo banquete do mestre de Miroku_imagem.jpg' WHERE id = 10129;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\136_Um youkai invis?vel aparece!_imagem.jpg' WHERE id = 10130;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\137_O nome da ancestral ? Kagome_imagem.jpg' WHERE id = 10131;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\138_A Sobreviv?ncia numa terra infestada de youkais_imagem.jpg' WHERE id = 10132;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\139_O grande duelo na cascata Shohun_imagem.jpg' WHERE id = 10133;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\13_O segredo do primeiro dia Inuyasha de cabelos pretos_imagem.jpg' WHERE id = 10134;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\140_Sentimentos eternos_imagem.jpg' WHERE id = 10135;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\141_A liberta??o do monstruoso cavalo youkai Entei_imagem.jpg' WHERE id = 10136;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\142_A fuga de Entei_imagem.jpg' WHERE id = 10137;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\143_A viagem em busca do pai_imagem.jpg' WHERE id = 10138;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\144_Housenki e o ?ltimo fragmento_imagem.jpg' WHERE id = 10139;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\145_Os estranhos guardi?es do portal_imagem.jpg' WHERE id = 10140;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\146_Abi, a incontrol?vel dominadora de aves_imagem.jpg' WHERE id = 10141;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\147_Uma fat?dica can??o de amor antes de nos encontrarmos (Parte 1)_imagem.jpg' WHERE id = 10142;
UPDATE episodio SET capa_url = 'F:\\\\Inuyasha\\\\148_Uma fat?dica can??o de amor antes de nos encontrarmos (Parte 2)_imagem.jpg' WHERE id = 10143;
