INSERT INTO genero (nome, descricao, status_desc, uuid) VALUES
('Ação', 'Cenas de luta intensas, combates épicos e protagonistas que encaram desafios físicos com coragem e determinação.', 'ATIVO', UUID()),
('Aventura', 'Histórias épicas de jornadas, exploração de mundos desconhecidos e descobertas de tesouros e segredos.', 'ATIVO', UUID()),
('Artes Marciais', 'Foco em estilos de luta como karatê, judô, kung fu e técnicas de combate corpo a corpo.', 'ATIVO', UUID()),
('Comédia', 'Situações engraçadas, personagens caricatos e humor que faz o público rir. Exemplos clássicos incluem Gintama e Konosuba.', 'ATIVO', UUID()),
('Drama', 'Narrativas profundas que exploram emoções humanas, conflitos internos e relações interpessoais complexas.', 'ATIVO', UUID()),
('Escola', 'Ambientado em escolas japonesas com foco em cotidiano de estudantes, amizades e romance.', 'ATIVO', UUID()),
('Esportes', 'Competições atléticas como futebol, basquete, tênis e natação com momentos de superação.', 'ATIVO', UUID()),
('Fantasia', 'Mundos mágicos com criaturas sobrenaturais, magias e aventuras em reinos fictícios.', 'ATIVO', UUID()),
('Ficção Científica', 'Futuros distópicos, tecnologias avançadas, viagens no tempo e alienígenas.', 'ATIVO', UUID()),
('Horror', 'Histórias de terror que provocam medo e suspense com elementos sobrenaturais e psicológicos.', 'ATIVO', UUID()),
('Isekai', 'Protagonistas transportados para outros mundos, geralmente com poderes especiais.', 'ATIVO', UUID()),
('Jogo', 'Baseados em jogos de RPG, MMOs ou jogos de cartas colecionáveis.', 'ATIVO', UUID()),
('Magical Girl', 'Garotas que ganham poderes mágicos e lutam contra forças do mal com transformações espectaculares.', 'ATIVO', UUID()),
('Mecha', 'Robôs gigantes pilotados por humanos em batalhas épicas contra alienígenas ou inimigos.', 'ATIVO', UUID()),
('Mistério', 'Enigmas para resolver, crimes para desvendar e segredos para descobrir.', 'ATIVO', UUID()),
('Musical', 'Música como elemento central, com performances, concursos e desenvolvimento artístico.', 'ATIVO', UUID()),
('Psicológico', 'Exploração da mente humana, dilemas morais e situações que desafiam a percepção da realidade.', 'ATIVO', UUID()),
('Romance', 'Histórias de amor entre personagens, com sentimentalismo e desenvolvimento de relacionamentos.', 'ATIVO', UUID()),
('Sci-Fi', 'Ficção científica com elementos tecnológicos, viagens espaciais e futuros imaginários.', 'ATIVO', UUID()),
('Seinen', 'Voltado para adultos jovens com temas maduros, violência realista e complexidade narrativa.', 'ATIVO', UUID()),
('Shojo', 'Voltado para garotas com foco em romance, amizade e crescimento pessoal.', 'ATIVO', UUID()),
('Shonen', 'Voltado para garotos com foco em amizade, superação e batalhas épicas.', 'ATIVO', UUID()),
('Slice of Life', 'Retrato do cotidiano japonês com situações reais e personagens comuns.', 'ATIVO', UUID()),
('Sobrenatural', 'Elementos fantásticos como espíritos, deuses e poderes mágicos que desafiam as leis da física.', 'ATIVO', UUID()),
('Suspense', 'Situações de tensão e antecipação que prendem a atenção do espectador até o final.', 'ATIVO', UUID()),
('Terror', 'Gênero que provoca medo e repulsa com cenas perturbadoras e tensão constante.', 'ATIVO', UUID()),
('Thriller', 'Narrativas intensas com reviravoltas inesperadas e sensação de perigo iminente.', 'ATIVO', UUID()),
('Vampiro', 'Mundo sombrio com criaturas da noite, caçadores de vampiros e mitologia vampírica.', 'ATIVO', UUID()),
('Yaoi', 'Romance entre personagens masculinos, voltado para o público feminino.', 'ATIVO', UUID()),
('Yuri', 'Romance entre personagens femininos, explorando relações entre garotas.', 'ATIVO', UUID()),
('Cyberpunk', 'Futuros distópicos com tecnologia avançada, hacking e sociedades decadentes.', 'ATIVO', UUID()),
('Guerra', 'Conflitos militares, estratégias de batalha e impactos da guerra na sociedade.', 'ATIVO', UUID()),
('Histórico', 'Baseados em eventos históricos reais ou figuras históricas japonesas.', 'ATIVO', UUID()),
('Harem', 'Protagonista cercado por múltiplos personagens românticos de forma cômica.', 'ATIVO', UUID()),
('Mahou Shoujo', 'Garotas mágicas com poderes de transformação e batalhas contra o mal.', 'ATIVO', UUID()),
('Post-apocalíptico', 'Mundos devastados por catástrofes onde sobreviventes lutam pela existência.', 'ATIVO', UUID()),
('Steampunk', 'Estética vitoriana com tecnologia a vapor e máquinas antigas.', 'ATIVO', UUID()),
('Space Opera', 'Épicos espaciais com batalhas cósmicas, política intergaláctica e drama humano.', 'ATIVO', UUID()),
('Coming-of-Age', 'Histórias de crescimento pessoal e amadurecimento de jovens personagens.', 'ATIVO', UUID()),
('Dementia', 'Narrativas que exploram distúrbios mentais e a dissolução da realidade.', 'ATIVO', UUID()),
('Ecchi', 'Elementos sugestivos e fanservice com humor para o público masculino.', 'ATIVO', UUID()),
('Fantasia Urbana', 'Magia e criaturas sobrenaturais em meio ao cotidiano da cidade moderna.', 'ATIVO', UUID()),
('Gore', 'Violência gráfica e cenas extremas de sangue e destruição.', 'ATIVO', UUID()),
('Idol', 'Foco em garotas idols japonesas, música pop e performances ao vivo.', 'ATIVO', UUID()),
('Josei', 'Voltado para mulheres adultas com dramas realistas e relacionamentos maduros.', 'ATIVO', UUID()),
('Kodomo', 'Voltado para crianças com mensagens educativas e aventuras leves.', 'ATIVO', UUID()),
('Paródia', 'Sátira e paródia de outros animes e tropos do gênero.', 'ATIVO', UUID()),
('Policial', 'Investigações criminais, detetives e mundo do crime.', 'ATIVO', UUID()),
('Samurai', 'Guerreiros japoneses com espadas, código de honra e batalhas épicas.', 'ATIVO', UUID()),
('School Life', 'Cotidiano escolar com amizades, estudos e atividades extracurriculares.', 'ATIVO', UUID()),
('Tragedy', 'Histórias tristes com finais inevitáveis e sofrimento humano.', 'ATIVO', UUID());
