-- Seed: canal (10 channels)
-- Auto-generated from database

INSERT INTO canal (id, descricao, logotipo_url, nome, site, status_desc, uuid) VALUES
(2, 'Seu portal definitivo para animes de alta definição. Explore mundos épicos, lutas eletrizantes e histórias que transcendem os limites da imaginação. Aqui, cada frame é uma obra-prima e cada episódio é uma nova aventura.', NULL, 'AnimeVault HD', NULL, 'Active', '117b4081-a9e1-11f1-adb3-5612c5722cec'),
(3, 'Um oceano infinito de criatividade onde ideias borbulham como cores vibrantes. Das artes visuais à música, do design à inovação - este canal é o laboratório onde sonhos se transformam em realidade, 24 horas por dia.', NULL, 'Canal Criatividade 24h', NULL, 'Active', '117b4901-a9e1-11f1-adb3-5612c5722cec'),
(4, 'A tela mágica onde os melhores animes ganham vida com qualidade cinematográfica. Uma experiência premium que Transporta você para dimensões onde coragem, amizade e superação são os idiomas universais.', NULL, 'Telecine Anime', NULL, 'Active', '117b4c7d-a9e1-11f1-adb3-5612c5722cec'),
(5, 'O coração pulsante da animação brasileira! Aqui late a paixão por animes com dublagem que arrepia e legendas que encantam. Um refúgio para fãs que respiram anime a cada batimento cardíaco.', NULL, 'Animax Brasil', NULL, 'Active', '117b4df9-a9e1-11f1-adb3-5612c5722cec'),
(6, 'Carregando... carregando... PRONTO! Você entrou no universo onde cada download é uma portal para outras dimensões. Animes raros, clássicos atemporais e lançamentos que fazem o coração acelerar.', NULL, 'Loading... Anime', NULL, 'Active', '117b4fae-a9e1-11f1-adb3-5612c5722cec'),
(7, 'O templo sagrado dos otaku! Com a maior biblioteca de animes do planeta, aqui você encontra desde os clássicos dos anos 90 até os últimos episódios dos simulcasts. Sua jornada anime começa aqui.', NULL, 'Crunchyroll TV', NULL, 'Active', '117b5165-a9e1-11f1-adb3-5612c5722cec'),
(8, 'Onde a Netflix encontra o Japão! Uma curadoria exclusiva dos melhores animes, com produções originais que estão redefinindo os limites da animação. Prepare pipoca e prepare-se para séries viciantes.', NULL, 'Netflix Anime', NULL, 'Active', '117b528e-a9e1-11f1-adb3-5612c5722cec'),
(9, 'A elite do entretenimento anime! Produções premium, dublagem impecável e uma seleção que mistura os maiores sucessos com pérolas ocultas. Aqui, qualidade não é opcional - é o padrão.', NULL, 'HBO Max Anime', NULL, 'Active', '117b53f1-a9e1-11f1-adb3-5612c5722cec'),
(10, 'O reino da magia da Disney se expandiu para o universo anime! De Studios Ghibli a produções exclusivas, este canal é a ponte entre o conto de fadas clássico e a épica anime moderna.', NULL, 'Disney+ Anime', NULL, 'Active', '117b552c-a9e1-11f1-adb3-5612c5722cec'),
(11, 'Amazon Prime desembarca no Japão com uma seleção devastadora de animes. De Action-packed a slice of life, aquí você encontra qualidade streaming com a conveniência que só a Amazon oferece.', NULL, 'Amazon Prime Anime', NULL, 'Active', '117b562f-a9e1-11f1-adb3-5612c5722cec');
