spring.application.name=ws
##SWAGGER##
#springdoc.swagger-ui.path=/ws-documentation
#springdoc.api-docs.path=/ws-api-docs
#springdoc.packages-to-scan=com.hvs.ws.back.app
#springdoc.swagger-ui.tryItOutEnabled=true
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha
#springdoc.swagger-ui.filter=true
##APPLICATION PORT##
server.port=8080