spring.application.name=webstore
##SWAGGER##
#springdoc.swagger-ui.path=/webstore-documentation
#springdoc.api-docs.path=/webstore-api-docs
#springdoc.packages-to-scan=com.hvs.webstore.back.app
#springdoc.swagger-ui.tryItOutEnabled=true
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha
#springdoc.swagger-ui.filter=true
##APPLICATION PORT##
server.port=8080