##MEDIA##
#webstore.media.root=/data/media/
##LIQUIBASE##
spring.liquibase.change-log=classpath:db/changelog/db.changelog-root.xml
##MYSQL - HIBERNATE##
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ec-db
spring.datasource.username=root
spring.datasource.password=root
##KEYCLOAK##
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/hvstv
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/hvstv/protocol/openid-connect/certs