package com.hvs.webstore.back.app.command.television.programa;

import java.util.List;

public record CreateProgramaCommand(String aNome,
                                    Boolean aEmProducao,
                                    String aTipoCode,
                                    Long aTemporadas,
                                    List<Long> aEpisodioIds,
                                    String aLancamento,
                                    String aEncerramento,
                                    List<Long> aBlocoIds,
                                    String aSinopse,
                                    String aClassificacaoEtariaCode,
                                    String aEstudio,
                                    String aDiretor,
                                    String aCapaUrl,
                                    String aTemporadaOriginal,
                                    String aRedeOriginal,
                                    String aTipoExibicaoCode,
                                    String aTituloAlternativo,
                                    String aAudioIdiomas,
                                    String aLegendasDisponiveis,
                                    String aSiteOficial,
                                    List<Long> aGeneroIds) {

    public static CreateProgramaCommand from(final String aNome,
                                             final Boolean aEmProducao,
                                             final String aTipoCode,
                                             final Long aTemporadas,
                                             final List<Long> aEpisodioIds,
                                             final String aLancamento,
                                             final String aEncerramento,
                                             final List<Long> aBlocoIds,
                                             final String aSinopse,
                                             final String aClassificacaoEtariaCode,
                                             final String aEstudio,
                                             final String aDiretor,
                                             final String aCapaUrl,
                                             final String aTemporadaOriginal,
                                             final String aRedeOriginal,
                                             final String aTipoExibicaoCode,
                                             final String aTituloAlternativo,
                                             final String aAudioIdiomas,
                                             final String aLegendasDisponiveis,
                                             final String aSiteOficial,
                                             final List<Long> aGeneroIds) {

        return new CreateProgramaCommand(
                aNome,
                aEmProducao,
                aTipoCode,
                aTemporadas,
                aEpisodioIds,
                aLancamento,
                aEncerramento,
                aBlocoIds,
                aSinopse,
                aClassificacaoEtariaCode,
                aEstudio,
                aDiretor,
                aCapaUrl,
                aTemporadaOriginal,
                aRedeOriginal,
                aTipoExibicaoCode,
                aTituloAlternativo,
                aAudioIdiomas,
                aLegendasDisponiveis,
                aSiteOficial,
                aGeneroIds
        );
    }
}